ACTION_KEYS = (
    ('specifications', 'approve'),
    ('specifications', 'obsolete'),
    ('samples', 'approve'),
    ('samples', 'cancel'),
    ('samples', 'collect'),
    ('samples', 'create_analysis'),
    ('samples', 'receive'),
    ('samples', 'reject'),
    ('samples', 'review'),
    ('samples', 'start_analysis'),
    ('analyses', 'approve'),
    ('analyses', 'complete'),
    ('analyses', 'reject'),
    ('analyses', 'review'),
    ('analyses', 'start'),
    ('results', 'evaluate'),
    ('investigations', 'approve_repeat'),
    ('investigations', 'approve_resampling'),
    ('investigations', 'approve_retest'),
    ('investigations', 'conclude'),
    ('investigations', 'start'),
    ('documents', 'cancel'),
    ('documents', 'issue'),
)
