ACTION_KEYS = (
    ('complaints', 'cancel'),
    ('complaints', 'close'),
    ('complaints', 'record_regulatory_communication'),
    ('complaints', 'start_investigation'),
    ('complaints', 'start_triage'),
    ('returns', 'authorize'),
    ('returns', 'cancel'),
    ('returns', 'close'),
    ('returns', 'inspect'),
    ('returns', 'receive'),
    ('campaigns', 'approve'),
    ('campaigns', 'cancel'),
    ('campaigns', 'close'),
    ('campaigns', 'start'),
    ('impacted-customers', 'record_response'),
    ('impacted-customers', 'record_return'),
    ('communications', 'acknowledge'),
    ('communications', 'send'),
    ('reports', 'generate'),
)
