# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('source_module', models.CharField(choices=[('auxiliary', 'Cadastros auxiliares'), ('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo')),
                ('check_type', models.CharField(choices=[('single_instance_scope', 'Single-instance'), ('permission', 'Permissao'), ('audit', 'Auditoria'), ('status_history', 'Historico de status'), ('transaction', 'Transacao'), ('ptbr_messages', 'Mensagens pt-BR'), ('docs', 'Documentacao'), ('menu', 'Menu'), ('tests', 'Testes'), ('api', 'API')], max_length=32, verbose_name='tipo de check')),
                ('status', models.CharField(choices=[('pass', 'Aprovado'), ('warning', 'Alerta'), ('fail', 'Falhou')], max_length=16, verbose_name='status')),
                ('evidence', models.TextField(verbose_name='evidencia')),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='verificado em')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_checks', to=settings.AUTH_USER_MODEL, verbose_name='verificado por')),
                ('source_module_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='modulo normalizado')),
            ],
            options={
                'verbose_name': 'item de checklist transversal',
                'verbose_name_plural': 'itens de checklist transversal',
                'ordering': ['source_module', 'check_type'],
                'indexes': [models.Index(fields=['source_module', 'status'], name='compliance__source__2c29f1_idx'), models.Index(fields=['check_type'], name='compliance__check_t_c73e4c_idx'), models.Index(fields=['checked_by'], name='compliance__checked_68f236_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_module', 'check_type'), name='unique_module_compliance_check')],
            },
        ),
        migrations.CreateModel(
            name='CriticalActionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('action_code', models.CharField(max_length=120, verbose_name='codigo da acao')),
                ('source_module', models.CharField(choices=[('auxiliary', 'Cadastros auxiliares'), ('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo')),
                ('target_model', models.CharField(blank=True, max_length=120, verbose_name='modelo alvo')),
                ('target_record_id', models.CharField(blank=True, max_length=120, verbose_name='registro alvo')),
                ('status', models.CharField(choices=[('running', 'Executando'), ('succeeded', 'Concluido'), ('failed', 'Falhou')], default='running', max_length=24, verbose_name='status')),
                ('requires_transaction', models.BooleanField(default=True, verbose_name='exige transacao')),
                ('transaction_id', models.CharField(blank=True, default='', max_length=64, unique=True, verbose_name='id da transacao')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('safe_context', models.JSONField(blank=True, default=dict, verbose_name='contexto seguro')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluido em')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='critical_action_executions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('source_module_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='modulo normalizado')),
                ('target_model_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model alvo normalizado')),
            ],
            options={
                'verbose_name': 'execução de ação crítica',
                'verbose_name_plural': 'execuções de ações críticas',
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['source_module', 'status'], name='compliance__source__c6bd76_idx'), models.Index(fields=['actor'], name='compliance__actor_i_0f93cf_idx'), models.Index(fields=['target_model', 'target_record_id'], name='compliance__target__0b2807_idx'), models.Index(fields=['transaction_id'], name='compliance__transac_eb8d77_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecordStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('source_module', models.CharField(choices=[('auxiliary', 'Cadastros auxiliares'), ('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo')),
                ('target_model', models.CharField(max_length=120, verbose_name='modelo alvo')),
                ('target_record_id', models.CharField(max_length=120, verbose_name='registro alvo')),
                ('previous_status', models.CharField(max_length=80, verbose_name='status anterior')),
                ('new_status', models.CharField(max_length=80, verbose_name='novo status')),
                ('action', models.CharField(max_length=120, verbose_name='acao')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ocorrido em')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='record_status_history', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('source_module_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='modulo normalizado')),
                ('target_model_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model alvo normalizado')),
            ],
            options={
                'verbose_name': 'historico de status',
                'verbose_name_plural': 'historicos de status',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['source_module', 'target_model', 'target_record_id'], name='compliance__source__a87571_idx'), models.Index(fields=['new_status'], name='compliance__new_sta_d433c7_idx'), models.Index(fields=['actor'], name='compliance__actor_i_9f0f6c_idx'), models.Index(fields=['occurred_at'], name='compliance__occurre_6bf2db_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransversalRequirementPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='codigo')),
                ('title', models.CharField(max_length=180, verbose_name='titulo')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('source_module', models.CharField(choices=[('auxiliary', 'Cadastros auxiliares'), ('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo')),
                ('enforcement_level', models.CharField(choices=[('monitoring', 'Monitoramento'), ('warning', 'Alerta'), ('blocking', 'Bloqueante')], default='warning', max_length=24, verbose_name='nivel de exigencia')),
                ('require_single_instance_scope', models.BooleanField(default=True, verbose_name='exige escopo single-instance')),
                ('require_permission_check', models.BooleanField(default=True, verbose_name='exige permissao')),
                ('require_audit_log', models.BooleanField(default=True, verbose_name='exige auditoria')),
                ('require_status_history', models.BooleanField(default=True, verbose_name='exige historico de status')),
                ('require_transaction', models.BooleanField(default=True, verbose_name='exige transacao')),
                ('require_ptbr_messages', models.BooleanField(default=True, verbose_name='exige mensagens pt-BR')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_transversal_policies', to=settings.AUTH_USER_MODEL, verbose_name='responsavel')),
                ('source_module_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='modulo normalizado')),
            ],
            options={
                'verbose_name': 'politica transversal',
                'verbose_name_plural': 'politicas transversais',
                'ordering': ['source_module', 'code'],
                'indexes': [models.Index(fields=['source_module', 'is_active'], name='compliance__source__5cdbd0_idx'), models.Index(fields=['enforcement_level'], name='compliance__enforce_832985_idx'), models.Index(fields=['owner'], name='compliance__owner_i_7d9e43_idx'), models.Index(fields=['code'], name='compliance__code_2aa008_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_transversal_policy_code')],
            },
        ),
    ]
