# Generated by Django 6.0.7 on 2026-07-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancechecklistitem',
            name='source_module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='modulo normalizado'),
        ),
        migrations.AddField(
            model_name='criticalactionexecution',
            name='source_module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='modulo normalizado'),
        ),
        migrations.AddField(
            model_name='criticalactionexecution',
            name='target_model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model alvo normalizado'),
        ),
        migrations.AddField(
            model_name='recordstatushistory',
            name='source_module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='modulo normalizado'),
        ),
        migrations.AddField(
            model_name='recordstatushistory',
            name='target_model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model alvo normalizado'),
        ),
        migrations.AddField(
            model_name='transversalrequirementpolicy',
            name='source_module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='modulo normalizado'),
        ),
    ]
