# Generated by Django 6.0.7 on 2026-07-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_compliancechecklistitem_source_module_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancechecklistitem',
            name='source_module',
            field=models.CharField(choices=[('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('knowledge', 'Conhecimento RAG'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
        migrations.AlterField(
            model_name='criticalactionexecution',
            name='source_module',
            field=models.CharField(choices=[('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('knowledge', 'Conhecimento RAG'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
        migrations.AlterField(
            model_name='recordstatushistory',
            name='source_module',
            field=models.CharField(choices=[('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('knowledge', 'Conhecimento RAG'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
        migrations.AlterField(
            model_name='transversalrequirementpolicy',
            name='source_module',
            field=models.CharField(choices=[('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('knowledge', 'Conhecimento RAG'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
    ]
