# Generated by Django 5.2.2 on 2026-07-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_alter_compliancechecklistitem_source_module_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criticalactionexecution',
            options={'ordering': ['-started_at', '-created_at'], 'verbose_name': 'execução de ação crítica', 'verbose_name_plural': 'execuções de ações críticas'},
        ),
    ]
