# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('compliance', '0004_alter_criticalactionexecution_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='compliancechecklistitem',
            name='unique_tenant_module_compliance_check',
        ),
        migrations.RemoveConstraint(
            model_name='transversalrequirementpolicy',
            name='unique_tenant_transversal_policy_code',
        ),
        migrations.RemoveIndex(
            model_name='compliancechecklistitem',
            name='compliance__tenant__666ca6_idx',
        ),
        migrations.RemoveIndex(
            model_name='compliancechecklistitem',
            name='compliance__tenant__7e6d55_idx',
        ),
        migrations.RemoveIndex(
            model_name='compliancechecklistitem',
            name='compliance__tenant__000694_idx',
        ),
        migrations.RemoveIndex(
            model_name='criticalactionexecution',
            name='compliance__tenant__d8746e_idx',
        ),
        migrations.RemoveIndex(
            model_name='criticalactionexecution',
            name='compliance__tenant__162285_idx',
        ),
        migrations.RemoveIndex(
            model_name='recordstatushistory',
            name='compliance__tenant__f15593_idx',
        ),
        migrations.RemoveIndex(
            model_name='recordstatushistory',
            name='compliance__tenant__e5e7a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='recordstatushistory',
            name='compliance__tenant__70adc3_idx',
        ),
        migrations.RemoveIndex(
            model_name='recordstatushistory',
            name='compliance__tenant__4f8dbc_idx',
        ),
        migrations.RemoveIndex(
            model_name='transversalrequirementpolicy',
            name='compliance__tenant__5755a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='transversalrequirementpolicy',
            name='compliance__tenant__f1edd8_idx',
        ),
        migrations.RemoveIndex(
            model_name='transversalrequirementpolicy',
            name='compliance__tenant__49bae2_idx',
        ),
        migrations.RemoveField(
            model_name='compliancechecklistitem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='criticalactionexecution',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='recordstatushistory',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='transversalrequirementpolicy',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='compliancechecklistitem',
            index=models.Index(fields=['source_module', 'status'], name='compliance__source__2c29f1_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancechecklistitem',
            index=models.Index(fields=['check_type'], name='compliance__check_t_c73e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancechecklistitem',
            index=models.Index(fields=['checked_by'], name='compliance__checked_68f236_idx'),
        ),
        migrations.AddIndex(
            model_name='criticalactionexecution',
            index=models.Index(fields=['source_module', 'status'], name='compliance__source__c6bd76_idx'),
        ),
        migrations.AddIndex(
            model_name='criticalactionexecution',
            index=models.Index(fields=['actor'], name='compliance__actor_i_0f93cf_idx'),
        ),
        migrations.AddIndex(
            model_name='recordstatushistory',
            index=models.Index(fields=['source_module', 'target_model', 'target_record_id'], name='compliance__source__a87571_idx'),
        ),
        migrations.AddIndex(
            model_name='recordstatushistory',
            index=models.Index(fields=['new_status'], name='compliance__new_sta_d433c7_idx'),
        ),
        migrations.AddIndex(
            model_name='recordstatushistory',
            index=models.Index(fields=['actor'], name='compliance__actor_i_9f0f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='recordstatushistory',
            index=models.Index(fields=['occurred_at'], name='compliance__occurre_6bf2db_idx'),
        ),
        migrations.AddIndex(
            model_name='transversalrequirementpolicy',
            index=models.Index(fields=['source_module', 'is_active'], name='compliance__source__5cdbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='transversalrequirementpolicy',
            index=models.Index(fields=['enforcement_level'], name='compliance__enforce_832985_idx'),
        ),
        migrations.AddIndex(
            model_name='transversalrequirementpolicy',
            index=models.Index(fields=['owner'], name='compliance__owner_i_7d9e43_idx'),
        ),
        migrations.AddConstraint(
            model_name='compliancechecklistitem',
            constraint=models.UniqueConstraint(fields=('source_module', 'check_type'), name='unique_module_compliance_check'),
        ),
        migrations.AddConstraint(
            model_name='transversalrequirementpolicy',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_transversal_policy_code'),
        ),
    ]
