# Generated by Django 5.2.16 on 2026-07-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_remove_compliancechecklistitem_unique_tenant_module_compliance_check_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transversalrequirementpolicy',
            old_name='require_tenant_scope',
            new_name='require_single_instance_scope',
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE compliance_compliancechecklistitem "
                "SET check_type = 'single_instance_scope' "
                "WHERE check_type = 'tenant_scope';"
            ),
            reverse_sql=(
                "UPDATE compliance_compliancechecklistitem "
                "SET check_type = 'tenant_scope' "
                "WHERE check_type = 'single_instance_scope';"
            ),
        ),
        migrations.AlterField(
            model_name='transversalrequirementpolicy',
            name='require_single_instance_scope',
            field=models.BooleanField(default=True, verbose_name='exige escopo single-instance'),
        ),
        migrations.AlterField(
            model_name='compliancechecklistitem',
            name='check_type',
            field=models.CharField(choices=[('single_instance_scope', 'Single-instance'), ('permission', 'Permissao'), ('audit', 'Auditoria'), ('status_history', 'Historico de status'), ('transaction', 'Transacao'), ('ptbr_messages', 'Mensagens pt-BR'), ('docs', 'Documentacao'), ('menu', 'Menu'), ('tests', 'Testes'), ('api', 'API')], max_length=32, verbose_name='tipo de check'),
        ),
    ]
