# Generated by Django 5.2.16 on 2026-07-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_rename_legacy_tenant_not_null_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancechecklistitem',
            name='source_module',
            field=models.CharField(choices=[('auxiliary', 'Cadastros auxiliares'), ('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('knowledge', 'Conhecimento RAG'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
        migrations.AlterField(
            model_name='criticalactionexecution',
            name='source_module',
            field=models.CharField(choices=[('auxiliary', 'Cadastros auxiliares'), ('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('knowledge', 'Conhecimento RAG'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
        migrations.AlterField(
            model_name='recordstatushistory',
            name='source_module',
            field=models.CharField(choices=[('auxiliary', 'Cadastros auxiliares'), ('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('knowledge', 'Conhecimento RAG'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
        migrations.AlterField(
            model_name='transversalrequirementpolicy',
            name='source_module',
            field=models.CharField(choices=[('auxiliary', 'Cadastros auxiliares'), ('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('knowledge', 'Conhecimento RAG'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
    ]
