# Generated by Django 6.0.8 on 2026-08-26 02:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeIndexGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('generation_id', models.CharField(max_length=64, unique=True, verbose_name='geração')),
                ('redis_index_name', models.CharField(max_length=180, unique=True, verbose_name='índice Redis')),
                ('status', models.CharField(choices=[('building', 'Em construção'), ('ready', 'Pronta'), ('active', 'Ativa'), ('failed', 'Falhou'), ('retired', 'Desativada')], default='building', max_length=24, verbose_name='status')),
                ('embedding_model', models.CharField(blank=True, max_length=160, verbose_name='modelo de embedding')),
                ('embedding_dimensions', models.PositiveIntegerField(default=0, verbose_name='dimensões do embedding')),
                ('chunk_count', models.PositiveIntegerField(default=0, verbose_name='quantidade de chunks')),
                ('manifest_hash', models.CharField(blank=True, max_length=64, verbose_name='hash do manifesto')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='ativada em')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
            ],
            options={
                'verbose_name': 'geração do índice de conhecimento',
                'verbose_name_plural': 'gerações do índice de conhecimento',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='knowledge_k_status_a858ad_idx'), models.Index(fields=['activated_at'], name='knowledge_k_activat_17830b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='unique_active_knowledge_generation')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=100, verbose_name='código')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('source_type', models.CharField(choices=[('regulation', 'Legislação'), ('pharmacopoeia', 'Farmacopeia'), ('guideline', 'Guia'), ('standard', 'Norma'), ('book_reference', 'Referência bibliográfica'), ('web', 'Página web'), ('system_manual', 'Manual do sistema'), ('other', 'Outra')], max_length=32, verbose_name='tipo')),
                ('publisher', models.CharField(max_length=160, verbose_name='publicador')),
                ('jurisdiction', models.CharField(blank=True, max_length=80, verbose_name='jurisdição')),
                ('version', models.CharField(blank=True, max_length=120, verbose_name='versão')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='URL')),
                ('license_note', models.TextField(blank=True, verbose_name='nota de licença')),
                ('is_official', models.BooleanField(default=False, verbose_name='fonte oficial')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('chat_eligible', models.BooleanField(default=False, verbose_name='elegível para o manual do ERP')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
            ],
            options={
                'verbose_name': 'fonte de conhecimento',
                'verbose_name_plural': 'fontes de conhecimento',
                'ordering': ['publisher', 'code'],
                'indexes': [models.Index(fields=['source_type', 'is_active'], name='knowledge_k_source__db1b5b_idx'), models.Index(fields=['source_type', 'chat_eligible', 'is_active'], name='knowledge_source_manual_idx'), models.Index(fields=['publisher'], name='knowledge_k_publish_add322_idx'), models.Index(fields=['code'], name='knowledge_k_code_b42a1f_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_knowledge_source_code')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('document_type', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('text', 'Texto'), ('reference', 'Referência')], max_length=24, verbose_name='tipo de documento')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='URL de origem')),
                ('version_label', models.CharField(blank=True, max_length=120, verbose_name='versão')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='publicado em')),
                ('retrieved_at', models.DateTimeField(blank=True, null=True, verbose_name='coletado em')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('ingested', 'Ingerido'), ('failed', 'Falhou')], default='pending', max_length=24, verbose_name='status')),
                ('content_hash', models.CharField(max_length=64, verbose_name='hash do conteúdo')),
                ('extracted_text', models.TextField(blank=True, verbose_name='texto extraído')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='knowledge.knowledgesource', verbose_name='fonte')),
            ],
            options={
                'verbose_name': 'documento de conhecimento',
                'verbose_name_plural': 'documentos de conhecimento',
                'ordering': ['source__publisher', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('chunk_index', models.PositiveIntegerField(verbose_name='índice')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('section_reference', models.CharField(blank=True, max_length=180, verbose_name='seção')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='página')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('content_hash', models.CharField(max_length=64, verbose_name='hash do conteúdo')),
                ('token_count', models.PositiveIntegerField(default=0, verbose_name='tokens')),
                ('embedding_vector', models.JSONField(blank=True, default=list, verbose_name='vetor')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument', verbose_name='documento')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chunks', to='knowledge.knowledgesource', verbose_name='fonte')),
            ],
            options={
                'verbose_name': 'chunk de conhecimento',
                'verbose_name_plural': 'chunks de conhecimento',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='RAGChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Encerrada')], default='open', max_length=24, verbose_name='status')),
                ('last_question_at', models.DateTimeField(blank=True, null=True, verbose_name='última pergunta em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rag_chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
            ],
            options={
                'verbose_name': 'sessão de chat RAG',
                'verbose_name_plural': 'sessões de chat RAG',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('system', 'Sistema')], max_length=24, verbose_name='papel')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('model_name', models.CharField(blank=True, max_length=160, verbose_name='modelo')),
                ('status', models.CharField(choices=[('succeeded', 'Concluída'), ('failed', 'Falhou')], default='succeeded', max_length=24, verbose_name='status')),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='latência ms')),
                ('retrieved_context', models.JSONField(blank=True, default=list, verbose_name='contexto recuperado')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rag_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='knowledge.ragchatsession', verbose_name='sessão')),
            ],
            options={
                'verbose_name': 'mensagem de chat RAG',
                'verbose_name_plural': 'mensagens de chat RAG',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='URL')),
                ('section_reference', models.CharField(blank=True, max_length=180, verbose_name='seção')),
                ('excerpt', models.TextField(verbose_name='trecho')),
                ('relevance_score', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='relevância')),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='knowledge.knowledgechunk', verbose_name='chunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='knowledge.knowledgedocument', verbose_name='documento')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='knowledge.ragchatmessage', verbose_name='mensagem')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='knowledge.knowledgesource', verbose_name='fonte')),
            ],
            options={
                'verbose_name': 'citação RAG',
                'verbose_name_plural': 'citações RAG',
                'ordering': ['-relevance_score', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeIngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('started', 'Iniciada'), ('succeeded', 'Concluída'), ('failed', 'Falhou'), ('skipped', 'Ignorada')], default='started', max_length=24, verbose_name='status')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='iniciada em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('chunks_created', models.PositiveIntegerField(default=0, verbose_name='chunks criados')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='detalhes')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_logs', to='knowledge.knowledgedocument', verbose_name='documento')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_logs', to='knowledge.knowledgesource', verbose_name='fonte')),
            ],
            options={
                'verbose_name': 'log de ingestão RAG',
                'verbose_name_plural': 'logs de ingestão RAG',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='knowledge_k_source__6af311_idx'), models.Index(fields=['started_at'], name='knowledge_k_started_bf47a3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['source', 'status'], name='knowledge_k_source__82f51b_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['document_type'], name='knowledge_k_documen_a9d211_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['content_hash'], name='knowledge_k_content_ad5a56_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['retrieved_at'], name='knowledge_k_retriev_827889_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.UniqueConstraint(fields=('source', 'content_hash'), name='unique_knowledge_document_hash'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['source'], name='knowledge_k_source__d1157e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['document'], name='knowledge_k_documen_60a89c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['content_hash'], name='knowledge_k_content_6db3af_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_document_chunk_index'),
        ),
        migrations.AddIndex(
            model_name='ragchatsession',
            index=models.Index(fields=['created_by', 'status'], name='knowledge_r_created_e7b926_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchatsession',
            index=models.Index(fields=['last_question_at'], name='knowledge_r_last_qu_deddf4_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchatmessage',
            index=models.Index(fields=['session', 'created_at'], name='knowledge_r_session_a95ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchatmessage',
            index=models.Index(fields=['role', 'status'], name='knowledge_r_role_72933f_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchatmessage',
            index=models.Index(fields=['created_by'], name='knowledge_r_created_c73e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='ragcitation',
            index=models.Index(fields=['message'], name='knowledge_r_message_531162_idx'),
        ),
        migrations.AddIndex(
            model_name='ragcitation',
            index=models.Index(fields=['source'], name='knowledge_r_source__9478ff_idx'),
        ),
        migrations.AddIndex(
            model_name='ragcitation',
            index=models.Index(fields=['document'], name='knowledge_r_documen_e7962f_idx'),
        ),
    ]
