# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='knowledgechunk',
            name='unique_tenant_document_chunk_index',
        ),
        migrations.RemoveConstraint(
            model_name='knowledgedocument',
            name='unique_tenant_knowledge_document_hash',
        ),
        migrations.RemoveConstraint(
            model_name='knowledgesource',
            name='unique_tenant_knowledge_source_code',
        ),
        migrations.RemoveIndex(
            model_name='knowledgechunk',
            name='knowledge_k_tenant__6508c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgechunk',
            name='knowledge_k_tenant__446103_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgechunk',
            name='knowledge_k_tenant__e69297_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgedocument',
            name='knowledge_k_tenant__86f5d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgedocument',
            name='knowledge_k_tenant__e42b9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgeingestionlog',
            name='knowledge_k_tenant__6405c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgeingestionlog',
            name='knowledge_k_tenant__e6c20e_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgesource',
            name='knowledge_k_tenant__2239d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgesource',
            name='knowledge_k_tenant__f00b31_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragchatmessage',
            name='knowledge_r_tenant__879236_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragchatmessage',
            name='knowledge_r_tenant__1a8a7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragchatmessage',
            name='knowledge_r_tenant__6d970a_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragchatsession',
            name='knowledge_r_tenant__9a2182_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragchatsession',
            name='knowledge_r_tenant__0091e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragcitation',
            name='knowledge_r_tenant__aeef43_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragcitation',
            name='knowledge_r_tenant__95a08c_idx',
        ),
        migrations.RemoveIndex(
            model_name='ragcitation',
            name='knowledge_r_tenant__a546ec_idx',
        ),
        migrations.RemoveField(
            model_name='knowledgechunk',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='knowledgeingestionlog',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='knowledgesource',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='ragchatmessage',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='ragchatsession',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='ragcitation',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['source'], name='knowledge_k_source__d1157e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['document'], name='knowledge_k_documen_60a89c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['content_hash'], name='knowledge_k_content_6db3af_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['source', 'status'], name='knowledge_k_source__82f51b_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['document_type'], name='knowledge_k_documen_a9d211_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeingestionlog',
            index=models.Index(fields=['source', 'status'], name='knowledge_k_source__6af311_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeingestionlog',
            index=models.Index(fields=['started_at'], name='knowledge_k_started_bf47a3_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['source_type', 'is_active'], name='knowledge_k_source__db1b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['publisher'], name='knowledge_k_publish_add322_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchatmessage',
            index=models.Index(fields=['session', 'created_at'], name='knowledge_r_session_a95ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchatmessage',
            index=models.Index(fields=['role', 'status'], name='knowledge_r_role_72933f_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchatmessage',
            index=models.Index(fields=['created_by'], name='knowledge_r_created_c73e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchatsession',
            index=models.Index(fields=['created_by', 'status'], name='knowledge_r_created_e7b926_idx'),
        ),
        migrations.AddIndex(
            model_name='ragchatsession',
            index=models.Index(fields=['last_question_at'], name='knowledge_r_last_qu_deddf4_idx'),
        ),
        migrations.AddIndex(
            model_name='ragcitation',
            index=models.Index(fields=['message'], name='knowledge_r_message_531162_idx'),
        ),
        migrations.AddIndex(
            model_name='ragcitation',
            index=models.Index(fields=['source'], name='knowledge_r_source__9478ff_idx'),
        ),
        migrations.AddIndex(
            model_name='ragcitation',
            index=models.Index(fields=['document'], name='knowledge_r_documen_e7962f_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_document_chunk_index'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.UniqueConstraint(fields=('source', 'content_hash'), name='unique_knowledge_document_hash'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_knowledge_source_code'),
        ),
    ]
