# Generated by Django 5.2.16 on 2026-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_remove_knowledgechunk_unique_tenant_document_chunk_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgesource',
            name='code',
            field=models.CharField(blank=True, max_length=100, verbose_name='código'),
        ),
    ]
