# Generated by Django 6.0.7 on 2026-07-07 22:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('documents', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        ('quality', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('event_number', models.CharField(blank=True, max_length=80, verbose_name='evento')),
                ('event_type', models.CharField(choices=[('deviation', 'Desvio'), ('nonconformity', 'Não conformidade')], max_length=24, verbose_name='tipo')),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automática'), ('production', 'Produção'), ('quality_control', 'Controle de qualidade'), ('customer_complaint', 'Reclamação de cliente'), ('supplier', 'Fornecedor'), ('audit', 'Auditoria'), ('inventory', 'Estoque'), ('document', 'Documento')], max_length=32, verbose_name='origem')),
                ('area', models.CharField(max_length=120, verbose_name='área')),
                ('equipment_reference', models.CharField(blank=True, max_length=120, verbose_name='equipamento')),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=24, verbose_name='severidade')),
                ('criticality', models.CharField(choices=[('minor', 'Menor'), ('major', 'Maior'), ('critical', 'Crítica')], max_length=24, verbose_name='criticidade')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('under_investigation', 'Em investigação'), ('pending_approval', 'Pendente de aprovação'), ('closed', 'Encerrado'), ('cancelled', 'Cancelado')], default='open', max_length=32, verbose_name='status')),
                ('description', models.TextField(verbose_name='descrição')),
                ('detected_at', models.DateTimeField(verbose_name='detectado em')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='aberto em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrado em')),
                ('closure_summary', models.TextField(blank=True, verbose_name='resumo de encerramento')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_quality_events', to=settings.AUTH_USER_MODEL, verbose_name='encerrado por')),
                ('controlled_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_events', to='documents.controlleddocument', verbose_name='documento controlado')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_quality_events', to='masters.businesspartner', verbose_name='cliente')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opened_quality_events', to=settings.AUTH_USER_MODEL, verbose_name='aberto por')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_events', to='masters.product', verbose_name='produto')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_quality_events', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_events', to='inventory.stocklot', verbose_name='lote')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quality_events', to='masters.businesspartner', verbose_name='fornecedor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'desvio/não conformidade',
                'verbose_name_plural': 'desvios/não conformidades',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('link_type', models.CharField(choices=[('capa', 'CAPA'), ('change', 'Mudança'), ('audit', 'Auditoria'), ('complaint', 'Reclamação'), ('oos_oot', 'OOS/OOT'), ('lot', 'Lote'), ('document', 'Documento'), ('risk', 'Risco')], max_length=24, verbose_name='tipo de vínculo')),
                ('reference_code', models.CharField(blank=True, max_length=120, verbose_name='referência')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('controlled_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deviation_links', to='documents.controlleddocument', verbose_name='documento')),
                ('customer_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deviation_links', to='crm.customercomplaint', verbose_name='reclamação')),
                ('quality_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deviation_links', to='quality.qualityresult', verbose_name='resultado OOS/OOT')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deviation_links', to='inventory.stocklot', verbose_name='lote')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='deviations.qualityevent', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'vínculo de desvio',
                'verbose_name_plural': 'vínculos de desvios',
                'ordering': ['event__event_number', 'link_type'],
            },
        ),
        migrations.CreateModel(
            name='DeviationInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em andamento'), ('concluded', 'Concluída'), ('cancelled', 'Cancelada')], default='open', max_length=24, verbose_name='status')),
                ('immediate_actions', models.TextField(verbose_name='ações imediatas')),
                ('containment_actions', models.TextField(verbose_name='ações de contenção')),
                ('root_cause', models.TextField(blank=True, verbose_name='causa raiz')),
                ('impact_conclusion', models.TextField(blank=True, verbose_name='conclusão de impacto')),
                ('conclusion', models.TextField(blank=True, verbose_name='conclusão')),
                ('concluded_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('concluded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concluded_deviation_investigations', to=settings.AUTH_USER_MODEL, verbose_name='concluído por')),
                ('investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deviation_investigations', to=settings.AUTH_USER_MODEL, verbose_name='investigador')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='deviations.qualityevent', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'investigação de desvio',
                'verbose_name_plural': 'investigações de desvios',
                'ordering': ['event__event_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviationImpactAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('impacts_quality', models.BooleanField(default=False, verbose_name='impacta qualidade')),
                ('impacts_safety', models.BooleanField(default=False, verbose_name='impacta segurança')),
                ('impacts_efficacy', models.BooleanField(default=False, verbose_name='impacta eficácia')),
                ('impacts_regulatory', models.BooleanField(default=False, verbose_name='impacta regulatório')),
                ('impacts_patient', models.BooleanField(default=False, verbose_name='impacta paciente')),
                ('impacts_inventory', models.BooleanField(default=False, verbose_name='impacta estoque')),
                ('impacts_cost', models.BooleanField(default=False, verbose_name='impacta custo')),
                ('impacts_deadline', models.BooleanField(default=False, verbose_name='impacta prazo')),
                ('summary', models.TextField(verbose_name='sumário de impacto')),
                ('is_completed', models.BooleanField(default=False, verbose_name='concluída')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessed_deviation_impacts', to=settings.AUTH_USER_MODEL, verbose_name='avaliado por')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_deviation_impacts', to=settings.AUTH_USER_MODEL, verbose_name='concluído por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_assessment', to='deviations.qualityevent', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'avaliação de impacto de desvio',
                'verbose_name_plural': 'avaliações de impacto de desvios',
                'ordering': ['event__event_number'],
            },
        ),
        migrations.CreateModel(
            name='DeviationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('file_reference', models.CharField(max_length=255, verbose_name='arquivo')),
                ('content_hash', models.CharField(max_length=128, verbose_name='hash do conteúdo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_deviation_evidences', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='deviations.qualityevent', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'evidência de desvio',
                'verbose_name_plural': 'evidências de desvios',
                'ordering': ['event__event_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DeviationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(choices=[('qa', 'Garantia da Qualidade'), ('qc', 'Controle de Qualidade'), ('production', 'Produção'), ('regulatory', 'Regulatório'), ('responsible_area', 'Área responsável')], max_length=32, verbose_name='papel')),
                ('required', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('decision', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=24, verbose_name='decisão')),
                ('comments', models.TextField(blank=True, verbose_name='comentários')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidido em')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deviation_approvals', to=settings.AUTH_USER_MODEL, verbose_name='aprovador')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_deviation_approvals', to=settings.AUTH_USER_MODEL, verbose_name='decidido por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='deviations.qualityevent', verbose_name='evento')),
            ],
            options={
                'verbose_name': 'aprovação de desvio',
                'verbose_name_plural': 'aprovações de desvios',
                'ordering': ['event__event_number', 'role'],
            },
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['tenant', 'event_type', 'status'], name='deviations__tenant__6e2bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['tenant', 'origin'], name='deviations__tenant__2b571c_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['tenant', 'severity', 'criticality'], name='deviations__tenant__14ba5a_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['tenant', 'product'], name='deviations__tenant__48428c_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['tenant', 'stock_lot'], name='deviations__tenant__b33437_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['event_number'], name='deviations__event_n_51eb53_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'event_number'), name='unique_tenant_quality_event_number'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['tenant', 'event', 'link_type'], name='deviations__tenant__0d6191_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['tenant', 'customer_complaint'], name='deviations__tenant__5b965a_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['tenant', 'quality_result'], name='deviations__tenant__778175_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['tenant', 'stock_lot'], name='deviations__tenant__4a17c6_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['tenant', 'controlled_document'], name='deviations__tenant__6071c3_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['reference_code'], name='deviations__referen_9e54c4_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationinvestigation',
            index=models.Index(fields=['tenant', 'event', 'status'], name='deviations__tenant__47bc8f_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationinvestigation',
            index=models.Index(fields=['tenant', 'investigator'], name='deviations__tenant__c863dd_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationimpactassessment',
            index=models.Index(fields=['tenant', 'event'], name='deviations__tenant__3a5558_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationimpactassessment',
            index=models.Index(fields=['tenant', 'is_completed'], name='deviations__tenant__d724e6_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationevidence',
            index=models.Index(fields=['tenant', 'event'], name='deviations__tenant__e4a34e_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationevidence',
            index=models.Index(fields=['content_hash'], name='deviations__content_e18976_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationapproval',
            index=models.Index(fields=['tenant', 'event', 'decision'], name='deviations__tenant__2355c0_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationapproval',
            index=models.Index(fields=['tenant', 'approver'], name='deviations__tenant__02b24b_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviationapproval',
            constraint=models.UniqueConstraint(fields=('tenant', 'event', 'role', 'approver'), name='unique_tenant_deviation_approval_role_user'),
        ),
    ]
