# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('deviations', '0001_initial'),
        ('documents', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deviationlink',
            name='quality_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deviation_links', to='quality.qualityresult', verbose_name='resultado OOS/OOT'),
        ),
        migrations.AddField(
            model_name='deviationlink',
            name='stock_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deviation_links', to='inventory.stocklot', verbose_name='lote'),
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='area_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.businessarea', verbose_name='área normalizada'),
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_quality_events', to=settings.AUTH_USER_MODEL, verbose_name='encerrado por'),
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='controlled_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_events', to='documents.controlleddocument', verbose_name='documento controlado'),
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='criticality_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='criticidade normalizada'),
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_quality_events', to='masters.businesspartner', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opened_quality_events', to=settings.AUTH_USER_MODEL, verbose_name='aberto por'),
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_events', to='masters.product', verbose_name='produto'),
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_quality_events', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='severity_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='severidade normalizada'),
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='stock_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_events', to='inventory.stocklot', verbose_name='lote'),
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quality_events', to='masters.businesspartner', verbose_name='fornecedor'),
        ),
        migrations.AddField(
            model_name='deviationlink',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='deviations.qualityevent', verbose_name='evento'),
        ),
        migrations.AddField(
            model_name='deviationinvestigation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='deviations.qualityevent', verbose_name='evento'),
        ),
        migrations.AddField(
            model_name='deviationimpactassessment',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_assessment', to='deviations.qualityevent', verbose_name='evento'),
        ),
        migrations.AddField(
            model_name='deviationevidence',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='deviations.qualityevent', verbose_name='evento'),
        ),
        migrations.AddField(
            model_name='deviationapproval',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='deviations.qualityevent', verbose_name='evento'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['event_type', 'status'], name='deviations__event_t_603960_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['origin'], name='deviations__origin_884e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['severity', 'criticality'], name='deviations__severit_8138ba_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['product'], name='deviations__product_88bbe9_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['stock_lot'], name='deviations__stock_l_1cf0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['event_number'], name='deviations__event_n_51eb53_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityevent',
            constraint=models.UniqueConstraint(fields=('event_number',), name='unique_quality_event_number'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['event', 'link_type'], name='deviations__event_i_bb385b_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['customer_complaint'], name='deviations__custome_dcbd3a_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['quality_result'], name='deviations__quality_4b80e9_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['stock_lot'], name='deviations__stock_l_0142ed_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['controlled_document'], name='deviations__control_7a010c_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['reference_code'], name='deviations__referen_9e54c4_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationinvestigation',
            index=models.Index(fields=['event', 'status'], name='deviations__event_i_600fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationinvestigation',
            index=models.Index(fields=['investigator'], name='deviations__investi_ff5051_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationimpactassessment',
            index=models.Index(fields=['event'], name='deviations__event_i_14dae1_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationimpactassessment',
            index=models.Index(fields=['is_completed'], name='deviations__is_comp_d7d742_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationevidence',
            index=models.Index(fields=['event'], name='deviations__event_i_a9afca_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationevidence',
            index=models.Index(fields=['content_hash'], name='deviations__content_e18976_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationapproval',
            index=models.Index(fields=['event', 'decision'], name='deviations__event_i_fae2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationapproval',
            index=models.Index(fields=['approver'], name='deviations__approve_f559fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviationapproval',
            constraint=models.UniqueConstraint(fields=('event', 'role', 'approver'), name='unique_deviation_approval_role_user'),
        ),
    ]
