# Generated by Django 6.0.7 on 2026-07-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('deviations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityevent',
            name='area_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.businessarea', verbose_name='área normalizada'),
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='criticality_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='criticidade normalizada'),
        ),
        migrations.AddField(
            model_name='qualityevent',
            name='severity_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='severidade normalizada'),
        ),
    ]
