# Generated by Django 6.0.8 on 2026-08-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityevent',
            name='equipment_reference',
        ),
    ]
