# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('crm', '0004_remove_campaign_unique_tenant_campaign_code_and_more'),
        ('deviations', '0002_qualityevent_area_ref_qualityevent_criticality_ref_and_more'),
        ('documents', '0003_remove_controlleddocument_unique_tenant_document_code_version_and_more'),
        ('inventory', '0002_remove_stockbalance_unique_tenant_stock_balance_address_status_and_more'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('quality', '0003_remove_analyticalspecification_unique_tenant_qc_spec_product_lot_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deviationapproval',
            name='unique_tenant_deviation_approval_role_user',
        ),
        migrations.RemoveConstraint(
            model_name='qualityevent',
            name='unique_tenant_quality_event_number',
        ),
        migrations.RemoveIndex(
            model_name='deviationapproval',
            name='deviations__tenant__2355c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviationapproval',
            name='deviations__tenant__02b24b_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviationevidence',
            name='deviations__tenant__e4a34e_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviationimpactassessment',
            name='deviations__tenant__3a5558_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviationimpactassessment',
            name='deviations__tenant__d724e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviationinvestigation',
            name='deviations__tenant__47bc8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviationinvestigation',
            name='deviations__tenant__c863dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviationlink',
            name='deviations__tenant__0d6191_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviationlink',
            name='deviations__tenant__5b965a_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviationlink',
            name='deviations__tenant__778175_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviationlink',
            name='deviations__tenant__4a17c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviationlink',
            name='deviations__tenant__6071c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityevent',
            name='deviations__tenant__6e2bd5_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityevent',
            name='deviations__tenant__2b571c_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityevent',
            name='deviations__tenant__14ba5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityevent',
            name='deviations__tenant__48428c_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityevent',
            name='deviations__tenant__b33437_idx',
        ),
        migrations.RemoveField(
            model_name='deviationapproval',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='deviationevidence',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='deviationimpactassessment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='deviationinvestigation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='deviationlink',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='qualityevent',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='deviationapproval',
            index=models.Index(fields=['event', 'decision'], name='deviations__event_i_fae2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationapproval',
            index=models.Index(fields=['approver'], name='deviations__approve_f559fc_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationevidence',
            index=models.Index(fields=['event'], name='deviations__event_i_a9afca_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationimpactassessment',
            index=models.Index(fields=['event'], name='deviations__event_i_14dae1_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationimpactassessment',
            index=models.Index(fields=['is_completed'], name='deviations__is_comp_d7d742_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationinvestigation',
            index=models.Index(fields=['event', 'status'], name='deviations__event_i_600fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationinvestigation',
            index=models.Index(fields=['investigator'], name='deviations__investi_ff5051_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['event', 'link_type'], name='deviations__event_i_bb385b_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['customer_complaint'], name='deviations__custome_dcbd3a_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['quality_result'], name='deviations__quality_4b80e9_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['stock_lot'], name='deviations__stock_l_0142ed_idx'),
        ),
        migrations.AddIndex(
            model_name='deviationlink',
            index=models.Index(fields=['controlled_document'], name='deviations__control_7a010c_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['event_type', 'status'], name='deviations__event_t_603960_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['origin'], name='deviations__origin_884e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['severity', 'criticality'], name='deviations__severit_8138ba_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['product'], name='deviations__product_88bbe9_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['stock_lot'], name='deviations__stock_l_1cf0d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviationapproval',
            constraint=models.UniqueConstraint(fields=('event', 'role', 'approver'), name='unique_deviation_approval_role_user'),
        ),
        migrations.AddConstraint(
            model_name='qualityevent',
            constraint=models.UniqueConstraint(fields=('event_number',), name='unique_quality_event_number'),
        ),
    ]
