# Generated by Django 6.0.8 on 2026-08-25 17:08

import base.sequences
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('account_type', models.CharField(choices=[('asset', 'Ativo'), ('liability', 'Passivo'), ('revenue', 'Receita'), ('expense', 'Despesa'), ('equity', 'Patrimônio líquido')], max_length=24, verbose_name='tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.chartofaccount', verbose_name='conta superior')),
            ],
            options={
                'verbose_name': 'plano de contas',
                'verbose_name_plural': 'plano de contas',
                'ordering': ['code'],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('account_type', models.CharField(choices=[('cash', 'Caixa'), ('bank', 'Banco')], max_length=24, verbose_name='tipo')),
                ('bank_name', models.CharField(blank=True, max_length=120, verbose_name='banco')),
                ('agency_number', models.CharField(blank=True, max_length=40, verbose_name='agência')),
                ('account_number', models.CharField(blank=True, max_length=40, verbose_name='conta')),
                ('opening_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='saldo inicial')),
                ('current_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='saldo atual')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'conta financeira',
                'verbose_name_plural': 'contas financeiras',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['account_type', 'is_active'], name='finance_fin_account_808798_idx'), models.Index(fields=['code'], name='finance_fin_code_8b77c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_financial_account_code')],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('category_type', models.CharField(choices=[('payable', 'Pagar'), ('receivable', 'Receber'), ('both', 'Ambos')], max_length=24, verbose_name='tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('chart_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_categories', to='finance.chartofaccount', verbose_name='conta contábil')),
            ],
            options={
                'verbose_name': 'categoria financeira',
                'verbose_name_plural': 'categorias financeiras',
                'ordering': ['category_type', 'code'],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FinancialPeriodClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='mês')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('validated', 'Validado'), ('closed', 'Fechado'), ('reopened', 'Reaberto')], default='open', max_length=24, verbose_name='status')),
                ('validation_notes', models.TextField(blank=True, verbose_name='observações de validação')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechado em')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_financial_periods', to=settings.AUTH_USER_MODEL, verbose_name='fechado por')),
            ],
            options={
                'verbose_name': 'fechamento financeiro',
                'verbose_name_plural': 'fechamentos financeiros',
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title_number', models.CharField(blank=True, max_length=80, verbose_name='título')),
                ('title_type', models.CharField(choices=[('payable', 'Conta a pagar'), ('receivable', 'Conta a receber')], max_length=24, verbose_name='tipo')),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('purchase', 'Compra'), ('fiscal_note', 'Nota fiscal'), ('sale', 'Venda'), ('contract', 'Contrato')], default='manual', max_length=24, verbose_name='origem')),
                ('fiscal_document_number', models.CharField(blank=True, max_length=80, verbose_name='documento fiscal')),
                ('contract_reference', models.CharField(blank=True, max_length=80, verbose_name='contrato')),
                ('sale_reference', models.CharField(blank=True, max_length=80, verbose_name='venda')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('partially_settled', 'Baixado parcialmente'), ('settled', 'Baixado'), ('overdue', 'Vencido'), ('cancelled', 'Cancelado'), ('reversed', 'Estornado')], default='pending', max_length=32, verbose_name='status')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='emissão')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('original_amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='valor original')),
                ('open_amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='valor em aberto')),
                ('paid_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='valor baixado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_financial_titles', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_titles', to='finance.financialcategory', verbose_name='categoria')),
                ('financial_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_titles', to='finance.financialaccount', verbose_name='conta financeira')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_titles', to='masters.businesspartner', verbose_name='parceiro')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_titles', to='procurement.purchaseorder', verbose_name='pedido de compra')),
            ],
            options={
                'verbose_name': 'título financeiro',
                'verbose_name_plural': 'títulos financeiros',
                'ordering': ['due_date', 'title_number'],
            },
        ),
        migrations.CreateModel(
            name='FinancialSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('settlement_date', models.DateField(verbose_name='data da baixa')),
                ('method', models.CharField(choices=[('bank_transfer', 'Transferência'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('cash', 'Dinheiro'), ('card', 'Cartão')], max_length=24, verbose_name='método')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='valor baixado')),
                ('interest_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='juros')),
                ('penalty_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='multa')),
                ('discount_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='desconto')),
                ('net_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='valor líquido')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('reversed', 'Estornada')], default='active', max_length=24, verbose_name='status')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='conciliado em')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='estornado em')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='justificativa de estorno')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='referência')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='finance.financialaccount', verbose_name='conta financeira')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciled_financial_settlements', to=settings.AUTH_USER_MODEL, verbose_name='conciliado por')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_financial_settlements', to=settings.AUTH_USER_MODEL, verbose_name='estornado por')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='finance.financialtitle', verbose_name='título')),
            ],
            options={
                'verbose_name': 'baixa financeira',
                'verbose_name_plural': 'baixas financeiras',
                'ordering': ['-settlement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('flow_type', models.CharField(choices=[('planned', 'Previsto'), ('realized', 'Realizado')], max_length=24, verbose_name='tipo')),
                ('direction', models.CharField(choices=[('inflow', 'Entrada'), ('outflow', 'Saída')], max_length=24, verbose_name='direção')),
                ('cash_date', models.DateField(verbose_name='data do fluxo')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='valor')),
                ('status', models.CharField(choices=[('forecast', 'Previsto'), ('realized', 'Realizado'), ('cancelled', 'Cancelado')], max_length=24, verbose_name='status')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('financial_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_flow_entries', to='finance.financialaccount', verbose_name='conta financeira')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_flow_entries', to='finance.financialsettlement', verbose_name='baixa')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_flow_entries', to='finance.financialtitle', verbose_name='título')),
            ],
            options={
                'verbose_name': 'fluxo de caixa',
                'verbose_name_plural': 'fluxos de caixa',
                'ordering': ['cash_date', 'direction'],
            },
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['account_type', 'is_active'], name='finance_cha_account_5a0308_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['code'], name='finance_cha_code_c659c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_chart_account_code'),
        ),
        migrations.AddIndex(
            model_name='financialcategory',
            index=models.Index(fields=['category_type', 'is_active'], name='finance_fin_categor_1da18b_idx'),
        ),
        migrations.AddIndex(
            model_name='financialcategory',
            index=models.Index(fields=['code'], name='finance_fin_code_9a4494_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialcategory',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_financial_category_code'),
        ),
        migrations.AddIndex(
            model_name='financialperiodclosing',
            index=models.Index(fields=['status'], name='finance_fin_status_3dea5c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialperiodclosing',
            index=models.Index(fields=['period_year', 'period_month'], name='finance_fin_period__22f82e_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialperiodclosing',
            constraint=models.UniqueConstraint(fields=('period_year', 'period_month'), name='unique_financial_period'),
        ),
        migrations.AddIndex(
            model_name='financialtitle',
            index=models.Index(fields=['title_type', 'status'], name='finance_fin_title_t_6ad410_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtitle',
            index=models.Index(fields=['partner', 'status'], name='finance_fin_partner_6fbf41_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtitle',
            index=models.Index(fields=['due_date'], name='finance_fin_due_dat_1b0898_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtitle',
            index=models.Index(fields=['source_type'], name='finance_fin_source__979a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtitle',
            index=models.Index(fields=['title_number'], name='finance_fin_title_n_d6a844_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialtitle',
            constraint=models.UniqueConstraint(fields=('title_number',), name='unique_financial_title_number'),
        ),
        migrations.AddIndex(
            model_name='financialsettlement',
            index=models.Index(fields=['title'], name='finance_fin_title_i_022462_idx'),
        ),
        migrations.AddIndex(
            model_name='financialsettlement',
            index=models.Index(fields=['financial_account'], name='finance_fin_financi_0f7394_idx'),
        ),
        migrations.AddIndex(
            model_name='financialsettlement',
            index=models.Index(fields=['settlement_date'], name='finance_fin_settlem_77fffc_idx'),
        ),
        migrations.AddIndex(
            model_name='financialsettlement',
            index=models.Index(fields=['status'], name='finance_fin_status_4b71fc_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['flow_type', 'direction'], name='finance_cas_flow_ty_32e803_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['cash_date'], name='finance_cas_cash_da_f1b26f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['status'], name='finance_cas_status_b2b378_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['financial_account'], name='finance_cas_financi_37513d_idx'),
        ),
    ]
