# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_remove_costcenter_unique_tenant_cost_center_code_and_more'),
        ('finance', '0001_initial'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('procurement', '0004_remove_purchaseorder_unique_tenant_purchase_order_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chartofaccount',
            name='unique_tenant_chart_account_code',
        ),
        migrations.RemoveConstraint(
            model_name='financialaccount',
            name='unique_tenant_financial_account_code',
        ),
        migrations.RemoveConstraint(
            model_name='financialcategory',
            name='unique_tenant_financial_category_code',
        ),
        migrations.RemoveConstraint(
            model_name='financialperiodclosing',
            name='unique_tenant_financial_period',
        ),
        migrations.RemoveConstraint(
            model_name='financialtitle',
            name='unique_tenant_financial_title_number',
        ),
        migrations.RemoveIndex(
            model_name='cashflowentry',
            name='finance_cas_tenant__034029_idx',
        ),
        migrations.RemoveIndex(
            model_name='cashflowentry',
            name='finance_cas_tenant__7b8a48_idx',
        ),
        migrations.RemoveIndex(
            model_name='cashflowentry',
            name='finance_cas_tenant__81e3a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='cashflowentry',
            name='finance_cas_tenant__de6026_idx',
        ),
        migrations.RemoveIndex(
            model_name='chartofaccount',
            name='finance_cha_tenant__8e37e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialaccount',
            name='finance_fin_tenant__aacb00_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialcategory',
            name='finance_fin_tenant__88de7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialperiodclosing',
            name='finance_fin_tenant__807a31_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialperiodclosing',
            name='finance_fin_tenant__ba4bcc_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialsettlement',
            name='finance_fin_tenant__b87b2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialsettlement',
            name='finance_fin_tenant__86fcfc_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialsettlement',
            name='finance_fin_tenant__2c0cb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialsettlement',
            name='finance_fin_tenant__10a404_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialtitle',
            name='finance_fin_tenant__44f367_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialtitle',
            name='finance_fin_tenant__2e4b1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialtitle',
            name='finance_fin_tenant__1c38e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialtitle',
            name='finance_fin_tenant__6ee8ec_idx',
        ),
        migrations.RemoveField(
            model_name='cashflowentry',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='chartofaccount',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='financialaccount',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='financialcategory',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='financialperiodclosing',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='financialsettlement',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='financialtitle',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['flow_type', 'direction'], name='finance_cas_flow_ty_32e803_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['cash_date'], name='finance_cas_cash_da_f1b26f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['status'], name='finance_cas_status_b2b378_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['financial_account'], name='finance_cas_financi_37513d_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['account_type', 'is_active'], name='finance_cha_account_5a0308_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['account_type', 'is_active'], name='finance_fin_account_808798_idx'),
        ),
        migrations.AddIndex(
            model_name='financialcategory',
            index=models.Index(fields=['category_type', 'is_active'], name='finance_fin_categor_1da18b_idx'),
        ),
        migrations.AddIndex(
            model_name='financialperiodclosing',
            index=models.Index(fields=['status'], name='finance_fin_status_3dea5c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialperiodclosing',
            index=models.Index(fields=['period_year', 'period_month'], name='finance_fin_period__22f82e_idx'),
        ),
        migrations.AddIndex(
            model_name='financialsettlement',
            index=models.Index(fields=['title'], name='finance_fin_title_i_022462_idx'),
        ),
        migrations.AddIndex(
            model_name='financialsettlement',
            index=models.Index(fields=['financial_account'], name='finance_fin_financi_0f7394_idx'),
        ),
        migrations.AddIndex(
            model_name='financialsettlement',
            index=models.Index(fields=['settlement_date'], name='finance_fin_settlem_77fffc_idx'),
        ),
        migrations.AddIndex(
            model_name='financialsettlement',
            index=models.Index(fields=['status'], name='finance_fin_status_4b71fc_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtitle',
            index=models.Index(fields=['title_type', 'status'], name='finance_fin_title_t_6ad410_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtitle',
            index=models.Index(fields=['partner', 'status'], name='finance_fin_partner_6fbf41_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtitle',
            index=models.Index(fields=['due_date'], name='finance_fin_due_dat_1b0898_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtitle',
            index=models.Index(fields=['source_type'], name='finance_fin_source__979a2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_chart_account_code'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_financial_account_code'),
        ),
        migrations.AddConstraint(
            model_name='financialcategory',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_financial_category_code'),
        ),
        migrations.AddConstraint(
            model_name='financialperiodclosing',
            constraint=models.UniqueConstraint(fields=('period_year', 'period_month'), name='unique_financial_period'),
        ),
        migrations.AddConstraint(
            model_name='financialtitle',
            constraint=models.UniqueConstraint(fields=('title_number',), name='unique_financial_title_number'),
        ),
    ]
