# Generated by Django 5.2.16 on 2026-08-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_chartofaccount_unique_tenant_chart_account_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialtitle',
            name='cost_center',
        ),
    ]
