# Generated by Django 5.2.16 on 2026-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_financialtitle_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='financialcategory',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
    ]
