# Generated by Django 6.0.8 on 2026-08-25 17:08

import base.sequences
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('kind', models.CharField(choices=[('family', 'Família'), ('group', 'Grupo'), ('category', 'Categoria'), ('therapeutic_class', 'Classe terapêutica'), ('pharmaceutical_form', 'Forma farmacêutica'), ('presentation', 'Apresentação'), ('concentration', 'Concentração'), ('administration_route', 'Via de administração')], max_length=32, verbose_name='tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='masters.mastercategory', verbose_name='categoria superior')),
            ],
            options={
                'verbose_name': 'categoria mestre',
                'verbose_name_plural': 'categorias mestres',
                'ordering': ['kind', 'name'],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('site_type', models.CharField(choices=[('plant', 'Planta fabril'), ('distribution', 'Distribuição'), ('lab', 'Laboratório'), ('admin', 'Administrativo')], default='plant', max_length=24, verbose_name='tipo')),
                ('zipcode', models.CharField(blank=True, max_length=20, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='logradouro')),
                ('street_number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('city_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='Cidade')),
                ('country_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliary.country', verbose_name='país')),
                ('state_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF')),
            ],
            options={
                'verbose_name': 'planta/unidade',
                'verbose_name_plural': 'plantas/unidades',
                'ordering': ['name'],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=20, verbose_name='código')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('symbol', models.CharField(max_length=20, verbose_name='símbolo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'unidade de medida',
                'verbose_name_plural': 'unidades de medida',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['is_active'], name='masters_uni_is_acti_1fa451_idx'), models.Index(fields=['code'], name='masters_uni_code_61cd71_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_unit_code')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=64, verbose_name='código')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('item_type', models.CharField(choices=[('finished_product', 'Produto acabado'), ('semifinished', 'Semiacabado'), ('intermediate', 'Intermediário'), ('raw_material', 'Matéria-prima'), ('excipient', 'Excipiente'), ('packaging', 'Embalagem'), ('reagent', 'Reagente'), ('standard', 'Padrão'), ('promotional', 'Material promocional'), ('service', 'Serviço')], max_length=32, verbose_name='tipo de item')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('blocked', 'Bloqueado'), ('obsolete', 'Obsoleto')], default='draft', max_length=24, verbose_name='status')),
                ('storage_condition', models.CharField(blank=True, max_length=255, verbose_name='condição de armazenamento')),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='vida útil em dias')),
                ('requires_quality_release', models.BooleanField(default=True, verbose_name='exige liberação da qualidade')),
                ('requires_approved_supplier', models.BooleanField(default=False, verbose_name='exige fornecedor aprovado')),
                ('fiscal_ncm', models.CharField(blank=True, max_length=16, verbose_name='NCM')),
                ('fiscal_cest', models.CharField(blank=True, max_length=16, verbose_name='CEST')),
                ('administration_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_products', to='masters.mastercategory', verbose_name='via de administração')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='masters.mastercategory', verbose_name='categoria')),
                ('pharmaceutical_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_products', to='masters.mastercategory', verbose_name='forma farmacêutica')),
                ('therapeutic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='therapeutic_products', to='masters.mastercategory', verbose_name='classe terapêutica')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'produto/material',
                'verbose_name_plural': 'produtos/materiais',
                'ordering': ['code'],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('warehouse_type', models.CharField(choices=[('raw_material', 'Matéria-prima'), ('packaging', 'Embalagem'), ('finished_product', 'Produto acabado'), ('quality', 'Qualidade'), ('rejected', 'Reprovado'), ('general', 'Geral')], max_length=32, verbose_name='tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='masters.site', verbose_name='planta')),
            ],
            options={
                'verbose_name': 'almoxarifado',
                'verbose_name_plural': 'almoxarifados',
                'ordering': ['site__name', 'name'],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='masters.warehouse', verbose_name='almoxarifado')),
            ],
            options={
                'verbose_name': 'localização de estoque',
                'verbose_name_plural': 'localizações de estoque',
                'ordering': ['warehouse__name', 'code'],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=64, verbose_name='código')),
                ('legal_name', models.CharField(max_length=255, verbose_name='razão social/nome')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='nome fantasia')),
                ('document', models.CharField(blank=True, max_length=40, verbose_name='documento fiscal/regulatório')),
                ('partner_type', models.CharField(choices=[('supplier', 'Fornecedor'), ('manufacturer', 'Fabricante'), ('distributor', 'Distribuidor'), ('carrier', 'Transportadora'), ('customer', 'Cliente'), ('partner', 'Parceiro'), ('outsourced_lab', 'Laboratório terceirizado'), ('regulatory_authority', 'Autoridade regulatória')], max_length=32, verbose_name='tipo')),
                ('qualification_status', models.CharField(choices=[('draft', 'Rascunho'), ('qualified', 'Qualificado'), ('not_qualified', 'Não qualificado'), ('expired', 'Vencido'), ('blocked', 'Bloqueado')], default='draft', max_length=24, verbose_name='status de qualificação')),
                ('qualification_valid_until', models.DateField(blank=True, null=True, verbose_name='qualificação válida até')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('zipcode', models.CharField(blank=True, max_length=20, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='logradouro')),
                ('street_number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='bloqueado')),
                ('city_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='Cidade')),
                ('country_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliary.country', verbose_name='país')),
                ('state_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF')),
            ],
            options={
                'verbose_name': 'parceiro de negócio',
                'verbose_name_plural': 'parceiros de negócio',
                'ordering': ['legal_name'],
                'indexes': [models.Index(fields=['partner_type'], name='masters_bus_partner_7038f5_idx'), models.Index(fields=['qualification_status'], name='masters_bus_qualifi_e893ea_idx'), models.Index(fields=['code'], name='masters_bus_code_c192c0_idx'), models.Index(fields=['document'], name='masters_bus_documen_fd3553_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_partner_code')],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='mastercategory',
            index=models.Index(fields=['kind', 'is_active'], name='masters_mas_kind_9901c2_idx'),
        ),
        migrations.AddIndex(
            model_name='mastercategory',
            index=models.Index(fields=['code'], name='masters_mas_code_4d8b99_idx'),
        ),
        migrations.AddConstraint(
            model_name='mastercategory',
            constraint=models.UniqueConstraint(fields=('kind', 'code'), name='unique_category_kind_code'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['site_type', 'is_active'], name='masters_sit_site_ty_c8478c_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['code'], name='masters_sit_code_208280_idx'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_site_code'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='masters_pro_status_a8bd56_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['item_type'], name='masters_pro_item_ty_c2b136_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='masters_pro_code_f7db4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_product_code'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['warehouse_type', 'is_active'], name='masters_war_warehou_0aac2d_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='masters_war_code_35f1a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='unique_site_warehouse_code'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['is_active'], name='masters_sto_is_acti_47a5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['code'], name='masters_sto_code_644009_idx'),
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_warehouse_location_code'),
        ),
    ]
