# Generated by Django 6.0.7 on 2026-07-12 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0002_populate_auxiliary_references'),
        ('masters', '0002_businesspartner_city_ref_businesspartner_state_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=120, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='logradouro'),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='site',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='site',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='cidade normalizada'),
        ),
        migrations.AddField(
            model_name='site',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=120, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='site',
            name='state',
            field=models.CharField(blank=True, max_length=80, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='site',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF/estado normalizado'),
        ),
        migrations.AddField(
            model_name='site',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='logradouro'),
        ),
        migrations.AddField(
            model_name='site',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP'),
        ),
    ]
