# Generated by Django 6.0 on 2026-09-03

from django.db import migrations, models


def remove_application_area_categories(apps, schema_editor):
    MasterCategory = apps.get_model('masters', 'MasterCategory')
    MasterCategory.objects.filter(kind='application_area').delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('masters', '0002_cosmetics_product_taxonomy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='application_area',
        ),
        migrations.AlterField(
            model_name='mastercategory',
            name='kind',
            field=models.CharField(
                choices=[
                    ('family', 'Família'),
                    ('group', 'Grupo'),
                    ('category', 'Categoria'),
                    ('product_line', 'Linha de produto'),
                    ('cosmetic_form', 'Forma cosmética'),
                    ('presentation', 'Apresentação'),
                    ('concentration', 'Concentração'),
                ],
                max_length=32,
                verbose_name='tipo',
            ),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='código'),
        ),
        migrations.RunPython(remove_application_area_categories, noop),
    ]
