# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('masters', '0003_add_zipcode_and_address'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businesspartner',
            name='unique_tenant_partner_code',
        ),
        migrations.RemoveConstraint(
            model_name='mastercategory',
            name='unique_tenant_category_kind_code',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_tenant_product_code',
        ),
        migrations.RemoveConstraint(
            model_name='site',
            name='unique_tenant_site_code',
        ),
        migrations.RemoveConstraint(
            model_name='storagelocation',
            name='unique_tenant_warehouse_location_code',
        ),
        migrations.RemoveConstraint(
            model_name='unitofmeasure',
            name='unique_tenant_unit_code',
        ),
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='unique_tenant_site_warehouse_code',
        ),
        migrations.RemoveIndex(
            model_name='businesspartner',
            name='masters_bus_tenant__e8931c_idx',
        ),
        migrations.RemoveIndex(
            model_name='businesspartner',
            name='masters_bus_tenant__d45a0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='mastercategory',
            name='masters_mas_tenant__81e625_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='masters_pro_tenant__00f144_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='masters_pro_tenant__562a39_idx',
        ),
        migrations.RemoveIndex(
            model_name='site',
            name='masters_sit_tenant__0d1b16_idx',
        ),
        migrations.RemoveIndex(
            model_name='storagelocation',
            name='masters_sto_tenant__93e7a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='unitofmeasure',
            name='masters_uni_tenant__328243_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouse',
            name='masters_war_tenant__aca803_idx',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='mastercategory',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='site',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='storagelocation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='unitofmeasure',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='businesspartner',
            index=models.Index(fields=['partner_type'], name='masters_bus_partner_7038f5_idx'),
        ),
        migrations.AddIndex(
            model_name='businesspartner',
            index=models.Index(fields=['qualification_status'], name='masters_bus_qualifi_e893ea_idx'),
        ),
        migrations.AddIndex(
            model_name='mastercategory',
            index=models.Index(fields=['kind', 'is_active'], name='masters_mas_kind_9901c2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='masters_pro_status_a8bd56_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['item_type'], name='masters_pro_item_ty_c2b136_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['site_type', 'is_active'], name='masters_sit_site_ty_c8478c_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['is_active'], name='masters_sto_is_acti_47a5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['is_active'], name='masters_uni_is_acti_1fa451_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['warehouse_type', 'is_active'], name='masters_war_warehou_0aac2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='businesspartner',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_partner_code'),
        ),
        migrations.AddConstraint(
            model_name='mastercategory',
            constraint=models.UniqueConstraint(fields=('kind', 'code'), name='unique_category_kind_code'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_product_code'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_site_code'),
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_warehouse_location_code'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_unit_code'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='unique_site_warehouse_code'),
        ),
    ]
