# Generated by Django 6.0.8 on 2026-09-05 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('masters', '0003_remove_product_application_area_and_category_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application_area',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='application_area_products',
                to='masters.mastercategory',
                verbose_name='área de aplicação',
            ),
        ),
        migrations.AlterField(
            model_name='mastercategory',
            name='kind',
            field=models.CharField(
                choices=[
                    ('family', 'Família'),
                    ('group', 'Grupo'),
                    ('category', 'Categoria'),
                    ('product_line', 'Linha de produto'),
                    ('cosmetic_form', 'Forma cosmética'),
                    ('presentation', 'Apresentação'),
                    ('concentration', 'Concentração'),
                    ('application_area', 'Área de aplicação'),
                ],
                max_length=32,
                verbose_name='tipo',
            ),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='code',
            field=models.CharField(max_length=20, verbose_name='código'),
        ),
    ]
