# Generated by Django 5.2.16 on 2026-08-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_businesspartner_country_ref_site_country_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='code',
            field=models.CharField(blank=True, max_length=64, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='mastercategory',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=64, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
    ]
