# Generated by Django 6.0.7 on 2026-07-07 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('document', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Informe apenas números, pontos, barras e hífens.', regex='^[0-9./-]*$')], verbose_name='CNPJ')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='domínio')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='tenants_ten_slug_63daca_idx'), models.Index(fields=['domain'], name='tenants_ten_domain_a84b8d_idx'), models.Index(fields=['is_active'], name='tenants_ten_is_acti_8f654a_idx')],
            },
        ),
    ]
