# Generated by Django 6.0.7 on 2026-07-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='module_contract_enforced',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica que o acesso aos módulos deve seguir integralmente TenantModuleSetting.', verbose_name='contrato de módulos aplicado'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['module_contract_enforced'], name='tenants_ten_module__12574a_idx'),
        ),
    ]
