# Generated by Django 6.0.7 on 2026-07-11 21:48

import re

from django.db import migrations, models


def backfill_normalized_documents(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    seen = set()
    for tenant in Tenant.objects.exclude(document='').order_by('pk').iterator(chunk_size=500):
        normalized = re.sub(r'\D', '', tenant.document or '')
        if len(normalized) != 14 or normalized in seen:
            continue
        Tenant.objects.filter(pk=tenant.pk).update(document_normalized=normalized)
        seen.add(normalized)


def clear_normalized_documents(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    Tenant.objects.update(document_normalized=None)


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_module_contract_enforced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='document_normalized',
            field=models.CharField(blank=True, editable=False, max_length=14, null=True, unique=True, verbose_name='CNPJ normalizado'),
        ),
        migrations.RunPython(backfill_normalized_documents, clear_normalized_documents),
    ]
