# Generated by Django 6.0.7 on 2026-07-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0002_populate_auxiliary_references'),
        ('tenants', '0003_tenant_document_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='cidade normalizada'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=120, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='state',
            field=models.CharField(blank=True, max_length=80, verbose_name='UF/estado'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF/estado normalizado'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='logradouro'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP'),
        ),
    ]
