# Generated by Django 5.2.16 on 2026-07-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_city_tenant_city_ref_tenant_email_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenant',
            name='tenants_ten_module__12574a_idx',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='module_contract_enforced',
        ),
    ]
