# Generated by Django 6.0.7 on 2026-07-07 16:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulations', '0001_initial'),
        ('masters', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('order_number', models.CharField(max_length=80, verbose_name='ordem')),
                ('batch_number', models.CharField(blank=True, max_length=80, verbose_name='lote')),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade planejada')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovada'), ('released', 'Liberada'), ('in_progress', 'Em execução'), ('paused', 'Pausada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('closed', 'Encerrada')], default='draft', max_length=24, verbose_name='status')),
                ('scheduled_start', models.DateField(blank=True, null=True, verbose_name='início previsto')),
                ('scheduled_end', models.DateField(blank=True, null=True, verbose_name='fim previsto')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='início real')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='fim real')),
                ('production_line', models.CharField(blank=True, max_length=120, verbose_name='linha')),
                ('equipment_code', models.CharField(blank=True, max_length=80, verbose_name='equipamento')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='liberada em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='justificativa de cancelamento')),
                ('actual_yield_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='rendimento real')),
                ('real_loss_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='perda real')),
                ('rework_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='retrabalho')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='cancelada por')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='formulations.masterformula', verbose_name='fórmula')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='masters.product', verbose_name='produto')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='liberada por')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='formulations.manufacturingroute', verbose_name='roteiro')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='iniciada por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'ordem de produção',
                'verbose_name_plural': 'ordens de produção',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade planejada')),
                ('actual_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade real')),
                ('loss_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='perda')),
                ('returned_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='devolução')),
                ('lot_number', models.CharField(blank=True, max_length=80, verbose_name='lote do material')),
                ('quality_status', models.CharField(choices=[('quarantine', 'Quarentena'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('blocked', 'Bloqueado'), ('reserved', 'Reservado'), ('in_analysis', 'Em análise'), ('returned', 'Devolvido'), ('segregated', 'Segregado'), ('expired', 'Vencido')], default='quarantine', max_length=24, verbose_name='status de qualidade')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='formulations.formulacomponent', verbose_name='componente')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='masters.product', verbose_name='material')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='masters.unitofmeasure', verbose_name='unidade')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='production.productionorder', verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'consumo de material',
                'verbose_name_plural': 'consumos de material',
                'ordering': ['order', 'material__code'],
            },
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['tenant', 'status'], name='production__tenant__168d69_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['tenant', 'product', 'status'], name='production__tenant__e17088_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['order_number'], name='production__order_n_6086ee_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['batch_number'], name='production__batch_n_6f2847_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'order_number'), name='unique_tenant_production_order_number'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'batch_number'), name='unique_tenant_production_batch_number'),
        ),
        migrations.AddIndex(
            model_name='materialconsumption',
            index=models.Index(fields=['tenant', 'order'], name='production__tenant__dd021b_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconsumption',
            index=models.Index(fields=['tenant', 'material'], name='production__tenant__7294c4_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconsumption',
            index=models.Index(fields=['quality_status'], name='production__quality_1a63e3_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconsumption',
            index=models.Index(fields=['lot_number'], name='production__lot_num_cfd1ef_idx'),
        ),
    ]
