# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulations', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('order_number', models.CharField(max_length=80, verbose_name='ordem')),
                ('batch_number', models.CharField(blank=True, max_length=80, verbose_name='lote')),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade planejada')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovada'), ('released', 'Liberada'), ('in_progress', 'Em execução'), ('paused', 'Pausada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('closed', 'Encerrada')], default='draft', max_length=24, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=16, verbose_name='prioridade')),
                ('scheduled_start', models.DateField(blank=True, null=True, verbose_name='início previsto')),
                ('scheduled_end', models.DateField(blank=True, null=True, verbose_name='fim previsto')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='início real')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='fim real')),
                ('production_line', models.CharField(blank=True, max_length=120, verbose_name='linha')),
                ('equipment_code', models.CharField(blank=True, max_length=80, verbose_name='equipamento')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='liberada em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='justificativa de cancelamento')),
                ('actual_yield_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='rendimento real')),
                ('real_loss_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='perda real')),
                ('rework_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='retrabalho')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='cancelada por')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='formulations.masterformula', verbose_name='fórmula')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='masters.product', verbose_name='produto')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='liberada por')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='formulations.manufacturingroute', verbose_name='roteiro')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='iniciada por')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'ordem de produção',
                'verbose_name_plural': 'ordens de produção',
                'ordering': ['-created_at'],
                'permissions': [('view_production_maps', 'Pode consultar mapas da ordem de produção')],
            },
        ),
        migrations.CreateModel(
            name='ProductionOperationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequência')),
                ('operation', models.CharField(max_length=160, verbose_name='operação')),
                ('work_center', models.CharField(blank=True, max_length=120, verbose_name='centro de trabalho')),
                ('equipment_code', models.CharField(blank=True, max_length=80, verbose_name='equipamento')),
                ('planned_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='minutos planejados')),
                ('actual_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='minutos reais')),
                ('machine_hourly_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo de máquina por hora')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em execução'), ('completed', 'Concluído'), ('skipped', 'Não executado')], default='pending', max_length=20, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('route_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formulations.routestep')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_executions', to='production.productionorder')),
            ],
            options={
                'ordering': ['order', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLaborEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(max_length=120, verbose_name='função')),
                ('equipment_code', models.CharField(blank=True, max_length=80, verbose_name='equipamento')),
                ('started_at', models.DateTimeField(verbose_name='início')),
                ('ended_at', models.DateTimeField(verbose_name='fim')),
                ('duration_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='duração em minutos')),
                ('hourly_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo por hora')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_labor_entries', to=settings.AUTH_USER_MODEL)),
                ('operation_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labor_entries', to='production.productionoperationexecution')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='production.productionorder')),
            ],
            options={
                'ordering': ['order', 'started_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade planejada')),
                ('actual_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade real')),
                ('loss_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='perda')),
                ('returned_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='devolução')),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade reservada')),
                ('issued_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade baixada')),
                ('lot_number', models.CharField(blank=True, max_length=80, verbose_name='lote do material')),
                ('quality_status', models.CharField(choices=[('quarantine', 'Quarentena'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('blocked', 'Bloqueado'), ('reserved', 'Reservado'), ('in_analysis', 'Em análise'), ('returned', 'Devolvido'), ('segregated', 'Segregado'), ('expired', 'Vencido')], default='quarantine', max_length=24, verbose_name='status de qualidade')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='formulations.formulacomponent', verbose_name='componente')),
                ('issue_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_material_consumption', to='inventory.stockmovement', verbose_name='movimento de baixa')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_allocations', to='masters.storagelocation', verbose_name='localização')),
                ('loss_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lost_material_consumption', to='inventory.stockmovement', verbose_name='movimento de perda')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='masters.product', verbose_name='material')),
                ('reservation_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_material_consumption', to='inventory.stockmovement', verbose_name='movimento de reserva')),
                ('return_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_material_consumption', to='inventory.stockmovement', verbose_name='movimento de devolução de reserva')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_allocations', to='inventory.stocklot', verbose_name='lote de estoque')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='masters.unitofmeasure', verbose_name='unidade')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_allocations', to='masters.warehouse', verbose_name='almoxarifado')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='production.productionorder', verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'consumo de material',
                'verbose_name_plural': 'consumos de material',
                'ordering': ['order', 'material__code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('lot_number', models.CharField(max_length=80, verbose_name='lote')),
                ('sublot_number', models.CharField(blank=True, max_length=80, verbose_name='sublote')),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade planejada')),
                ('produced_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade produzida')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='fabricação')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('received', 'Recebido em quarentena')], default='pending', max_length=16, verbose_name='status')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.storagelocation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='production.productionorder', verbose_name='ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_outputs', to='masters.product', verbose_name='produto')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stock_lot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklot')),
                ('stock_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stockmovement')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_outputs', to='masters.unitofmeasure')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.warehouse')),
            ],
            options={
                'ordering': ['order', 'lot_number', 'sublot_number'],
                'permissions': [('receive_productionoutput', 'Pode receber produto acabado')],
            },
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status'], name='production__status_b4dbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['product', 'status'], name='production__product_d6a960_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['order_number'], name='production__order_n_6086ee_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['batch_number'], name='production__batch_n_6f2847_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(fields=('order_number',), name='unique_production_order_number'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(fields=('batch_number',), name='unique_production_batch_number'),
        ),
        migrations.AddConstraint(
            model_name='productionoperationexecution',
            constraint=models.UniqueConstraint(fields=('order', 'sequence'), name='unique_production_operation_sequence'),
        ),
        migrations.AddConstraint(
            model_name='productionoperationexecution',
            constraint=models.CheckConstraint(condition=models.Q(('actual_minutes__gte', 0), ('machine_hourly_cost__gte', 0), ('planned_minutes__gte', 0)), name='production_operation_values_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionoperationexecution',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='production_operation_times_ordered'),
        ),
        migrations.AddConstraint(
            model_name='productionoperationexecution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actual_minutes', 0), ('ended_at__isnull', True), ('started_at__isnull', True), ('status', 'pending')), models.Q(('actual_minutes', 0), ('ended_at__isnull', True), ('recorded_by__isnull', False), ('started_at__isnull', False), ('status', 'in_progress')), models.Q(('ended_at__isnull', False), ('recorded_by__isnull', False), ('started_at__isnull', False), ('status', 'completed')), models.Q(('actual_minutes', 0), ('ended_at__isnull', True), ('recorded_by__isnull', False), ('started_at__isnull', True), ('status', 'skipped')), _connector='OR'), name='production_operation_status_evidence'),
        ),
        migrations.AddConstraint(
            model_name='productionoperationexecution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'skipped'), _negated=True), ('notes__regex', '\\S'), _connector='OR'), name='production_operation_skipped_reason'),
        ),
        migrations.AddIndex(
            model_name='productionlaborentry',
            index=models.Index(fields=['order', 'started_at'], name='prod_labor_order_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionlaborentry',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 0), ('hourly_cost__gte', 0)), name='production_labor_values_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionlaborentry',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__gte', models.F('started_at'))), name='production_labor_times_ordered'),
        ),
        migrations.AddIndex(
            model_name='materialconsumption',
            index=models.Index(fields=['order'], name='production__order_i_9d523e_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconsumption',
            index=models.Index(fields=['material'], name='production__materia_efa878_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconsumption',
            index=models.Index(fields=['quality_status'], name='production__quality_1a63e3_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconsumption',
            index=models.Index(fields=['lot_number'], name='production__lot_num_cfd1ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('actual_quantity__gte', 0), ('issued_quantity__gte', 0), ('loss_quantity__gte', 0), ('planned_quantity__gte', 0), ('reserved_quantity__gte', 0), ('returned_quantity__gte', 0)), name='production_material_quantities_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionoutput',
            constraint=models.UniqueConstraint(fields=('order', 'lot_number', 'sublot_number'), name='unique_production_output_lot'),
        ),
        migrations.AddConstraint(
            model_name='productionoutput',
            constraint=models.CheckConstraint(condition=models.Q(('planned_quantity__gte', 0), ('produced_quantity__gte', 0)), name='production_output_quantities_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionoutput',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'received'))), name='production_output_status_valid'),
        ),
    ]
