# Generated by Django 6.0.8 on 2026-08-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='ordem'),
        ),
    ]
