# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0002_remove_manufacturingroute_unique_tenant_route_product_version_and_more'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionorder',
            name='unique_tenant_production_order_number',
        ),
        migrations.RemoveConstraint(
            model_name='productionorder',
            name='unique_tenant_production_batch_number',
        ),
        migrations.RemoveIndex(
            model_name='materialconsumption',
            name='production__tenant__dd021b_idx',
        ),
        migrations.RemoveIndex(
            model_name='materialconsumption',
            name='production__tenant__7294c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='productionorder',
            name='production__tenant__168d69_idx',
        ),
        migrations.RemoveIndex(
            model_name='productionorder',
            name='production__tenant__e17088_idx',
        ),
        migrations.RemoveField(
            model_name='materialconsumption',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='materialconsumption',
            index=models.Index(fields=['order'], name='production__order_i_9d523e_idx'),
        ),
        migrations.AddIndex(
            model_name='materialconsumption',
            index=models.Index(fields=['material'], name='production__materia_efa878_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status'], name='production__status_b4dbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['product', 'status'], name='production__product_d6a960_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(fields=('order_number',), name='unique_production_order_number'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(fields=('batch_number',), name='unique_production_batch_number'),
        ),
    ]
