# Generated by Django 5.2.16 on 2026-07-27 20:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0002_remove_manufacturingroute_unique_tenant_route_product_version_and_more'),
        ('inventory', '0002_remove_stockbalance_unique_tenant_stock_balance_address_status_and_more'),
        ('masters', '0006_businesspartner_country_ref_site_country_ref'),
        ('production', '0002_remove_productionorder_unique_tenant_production_order_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialconsumption',
            name='issue_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_material_consumption', to='inventory.stockmovement', verbose_name='movimento de baixa'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='issued_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade baixada'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_allocations', to='masters.storagelocation', verbose_name='localização'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='loss_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lost_material_consumption', to='inventory.stockmovement', verbose_name='movimento de perda'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='reservation_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_material_consumption', to='inventory.stockmovement', verbose_name='movimento de reserva'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade reservada'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='return_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_material_consumption', to='inventory.stockmovement', verbose_name='movimento de devolução de reserva'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='stock_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_allocations', to='inventory.stocklot', verbose_name='lote de estoque'),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_allocations', to='masters.warehouse', verbose_name='almoxarifado'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=16, verbose_name='prioridade'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.CreateModel(
            name='ProductionOperationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequência')),
                ('operation', models.CharField(max_length=160, verbose_name='operação')),
                ('work_center', models.CharField(blank=True, max_length=120, verbose_name='centro de trabalho')),
                ('equipment_code', models.CharField(blank=True, max_length=80, verbose_name='equipamento')),
                ('planned_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='minutos planejados')),
                ('actual_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='minutos reais')),
                ('machine_hourly_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo de máquina por hora')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em execução'), ('completed', 'Concluído'), ('skipped', 'Não executado')], default='pending', max_length=20, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_executions', to='production.productionorder')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('route_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formulations.routestep')),
            ],
            options={
                'ordering': ['order', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLaborEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(max_length=120, verbose_name='função')),
                ('equipment_code', models.CharField(blank=True, max_length=80, verbose_name='equipamento')),
                ('started_at', models.DateTimeField(verbose_name='início')),
                ('ended_at', models.DateTimeField(verbose_name='fim')),
                ('duration_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='duração em minutos')),
                ('hourly_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo por hora')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='production.productionorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_labor_entries', to=settings.AUTH_USER_MODEL)),
                ('operation_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labor_entries', to='production.productionoperationexecution')),
            ],
            options={
                'ordering': ['order', 'started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('lot_number', models.CharField(max_length=80, verbose_name='lote')),
                ('sublot_number', models.CharField(blank=True, max_length=80, verbose_name='sublote')),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade planejada')),
                ('produced_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade produzida')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='fabricação')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('received', 'Recebido em quarentena')], default='pending', max_length=16, verbose_name='status')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.storagelocation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='production.productionorder', verbose_name='ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_outputs', to='masters.product', verbose_name='produto')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stock_lot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklot')),
                ('stock_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stockmovement')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_outputs', to='masters.unitofmeasure')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.warehouse')),
            ],
            options={
                'ordering': ['order', 'lot_number', 'sublot_number'],
                'permissions': [('receive_productionoutput', 'Pode receber produto acabado')],
            },
        ),
        migrations.AddConstraint(
            model_name='productionoperationexecution',
            constraint=models.UniqueConstraint(fields=('order', 'sequence'), name='unique_production_operation_sequence'),
        ),
        migrations.AddConstraint(
            model_name='productionoutput',
            constraint=models.UniqueConstraint(fields=('order', 'lot_number', 'sublot_number'), name='unique_production_output_lot'),
        ),
    ]
