# Generated by Django 6.0.8 on 2026-08-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_productionorder_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionlaborentry',
            name='equipment_code',
        ),
        migrations.RemoveField(
            model_name='productionoperationexecution',
            name='equipment_code',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='equipment_code',
        ),
    ]
