# Generated by Django 5.2.16 on 2026-07-27 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0002_remove_manufacturingroute_unique_tenant_route_product_version_and_more'),
        ('inventory', '0002_remove_stockbalance_unique_tenant_stock_balance_address_status_and_more'),
        ('masters', '0006_businesspartner_country_ref_site_country_ref'),
        ('production', '0003_production_operational_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productionlaborentry',
            index=models.Index(fields=['order', 'started_at'], name='prod_labor_order_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('actual_quantity__gte', 0), ('issued_quantity__gte', 0), ('loss_quantity__gte', 0), ('planned_quantity__gte', 0), ('reserved_quantity__gte', 0), ('returned_quantity__gte', 0)), name='production_material_quantities_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionlaborentry',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 0), ('hourly_cost__gte', 0)), name='production_labor_values_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionlaborentry',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__gte', models.F('started_at'))), name='production_labor_times_ordered'),
        ),
        migrations.AddConstraint(
            model_name='productionoperationexecution',
            constraint=models.CheckConstraint(condition=models.Q(('actual_minutes__gte', 0), ('machine_hourly_cost__gte', 0), ('planned_minutes__gte', 0)), name='production_operation_values_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionoperationexecution',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='production_operation_times_ordered'),
        ),
        migrations.AddConstraint(
            model_name='productionoutput',
            constraint=models.CheckConstraint(condition=models.Q(('planned_quantity__gte', 0), ('produced_quantity__gte', 0)), name='production_output_quantities_nonnegative'),
        ),
    ]
