# Generated by Django 5.2.16 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_enforce_operational_invariants'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productionoutput',
            constraint=models.CheckConstraint(
                condition=models.Q(status__in=('pending', 'received')),
                name='production_output_status_valid',
            ),
        ),
    ]
