# Generated by Django 5.2.16 on 2026-07-27

from django.db import migrations, models


def preflight_operation_evidence(apps, schema_editor):
    Operation = apps.get_model('production', 'ProductionOperationExecution')
    categories = (
        (
            'unknown_status',
            ~models.Q(status__in=('pending', 'in_progress', 'completed', 'skipped')),
        ),
        (
            'pending_evidence',
            models.Q(status='pending')
            & (
                ~models.Q(started_at__isnull=True)
                | ~models.Q(ended_at__isnull=True)
                | ~models.Q(actual_minutes=0)
            ),
        ),
        (
            'in_progress_evidence',
            models.Q(status='in_progress')
            & (
                ~models.Q(started_at__isnull=False)
                | ~models.Q(ended_at__isnull=True)
                | ~models.Q(actual_minutes=0)
                | ~models.Q(recorded_by__isnull=False)
            ),
        ),
        (
            'completed_evidence',
            models.Q(status='completed')
            & (
                ~models.Q(started_at__isnull=False)
                | ~models.Q(ended_at__isnull=False)
                | ~models.Q(recorded_by__isnull=False)
            ),
        ),
        (
            'skipped_evidence',
            models.Q(status='skipped')
            & (
                ~models.Q(started_at__isnull=True)
                | ~models.Q(ended_at__isnull=True)
                | ~models.Q(actual_minutes=0)
                | ~models.Q(recorded_by__isnull=False)
            ),
        ),
        (
            'skipped_reason_blank_or_whitespace',
            models.Q(status='skipped') & ~models.Q(notes__regex=r'\S'),
        ),
    )
    incompatible = []
    for category, condition in categories:
        record_ids = list(
            Operation.objects.filter(condition).order_by('pk').values_list('pk', flat=True)
        )
        if record_ids:
            incompatible.append(f'{category}: IDs={record_ids}')

    if incompatible:
        details = '; '.join(incompatible)
        raise RuntimeError(
            'A migration production 0006 encontrou execuções de operação incompatíveis: '
            f'{details}. Nenhuma evidência foi alterada. Faça o saneamento explícito e '
            'documentado desses registros conforme a categoria, preserve a trilha de '
            'auditoria e execute novamente `migrate production 0006`.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_constrain_production_output_status'),
    ]

    operations = [
        migrations.RunPython(
            preflight_operation_evidence,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='productionoperationexecution',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        status='pending',
                        started_at__isnull=True,
                        ended_at__isnull=True,
                        actual_minutes=0,
                    )
                    | models.Q(
                        status='in_progress',
                        started_at__isnull=False,
                        ended_at__isnull=True,
                        actual_minutes=0,
                        recorded_by__isnull=False,
                    )
                    | models.Q(
                        status='completed',
                        started_at__isnull=False,
                        ended_at__isnull=False,
                        recorded_by__isnull=False,
                    )
                    | models.Q(
                        status='skipped',
                        started_at__isnull=True,
                        ended_at__isnull=True,
                        actual_minutes=0,
                        recorded_by__isnull=False,
                    )
                ),
                name='production_operation_status_evidence',
            ),
        ),
        migrations.AddConstraint(
            model_name='productionoperationexecution',
            constraint=models.CheckConstraint(
                condition=~models.Q(status='skipped') | models.Q(notes__regex=r'\S'),
                name='production_operation_skipped_reason',
            ),
        ),
    ]
