# Generated by Django 5.2.16 on 2026-07-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_constrain_operation_status_evidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorder',
            options={'ordering': ['-created_at'], 'permissions': [('view_production_maps', 'Pode consultar mapas da ordem de produção')], 'verbose_name': 'ordem de produção', 'verbose_name_plural': 'ordens de produção'},
        ),
    ]
