# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0003_initial'),
        ('auxiliary', '0001_initial'),
        ('capa', '0002_initial'),
        ('changes', '0001_initial'),
        ('deviations', '0001_initial'),
        ('documents', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('risk_number', models.CharField(blank=True, max_length=80, verbose_name='risco')),
                ('risk_category', models.CharField(choices=[('quality', 'Qualidade'), ('production', 'Produção'), ('supplier', 'Fornecedor'), ('process', 'Processo'), ('product', 'Produto'), ('regulatory', 'Regulatório'), ('financial', 'Financeiro'), ('fiscal', 'Fiscal'), ('operations', 'Operações')], max_length=32, verbose_name='categoria')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('process_area', models.CharField(max_length=140, verbose_name='processo/área')),
                ('due_date', models.DateField(verbose_name='prazo de tratamento')),
                ('next_review_date', models.DateField(verbose_name='próxima revisão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_treatment', 'Em tratamento'), ('monitoring', 'Em monitoramento'), ('closed', 'Encerrado'), ('cancelled', 'Cancelado')], default='draft', max_length=32, verbose_name='status')),
                ('identified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='identificado em')),
                ('treatment_started_at', models.DateTimeField(blank=True, null=True, verbose_name='tratamento iniciado em')),
                ('monitoring_started_at', models.DateTimeField(blank=True, null=True, verbose_name='monitoramento iniciado em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrado em')),
                ('closure_summary', models.TextField(blank=True, verbose_name='resumo de encerramento')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('initial_score', models.PositiveIntegerField(default=0, verbose_name='score inicial')),
                ('initial_level', models.CharField(blank=True, choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=24, verbose_name='nível inicial')),
                ('residual_score', models.PositiveIntegerField(default=0, verbose_name='score residual')),
                ('residual_level', models.CharField(blank=True, choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=24, verbose_name='nível residual')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_risks', to=settings.AUTH_USER_MODEL, verbose_name='encerrado por')),
                ('identified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identified_risks', to=settings.AUTH_USER_MODEL, verbose_name='identificado por')),
                ('monitoring_started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_risk_monitoring', to=settings.AUTH_USER_MODEL, verbose_name='monitoramento iniciado por')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('process_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.businessprocess', verbose_name='processo normalizado')),
                ('treatment_started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_risk_treatments', to=settings.AUTH_USER_MODEL, verbose_name='tratamento iniciado por')),
            ],
            options={
                'verbose_name': 'risco',
                'verbose_name_plural': 'riscos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskMitigationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('action_type', models.CharField(choices=[('mitigation', 'Mitigação'), ('contingency', 'Contingência'), ('monitoring', 'Monitoramento'), ('review', 'Revisão')], max_length=24, verbose_name='tipo de ação')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('due_date', models.DateField(verbose_name='prazo')),
                ('mandatory', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('evidence_required', models.BooleanField(default=True, verbose_name='exige evidência')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=24, verbose_name='status')),
                ('completion_notes', models.TextField(blank=True, verbose_name='observações de conclusão')),
                ('evidence_reference', models.CharField(blank=True, max_length=255, verbose_name='evidência')),
                ('content_hash', models.CharField(blank=True, max_length=128, verbose_name='hash do conteúdo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_risk_actions', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_actions', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='risks.riskrecord', verbose_name='risco')),
            ],
            options={
                'verbose_name': 'ação de risco',
                'verbose_name_plural': 'ações de risco',
                'ordering': ['risk__risk_number', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('link_type', models.CharField(choices=[('process', 'Processo'), ('product', 'Produto'), ('document', 'Documento'), ('deviation', 'Desvio'), ('capa', 'CAPA'), ('change', 'Mudança'), ('audit', 'Auditoria'), ('supplier', 'Fornecedor'), ('equipment', 'Equipamento')], max_length=24, verbose_name='tipo de vínculo')),
                ('reference_code', models.CharField(blank=True, max_length=120, verbose_name='referência')),
                ('impact_description', models.TextField(verbose_name='descrição do impacto')),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_links', to='audits.auditplan', verbose_name='auditoria')),
                ('capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_links', to='capa.caparecord', verbose_name='CAPA')),
                ('change_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_links', to='changes.changecontrol', verbose_name='mudança')),
                ('deviation_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_links', to='deviations.qualityevent', verbose_name='desvio')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_links', to='documents.controlleddocument', verbose_name='documento')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_links', to='masters.product', verbose_name='produto')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_links', to='masters.businesspartner', verbose_name='fornecedor')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='risks.riskrecord', verbose_name='risco')),
            ],
            options={
                'verbose_name': 'vínculo de risco',
                'verbose_name_plural': 'vínculos de risco',
                'ordering': ['risk__risk_number', 'link_type'],
            },
        ),
        migrations.CreateModel(
            name='RiskControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('control_type', models.CharField(choices=[('preventive', 'Preventivo'), ('detective', 'Detectivo'), ('corrective', 'Corretivo'), ('contingency', 'Contingência')], max_length=24, verbose_name='tipo de controle')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('ineffective', 'Ineficaz'), ('retired', 'Retirado')], default='active', max_length=24, verbose_name='status')),
                ('evidence_reference', models.CharField(blank=True, max_length=255, verbose_name='evidência')),
                ('content_hash', models.CharField(blank=True, max_length=128, verbose_name='hash do conteúdo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_risk_controls', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='risks.riskrecord', verbose_name='risco')),
            ],
            options={
                'verbose_name': 'controle de risco',
                'verbose_name_plural': 'controles de risco',
                'ordering': ['risk__risk_number', 'control_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('assessment_type', models.CharField(choices=[('initial', 'Inicial'), ('residual', 'Residual'), ('periodic', 'Periódica')], max_length=24, verbose_name='tipo')),
                ('method', models.CharField(choices=[('matrix', 'Matriz de risco'), ('fmea', 'FMEA')], max_length=24, verbose_name='método')),
                ('probability', models.PositiveSmallIntegerField(verbose_name='probabilidade')),
                ('severity', models.PositiveSmallIntegerField(verbose_name='severidade')),
                ('detectability', models.PositiveSmallIntegerField(default=1, verbose_name='detectabilidade')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='score')),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=24, verbose_name='nível de risco')),
                ('rationale', models.TextField(verbose_name='racional')),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='avaliado em')),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessments', to=settings.AUTH_USER_MODEL, verbose_name='avaliado por')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='risks.riskrecord', verbose_name='risco')),
            ],
            options={
                'verbose_name': 'avaliação de risco',
                'verbose_name_plural': 'avaliações de risco',
                'ordering': ['risk__risk_number', '-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('alert_type', models.CharField(choices=[('critical_risk', 'Risco crítico'), ('overdue_action', 'Ação atrasada'), ('review_due', 'Revisão vencida')], max_length=32, verbose_name='tipo')),
                ('severity', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=24, verbose_name='severidade')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('sent', 'Enviado'), ('acknowledged', 'Reconhecido')], default='open', max_length=24, verbose_name='status')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='reconhecido em')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_risk_alerts', to=settings.AUTH_USER_MODEL, verbose_name='reconhecido por')),
                ('severity_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='severidade normalizada')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='risks.riskmitigationaction', verbose_name='ação')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='risks.riskrecord', verbose_name='risco')),
            ],
            options={
                'verbose_name': 'alerta de risco',
                'verbose_name_plural': 'alertas de risco',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('planned_date', models.DateField(verbose_name='data planejada')),
                ('review_scope', models.TextField(verbose_name='escopo da revisão')),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='planned', max_length=24, verbose_name='status')),
                ('result', models.TextField(blank=True, verbose_name='resultado')),
                ('next_review_date', models.DateField(blank=True, null=True, verbose_name='próxima revisão')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_risk_reviews', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_reviews', to=settings.AUTH_USER_MODEL, verbose_name='revisor')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='risks.riskrecord', verbose_name='risco')),
            ],
            options={
                'verbose_name': 'revisão de risco',
                'verbose_name_plural': 'revisões de risco',
                'ordering': ['risk__risk_number', 'planned_date'],
            },
        ),
        migrations.AddIndex(
            model_name='riskrecord',
            index=models.Index(fields=['risk_category', 'status'], name='risks_riskr_risk_ca_edaa76_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrecord',
            index=models.Index(fields=['owner'], name='risks_riskr_owner_i_880f68_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrecord',
            index=models.Index(fields=['due_date'], name='risks_riskr_due_dat_f5cc2d_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrecord',
            index=models.Index(fields=['next_review_date'], name='risks_riskr_next_re_0bb8df_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrecord',
            index=models.Index(fields=['initial_level'], name='risks_riskr_initial_ee0e43_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrecord',
            index=models.Index(fields=['residual_level'], name='risks_riskr_residua_df9adc_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrecord',
            index=models.Index(fields=['risk_number'], name='risks_riskr_risk_nu_f2a37c_idx'),
        ),
        migrations.AddConstraint(
            model_name='riskrecord',
            constraint=models.UniqueConstraint(fields=('risk_number',), name='unique_risk_number'),
        ),
        migrations.AddIndex(
            model_name='riskmitigationaction',
            index=models.Index(fields=['risk', 'status'], name='risks_riskm_risk_id_f0dd07_idx'),
        ),
        migrations.AddIndex(
            model_name='riskmitigationaction',
            index=models.Index(fields=['responsible', 'due_date'], name='risks_riskm_respons_f58c61_idx'),
        ),
        migrations.AddIndex(
            model_name='riskmitigationaction',
            index=models.Index(fields=['mandatory'], name='risks_riskm_mandato_fb7420_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['risk', 'link_type'], name='risks_riskl_risk_id_b10a88_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['product'], name='risks_riskl_product_6f996c_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['document'], name='risks_riskl_documen_854f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['deviation_event'], name='risks_riskl_deviati_18b8f3_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['capa'], name='risks_riskl_capa_id_9bd1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['change_control'], name='risks_riskl_change__303eac_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['audit'], name='risks_riskl_audit_i_336f07_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['supplier'], name='risks_riskl_supplie_a14a97_idx'),
        ),
        migrations.AddIndex(
            model_name='riskcontrol',
            index=models.Index(fields=['risk', 'status'], name='risks_riskc_risk_id_8d8f79_idx'),
        ),
        migrations.AddIndex(
            model_name='riskcontrol',
            index=models.Index(fields=['control_type'], name='risks_riskc_control_859713_idx'),
        ),
        migrations.AddIndex(
            model_name='riskcontrol',
            index=models.Index(fields=['owner'], name='risks_riskc_owner_i_c6ca62_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['risk', 'assessment_type'], name='risks_riska_risk_id_f98b04_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['method', 'risk_level'], name='risks_riska_method_8d3ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['assessed_by'], name='risks_riska_assesse_784666_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['assessed_at'], name='risks_riska_assesse_d9253c_idx'),
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['risk', 'alert_type', 'status'], name='risks_riska_risk_id_37f753_idx'),
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['action'], name='risks_riska_action__7125cc_idx'),
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['due_date'], name='risks_riska_due_dat_404087_idx'),
        ),
        migrations.AddIndex(
            model_name='riskreview',
            index=models.Index(fields=['risk', 'status'], name='risks_riskr_risk_id_da7203_idx'),
        ),
        migrations.AddIndex(
            model_name='riskreview',
            index=models.Index(fields=['reviewer', 'planned_date'], name='risks_riskr_reviewe_d51adb_idx'),
        ),
        migrations.AddIndex(
            model_name='riskreview',
            index=models.Index(fields=['next_review_date'], name='risks_riskr_next_re_02d334_idx'),
        ),
    ]
