# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_remove_auditplan_unique_tenant_audit_number_and_more'),
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('capa', '0002_remove_capaapproval_unique_tenant_capa_approval_role_user_and_more'),
        ('changes', '0003_remove_changeapproval_unique_tenant_change_approval_role_user_and_more'),
        ('deviations', '0003_remove_deviationapproval_unique_tenant_deviation_approval_role_user_and_more'),
        ('documents', '0003_remove_controlleddocument_unique_tenant_document_code_version_and_more'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('risks', '0002_riskalert_severity_ref_riskrecord_process_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='riskrecord',
            name='unique_tenant_risk_number',
        ),
        migrations.RemoveIndex(
            model_name='riskalert',
            name='risks_riska_tenant__4a7e0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskalert',
            name='risks_riska_tenant__729676_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskalert',
            name='risks_riska_tenant__5f45a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskassessment',
            name='risks_riska_tenant__77af73_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskassessment',
            name='risks_riska_tenant__b685b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskassessment',
            name='risks_riska_tenant__4741ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskassessment',
            name='risks_riska_tenant__bf91ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskcontrol',
            name='risks_riskc_tenant__a21f5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskcontrol',
            name='risks_riskc_tenant__c12154_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskcontrol',
            name='risks_riskc_tenant__a9e849_idx',
        ),
        migrations.RemoveIndex(
            model_name='risklink',
            name='risks_riskl_tenant__2ed836_idx',
        ),
        migrations.RemoveIndex(
            model_name='risklink',
            name='risks_riskl_tenant__c33402_idx',
        ),
        migrations.RemoveIndex(
            model_name='risklink',
            name='risks_riskl_tenant__f83abe_idx',
        ),
        migrations.RemoveIndex(
            model_name='risklink',
            name='risks_riskl_tenant__29ef92_idx',
        ),
        migrations.RemoveIndex(
            model_name='risklink',
            name='risks_riskl_tenant__5cfde9_idx',
        ),
        migrations.RemoveIndex(
            model_name='risklink',
            name='risks_riskl_tenant__e60bf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='risklink',
            name='risks_riskl_tenant__814497_idx',
        ),
        migrations.RemoveIndex(
            model_name='risklink',
            name='risks_riskl_tenant__d64f3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskmitigationaction',
            name='risks_riskm_tenant__cd4133_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskmitigationaction',
            name='risks_riskm_tenant__037b96_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskmitigationaction',
            name='risks_riskm_tenant__24e66f_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskrecord',
            name='risks_riskr_tenant__529239_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskrecord',
            name='risks_riskr_tenant__57a7c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskrecord',
            name='risks_riskr_tenant__f6bf32_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskrecord',
            name='risks_riskr_tenant__ae78c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskrecord',
            name='risks_riskr_tenant__03e1d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskrecord',
            name='risks_riskr_tenant__232e51_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskreview',
            name='risks_riskr_tenant__972435_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskreview',
            name='risks_riskr_tenant__db461a_idx',
        ),
        migrations.RemoveIndex(
            model_name='riskreview',
            name='risks_riskr_tenant__c92ebe_idx',
        ),
        migrations.RemoveField(
            model_name='riskalert',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='riskcontrol',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='risklink',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='riskmitigationaction',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='riskrecord',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='riskreview',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['risk', 'alert_type', 'status'], name='risks_riska_risk_id_37f753_idx'),
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['action'], name='risks_riska_action__7125cc_idx'),
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['due_date'], name='risks_riska_due_dat_404087_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['risk', 'assessment_type'], name='risks_riska_risk_id_f98b04_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['method', 'risk_level'], name='risks_riska_method_8d3ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['assessed_by'], name='risks_riska_assesse_784666_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['assessed_at'], name='risks_riska_assesse_d9253c_idx'),
        ),
        migrations.AddIndex(
            model_name='riskcontrol',
            index=models.Index(fields=['risk', 'status'], name='risks_riskc_risk_id_8d8f79_idx'),
        ),
        migrations.AddIndex(
            model_name='riskcontrol',
            index=models.Index(fields=['control_type'], name='risks_riskc_control_859713_idx'),
        ),
        migrations.AddIndex(
            model_name='riskcontrol',
            index=models.Index(fields=['owner'], name='risks_riskc_owner_i_c6ca62_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['risk', 'link_type'], name='risks_riskl_risk_id_b10a88_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['product'], name='risks_riskl_product_6f996c_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['document'], name='risks_riskl_documen_854f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['deviation_event'], name='risks_riskl_deviati_18b8f3_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['capa'], name='risks_riskl_capa_id_9bd1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['change_control'], name='risks_riskl_change__303eac_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['audit'], name='risks_riskl_audit_i_336f07_idx'),
        ),
        migrations.AddIndex(
            model_name='risklink',
            index=models.Index(fields=['supplier'], name='risks_riskl_supplie_a14a97_idx'),
        ),
        migrations.AddIndex(
            model_name='riskmitigationaction',
            index=models.Index(fields=['risk', 'status'], name='risks_riskm_risk_id_f0dd07_idx'),
        ),
        migrations.AddIndex(
            model_name='riskmitigationaction',
            index=models.Index(fields=['responsible', 'due_date'], name='risks_riskm_respons_f58c61_idx'),
        ),
        migrations.AddIndex(
            model_name='riskmitigationaction',
            index=models.Index(fields=['mandatory'], name='risks_riskm_mandato_fb7420_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrecord',
            index=models.Index(fields=['risk_category', 'status'], name='risks_riskr_risk_ca_edaa76_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrecord',
            index=models.Index(fields=['owner'], name='risks_riskr_owner_i_880f68_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrecord',
            index=models.Index(fields=['due_date'], name='risks_riskr_due_dat_f5cc2d_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrecord',
            index=models.Index(fields=['next_review_date'], name='risks_riskr_next_re_0bb8df_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrecord',
            index=models.Index(fields=['initial_level'], name='risks_riskr_initial_ee0e43_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrecord',
            index=models.Index(fields=['residual_level'], name='risks_riskr_residua_df9adc_idx'),
        ),
        migrations.AddIndex(
            model_name='riskreview',
            index=models.Index(fields=['risk', 'status'], name='risks_riskr_risk_id_da7203_idx'),
        ),
        migrations.AddIndex(
            model_name='riskreview',
            index=models.Index(fields=['reviewer', 'planned_date'], name='risks_riskr_reviewe_d51adb_idx'),
        ),
        migrations.AddIndex(
            model_name='riskreview',
            index=models.Index(fields=['next_review_date'], name='risks_riskr_next_re_02d334_idx'),
        ),
        migrations.AddConstraint(
            model_name='riskrecord',
            constraint=models.UniqueConstraint(fields=('risk_number',), name='unique_risk_number'),
        ),
    ]
