# Generated by Django 6.0.7 on 2026-07-07 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('quality', 'Qualidade'), ('production', 'Produção'), ('regulatory', 'Regulatório'), ('finance', 'Financeiro'), ('viewer', 'Leitura')], default='viewer', max_length=32, verbose_name='papel')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant', verbose_name='tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'associação de tenant',
                'verbose_name_plural': 'associações de tenant',
                'ordering': ['tenant__name', 'user__email'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_te_user_id_c6cf37_idx'), models.Index(fields=['tenant', 'is_active'], name='accounts_te_tenant__6c4fdd_idx'), models.Index(fields=['role'], name='accounts_te_role_afc89e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant'), name='unique_user_tenant_membership')],
            },
        ),
    ]
