# Generated by Django 6.0.7 on 2026-07-11 19:56

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_platform_operator'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembershipInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='seletor')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('quality', 'Qualidade'), ('production', 'Produção'), ('regulatory', 'Regulatório'), ('finance', 'Financeiro'), ('viewer', 'Leitura')], max_length=32, verbose_name='papel')),
                ('source', models.CharField(choices=[('platform_onboarding', 'Onboarding da plataforma'), ('tenant_admin', 'Administrador do tenant')], max_length=32, verbose_name='origem')),
                ('token_digest', models.CharField(editable=False, max_length=64, verbose_name='digest do token')),
                ('expires_at', models.DateTimeField(db_index=True, default=accounts.models.default_membership_invitation_expiry, verbose_name='expira em')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='aceito em')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revogado em')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=16, verbose_name='status de envio')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('last_error', models.TextField(blank=True, verbose_name='último erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_tenant_invitations', to=settings.AUTH_USER_MODEL, verbose_name='convidado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_invitations', to='tenants.tenant', verbose_name='tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_invitations', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'convite de associação ao tenant',
                'verbose_name_plural': 'convites de associação ao tenant',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'email', 'accepted_at', 'revoked_at'], name='accounts_te_tenant__d5e19f_idx'), models.Index(fields=['tenant', 'role', 'created_at'], name='accounts_te_tenant__a2cd63_idx'), models.Index(fields=['delivery_status', 'created_at'], name='accounts_te_deliver_5bda36_idx')],
            },
        ),
    ]
