# Generated by Django 6.0.7 on 2026-07-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenantmembershipinvitation'),
        ('tenants', '0002_tenant_module_contract_enforced_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tenantmembershipinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True)), fields=('tenant', 'email'), name='unique_pending_tenant_invitation'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembershipinvitation',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True), _connector='OR'), name='invitation_not_accepted_and_revoked'),
        ),
    ]
