# Generated by Django 5.2.16 on 2026-07-17 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenantmembershipinvitation_unique_pending_tenant_invitation_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0004_tenant_city_tenant_city_ref_tenant_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenantmembership',
            name='unique_user_tenant_membership',
        ),
        migrations.RemoveConstraint(
            model_name='tenantmembershipinvitation',
            name='unique_pending_tenant_invitation',
        ),
        migrations.RemoveIndex(
            model_name='tenantmembership',
            name='accounts_te_tenant__6c4fdd_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantmembershipinvitation',
            name='accounts_te_tenant__d5e19f_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantmembershipinvitation',
            name='accounts_te_tenant__a2cd63_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_tenant__78e6c9_idx',
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='tenantmembershipinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='convidado por'),
        ),
        migrations.AlterField(
            model_name='tenantmembershipinvitation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['is_active'], name='accounts_te_is_acti_860487_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembershipinvitation',
            index=models.Index(fields=['email', 'accepted_at', 'revoked_at'], name='accounts_te_email_700556_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembershipinvitation',
            index=models.Index(fields=['role', 'created_at'], name='accounts_te_role_c29ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('user', 'tenant'), name='unique_user_membership'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembershipinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True)), fields=('email',), name='unique_pending_invitation'),
        ),
    ]
