# Generated by Django 5.2.16 on 2026-07-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_tenantmembership_unique_user_tenant_membership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tenant',
        ),
    ]
