# Generated by Django 5.2.16 on 2026-07-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantMembershipInvitation',
        ),
    ]
