from django.urls import include, path


urlpatterns = [
    path('accounts/', include('accounts.api_urls', namespace='v1_accounts_api')),
    path('ai-agents/', include('ai_agents.urls', namespace='v1_ai_agents')),
    path('audits/', include('audits.urls', namespace='v1_audits')),
    path('capa/', include('capa.urls', namespace='v1_capa')),
    path('changes/', include('changes.urls', namespace='v1_changes')),
    path('compliance/', include('compliance.urls', namespace='v1_compliance')),
    path('costing/', include('costing.urls', namespace='v1_costing')),
    path('crm/', include('crm.urls', namespace='v1_crm')),
    path('deviations/', include('deviations.urls', namespace='v1_deviations')),
    path('documents/', include('documents.urls', namespace='v1_documents')),
    path('files/', include('files.urls', namespace='v1_files')),
    path('finance/', include('finance.urls', namespace='v1_finance')),
    path('fiscal/', include('fiscal.urls', namespace='v1_fiscal')),
    path('formulations/', include('formulations.urls', namespace='v1_formulations')),
    path('governance/', include('governance.urls', namespace='v1_governance')),
    path('integrations/', include('integrations.urls', namespace='v1_integrations')),
    path('inventory/', include('inventory.urls', namespace='v1_inventory')),
    path('maintenance/', include('maintenance.urls', namespace='v1_maintenance')),
    path('masters/', include('masters.urls', namespace='v1_masters')),
    path('planning/', include('planning.urls', namespace='v1_planning')),
    path('procurement/', include('procurement.urls', namespace='v1_procurement')),
    path('production/', include('production.urls', namespace='v1_production')),
    path('qa/', include('qa.urls', namespace='v1_qa')),
    path('quality/', include('quality.urls', namespace='v1_quality')),
    path('recalls/', include('recalls.urls', namespace='v1_recalls')),
    path('reports/', include('reports.urls', namespace='v1_reports')),
    path('risks/', include('risks.urls', namespace='v1_risks')),
    path('training/', include('training.urls', namespace='v1_training')),
    path('workflow/', include('workflow.urls', namespace='v1_workflow')),
]
