# Generated by Django 6.0.8 on 2026-08-25 17:08

import base.sequences
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('resource_type', models.CharField(choices=[('line', 'Linha'), ('equipment', 'Equipamento'), ('work_center', 'Centro de trabalho'), ('shift', 'Turno')], max_length=24, verbose_name='tipo de recurso')),
                ('work_center', models.CharField(blank=True, max_length=120, verbose_name='centro de trabalho')),
                ('daily_capacity_minutes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='capacidade diária em minutos')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'recurso de capacidade',
                'verbose_name_plural': 'recursos de capacidade',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['resource_type', 'is_active'], name='planning_ca_resourc_6b9dd3_idx'), models.Index(fields=['code'], name='planning_ca_code_ea5a50_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_capacity_resource_code')],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MasterProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('period_start', models.DateField(verbose_name='início do período')),
                ('period_end', models.DateField(verbose_name='fim do período')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'plano mestre de produção',
                'verbose_name_plural': 'planos mestres de produção',
                'ordering': ['-period_start', 'code'],
                'indexes': [models.Index(fields=['status'], name='planning_ma_status_07358f_idx'), models.Index(fields=['period_start', 'period_end'], name='planning_ma_period__8f1d94_idx'), models.Index(fields=['code'], name='planning_ma_code_7e174d_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_mps_code')],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MRPRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('calculated', 'Calculado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='status')),
                ('run_at', models.DateTimeField(blank=True, null=True, verbose_name='calculado em')),
                ('scenario_name', models.CharField(blank=True, max_length=120, verbose_name='cenário de simulação')),
                ('demand_variation_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='variação de demanda (%)')),
                ('lead_time_variation_days', models.IntegerField(default=0, verbose_name='variação de lead time em dias')),
                ('capacity_variation_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='variação de capacidade (%)')),
                ('restriction_notes', models.TextField(blank=True, verbose_name='restrições simuladas')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_runs', to='planning.masterproductionschedule', verbose_name='plano mestre')),
            ],
            options={
                'verbose_name': 'execução de MRP',
                'verbose_name_plural': 'execuções de MRP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapacityLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('period_date', models.DateField(verbose_name='data do período')),
                ('shift', models.CharField(blank=True, max_length=80, verbose_name='turno')),
                ('required_minutes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='minutos requeridos')),
                ('available_minutes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='minutos disponíveis')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacity_loads', to='planning.capacityresource', verbose_name='recurso')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacity_loads', to='planning.mrprun', verbose_name='execução MRP')),
            ],
            options={
                'verbose_name': 'carga de capacidade',
                'verbose_name_plural': 'cargas de capacidade',
                'ordering': ['period_date', 'resource__code'],
            },
        ),
        migrations.CreateModel(
            name='MRPSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('suggestion_type', models.CharField(choices=[('buy', 'Compra'), ('produce', 'Produção'), ('transfer', 'Transferência'), ('outsource', 'Terceirização')], max_length=20, verbose_name='tipo de sugestão')),
                ('due_date', models.DateField(verbose_name='data de necessidade')),
                ('required_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='necessidade bruta')),
                ('available_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='saldo projetado disponível')),
                ('net_requirement', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='necessidade líquida')),
                ('suggested_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade sugerida')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='lead time em dias')),
                ('release_date', models.DateField(verbose_name='data sugerida de liberação')),
                ('alert_level', models.CharField(choices=[('none', 'Sem alerta'), ('shortage', 'Ruptura'), ('late', 'Atraso previsto'), ('excess', 'Excesso'), ('expiring', 'Vencimento próximo'), ('capacity', 'Capacidade insuficiente')], default='none', max_length=20, verbose_name='alerta')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_suggestions', to='masters.product', verbose_name='produto')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='planning.mrprun', verbose_name='execução MRP')),
            ],
            options={
                'verbose_name': 'sugestão do MRP',
                'verbose_name_plural': 'sugestões do MRP',
                'ordering': ['due_date', 'product__code'],
            },
        ),
        migrations.CreateModel(
            name='PlanningPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('preferred_source', models.CharField(choices=[('buy', 'Compra'), ('produce', 'Produção'), ('transfer', 'Transferência'), ('outsource', 'Terceirização')], default='produce', max_length=20, verbose_name='origem preferencial')),
                ('safety_stock_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='estoque de segurança')),
                ('minimum_order_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='lote mínimo')),
                ('order_multiple', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='múltiplo de lote')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='lead time em dias')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='planning_policy', to='masters.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'política de planejamento',
                'verbose_name_plural': 'políticas de planejamento',
                'ordering': ['product__code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('on_hand_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='saldo físico')),
                ('quarantine_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quarentena')),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='reservado')),
                ('incoming_purchase_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='compras em aberto')),
                ('incoming_production_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='ordens em aberto')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='validade mais próxima')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='capturado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_position', to='masters.product', verbose_name='produto')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_positions', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'posição de estoque para MRP',
                'verbose_name_plural': 'posições de estoque para MRP',
                'ordering': ['product__code'],
                'indexes': [models.Index(fields=['product'], name='planning_in_product_6596d8_idx'), models.Index(fields=['expiry_date'], name='planning_in_expiry__9e581d_idx')],
                'constraints': [models.UniqueConstraint(fields=('product',), name='unique_inventory_position_product')],
            },
        ),
        migrations.CreateModel(
            name='MPSLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('due_date', models.DateField(verbose_name='data de necessidade')),
                ('demand_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade demandada')),
                ('source', models.CharField(choices=[('forecast', 'Previsão'), ('sales_order', 'Pedido em carteira'), ('contract', 'Contrato'), ('campaign', 'Campanha'), ('safety_stock', 'Estoque de segurança'), ('manual', 'Manual')], max_length=24, verbose_name='origem da demanda')),
                ('customer_reference', models.CharField(blank=True, max_length=120, verbose_name='referência comercial')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mps_lines', to='masters.product', verbose_name='produto')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='planning.masterproductionschedule', verbose_name='plano mestre')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mps_lines', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'linha do MPS',
                'verbose_name_plural': 'linhas do MPS',
                'ordering': ['due_date', 'product__code'],
                'indexes': [models.Index(fields=['schedule', 'due_date'], name='planning_mp_schedul_41a60a_idx'), models.Index(fields=['product', 'due_date'], name='planning_mp_product_d03995_idx'), models.Index(fields=['source'], name='planning_mp_source_5e40a8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mrprun',
            index=models.Index(fields=['status'], name='planning_mr_status_f421e4_idx'),
        ),
        migrations.AddIndex(
            model_name='mrprun',
            index=models.Index(fields=['schedule', 'created_at'], name='planning_mr_schedul_4a01af_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityload',
            index=models.Index(fields=['period_date'], name='planning_ca_period__1f82e5_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityload',
            index=models.Index(fields=['resource', 'period_date'], name='planning_ca_resourc_bdc0c0_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityload',
            index=models.Index(fields=['run'], name='planning_ca_run_id_02c94c_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpsuggestion',
            index=models.Index(fields=['run'], name='planning_mr_run_id_dd47d7_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpsuggestion',
            index=models.Index(fields=['product', 'suggestion_type'], name='planning_mr_product_18f4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpsuggestion',
            index=models.Index(fields=['alert_level'], name='planning_mr_alert_l_de2af0_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpsuggestion',
            index=models.Index(fields=['due_date'], name='planning_mr_due_dat_18c319_idx'),
        ),
        migrations.AddIndex(
            model_name='planningpolicy',
            index=models.Index(fields=['preferred_source', 'is_active'], name='planning_pl_preferr_701b10_idx'),
        ),
        migrations.AddIndex(
            model_name='planningpolicy',
            index=models.Index(fields=['product'], name='planning_pl_product_82bf15_idx'),
        ),
        migrations.AddConstraint(
            model_name='planningpolicy',
            constraint=models.UniqueConstraint(fields=('product',), name='unique_planning_policy_product'),
        ),
    ]
