# Generated by Django 6.0.7 on 2026-07-07 16:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('resource_type', models.CharField(choices=[('line', 'Linha'), ('equipment', 'Equipamento'), ('work_center', 'Centro de trabalho'), ('shift', 'Turno')], max_length=24, verbose_name='tipo de recurso')),
                ('work_center', models.CharField(blank=True, max_length=120, verbose_name='centro de trabalho')),
                ('daily_capacity_minutes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='capacidade diária em minutos')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'recurso de capacidade',
                'verbose_name_plural': 'recursos de capacidade',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('on_hand_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='saldo físico')),
                ('quarantine_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quarentena')),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='reservado')),
                ('incoming_purchase_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='compras em aberto')),
                ('incoming_production_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='ordens em aberto')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='validade mais próxima')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='capturado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_position', to='masters.product', verbose_name='produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_positions', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'posição de estoque para MRP',
                'verbose_name_plural': 'posições de estoque para MRP',
                'ordering': ['product__code'],
            },
        ),
        migrations.CreateModel(
            name='MasterProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('period_start', models.DateField(verbose_name='início do período')),
                ('period_end', models.DateField(verbose_name='fim do período')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'plano mestre de produção',
                'verbose_name_plural': 'planos mestres de produção',
                'ordering': ['-period_start', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MPSLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('due_date', models.DateField(verbose_name='data de necessidade')),
                ('demand_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade demandada')),
                ('source', models.CharField(choices=[('forecast', 'Previsão'), ('sales_order', 'Pedido em carteira'), ('contract', 'Contrato'), ('campaign', 'Campanha'), ('safety_stock', 'Estoque de segurança'), ('manual', 'Manual')], max_length=24, verbose_name='origem da demanda')),
                ('customer_reference', models.CharField(blank=True, max_length=120, verbose_name='referência comercial')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mps_lines', to='masters.product', verbose_name='produto')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='planning.masterproductionschedule', verbose_name='plano mestre')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mps_lines', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'linha do MPS',
                'verbose_name_plural': 'linhas do MPS',
                'ordering': ['due_date', 'product__code'],
            },
        ),
        migrations.CreateModel(
            name='MRPRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('calculated', 'Calculado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='status')),
                ('run_at', models.DateTimeField(blank=True, null=True, verbose_name='calculado em')),
                ('scenario_name', models.CharField(blank=True, max_length=120, verbose_name='cenário de simulação')),
                ('demand_variation_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='variação de demanda (%)')),
                ('lead_time_variation_days', models.IntegerField(default=0, verbose_name='variação de lead time em dias')),
                ('capacity_variation_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='variação de capacidade (%)')),
                ('restriction_notes', models.TextField(blank=True, verbose_name='restrições simuladas')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_runs', to='planning.masterproductionschedule', verbose_name='plano mestre')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'execução de MRP',
                'verbose_name_plural': 'execuções de MRP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapacityLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('period_date', models.DateField(verbose_name='data do período')),
                ('shift', models.CharField(blank=True, max_length=80, verbose_name='turno')),
                ('required_minutes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='minutos requeridos')),
                ('available_minutes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='minutos disponíveis')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacity_loads', to='planning.capacityresource', verbose_name='recurso')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacity_loads', to='planning.mrprun', verbose_name='execução MRP')),
            ],
            options={
                'verbose_name': 'carga de capacidade',
                'verbose_name_plural': 'cargas de capacidade',
                'ordering': ['period_date', 'resource__code'],
            },
        ),
        migrations.CreateModel(
            name='MRPSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('suggestion_type', models.CharField(choices=[('buy', 'Compra'), ('produce', 'Produção'), ('transfer', 'Transferência'), ('outsource', 'Terceirização')], max_length=20, verbose_name='tipo de sugestão')),
                ('due_date', models.DateField(verbose_name='data de necessidade')),
                ('required_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='necessidade bruta')),
                ('available_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='saldo projetado disponível')),
                ('net_requirement', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='necessidade líquida')),
                ('suggested_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade sugerida')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='lead time em dias')),
                ('release_date', models.DateField(verbose_name='data sugerida de liberação')),
                ('alert_level', models.CharField(choices=[('none', 'Sem alerta'), ('shortage', 'Ruptura'), ('late', 'Atraso previsto'), ('excess', 'Excesso'), ('expiring', 'Vencimento próximo'), ('capacity', 'Capacidade insuficiente')], default='none', max_length=20, verbose_name='alerta')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_suggestions', to='masters.product', verbose_name='produto')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='planning.mrprun', verbose_name='execução MRP')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'sugestão do MRP',
                'verbose_name_plural': 'sugestões do MRP',
                'ordering': ['due_date', 'product__code'],
            },
        ),
        migrations.CreateModel(
            name='PlanningPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('preferred_source', models.CharField(choices=[('buy', 'Compra'), ('produce', 'Produção'), ('transfer', 'Transferência'), ('outsource', 'Terceirização')], default='produce', max_length=20, verbose_name='origem preferencial')),
                ('safety_stock_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='estoque de segurança')),
                ('minimum_order_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='lote mínimo')),
                ('order_multiple', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='múltiplo de lote')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='lead time em dias')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='planning_policy', to='masters.product', verbose_name='produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'política de planejamento',
                'verbose_name_plural': 'políticas de planejamento',
                'ordering': ['product__code'],
            },
        ),
        migrations.AddIndex(
            model_name='capacityresource',
            index=models.Index(fields=['tenant', 'resource_type', 'is_active'], name='planning_ca_tenant__241992_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityresource',
            index=models.Index(fields=['code'], name='planning_ca_code_ea5a50_idx'),
        ),
        migrations.AddConstraint(
            model_name='capacityresource',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_capacity_resource_code'),
        ),
        migrations.AddIndex(
            model_name='inventoryposition',
            index=models.Index(fields=['tenant', 'product'], name='planning_in_tenant__e10e23_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryposition',
            index=models.Index(fields=['tenant', 'expiry_date'], name='planning_in_tenant__fe1591_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryposition',
            constraint=models.UniqueConstraint(fields=('tenant', 'product'), name='unique_tenant_inventory_position_product'),
        ),
        migrations.AddIndex(
            model_name='masterproductionschedule',
            index=models.Index(fields=['tenant', 'status'], name='planning_ma_tenant__c1321c_idx'),
        ),
        migrations.AddIndex(
            model_name='masterproductionschedule',
            index=models.Index(fields=['tenant', 'period_start', 'period_end'], name='planning_ma_tenant__5863c8_idx'),
        ),
        migrations.AddIndex(
            model_name='masterproductionschedule',
            index=models.Index(fields=['code'], name='planning_ma_code_7e174d_idx'),
        ),
        migrations.AddConstraint(
            model_name='masterproductionschedule',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_mps_code'),
        ),
        migrations.AddIndex(
            model_name='mpsline',
            index=models.Index(fields=['tenant', 'schedule', 'due_date'], name='planning_mp_tenant__d59dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='mpsline',
            index=models.Index(fields=['tenant', 'product', 'due_date'], name='planning_mp_tenant__01f534_idx'),
        ),
        migrations.AddIndex(
            model_name='mpsline',
            index=models.Index(fields=['source'], name='planning_mp_source_5e40a8_idx'),
        ),
        migrations.AddIndex(
            model_name='mrprun',
            index=models.Index(fields=['tenant', 'status'], name='planning_mr_tenant__25b060_idx'),
        ),
        migrations.AddIndex(
            model_name='mrprun',
            index=models.Index(fields=['tenant', 'schedule', 'created_at'], name='planning_mr_tenant__a1891e_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityload',
            index=models.Index(fields=['tenant', 'period_date'], name='planning_ca_tenant__6d75ec_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityload',
            index=models.Index(fields=['tenant', 'resource', 'period_date'], name='planning_ca_tenant__b71438_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityload',
            index=models.Index(fields=['tenant', 'run'], name='planning_ca_tenant__2e3b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpsuggestion',
            index=models.Index(fields=['tenant', 'run'], name='planning_mr_tenant__c84ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpsuggestion',
            index=models.Index(fields=['tenant', 'product', 'suggestion_type'], name='planning_mr_tenant__0ac89c_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpsuggestion',
            index=models.Index(fields=['tenant', 'alert_level'], name='planning_mr_tenant__17f35c_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpsuggestion',
            index=models.Index(fields=['due_date'], name='planning_mr_due_dat_18c319_idx'),
        ),
        migrations.AddIndex(
            model_name='planningpolicy',
            index=models.Index(fields=['tenant', 'preferred_source', 'is_active'], name='planning_pl_tenant__02e517_idx'),
        ),
        migrations.AddIndex(
            model_name='planningpolicy',
            index=models.Index(fields=['tenant', 'product'], name='planning_pl_tenant__402233_idx'),
        ),
        migrations.AddConstraint(
            model_name='planningpolicy',
            constraint=models.UniqueConstraint(fields=('tenant', 'product'), name='unique_tenant_planning_policy_product'),
        ),
    ]
