# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capacityresource',
            name='unique_tenant_capacity_resource_code',
        ),
        migrations.RemoveConstraint(
            model_name='inventoryposition',
            name='unique_tenant_inventory_position_product',
        ),
        migrations.RemoveConstraint(
            model_name='masterproductionschedule',
            name='unique_tenant_mps_code',
        ),
        migrations.RemoveConstraint(
            model_name='planningpolicy',
            name='unique_tenant_planning_policy_product',
        ),
        migrations.RemoveIndex(
            model_name='capacityload',
            name='planning_ca_tenant__6d75ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='capacityload',
            name='planning_ca_tenant__b71438_idx',
        ),
        migrations.RemoveIndex(
            model_name='capacityload',
            name='planning_ca_tenant__2e3b7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='capacityresource',
            name='planning_ca_tenant__241992_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryposition',
            name='planning_in_tenant__e10e23_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryposition',
            name='planning_in_tenant__fe1591_idx',
        ),
        migrations.RemoveIndex(
            model_name='masterproductionschedule',
            name='planning_ma_tenant__c1321c_idx',
        ),
        migrations.RemoveIndex(
            model_name='masterproductionschedule',
            name='planning_ma_tenant__5863c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='mpsline',
            name='planning_mp_tenant__d59dfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='mpsline',
            name='planning_mp_tenant__01f534_idx',
        ),
        migrations.RemoveIndex(
            model_name='mrprun',
            name='planning_mr_tenant__25b060_idx',
        ),
        migrations.RemoveIndex(
            model_name='mrprun',
            name='planning_mr_tenant__a1891e_idx',
        ),
        migrations.RemoveIndex(
            model_name='mrpsuggestion',
            name='planning_mr_tenant__c84ccc_idx',
        ),
        migrations.RemoveIndex(
            model_name='mrpsuggestion',
            name='planning_mr_tenant__0ac89c_idx',
        ),
        migrations.RemoveIndex(
            model_name='mrpsuggestion',
            name='planning_mr_tenant__17f35c_idx',
        ),
        migrations.RemoveIndex(
            model_name='planningpolicy',
            name='planning_pl_tenant__02e517_idx',
        ),
        migrations.RemoveIndex(
            model_name='planningpolicy',
            name='planning_pl_tenant__402233_idx',
        ),
        migrations.RemoveField(
            model_name='capacityload',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='capacityresource',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='inventoryposition',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='masterproductionschedule',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='mpsline',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='mrprun',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='mrpsuggestion',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='planningpolicy',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='capacityload',
            index=models.Index(fields=['period_date'], name='planning_ca_period__1f82e5_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityload',
            index=models.Index(fields=['resource', 'period_date'], name='planning_ca_resourc_bdc0c0_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityload',
            index=models.Index(fields=['run'], name='planning_ca_run_id_02c94c_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityresource',
            index=models.Index(fields=['resource_type', 'is_active'], name='planning_ca_resourc_6b9dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryposition',
            index=models.Index(fields=['product'], name='planning_in_product_6596d8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryposition',
            index=models.Index(fields=['expiry_date'], name='planning_in_expiry__9e581d_idx'),
        ),
        migrations.AddIndex(
            model_name='masterproductionschedule',
            index=models.Index(fields=['status'], name='planning_ma_status_07358f_idx'),
        ),
        migrations.AddIndex(
            model_name='masterproductionschedule',
            index=models.Index(fields=['period_start', 'period_end'], name='planning_ma_period__8f1d94_idx'),
        ),
        migrations.AddIndex(
            model_name='mpsline',
            index=models.Index(fields=['schedule', 'due_date'], name='planning_mp_schedul_41a60a_idx'),
        ),
        migrations.AddIndex(
            model_name='mpsline',
            index=models.Index(fields=['product', 'due_date'], name='planning_mp_product_d03995_idx'),
        ),
        migrations.AddIndex(
            model_name='mrprun',
            index=models.Index(fields=['status'], name='planning_mr_status_f421e4_idx'),
        ),
        migrations.AddIndex(
            model_name='mrprun',
            index=models.Index(fields=['schedule', 'created_at'], name='planning_mr_schedul_4a01af_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpsuggestion',
            index=models.Index(fields=['run'], name='planning_mr_run_id_dd47d7_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpsuggestion',
            index=models.Index(fields=['product', 'suggestion_type'], name='planning_mr_product_18f4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='mrpsuggestion',
            index=models.Index(fields=['alert_level'], name='planning_mr_alert_l_de2af0_idx'),
        ),
        migrations.AddIndex(
            model_name='planningpolicy',
            index=models.Index(fields=['preferred_source', 'is_active'], name='planning_pl_preferr_701b10_idx'),
        ),
        migrations.AddIndex(
            model_name='planningpolicy',
            index=models.Index(fields=['product'], name='planning_pl_product_82bf15_idx'),
        ),
        migrations.AddConstraint(
            model_name='capacityresource',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_capacity_resource_code'),
        ),
        migrations.AddConstraint(
            model_name='inventoryposition',
            constraint=models.UniqueConstraint(fields=('product',), name='unique_inventory_position_product'),
        ),
        migrations.AddConstraint(
            model_name='masterproductionschedule',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_mps_code'),
        ),
        migrations.AddConstraint(
            model_name='planningpolicy',
            constraint=models.UniqueConstraint(fields=('product',), name='unique_planning_policy_product'),
        ),
    ]
