# Generated by Django 5.2.16 on 2026-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_remove_capacityresource_unique_tenant_capacity_resource_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacityresource',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='masterproductionschedule',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
    ]
