# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFindingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('link_type', models.CharField(choices=[('capa', 'CAPA'), ('deviation', 'Desvio'), ('change', 'Mudança'), ('risk', 'Risco'), ('supplier', 'Fornecedor'), ('document', 'Documento'), ('training', 'Treinamento')], max_length=24, verbose_name='tipo de vínculo')),
                ('reference_code', models.CharField(blank=True, max_length=120, verbose_name='referência')),
            ],
            options={
                'verbose_name': 'vínculo de achado de auditoria',
                'verbose_name_plural': 'vínculos de achados de auditoria',
                'ordering': ['finding__audit__audit_number', 'link_type'],
            },
        ),
        migrations.CreateModel(
            name='AuditFollowUpAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('due_date', models.DateField(verbose_name='prazo')),
                ('mandatory', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('evidence_required', models.BooleanField(default=True, verbose_name='exige evidência')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=24, verbose_name='status')),
                ('completion_notes', models.TextField(blank=True, verbose_name='observações de conclusão')),
                ('evidence_reference', models.CharField(blank=True, max_length=255, verbose_name='evidência')),
                ('content_hash', models.CharField(blank=True, max_length=128, verbose_name='hash do conteúdo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
            ],
            options={
                'verbose_name': 'ação de auditoria',
                'verbose_name_plural': 'ações de auditoria',
                'ordering': ['finding__audit__audit_number', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('audit_number', models.CharField(blank=True, max_length=80, verbose_name='auditoria')),
                ('audit_type', models.CharField(choices=[('internal', 'Interna'), ('external', 'Externa'), ('supplier', 'Fornecedor'), ('customer', 'Cliente'), ('regulatory', 'Regulatória')], max_length=24, verbose_name='tipo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('scope', models.TextField(verbose_name='escopo')),
                ('criteria', models.TextField(verbose_name='critérios')),
                ('agenda', models.TextField(verbose_name='agenda')),
                ('auditee_name', models.CharField(max_length=180, verbose_name='auditado')),
                ('area', models.CharField(max_length=120, verbose_name='área')),
                ('venue_zipcode', models.CharField(blank=True, max_length=20, verbose_name='CEP do local')),
                ('venue_street', models.CharField(blank=True, max_length=200, verbose_name='logradouro do local')),
                ('venue_street_number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('venue_complement', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('venue_neighborhood', models.CharField(blank=True, max_length=120, verbose_name='bairro do local')),
                ('scheduled_start', models.DateTimeField(verbose_name='início planejado')),
                ('scheduled_end', models.DateTimeField(verbose_name='fim planejado')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='início real')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='fim real')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('planned', 'Planejada'), ('in_progress', 'Em execução'), ('reporting', 'Em relatório'), ('closed', 'Encerrada'), ('cancelled', 'Cancelada')], default='draft', max_length=24, verbose_name='status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submetida em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrada em')),
                ('closure_summary', models.TextField(blank=True, verbose_name='resumo de encerramento')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
            ],
            options={
                'verbose_name': 'plano de auditoria',
                'verbose_name_plural': 'planos de auditoria',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='AuditProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('program_number', models.CharField(blank=True, max_length=80, verbose_name='programa')),
                ('audit_type', models.CharField(choices=[('internal', 'Interna'), ('external', 'Externa'), ('supplier', 'Fornecedor'), ('customer', 'Cliente'), ('regulatory', 'Regulatória')], max_length=24, verbose_name='tipo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('year', models.PositiveIntegerField(verbose_name='ano')),
                ('scope', models.TextField(verbose_name='escopo')),
                ('criteria', models.TextField(verbose_name='critérios')),
                ('starts_on', models.DateField(verbose_name='início')),
                ('ends_on', models.DateField(verbose_name='fim')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('closed', 'Encerrado'), ('cancelled', 'Cancelado')], default='draft', max_length=24, verbose_name='status')),
            ],
            options={
                'verbose_name': 'programa de auditoria',
                'verbose_name_plural': 'programas de auditoria',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('executive_summary', models.TextField(verbose_name='sumário executivo')),
                ('conclusion', models.TextField(verbose_name='conclusão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('issued', 'Emitido')], default='draft', max_length=24, verbose_name='status')),
                ('total_findings', models.PositiveIntegerField(default=0, verbose_name='achados totais')),
                ('critical_findings', models.PositiveIntegerField(default=0, verbose_name='achados críticos')),
                ('major_findings', models.PositiveIntegerField(default=0, verbose_name='achados maiores')),
                ('minor_findings', models.PositiveIntegerField(default=0, verbose_name='achados menores')),
                ('opportunities', models.PositiveIntegerField(default=0, verbose_name='oportunidades')),
                ('total_checklist_items', models.PositiveIntegerField(default=0, verbose_name='itens avaliados')),
                ('conform_items', models.PositiveIntegerField(default=0, verbose_name='itens conformes')),
                ('nonconform_items', models.PositiveIntegerField(default=0, verbose_name='itens não conformes')),
                ('compliance_rate', models.PositiveIntegerField(default=0, verbose_name='índice de conformidade')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='emitido em')),
            ],
            options={
                'verbose_name': 'relatório de auditoria',
                'verbose_name_plural': 'relatórios de auditoria',
                'ordering': ['audit__audit_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('section', models.CharField(max_length=120, verbose_name='seção')),
                ('question', models.TextField(verbose_name='pergunta')),
                ('requirement_reference', models.CharField(max_length=160, verbose_name='referência do requisito')),
                ('required', models.BooleanField(default=True, verbose_name='obrigatório')),
                ('status', models.CharField(choices=[('not_evaluated', 'Não avaliado'), ('conform', 'Conforme'), ('non_conform', 'Não conforme'), ('not_applicable', 'Não aplicável')], default='not_evaluated', max_length=24, verbose_name='status')),
                ('answer_text', models.TextField(blank=True, db_column='answer', verbose_name='resposta/evidência')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='respondido em')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answered_audit_checklists', to=settings.AUTH_USER_MODEL, verbose_name='respondido por')),
            ],
            options={
                'verbose_name': 'item de checklist de auditoria',
                'verbose_name_plural': 'itens de checklist de auditoria',
                'ordering': ['audit__audit_number', 'section', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('classification', models.CharField(choices=[('nonconformity', 'Não conformidade'), ('observation', 'Observação'), ('opportunity', 'Oportunidade de melhoria'), ('compliance', 'Conformidade')], max_length=32, verbose_name='classificação')),
                ('criticality', models.CharField(choices=[('minor', 'Menor'), ('major', 'Maior'), ('critical', 'Crítica')], max_length=24, verbose_name='criticidade')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('due_date', models.DateField(verbose_name='prazo')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_action', 'Em ação'), ('closed', 'Encerrado'), ('cancelled', 'Cancelado')], default='open', max_length=24, verbose_name='status')),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='audits.auditchecklistitem', verbose_name='item de checklist')),
                ('criticality_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='criticidade normalizada')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_findings', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'achado de auditoria',
                'verbose_name_plural': 'achados de auditoria',
                'ordering': ['audit__audit_number', '-criticality', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('file_reference', models.CharField(max_length=255, verbose_name='arquivo')),
                ('content_hash', models.CharField(max_length=128, verbose_name='hash do conteúdo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_audit_evidences', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='audits.auditfinding', verbose_name='achado')),
            ],
            options={
                'verbose_name': 'evidência de auditoria',
                'verbose_name_plural': 'evidências de auditoria',
                'ordering': ['audit__audit_number', 'title'],
            },
        ),
    ]
