# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        ('capa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfindinglink',
            name='capa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_links', to='capa.caparecord', verbose_name='CAPA'),
        ),
    ]
