# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_auditplan_site_auditplan_venue_city_and_more'),
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('capa', '0001_initial'),
        ('changes', '0003_remove_changeapproval_unique_tenant_change_approval_role_user_and_more'),
        ('deviations', '0002_qualityevent_area_ref_qualityevent_criticality_ref_and_more'),
        ('documents', '0003_remove_controlleddocument_unique_tenant_document_code_version_and_more'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auditplan',
            name='unique_tenant_audit_number',
        ),
        migrations.RemoveConstraint(
            model_name='auditprogram',
            name='unique_tenant_audit_program_number',
        ),
        migrations.RemoveConstraint(
            model_name='auditreport',
            name='unique_tenant_audit_report',
        ),
        migrations.RemoveIndex(
            model_name='auditchecklistitem',
            name='audits_audi_tenant__baa8b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditchecklistitem',
            name='audits_audi_tenant__4b6bf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditevidence',
            name='audits_audi_tenant__339be0_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditevidence',
            name='audits_audi_tenant__4fa856_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditfinding',
            name='audits_audi_tenant__2c7a20_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditfinding',
            name='audits_audi_tenant__6d451e_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditfinding',
            name='audits_audi_tenant__ae3fe7_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditfindinglink',
            name='audits_audi_tenant__3ac8a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditfindinglink',
            name='audits_audi_tenant__28d6d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditfindinglink',
            name='audits_audi_tenant__a6e340_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditfindinglink',
            name='audits_audi_tenant__2bccbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditfindinglink',
            name='audits_audi_tenant__afd320_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditfindinglink',
            name='audits_audi_tenant__c76446_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditfollowupaction',
            name='audits_audi_tenant__78fccd_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditfollowupaction',
            name='audits_audi_tenant__bf8d9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditplan',
            name='audits_audi_tenant__014c3f_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditplan',
            name='audits_audi_tenant__b48f16_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditplan',
            name='audits_audi_tenant__c02570_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditplan',
            name='audits_audi_tenant__5f25d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditplan',
            name='audits_audi_tenant__240dca_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditprogram',
            name='audits_audi_tenant__750195_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditprogram',
            name='audits_audi_tenant__73a065_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditprogram',
            name='audits_audi_tenant__841142_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditreport',
            name='audits_audi_tenant__631792_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditreport',
            name='audits_audi_tenant__398820_idx',
        ),
        migrations.RemoveField(
            model_name='auditchecklistitem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='auditevidence',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='auditfinding',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='auditfindinglink',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='auditfollowupaction',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='auditplan',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='auditprogram',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='auditreport',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='auditchecklistitem',
            index=models.Index(fields=['audit', 'status'], name='audits_audi_audit_i_eed0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditchecklistitem',
            index=models.Index(fields=['section'], name='audits_audi_section_65a6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevidence',
            index=models.Index(fields=['audit'], name='audits_audi_audit_i_acb287_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevidence',
            index=models.Index(fields=['finding'], name='audits_audi_finding_140be8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['audit', 'classification'], name='audits_audi_audit_i_c7cf52_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['criticality', 'status'], name='audits_audi_critica_cb125a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['responsible', 'due_date'], name='audits_audi_respons_972ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfindinglink',
            index=models.Index(fields=['finding', 'link_type'], name='audits_audi_finding_ac70e0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfindinglink',
            index=models.Index(fields=['capa'], name='audits_audi_capa_id_91b55a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfindinglink',
            index=models.Index(fields=['deviation_event'], name='audits_audi_deviati_7b1242_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfindinglink',
            index=models.Index(fields=['change_control'], name='audits_audi_change__57aa7b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfindinglink',
            index=models.Index(fields=['supplier'], name='audits_audi_supplie_e22be9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfindinglink',
            index=models.Index(fields=['document'], name='audits_audi_documen_55a104_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfollowupaction',
            index=models.Index(fields=['finding', 'status'], name='audits_audi_finding_7f5792_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfollowupaction',
            index=models.Index(fields=['responsible', 'due_date'], name='audits_audi_respons_5c5321_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['audit_type', 'status'], name='audits_audi_audit_t_fc3d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['program'], name='audits_audi_program_1679fe_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['lead_auditor'], name='audits_audi_lead_au_0ea4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['supplier'], name='audits_audi_supplie_a5bfcb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['scheduled_start'], name='audits_audi_schedul_88403f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditprogram',
            index=models.Index(fields=['audit_type', 'status'], name='audits_audi_audit_t_72bd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditprogram',
            index=models.Index(fields=['year'], name='audits_audi_year_1b93d5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditprogram',
            index=models.Index(fields=['owner'], name='audits_audi_owner_i_8a6207_idx'),
        ),
        migrations.AddIndex(
            model_name='auditreport',
            index=models.Index(fields=['audit', 'status'], name='audits_audi_audit_i_9b82b0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditreport',
            index=models.Index(fields=['issued_at'], name='audits_audi_issued__fb6ac0_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditplan',
            constraint=models.UniqueConstraint(fields=('audit_number',), name='unique_audit_number'),
        ),
        migrations.AddConstraint(
            model_name='auditprogram',
            constraint=models.UniqueConstraint(fields=('program_number',), name='unique_audit_program_number'),
        ),
        migrations.AddConstraint(
            model_name='auditreport',
            constraint=models.UniqueConstraint(fields=('audit',), name='unique_audit_report'),
        ),
    ]
