# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0003_initial'),
        ('auxiliary', '0001_initial'),
        ('deviations', '0001_initial'),
        ('documents', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfindinglink',
            name='deviation_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_links', to='deviations.qualityevent', verbose_name='desvio'),
        ),
        migrations.AddField(
            model_name='auditfindinglink',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_finding_links', to='documents.controlleddocument', verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='auditfindinglink',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='audits.auditfinding', verbose_name='achado'),
        ),
        migrations.AddField(
            model_name='auditfindinglink',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_finding_links', to='masters.businesspartner', verbose_name='fornecedor'),
        ),
        migrations.AddField(
            model_name='auditfollowupaction',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='concluída por'),
        ),
        migrations.AddField(
            model_name='auditfollowupaction',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='audits.auditfinding', verbose_name='achado'),
        ),
        migrations.AddField(
            model_name='auditfollowupaction',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_follow_up_actions', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='area_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.businessarea', verbose_name='área normalizada'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_audits', to=settings.AUTH_USER_MODEL, verbose_name='encerrada por'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_audits', to=settings.AUTH_USER_MODEL, verbose_name='execução concluída por'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='lead_auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_audits', to=settings.AUTH_USER_MODEL, verbose_name='auditor líder'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_plans', to='masters.site', verbose_name='unidade/planta auditada'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_audits', to=settings.AUTH_USER_MODEL, verbose_name='iniciada por'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_audits', to=settings.AUTH_USER_MODEL, verbose_name='submetida por'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_audits', to='masters.businesspartner', verbose_name='fornecedor/cliente auditado'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='venue_city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='venue_country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliary.country', verbose_name='país'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='venue_state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.auditplan', verbose_name='auditoria'),
        ),
        migrations.AddField(
            model_name='auditevidence',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='audits.auditplan', verbose_name='auditoria'),
        ),
        migrations.AddField(
            model_name='auditchecklistitem',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='audits.auditplan', verbose_name='auditoria'),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_audit_programs', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='audits.auditprogram', verbose_name='programa'),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='audits.auditplan', verbose_name='auditoria'),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_audit_reports', to=settings.AUTH_USER_MODEL, verbose_name='emitido por'),
        ),
        migrations.AddIndex(
            model_name='auditfindinglink',
            index=models.Index(fields=['finding', 'link_type'], name='audits_audi_finding_ac70e0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfindinglink',
            index=models.Index(fields=['capa'], name='audits_audi_capa_id_91b55a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfindinglink',
            index=models.Index(fields=['deviation_event'], name='audits_audi_deviati_7b1242_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfindinglink',
            index=models.Index(fields=['change_control'], name='audits_audi_change__57aa7b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfindinglink',
            index=models.Index(fields=['supplier'], name='audits_audi_supplie_e22be9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfindinglink',
            index=models.Index(fields=['document'], name='audits_audi_documen_55a104_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfollowupaction',
            index=models.Index(fields=['finding', 'status'], name='audits_audi_finding_7f5792_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfollowupaction',
            index=models.Index(fields=['responsible', 'due_date'], name='audits_audi_respons_5c5321_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['audit', 'classification'], name='audits_audi_audit_i_c7cf52_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['criticality', 'status'], name='audits_audi_critica_cb125a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['responsible', 'due_date'], name='audits_audi_respons_972ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevidence',
            index=models.Index(fields=['audit'], name='audits_audi_audit_i_acb287_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevidence',
            index=models.Index(fields=['finding'], name='audits_audi_finding_140be8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevidence',
            index=models.Index(fields=['content_hash'], name='audits_audi_content_969307_idx'),
        ),
        migrations.AddIndex(
            model_name='auditchecklistitem',
            index=models.Index(fields=['audit', 'status'], name='audits_audi_audit_i_eed0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditchecklistitem',
            index=models.Index(fields=['section'], name='audits_audi_section_65a6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditprogram',
            index=models.Index(fields=['audit_type', 'status'], name='audits_audi_audit_t_72bd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditprogram',
            index=models.Index(fields=['year'], name='audits_audi_year_1b93d5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditprogram',
            index=models.Index(fields=['owner'], name='audits_audi_owner_i_8a6207_idx'),
        ),
        migrations.AddIndex(
            model_name='auditprogram',
            index=models.Index(fields=['program_number'], name='audits_audi_program_9e934c_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditprogram',
            constraint=models.UniqueConstraint(fields=('program_number',), name='unique_audit_program_number'),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['audit_type', 'status'], name='audits_audi_audit_t_fc3d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['program'], name='audits_audi_program_1679fe_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['lead_auditor'], name='audits_audi_lead_au_0ea4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['supplier'], name='audits_audi_supplie_a5bfcb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['scheduled_start'], name='audits_audi_schedul_88403f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['audit_number'], name='audits_audi_audit_n_5d3565_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditplan',
            constraint=models.UniqueConstraint(fields=('audit_number',), name='unique_audit_number'),
        ),
        migrations.AddIndex(
            model_name='auditreport',
            index=models.Index(fields=['audit', 'status'], name='audits_audi_audit_i_9b82b0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditreport',
            index=models.Index(fields=['issued_at'], name='audits_audi_issued__fb6ac0_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditreport',
            constraint=models.UniqueConstraint(fields=('audit',), name='unique_audit_report'),
        ),
    ]
