# Generated by Django 5.2.16 on 2026-07-22 17:53

import django.db.models.deletion
from django.db import migrations, models


def validate_legacy_location(apps, schema_editor):
    model = apps.get_model('audits', 'AuditPlan')
    invalid_locations = []

    for legacy_field, normalized_field in (
        ('venue_city', 'venue_city_ref'),
        ('venue_state', 'venue_state_ref'),
    ):
        has_unmigrated_location = (
            model.objects.filter(
                **{
                    f'{legacy_field}__isnull': False,
                    f'{normalized_field}__isnull': True,
                }
            )
            .exclude(**{legacy_field: ''})
            .exists()
        )
        if has_unmigrated_location:
            invalid_locations.append(legacy_field)

    if invalid_locations:
        raise RuntimeError(
            'Preencha as referências normalizadas antes de remover os campos legados: '
            + ', '.join(invalid_locations)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_remove_auditplan_unique_tenant_audit_number_and_more'),
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
    ]

    operations = [
        migrations.RunPython(validate_legacy_location, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='auditplan',
            name='venue_city',
        ),
        migrations.RemoveField(
            model_name='auditplan',
            name='venue_state',
        ),
        migrations.AddField(
            model_name='auditplan',
            name='venue_complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='venue_street_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='venue_city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='venue_state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF'),
        ),
    ]
