# Generated by Django 5.2.16 on 2026-07-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_remove_auditplan_venue_city_and_more'),
        ('auxiliary', '0006_stateprovince_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditplan',
            name='venue_country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliary.country', verbose_name='país'),
        ),
    ]
