# Generated by Django 6.0.7 on 2026-07-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'área operacional',
                'verbose_name_plural': 'áreas operacionais',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='auxiliary.businessarea', verbose_name='área')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'processo operacional',
                'verbose_name_plural': 'processos operacionais',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('target_field', models.CharField(blank=True, max_length=80, verbose_name='campo alvo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'tipo de catálogo',
                'verbose_name_plural': 'tipos de catálogo',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('value', models.CharField(max_length=120, verbose_name='valor técnico')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('catalog_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='auxiliary.catalogtype', verbose_name='tipo de catálogo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'valor de catálogo',
                'verbose_name_plural': 'valores de catálogo',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommercialTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('term_type', models.CharField(choices=[('payment', 'Pagamento'), ('delivery', 'Entrega')], max_length=16, verbose_name='tipo de condição')),
                ('days', models.PositiveIntegerField(default=0, verbose_name='dias')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'condição comercial',
                'verbose_name_plural': 'condições comerciais',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('iso_alpha2', models.CharField(blank=True, max_length=2, verbose_name='ISO alfa-2')),
                ('iso_alpha3', models.CharField(blank=True, max_length=3, verbose_name='ISO alfa-3')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('numeric_code', models.CharField(blank=True, max_length=3, verbose_name='código numérico')),
                ('symbol', models.CharField(blank=True, max_length=8, verbose_name='símbolo')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='casas decimais')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'moeda',
                'verbose_name_plural': 'moedas',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='auxiliary.businessarea', verbose_name='área')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImpactLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('level_type', models.CharField(choices=[('severity', 'Severidade'), ('criticality', 'Criticidade'), ('priority', 'Prioridade'), ('risk', 'Risco')], max_length=24, verbose_name='tipo de nível')),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='peso')),
                ('color', models.CharField(blank=True, max_length=24, verbose_name='cor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'nível de impacto',
                'verbose_name_plural': 'níveis de impacto',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'função organizacional',
                'verbose_name_plural': 'funções organizacionais',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StateProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('abbreviation', models.CharField(blank=True, max_length=16, verbose_name='UF/sigla')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='states', to='auxiliary.country', verbose_name='país')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'estado/UF',
                'verbose_name_plural': 'estados/UFs',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('ibge_code', models.CharField(blank=True, max_length=16, verbose_name='código IBGE')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='auxiliary.stateprovince', verbose_name='estado/UF')),
            ],
            options={
                'verbose_name': 'cidade/município',
                'verbose_name_plural': 'cidades/municípios',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('app_label', models.CharField(blank=True, max_length=80, verbose_name='app label')),
                ('menu_label', models.CharField(blank=True, max_length=120, verbose_name='rótulo do menu')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'módulo do sistema',
                'verbose_name_plural': 'módulos do sistema',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('app_label', models.CharField(blank=True, max_length=80, verbose_name='app label')),
                ('model_name', models.CharField(max_length=120, verbose_name='model')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='auxiliary.systemmodule', verbose_name='módulo')),
            ],
            options={
                'verbose_name': 'model do sistema',
                'verbose_name_plural': 'models do sistema',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='businessarea',
            index=models.Index(fields=['tenant', 'code'], name='auxiliary_b_tenant__9a1d30_idx'),
        ),
        migrations.AddIndex(
            model_name='businessarea',
            index=models.Index(fields=['tenant', 'is_active'], name='auxiliary_b_tenant__2fb5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='businessarea',
            index=models.Index(fields=['name'], name='auxiliary_b_name_91d394_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessarea',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_auxiliary_businessarea_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='businessprocess',
            index=models.Index(fields=['tenant', 'code'], name='auxiliary_b_tenant__9e1da3_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprocess',
            index=models.Index(fields=['tenant', 'is_active'], name='auxiliary_b_tenant__057816_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprocess',
            index=models.Index(fields=['name'], name='auxiliary_b_name_be018a_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprocess',
            index=models.Index(fields=['tenant', 'area', 'is_active'], name='auxiliary_b_tenant__72ea28_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessprocess',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_auxiliary_businessprocess_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='catalogtype',
            index=models.Index(fields=['tenant', 'code'], name='auxiliary_c_tenant__c43159_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogtype',
            index=models.Index(fields=['tenant', 'is_active'], name='auxiliary_c_tenant__495e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogtype',
            index=models.Index(fields=['name'], name='auxiliary_c_name_7c8a56_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogtype',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_auxiliary_catalogtype_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='catalogvalue',
            index=models.Index(fields=['tenant', 'code'], name='auxiliary_c_tenant__7376fc_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogvalue',
            index=models.Index(fields=['tenant', 'is_active'], name='auxiliary_c_tenant__98673d_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogvalue',
            index=models.Index(fields=['name'], name='auxiliary_c_name_b800c2_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogvalue',
            index=models.Index(fields=['tenant', 'catalog_type', 'is_active'], name='auxiliary_c_tenant__d2255b_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogvalue',
            index=models.Index(fields=['tenant', 'catalog_type', 'order'], name='auxiliary_c_tenant__834e1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogvalue',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_auxiliary_catalogvalue_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='commercialterm',
            index=models.Index(fields=['tenant', 'code'], name='auxiliary_c_tenant__ee5246_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialterm',
            index=models.Index(fields=['tenant', 'is_active'], name='auxiliary_c_tenant__d26503_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialterm',
            index=models.Index(fields=['name'], name='auxiliary_c_name_11c2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialterm',
            index=models.Index(fields=['tenant', 'term_type', 'is_active'], name='auxiliary_c_tenant__f742c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='commercialterm',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_auxiliary_commercialterm_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['tenant', 'code'], name='auxiliary_c_tenant__3d772e_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['tenant', 'is_active'], name='auxiliary_c_tenant__59ec36_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='auxiliary_c_name_32809d_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['tenant', 'iso_alpha2'], name='auxiliary_c_tenant__b4d60a_idx'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_auxiliary_country_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['tenant', 'code'], name='auxiliary_c_tenant__d77e97_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['tenant', 'is_active'], name='auxiliary_c_tenant__6fa82a_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['name'], name='auxiliary_c_name_562fff_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['tenant', 'numeric_code'], name='auxiliary_c_tenant__bdfe90_idx'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_auxiliary_currency_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'code'], name='auxiliary_d_tenant__1d8cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'is_active'], name='auxiliary_d_tenant__7a98a0_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='auxiliary_d_name_3c04f4_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'area', 'is_active'], name='auxiliary_d_tenant__8bc811_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_auxiliary_department_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='impactlevel',
            index=models.Index(fields=['tenant', 'code'], name='auxiliary_i_tenant__f4a640_idx'),
        ),
        migrations.AddIndex(
            model_name='impactlevel',
            index=models.Index(fields=['tenant', 'is_active'], name='auxiliary_i_tenant__fcfce4_idx'),
        ),
        migrations.AddIndex(
            model_name='impactlevel',
            index=models.Index(fields=['name'], name='auxiliary_i_name_af1ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='impactlevel',
            index=models.Index(fields=['tenant', 'level_type', 'is_active'], name='auxiliary_i_tenant__8440c8_idx'),
        ),
        migrations.AddIndex(
            model_name='impactlevel',
            index=models.Index(fields=['tenant', 'weight'], name='auxiliary_i_tenant__a31c72_idx'),
        ),
        migrations.AddConstraint(
            model_name='impactlevel',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_auxiliary_impactlevel_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='organizationalrole',
            index=models.Index(fields=['tenant', 'code'], name='auxiliary_o_tenant__463809_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalrole',
            index=models.Index(fields=['tenant', 'is_active'], name='auxiliary_o_tenant__4c422e_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalrole',
            index=models.Index(fields=['name'], name='auxiliary_o_name_b9f5d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationalrole',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_auxiliary_organizationalrole_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='stateprovince',
            index=models.Index(fields=['tenant', 'code'], name='auxiliary_s_tenant__8f942e_idx'),
        ),
        migrations.AddIndex(
            model_name='stateprovince',
            index=models.Index(fields=['tenant', 'is_active'], name='auxiliary_s_tenant__eae600_idx'),
        ),
        migrations.AddIndex(
            model_name='stateprovince',
            index=models.Index(fields=['name'], name='auxiliary_s_name_5e8e71_idx'),
        ),
        migrations.AddIndex(
            model_name='stateprovince',
            index=models.Index(fields=['tenant', 'country', 'is_active'], name='auxiliary_s_tenant__1e34a3_idx'),
        ),
        migrations.AddIndex(
            model_name='stateprovince',
            index=models.Index(fields=['tenant', 'abbreviation'], name='auxiliary_s_tenant__8d2729_idx'),
        ),
        migrations.AddConstraint(
            model_name='stateprovince',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_auxiliary_stateprovince_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['tenant', 'code'], name='auxiliary_c_tenant__70e409_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['tenant', 'is_active'], name='auxiliary_c_tenant__abe9fd_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='auxiliary_c_name_75e2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['tenant', 'state', 'is_active'], name='auxiliary_c_tenant__6c412e_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['tenant', 'ibge_code'], name='auxiliary_c_tenant__182720_idx'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_auxiliary_city_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='systemmodule',
            index=models.Index(fields=['tenant', 'code'], name='auxiliary_s_tenant__7aa68c_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmodule',
            index=models.Index(fields=['tenant', 'is_active'], name='auxiliary_s_tenant__83e46f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmodule',
            index=models.Index(fields=['name'], name='auxiliary_s_name_8f4737_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmodule',
            index=models.Index(fields=['tenant', 'app_label'], name='auxiliary_s_tenant__063d7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='systemmodule',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_auxiliary_systemmodule_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='systemmodel',
            index=models.Index(fields=['tenant', 'code'], name='auxiliary_s_tenant__f7033a_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmodel',
            index=models.Index(fields=['tenant', 'is_active'], name='auxiliary_s_tenant__09691d_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmodel',
            index=models.Index(fields=['name'], name='auxiliary_s_name_2c6cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmodel',
            index=models.Index(fields=['tenant', 'module', 'is_active'], name='auxiliary_s_tenant__7cd5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmodel',
            index=models.Index(fields=['tenant', 'app_label', 'model_name'], name='auxiliary_s_tenant__a8041c_idx'),
        ),
        migrations.AddConstraint(
            model_name='systemmodel',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_auxiliary_systemmodel_tenant_code'),
        ),
    ]
