# Generated by Django 6.0.8 on 2026-09-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0002_remove_backup_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='ibge_code',
            field=models.CharField(blank=True, max_length=7, verbose_name='código IBGE'),
        ),
        migrations.AddField(
            model_name='country',
            name='iso_alpha2',
            field=models.CharField(blank=True, max_length=2, verbose_name='ISO alfa-2'),
        ),
        migrations.AddField(
            model_name='country',
            name='iso_alpha3',
            field=models.CharField(blank=True, max_length=3, verbose_name='ISO alfa-3'),
        ),
        migrations.AddField(
            model_name='country',
            name='numeric_code',
            field=models.CharField(blank=True, max_length=3, verbose_name='código numérico'),
        ),
        migrations.AddField(
            model_name='stateprovince',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=2, verbose_name='sigla'),
        ),
        migrations.AddField(
            model_name='stateprovince',
            name='ibge_code',
            field=models.CharField(blank=True, max_length=2, verbose_name='código IBGE'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('ibge_code', ''), _negated=True), fields=('ibge_code',), name='unique_city_ibge_code'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('iso_alpha2', ''), _negated=True), fields=('iso_alpha2',), name='unique_country_iso_alpha2'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('iso_alpha3', ''), _negated=True), fields=('iso_alpha3',), name='unique_country_iso_alpha3'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('numeric_code', ''), _negated=True), fields=('numeric_code',), name='unique_country_numeric_code'),
        ),
        migrations.AddConstraint(
            model_name='stateprovince',
            constraint=models.UniqueConstraint(condition=models.Q(('abbreviation', ''), _negated=True), fields=('country', 'abbreviation'), name='unique_state_country_abbreviation'),
        ),
        migrations.AddConstraint(
            model_name='stateprovince',
            constraint=models.UniqueConstraint(condition=models.Q(('ibge_code', ''), _negated=True), fields=('ibge_code',), name='unique_state_ibge_code'),
        ),
    ]
