# Generated by Django 6.0.7 on 2026-07-12 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0002_populate_auxiliary_references'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('run_number', models.CharField(max_length=64, unique=True, verbose_name='número da execução')),
                ('kind', models.CharField(choices=[('postgres', 'PostgreSQL'), ('media', 'Mídia')], max_length=16, verbose_name='tipo')),
                ('source_path', models.CharField(max_length=512, verbose_name='caminho de origem')),
                ('encrypted_path', models.CharField(blank=True, max_length=512, verbose_name='caminho cifrado')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='tamanho (bytes)')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('encryption_key_id', models.CharField(blank=True, max_length=64, verbose_name='KID de criptografia')),
                ('encrypted', models.BooleanField(default=True, verbose_name='cifrado')),
                ('drive_folder_id', models.CharField(blank=True, max_length=128, verbose_name='ID da pasta no Drive')),
                ('drive_file_id', models.CharField(blank=True, max_length=128, verbose_name='ID do arquivo no Drive')),
                ('drive_file_name', models.CharField(blank=True, max_length=255, verbose_name='nome do arquivo no Drive')),
                ('drive_web_view_link', models.URLField(blank=True, max_length=500, verbose_name='link de visualização')),
                ('drive_mime_type', models.CharField(blank=True, max_length=128, verbose_name='mime type no Drive')),
                ('drive_md5_checksum', models.CharField(blank=True, max_length=64, verbose_name='md5 do Drive')),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('success', 'Sucesso'), ('failed', 'Falha'), ('skipped', 'Ignorado')], default='running', max_length=16, verbose_name='status')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizado em')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='duração (s)')),
                ('triggered_by', models.CharField(default='cron', max_length=32, verbose_name='origem da execução')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_runs', to=settings.AUTH_USER_MODEL, verbose_name='executor')),
            ],
            options={
                'verbose_name': 'execução de backup',
                'verbose_name_plural': 'execuções de backup',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'kind'], name='auxiliary_b_status_15341c_idx'), models.Index(fields=['started_at'], name='auxiliary_b_started_1f9f2b_idx'), models.Index(fields=['sha256'], name='auxiliary_b_sha256_536ade_idx')],
            },
        ),
    ]
