# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0003_backuprun'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businessarea',
            name='unique_auxiliary_businessarea_tenant_code',
        ),
        migrations.RemoveConstraint(
            model_name='businessprocess',
            name='unique_auxiliary_businessprocess_tenant_code',
        ),
        migrations.RemoveConstraint(
            model_name='catalogtype',
            name='unique_auxiliary_catalogtype_tenant_code',
        ),
        migrations.RemoveConstraint(
            model_name='catalogvalue',
            name='unique_auxiliary_catalogvalue_tenant_code',
        ),
        migrations.RemoveConstraint(
            model_name='city',
            name='unique_auxiliary_city_tenant_code',
        ),
        migrations.RemoveConstraint(
            model_name='commercialterm',
            name='unique_auxiliary_commercialterm_tenant_code',
        ),
        migrations.RemoveConstraint(
            model_name='country',
            name='unique_auxiliary_country_tenant_code',
        ),
        migrations.RemoveConstraint(
            model_name='currency',
            name='unique_auxiliary_currency_tenant_code',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_auxiliary_department_tenant_code',
        ),
        migrations.RemoveConstraint(
            model_name='impactlevel',
            name='unique_auxiliary_impactlevel_tenant_code',
        ),
        migrations.RemoveConstraint(
            model_name='organizationalrole',
            name='unique_auxiliary_organizationalrole_tenant_code',
        ),
        migrations.RemoveConstraint(
            model_name='stateprovince',
            name='unique_auxiliary_stateprovince_tenant_code',
        ),
        migrations.RemoveConstraint(
            model_name='systemmodel',
            name='unique_auxiliary_systemmodel_tenant_code',
        ),
        migrations.RemoveConstraint(
            model_name='systemmodule',
            name='unique_auxiliary_systemmodule_tenant_code',
        ),
        migrations.RemoveIndex(
            model_name='businessarea',
            name='auxiliary_b_tenant__9a1d30_idx',
        ),
        migrations.RemoveIndex(
            model_name='businessarea',
            name='auxiliary_b_tenant__2fb5fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='businessprocess',
            name='auxiliary_b_tenant__9e1da3_idx',
        ),
        migrations.RemoveIndex(
            model_name='businessprocess',
            name='auxiliary_b_tenant__057816_idx',
        ),
        migrations.RemoveIndex(
            model_name='businessprocess',
            name='auxiliary_b_tenant__72ea28_idx',
        ),
        migrations.RemoveIndex(
            model_name='catalogtype',
            name='auxiliary_c_tenant__c43159_idx',
        ),
        migrations.RemoveIndex(
            model_name='catalogtype',
            name='auxiliary_c_tenant__495e5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='catalogvalue',
            name='auxiliary_c_tenant__7376fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='catalogvalue',
            name='auxiliary_c_tenant__98673d_idx',
        ),
        migrations.RemoveIndex(
            model_name='catalogvalue',
            name='auxiliary_c_tenant__d2255b_idx',
        ),
        migrations.RemoveIndex(
            model_name='catalogvalue',
            name='auxiliary_c_tenant__834e1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='auxiliary_c_tenant__70e409_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='auxiliary_c_tenant__abe9fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='auxiliary_c_tenant__6c412e_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='auxiliary_c_tenant__182720_idx',
        ),
        migrations.RemoveIndex(
            model_name='commercialterm',
            name='auxiliary_c_tenant__ee5246_idx',
        ),
        migrations.RemoveIndex(
            model_name='commercialterm',
            name='auxiliary_c_tenant__d26503_idx',
        ),
        migrations.RemoveIndex(
            model_name='commercialterm',
            name='auxiliary_c_tenant__f742c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='country',
            name='auxiliary_c_tenant__3d772e_idx',
        ),
        migrations.RemoveIndex(
            model_name='country',
            name='auxiliary_c_tenant__59ec36_idx',
        ),
        migrations.RemoveIndex(
            model_name='country',
            name='auxiliary_c_tenant__b4d60a_idx',
        ),
        migrations.RemoveIndex(
            model_name='currency',
            name='auxiliary_c_tenant__d77e97_idx',
        ),
        migrations.RemoveIndex(
            model_name='currency',
            name='auxiliary_c_tenant__6fa82a_idx',
        ),
        migrations.RemoveIndex(
            model_name='currency',
            name='auxiliary_c_tenant__bdfe90_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='auxiliary_d_tenant__1d8cfb_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='auxiliary_d_tenant__7a98a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='auxiliary_d_tenant__8bc811_idx',
        ),
        migrations.RemoveIndex(
            model_name='impactlevel',
            name='auxiliary_i_tenant__f4a640_idx',
        ),
        migrations.RemoveIndex(
            model_name='impactlevel',
            name='auxiliary_i_tenant__fcfce4_idx',
        ),
        migrations.RemoveIndex(
            model_name='impactlevel',
            name='auxiliary_i_tenant__8440c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='impactlevel',
            name='auxiliary_i_tenant__a31c72_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationalrole',
            name='auxiliary_o_tenant__463809_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationalrole',
            name='auxiliary_o_tenant__4c422e_idx',
        ),
        migrations.RemoveIndex(
            model_name='stateprovince',
            name='auxiliary_s_tenant__8f942e_idx',
        ),
        migrations.RemoveIndex(
            model_name='stateprovince',
            name='auxiliary_s_tenant__eae600_idx',
        ),
        migrations.RemoveIndex(
            model_name='stateprovince',
            name='auxiliary_s_tenant__1e34a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='stateprovince',
            name='auxiliary_s_tenant__8d2729_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemmodel',
            name='auxiliary_s_tenant__f7033a_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemmodel',
            name='auxiliary_s_tenant__09691d_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemmodel',
            name='auxiliary_s_tenant__7cd5ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemmodel',
            name='auxiliary_s_tenant__a8041c_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemmodule',
            name='auxiliary_s_tenant__7aa68c_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemmodule',
            name='auxiliary_s_tenant__83e46f_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemmodule',
            name='auxiliary_s_tenant__063d7e_idx',
        ),
        migrations.RemoveField(
            model_name='businessarea',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='businessprocess',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='catalogtype',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='catalogvalue',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='city',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='commercialterm',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='country',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='impactlevel',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='organizationalrole',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='stateprovince',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='systemmodel',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='systemmodule',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='businessarea',
            index=models.Index(fields=['code'], name='auxiliary_b_code_23af77_idx'),
        ),
        migrations.AddIndex(
            model_name='businessarea',
            index=models.Index(fields=['is_active'], name='auxiliary_b_is_acti_3320f8_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprocess',
            index=models.Index(fields=['code'], name='auxiliary_b_code_50b99b_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprocess',
            index=models.Index(fields=['is_active'], name='auxiliary_b_is_acti_8bcec8_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprocess',
            index=models.Index(fields=['area', 'is_active'], name='auxiliary_b_area_id_f412d4_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogtype',
            index=models.Index(fields=['code'], name='auxiliary_c_code_fda574_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogtype',
            index=models.Index(fields=['is_active'], name='auxiliary_c_is_acti_3c3988_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogvalue',
            index=models.Index(fields=['code'], name='auxiliary_c_code_181c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogvalue',
            index=models.Index(fields=['is_active'], name='auxiliary_c_is_acti_ca384a_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogvalue',
            index=models.Index(fields=['catalog_type', 'is_active'], name='auxiliary_c_catalog_78365d_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogvalue',
            index=models.Index(fields=['catalog_type', 'order'], name='auxiliary_c_catalog_e746ea_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['code'], name='auxiliary_c_code_fcd583_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_active'], name='auxiliary_c_is_acti_45971b_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state', 'is_active'], name='auxiliary_c_state_i_eb2d89_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['ibge_code'], name='auxiliary_c_ibge_co_75e0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialterm',
            index=models.Index(fields=['code'], name='auxiliary_c_code_cfb915_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialterm',
            index=models.Index(fields=['is_active'], name='auxiliary_c_is_acti_cc393d_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialterm',
            index=models.Index(fields=['term_type', 'is_active'], name='auxiliary_c_term_ty_1533fd_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['code'], name='auxiliary_c_code_4843a4_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['is_active'], name='auxiliary_c_is_acti_82b5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['iso_alpha2'], name='auxiliary_c_iso_alp_5076d2_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['code'], name='auxiliary_c_code_a60940_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_active'], name='auxiliary_c_is_acti_f6c3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['numeric_code'], name='auxiliary_c_numeric_c7b9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='auxiliary_d_code_087fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='auxiliary_d_is_acti_b7aca8_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['area', 'is_active'], name='auxiliary_d_area_id_d5ca9a_idx'),
        ),
        migrations.AddIndex(
            model_name='impactlevel',
            index=models.Index(fields=['code'], name='auxiliary_i_code_775aac_idx'),
        ),
        migrations.AddIndex(
            model_name='impactlevel',
            index=models.Index(fields=['is_active'], name='auxiliary_i_is_acti_302ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='impactlevel',
            index=models.Index(fields=['level_type', 'is_active'], name='auxiliary_i_level_t_9e9707_idx'),
        ),
        migrations.AddIndex(
            model_name='impactlevel',
            index=models.Index(fields=['weight'], name='auxiliary_i_weight_0a260a_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalrole',
            index=models.Index(fields=['code'], name='auxiliary_o_code_064f94_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalrole',
            index=models.Index(fields=['is_active'], name='auxiliary_o_is_acti_9a474b_idx'),
        ),
        migrations.AddIndex(
            model_name='stateprovince',
            index=models.Index(fields=['code'], name='auxiliary_s_code_f11d18_idx'),
        ),
        migrations.AddIndex(
            model_name='stateprovince',
            index=models.Index(fields=['is_active'], name='auxiliary_s_is_acti_03513f_idx'),
        ),
        migrations.AddIndex(
            model_name='stateprovince',
            index=models.Index(fields=['country', 'is_active'], name='auxiliary_s_country_984714_idx'),
        ),
        migrations.AddIndex(
            model_name='stateprovince',
            index=models.Index(fields=['abbreviation'], name='auxiliary_s_abbrevi_5094fb_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmodel',
            index=models.Index(fields=['code'], name='auxiliary_s_code_1760e2_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmodel',
            index=models.Index(fields=['is_active'], name='auxiliary_s_is_acti_728797_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmodel',
            index=models.Index(fields=['module', 'is_active'], name='auxiliary_s_module__e4eda6_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmodel',
            index=models.Index(fields=['app_label', 'model_name'], name='auxiliary_s_app_lab_4d6f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmodule',
            index=models.Index(fields=['code'], name='auxiliary_s_code_c1ccd1_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmodule',
            index=models.Index(fields=['is_active'], name='auxiliary_s_is_acti_05b31c_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmodule',
            index=models.Index(fields=['app_label'], name='auxiliary_s_app_lab_240ae4_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessarea',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_auxiliary_businessarea_code'),
        ),
        migrations.AddConstraint(
            model_name='businessprocess',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_auxiliary_businessprocess_code'),
        ),
        migrations.AddConstraint(
            model_name='catalogtype',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_auxiliary_catalogtype_code'),
        ),
        migrations.AddConstraint(
            model_name='catalogvalue',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_auxiliary_catalogvalue_code'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_auxiliary_city_code'),
        ),
        migrations.AddConstraint(
            model_name='commercialterm',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_auxiliary_commercialterm_code'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_auxiliary_country_code'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_auxiliary_currency_code'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_auxiliary_department_code'),
        ),
        migrations.AddConstraint(
            model_name='impactlevel',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_auxiliary_impactlevel_code'),
        ),
        migrations.AddConstraint(
            model_name='organizationalrole',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_auxiliary_organizationalrole_code'),
        ),
        migrations.AddConstraint(
            model_name='stateprovince',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_auxiliary_stateprovince_code'),
        ),
        migrations.AddConstraint(
            model_name='systemmodel',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_auxiliary_systemmodel_code'),
        ),
        migrations.AddConstraint(
            model_name='systemmodule',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_auxiliary_systemmodule_code'),
        ),
    ]
