# Generated by Django 5.2.16 on 2026-07-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'cidade/município', 'verbose_name_plural': 'cidades/municípios'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'país', 'verbose_name_plural': 'países'},
        ),
        migrations.AlterModelOptions(
            name='stateprovince',
            options={'ordering': ['name'], 'verbose_name': 'estado/UF', 'verbose_name_plural': 'estados/UFs'},
        ),
        migrations.RemoveConstraint(
            model_name='city',
            name='unique_auxiliary_city_code',
        ),
        migrations.RemoveConstraint(
            model_name='country',
            name='unique_auxiliary_country_code',
        ),
        migrations.RemoveConstraint(
            model_name='stateprovince',
            name='unique_auxiliary_stateprovince_code',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='auxiliary_c_code_fcd583_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='auxiliary_c_is_acti_45971b_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='auxiliary_c_state_i_eb2d89_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='auxiliary_c_ibge_co_75e0e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='country',
            name='auxiliary_c_name_32809d_idx',
        ),
        migrations.RemoveIndex(
            model_name='country',
            name='auxiliary_c_code_4843a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='country',
            name='auxiliary_c_is_acti_82b5d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='country',
            name='auxiliary_c_iso_alp_5076d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='stateprovince',
            name='auxiliary_s_code_f11d18_idx',
        ),
        migrations.RemoveIndex(
            model_name='stateprovince',
            name='auxiliary_s_is_acti_03513f_idx',
        ),
        migrations.RemoveIndex(
            model_name='stateprovince',
            name='auxiliary_s_country_984714_idx',
        ),
        migrations.RemoveIndex(
            model_name='stateprovince',
            name='auxiliary_s_abbrevi_5094fb_idx',
        ),
        migrations.RemoveField(
            model_name='city',
            name='code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='ibge_code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='city',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='country',
            name='description',
        ),
        migrations.RemoveField(
            model_name='country',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso_alpha2',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso_alpha3',
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stateprovince',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='stateprovince',
            name='code',
        ),
        migrations.RemoveField(
            model_name='stateprovince',
            name='country',
        ),
        migrations.RemoveField(
            model_name='stateprovince',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stateprovince',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stateprovince',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stateprovince',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=180, unique=True, verbose_name='nome'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state'], name='auxiliary_c_state_i_00eb00_idx'),
        ),
    ]
