# Generated by Django 5.2.16 on 2026-07-23 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0005_simplify_country_stateprovince_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateprovince',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='states', to='auxiliary.country', verbose_name='país'),
        ),
    ]
