# Generated by Django 5.2.16 on 2026-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0006_stateprovince_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessarea',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='catalogtype',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='catalogvalue',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='commercialterm',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='impactlevel',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='organizationalrole',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='systemmodel',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='systemmodule',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
    ]
