# Generated by Django 6.0.7 on 2026-07-07 23:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('change_number', models.CharField(blank=True, max_length=80, verbose_name='mudança')),
                ('change_type', models.CharField(choices=[('permanent', 'Permanente'), ('temporary', 'Temporária'), ('emergency', 'Emergencial'), ('administrative', 'Administrativa'), ('process', 'Processo'), ('equipment', 'Equipamento'), ('system', 'Sistema'), ('document', 'Documento')], max_length=32, verbose_name='tipo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('scope', models.TextField(verbose_name='escopo')),
                ('justification', models.TextField(verbose_name='justificativa')),
                ('affected_areas', models.TextField(verbose_name='áreas afetadas')),
                ('equipment_reference', models.CharField(blank=True, max_length=120, verbose_name='equipamento')),
                ('system_reference', models.CharField(blank=True, max_length=120, verbose_name='sistema')),
                ('validation_plan', models.TextField(blank=True, verbose_name='plano de validação')),
                ('training_plan', models.TextField(blank=True, verbose_name='plano de treinamento')),
                ('regulatory_strategy', models.TextField(blank=True, verbose_name='estratégia regulatória')),
                ('impact_summary', models.TextField(blank=True, verbose_name='resumo de impacto')),
                ('due_date', models.DateField(verbose_name='prazo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('under_assessment', 'Em avaliação'), ('approved', 'Aprovada'), ('in_implementation', 'Em implementação'), ('closed', 'Encerrada'), ('cancelled', 'Cancelada')], default='draft', max_length=32, verbose_name='status')),
                ('requires_stock_assessment', models.BooleanField(default=False, verbose_name='exige avaliação de estoque')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submetida em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('implementation_started_at', models.DateTimeField(blank=True, null=True, verbose_name='implementação iniciada em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrada em')),
                ('closure_summary', models.TextField(blank=True, verbose_name='resumo de encerramento')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_changes', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_changes', to=settings.AUTH_USER_MODEL, verbose_name='encerrada por')),
                ('implementation_started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_change_implementations', to=settings.AUTH_USER_MODEL, verbose_name='implementação iniciada por')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_changes', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_changes', to=settings.AUTH_USER_MODEL, verbose_name='solicitada por')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_changes', to=settings.AUTH_USER_MODEL, verbose_name='submetida por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'controle de mudança',
                'verbose_name_plural': 'controles de mudança',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('department', models.CharField(choices=[('qa', 'Garantia da Qualidade'), ('qc', 'Controle de Qualidade'), ('production', 'Produção'), ('engineering', 'Engenharia'), ('regulatory', 'Regulatório'), ('fiscal', 'Fiscal'), ('finance', 'Financeiro'), ('warehouse', 'Estoque'), ('other', 'Outra área')], max_length=32, verbose_name='área')),
                ('impact_level', models.CharField(blank=True, choices=[('none', 'Sem impacto'), ('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=24, verbose_name='nível de impacto')),
                ('impact_description', models.TextField(blank=True, verbose_name='descrição do impacto')),
                ('required_actions', models.TextField(blank=True, verbose_name='ações requeridas')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída')], default='pending', max_length=24, verbose_name='status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_assessments', to=settings.AUTH_USER_MODEL, verbose_name='avaliador')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_change_assessments', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='changes.changecontrol', verbose_name='mudança')),
            ],
            options={
                'verbose_name': 'análise de mudança',
                'verbose_name_plural': 'análises de mudança',
                'ordering': ['change__change_number', 'department'],
            },
        ),
        migrations.CreateModel(
            name='ChangeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(choices=[('qa', 'Garantia da Qualidade'), ('qc', 'Controle de Qualidade'), ('production', 'Produção'), ('engineering', 'Engenharia'), ('regulatory', 'Regulatório'), ('fiscal', 'Fiscal'), ('finance', 'Financeiro'), ('owner', 'Responsável')], max_length=32, verbose_name='papel')),
                ('required', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('decision', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=24, verbose_name='decisão')),
                ('comments', models.TextField(blank=True, verbose_name='comentários')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidido em')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_approvals', to=settings.AUTH_USER_MODEL, verbose_name='aprovador')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_change_approvals', to=settings.AUTH_USER_MODEL, verbose_name='decidido por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='changes.changecontrol', verbose_name='mudança')),
            ],
            options={
                'verbose_name': 'aprovação de mudança',
                'verbose_name_plural': 'aprovações de mudança',
                'ordering': ['change__change_number', 'role'],
            },
        ),
        migrations.CreateModel(
            name='ChangeAffectedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('item_type', models.CharField(choices=[('product', 'Produto'), ('document', 'Documento'), ('supplier', 'Fornecedor'), ('equipment', 'Equipamento'), ('system', 'Sistema'), ('process', 'Processo'), ('training', 'Treinamento'), ('validation', 'Validação'), ('other', 'Outro')], max_length=24, verbose_name='tipo de item')),
                ('reference_code', models.CharField(blank=True, max_length=120, verbose_name='referência')),
                ('impact_description', models.TextField(verbose_name='descrição do impacto')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_impacts', to='documents.controlleddocument', verbose_name='documento')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_impacts', to='masters.product', verbose_name='produto')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_impacts', to='masters.businesspartner', verbose_name='fornecedor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_items', to='changes.changecontrol', verbose_name='mudança')),
            ],
            options={
                'verbose_name': 'item afetado pela mudança',
                'verbose_name_plural': 'itens afetados pela mudança',
                'ordering': ['change__change_number', 'item_type'],
            },
        ),
        migrations.CreateModel(
            name='ChangeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('action_type', models.CharField(choices=[('document_update', 'Atualização documental'), ('training', 'Treinamento'), ('validation', 'Validação'), ('regulatory_communication', 'Comunicação regulatória'), ('stock_assessment', 'Avaliação de estoque'), ('implementation', 'Implementação'), ('other', 'Outra ação')], max_length=32, verbose_name='tipo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('due_date', models.DateField(verbose_name='prazo')),
                ('mandatory', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('required_before_implementation', models.BooleanField(default=False, verbose_name='exige antes da implementação')),
                ('evidence_required', models.BooleanField(default=True, verbose_name='exige evidência')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=24, verbose_name='status')),
                ('completion_notes', models.TextField(blank=True, verbose_name='observações de conclusão')),
                ('evidence_reference', models.CharField(blank=True, max_length=255, verbose_name='evidência')),
                ('content_hash', models.CharField(blank=True, max_length=128, verbose_name='hash do conteúdo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_change_actions', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_actions', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='changes.changecontrol', verbose_name='mudança')),
            ],
            options={
                'verbose_name': 'ação de mudança',
                'verbose_name_plural': 'ações de mudança',
                'ordering': ['change__change_number', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ChangeStockAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantity_affected', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade afetada')),
                ('required', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída')], default='pending', max_length=24, verbose_name='status')),
                ('decision', models.CharField(blank=True, choices=[('not_applicable', 'Não aplicável'), ('use_as_is', 'Usar como está'), ('quarantine', 'Quarentenar'), ('relabel', 'Reetiquetar'), ('reprocess', 'Reprocessar'), ('discard', 'Descartar')], max_length=32, verbose_name='decisão')),
                ('assessment_summary', models.TextField(blank=True, verbose_name='resumo da avaliação')),
                ('assessed_at', models.DateTimeField(blank=True, null=True, verbose_name='avaliado em')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_change_stock_assessments', to=settings.AUTH_USER_MODEL, verbose_name='avaliado por')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_assessments', to='changes.changecontrol', verbose_name='mudança')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_stock_assessments', to='masters.product', verbose_name='produto')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_stock_assessments', to='inventory.stocklot', verbose_name='lote')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'avaliação de estoque da mudança',
                'verbose_name_plural': 'avaliações de estoque da mudança',
                'ordering': ['change__change_number', 'product__code'],
            },
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['tenant', 'change_type', 'status'], name='changes_cha_tenant__2ff083_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['tenant', 'owner'], name='changes_cha_tenant__88a491_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['tenant', 'due_date'], name='changes_cha_tenant__2a9684_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['change_number'], name='changes_cha_change__4ea2a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='changecontrol',
            constraint=models.UniqueConstraint(fields=('tenant', 'change_number'), name='unique_tenant_change_number'),
        ),
        migrations.AddIndex(
            model_name='changeassessment',
            index=models.Index(fields=['tenant', 'change', 'status'], name='changes_cha_tenant__0298ae_idx'),
        ),
        migrations.AddIndex(
            model_name='changeassessment',
            index=models.Index(fields=['tenant', 'department'], name='changes_cha_tenant__8a8f20_idx'),
        ),
        migrations.AddIndex(
            model_name='changeassessment',
            index=models.Index(fields=['tenant', 'assessor'], name='changes_cha_tenant__dbd618_idx'),
        ),
        migrations.AddConstraint(
            model_name='changeassessment',
            constraint=models.UniqueConstraint(fields=('tenant', 'change', 'department'), name='unique_tenant_change_assessment_department'),
        ),
        migrations.AddIndex(
            model_name='changeapproval',
            index=models.Index(fields=['tenant', 'change', 'decision'], name='changes_cha_tenant__5230b9_idx'),
        ),
        migrations.AddIndex(
            model_name='changeapproval',
            index=models.Index(fields=['tenant', 'approver'], name='changes_cha_tenant__ca51f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='changeapproval',
            constraint=models.UniqueConstraint(fields=('tenant', 'change', 'role', 'approver'), name='unique_tenant_change_approval_role_user'),
        ),
        migrations.AddIndex(
            model_name='changeaffecteditem',
            index=models.Index(fields=['tenant', 'change', 'item_type'], name='changes_cha_tenant__748d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaffecteditem',
            index=models.Index(fields=['tenant', 'product'], name='changes_cha_tenant__ae2d10_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaffecteditem',
            index=models.Index(fields=['tenant', 'document'], name='changes_cha_tenant__777666_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaffecteditem',
            index=models.Index(fields=['tenant', 'supplier'], name='changes_cha_tenant__8c084b_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaction',
            index=models.Index(fields=['tenant', 'change', 'status'], name='changes_cha_tenant__cd5862_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaction',
            index=models.Index(fields=['tenant', 'responsible', 'due_date'], name='changes_cha_tenant__9fd152_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaction',
            index=models.Index(fields=['tenant', 'action_type'], name='changes_cha_tenant__ebdc02_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaction',
            index=models.Index(fields=['tenant', 'required_before_implementation'], name='changes_cha_tenant__279494_idx'),
        ),
        migrations.AddIndex(
            model_name='changestockassessment',
            index=models.Index(fields=['tenant', 'change', 'status'], name='changes_cha_tenant__b45af4_idx'),
        ),
        migrations.AddIndex(
            model_name='changestockassessment',
            index=models.Index(fields=['tenant', 'product'], name='changes_cha_tenant__d5ca6f_idx'),
        ),
        migrations.AddIndex(
            model_name='changestockassessment',
            index=models.Index(fields=['tenant', 'stock_lot'], name='changes_cha_tenant__4af1fe_idx'),
        ),
    ]
