# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('changes', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changestockassessment',
            name='stock_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_stock_assessments', to='inventory.stocklot', verbose_name='lote'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['change_type', 'status'], name='changes_cha_change__268cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['owner'], name='changes_cha_owner_i_673db1_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['due_date'], name='changes_cha_due_dat_257905_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['change_number'], name='changes_cha_change__4ea2a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='changecontrol',
            constraint=models.UniqueConstraint(fields=('change_number',), name='unique_change_number'),
        ),
        migrations.AddIndex(
            model_name='changeassessment',
            index=models.Index(fields=['change', 'status'], name='changes_cha_change__5272c7_idx'),
        ),
        migrations.AddIndex(
            model_name='changeassessment',
            index=models.Index(fields=['department'], name='changes_cha_departm_09876a_idx'),
        ),
        migrations.AddIndex(
            model_name='changeassessment',
            index=models.Index(fields=['assessor'], name='changes_cha_assesso_c753e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='changeassessment',
            constraint=models.UniqueConstraint(fields=('change', 'department'), name='unique_change_assessment_department'),
        ),
        migrations.AddIndex(
            model_name='changeapproval',
            index=models.Index(fields=['change', 'decision'], name='changes_cha_change__e9cb3b_idx'),
        ),
        migrations.AddIndex(
            model_name='changeapproval',
            index=models.Index(fields=['approver'], name='changes_cha_approve_2aeafa_idx'),
        ),
        migrations.AddConstraint(
            model_name='changeapproval',
            constraint=models.UniqueConstraint(fields=('change', 'role', 'approver'), name='unique_change_approval_role_user'),
        ),
        migrations.AddIndex(
            model_name='changeaffecteditem',
            index=models.Index(fields=['change', 'item_type'], name='changes_cha_change__cb0556_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaffecteditem',
            index=models.Index(fields=['product'], name='changes_cha_product_f1c365_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaffecteditem',
            index=models.Index(fields=['document'], name='changes_cha_documen_9519e3_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaffecteditem',
            index=models.Index(fields=['supplier'], name='changes_cha_supplie_c33a48_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaction',
            index=models.Index(fields=['change', 'status'], name='changes_cha_change__8f5491_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaction',
            index=models.Index(fields=['responsible', 'due_date'], name='changes_cha_respons_eb24ca_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaction',
            index=models.Index(fields=['action_type'], name='changes_cha_action__7e323c_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaction',
            index=models.Index(fields=['required_before_implementation'], name='changes_cha_require_c092ca_idx'),
        ),
        migrations.AddIndex(
            model_name='changestockassessment',
            index=models.Index(fields=['change', 'status'], name='changes_cha_change__bca5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='changestockassessment',
            index=models.Index(fields=['product'], name='changes_cha_product_61e686_idx'),
        ),
        migrations.AddIndex(
            model_name='changestockassessment',
            index=models.Index(fields=['stock_lot'], name='changes_cha_stock_l_465ef5_idx'),
        ),
    ]
