# Generated by Django 6.0.8 on 2026-08-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changecontrol',
            name='equipment_reference',
        ),
        migrations.AlterField(
            model_name='changeaffecteditem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Produto'), ('document', 'Documento'), ('supplier', 'Fornecedor'), ('system', 'Sistema'), ('process', 'Processo'), ('training', 'Treinamento'), ('validation', 'Validação'), ('other', 'Outro')], max_length=24, verbose_name='tipo de item'),
        ),
        migrations.AlterField(
            model_name='changecontrol',
            name='change_type',
            field=models.CharField(choices=[('permanent', 'Permanente'), ('temporary', 'Temporária'), ('emergency', 'Emergencial'), ('administrative', 'Administrativa'), ('process', 'Processo'), ('system', 'Sistema'), ('document', 'Documento')], max_length=32, verbose_name='tipo'),
        ),
    ]
