# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('changes', '0002_changeassessment_department_ref'),
        ('documents', '0003_remove_controlleddocument_unique_tenant_document_code_version_and_more'),
        ('inventory', '0002_remove_stockbalance_unique_tenant_stock_balance_address_status_and_more'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='changeapproval',
            name='unique_tenant_change_approval_role_user',
        ),
        migrations.RemoveConstraint(
            model_name='changeassessment',
            name='unique_tenant_change_assessment_department',
        ),
        migrations.RemoveConstraint(
            model_name='changecontrol',
            name='unique_tenant_change_number',
        ),
        migrations.RemoveIndex(
            model_name='changeaction',
            name='changes_cha_tenant__cd5862_idx',
        ),
        migrations.RemoveIndex(
            model_name='changeaction',
            name='changes_cha_tenant__9fd152_idx',
        ),
        migrations.RemoveIndex(
            model_name='changeaction',
            name='changes_cha_tenant__ebdc02_idx',
        ),
        migrations.RemoveIndex(
            model_name='changeaction',
            name='changes_cha_tenant__279494_idx',
        ),
        migrations.RemoveIndex(
            model_name='changeaffecteditem',
            name='changes_cha_tenant__748d4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='changeaffecteditem',
            name='changes_cha_tenant__ae2d10_idx',
        ),
        migrations.RemoveIndex(
            model_name='changeaffecteditem',
            name='changes_cha_tenant__777666_idx',
        ),
        migrations.RemoveIndex(
            model_name='changeaffecteditem',
            name='changes_cha_tenant__8c084b_idx',
        ),
        migrations.RemoveIndex(
            model_name='changeapproval',
            name='changes_cha_tenant__5230b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='changeapproval',
            name='changes_cha_tenant__ca51f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='changeassessment',
            name='changes_cha_tenant__0298ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='changeassessment',
            name='changes_cha_tenant__8a8f20_idx',
        ),
        migrations.RemoveIndex(
            model_name='changeassessment',
            name='changes_cha_tenant__dbd618_idx',
        ),
        migrations.RemoveIndex(
            model_name='changecontrol',
            name='changes_cha_tenant__2ff083_idx',
        ),
        migrations.RemoveIndex(
            model_name='changecontrol',
            name='changes_cha_tenant__88a491_idx',
        ),
        migrations.RemoveIndex(
            model_name='changecontrol',
            name='changes_cha_tenant__2a9684_idx',
        ),
        migrations.RemoveIndex(
            model_name='changestockassessment',
            name='changes_cha_tenant__b45af4_idx',
        ),
        migrations.RemoveIndex(
            model_name='changestockassessment',
            name='changes_cha_tenant__d5ca6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='changestockassessment',
            name='changes_cha_tenant__4af1fe_idx',
        ),
        migrations.RemoveField(
            model_name='changeaction',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='changeaffecteditem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='changeapproval',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='changeassessment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='changecontrol',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='changestockassessment',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='changeaction',
            index=models.Index(fields=['change', 'status'], name='changes_cha_change__8f5491_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaction',
            index=models.Index(fields=['responsible', 'due_date'], name='changes_cha_respons_eb24ca_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaction',
            index=models.Index(fields=['action_type'], name='changes_cha_action__7e323c_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaction',
            index=models.Index(fields=['required_before_implementation'], name='changes_cha_require_c092ca_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaffecteditem',
            index=models.Index(fields=['change', 'item_type'], name='changes_cha_change__cb0556_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaffecteditem',
            index=models.Index(fields=['product'], name='changes_cha_product_f1c365_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaffecteditem',
            index=models.Index(fields=['document'], name='changes_cha_documen_9519e3_idx'),
        ),
        migrations.AddIndex(
            model_name='changeaffecteditem',
            index=models.Index(fields=['supplier'], name='changes_cha_supplie_c33a48_idx'),
        ),
        migrations.AddIndex(
            model_name='changeapproval',
            index=models.Index(fields=['change', 'decision'], name='changes_cha_change__e9cb3b_idx'),
        ),
        migrations.AddIndex(
            model_name='changeapproval',
            index=models.Index(fields=['approver'], name='changes_cha_approve_2aeafa_idx'),
        ),
        migrations.AddIndex(
            model_name='changeassessment',
            index=models.Index(fields=['change', 'status'], name='changes_cha_change__5272c7_idx'),
        ),
        migrations.AddIndex(
            model_name='changeassessment',
            index=models.Index(fields=['department'], name='changes_cha_departm_09876a_idx'),
        ),
        migrations.AddIndex(
            model_name='changeassessment',
            index=models.Index(fields=['assessor'], name='changes_cha_assesso_c753e2_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['change_type', 'status'], name='changes_cha_change__268cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['owner'], name='changes_cha_owner_i_673db1_idx'),
        ),
        migrations.AddIndex(
            model_name='changecontrol',
            index=models.Index(fields=['due_date'], name='changes_cha_due_dat_257905_idx'),
        ),
        migrations.AddIndex(
            model_name='changestockassessment',
            index=models.Index(fields=['change', 'status'], name='changes_cha_change__bca5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='changestockassessment',
            index=models.Index(fields=['product'], name='changes_cha_product_61e686_idx'),
        ),
        migrations.AddIndex(
            model_name='changestockassessment',
            index=models.Index(fields=['stock_lot'], name='changes_cha_stock_l_465ef5_idx'),
        ),
        migrations.AddConstraint(
            model_name='changeapproval',
            constraint=models.UniqueConstraint(fields=('change', 'role', 'approver'), name='unique_change_approval_role_user'),
        ),
        migrations.AddConstraint(
            model_name='changeassessment',
            constraint=models.UniqueConstraint(fields=('change', 'department'), name='unique_change_assessment_department'),
        ),
        migrations.AddConstraint(
            model_name='changecontrol',
            constraint=models.UniqueConstraint(fields=('change_number',), name='unique_change_number'),
        ),
    ]
