http:
  routers:
    rgnfarmasystem:
      rule: "Host(`rgnfarmasystem.rgnsystems.com.br`)"
      entrypoints:
        - websecure
      service: rgnfarmasystem
      tls:
        certResolver: cloudflare
        domains:
          - main: rgnfarmasystem.rgnsystems.com.br

    rgnfarmasystem-http:
      rule: "Host(`rgnfarmasystem.rgnsystems.com.br`)"
      entrypoints:
        - web
      service: rgnfarmasystem
      middlewares:
        - https-redirect

  services:
    rgnfarmasystem:
      loadBalancer:
        servers:
          - url: "http://tasks.rgnfarmasystem_app:8000"
        healthCheck:
          path: /health/
          interval: 30s
          timeout: 5s
          hostname: rgnfarmasystem.rgnsystems.com.br

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
