# Generated by Django 6.0.7 on 2026-07-11 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador do evento')),
                ('action', models.CharField(db_index=True, max_length=120, verbose_name='ação')),
                ('target_model', models.CharField(blank=True, max_length=120, verbose_name='modelo alvo')),
                ('target_record_id', models.CharField(blank=True, max_length=128, verbose_name='registro alvo')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados seguros')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='identificador da requisição')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ocorrido em')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='ator')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_audit_events', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'evento de auditoria da plataforma',
                'verbose_name_plural': 'eventos de auditoria da plataforma',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['tenant', 'occurred_at'], name='control_pla_tenant__9c1ade_idx'), models.Index(fields=['actor', 'occurred_at'], name='control_pla_actor_i_5a94de_idx'), models.Index(fields=['action', 'occurred_at'], name='control_pla_action_65cb0b_idx'), models.Index(fields=['target_model', 'target_record_id'], name='control_pla_target__1da73f_idx')],
            },
        ),
    ]
