# Generated by Django 6.0.7 on 2026-07-11 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0001_initial'),
        ('tenants', '0002_tenant_module_contract_enforced_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador da sessão')),
                ('access_mode', models.CharField(choices=[('read', 'Somente leitura'), ('write', 'Leitura e escrita')], max_length=16, verbose_name='modo de acesso')),
                ('status', models.CharField(choices=[('requested', 'Aguardando aprovação'), ('approved', 'Aprovada'), ('active', 'Ativa'), ('denied', 'Negada'), ('expired', 'Expirada'), ('revoked', 'Revogada'), ('ended', 'Encerrada')], db_index=True, max_length=16, verbose_name='status')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('duration_minutes', models.PositiveSmallIntegerField(verbose_name='duração em minutos')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='solicitada em')),
                ('approval_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovação expira em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('denied_at', models.DateTimeField(blank=True, null=True, verbose_name='negada em')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='ativada em')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expira em')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='última atividade em')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revogada em')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_support_sessions', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('denied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denied_support_sessions', to=settings.AUTH_USER_MODEL, verbose_name='negada por')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operated_support_sessions', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_support_sessions', to=settings.AUTH_USER_MODEL, verbose_name='revogada por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_sessions', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'sessão de suporte',
                'verbose_name_plural': 'sessões de suporte',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='control_pla_tenant__306993_idx'), models.Index(fields=['operator', 'status', 'expires_at'], name='control_pla_operato_544845_idx'), models.Index(fields=['access_mode', 'status'], name='control_pla_access__037adf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('operator',), name='unique_active_support_session_per_operator'), models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 5), ('duration_minutes__lte', 120)), name='support_session_duration_range'), models.CheckConstraint(condition=models.Q(('access_mode', 'read'), ('duration_minutes__lte', 15), _connector='OR'), name='support_write_duration_max_15')],
            },
        ),
    ]
