# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0002_supportsession'),
        ('tenants', '0004_tenant_city_tenant_city_ref_tenant_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='platformauditevent',
            name='control_pla_tenant__9c1ade_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportsession',
            name='control_pla_tenant__306993_idx',
        ),
        migrations.AddIndex(
            model_name='platformauditevent',
            index=models.Index(fields=['occurred_at'], name='control_pla_occurre_b35493_idx'),
        ),
        migrations.AddIndex(
            model_name='supportsession',
            index=models.Index(fields=['status', 'created_at'], name='control_pla_status_040c55_idx'),
        ),
    ]
