# Generated by Django 5.2.16 on 2026-07-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0003_remove_platformauditevent_control_pla_tenant__9c1ade_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformauditevent',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='supportsession',
            name='tenant',
        ),
    ]
