# Generated by Django 6.0.8 on 2026-08-25 17:08

import base.sequences
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('inventory', '0002_initial'),
        ('masters', '0001_initial'),
        ('production', '0001_initial'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QAReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('review_number', models.CharField(blank=True, max_length=80, verbose_name='revisão')),
                ('review_type', models.CharField(choices=[('lot_release', 'Liberação de lote'), ('production_order', 'Ordem de produção'), ('packaging_record', 'Registro de embalagem'), ('quality_document', 'Laudo/documento de qualidade'), ('deviation', 'Desvio'), ('capa', 'CAPA'), ('change', 'Mudança'), ('controlled_document', 'Documento controlado')], max_length=32, verbose_name='tipo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('packaging_record_reference', models.CharField(blank=True, max_length=120, verbose_name='registro de embalagem')),
                ('deviation_reference', models.CharField(blank=True, max_length=120, verbose_name='desvio')),
                ('capa_reference', models.CharField(blank=True, max_length=120, verbose_name='CAPA')),
                ('change_reference', models.CharField(blank=True, max_length=120, verbose_name='mudança')),
                ('controlled_document_reference', models.CharField(blank=True, max_length=120, verbose_name='documento controlado')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada')], default='draft', max_length=24, verbose_name='status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submetida em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='rejeitada em')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motivo da rejeição')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_qa_reviews', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_reviews', to='production.productionorder', verbose_name='ordem de produção')),
                ('quality_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_reviews', to='quality.qualitydocument', verbose_name='documento de qualidade')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_qa_reviews', to=settings.AUTH_USER_MODEL, verbose_name='rejeitada por')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_reviews', to='inventory.stocklot', verbose_name='lote')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_qa_reviews', to=settings.AUTH_USER_MODEL, verbose_name='submetida por')),
            ],
            options={
                'verbose_name': 'revisão QA',
                'verbose_name_plural': 'revisões QA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('release_number', models.CharField(blank=True, max_length=80, verbose_name='liberação')),
                ('release_status', models.CharField(choices=[('under_review', 'Em revisão'), ('released', 'Liberado'), ('rejected', 'Rejeitado'), ('blocked', 'Bloqueado')], default='under_review', max_length=24, verbose_name='status de liberação')),
                ('decision', models.TextField(blank=True, verbose_name='decisão')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='liberado em')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='rejeitado em')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motivo da rejeição')),
                ('blocked_at', models.DateTimeField(blank=True, null=True, verbose_name='bloqueado em')),
                ('block_reason', models.TextField(blank=True, verbose_name='motivo do bloqueio')),
                ('unblocked_at', models.DateTimeField(blank=True, null=True, verbose_name='desbloqueado em')),
                ('unblock_reason', models.TextField(blank=True, verbose_name='motivo do desbloqueio')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blocked_qa_lots', to=settings.AUTH_USER_MODEL, verbose_name='bloqueado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qa_lot_releases', to='masters.product', verbose_name='produto')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_lot_releases', to='production.productionorder', verbose_name='ordem de produção')),
                ('quality_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_lot_releases', to='quality.qualitydocument', verbose_name='documento de qualidade')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_qa_lots', to=settings.AUTH_USER_MODEL, verbose_name='rejeitado por')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_qa_lots', to=settings.AUTH_USER_MODEL, verbose_name='liberado por')),
                ('stock_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qa_lot_releases', to='inventory.stocklot', verbose_name='lote')),
                ('unblocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unblocked_qa_lots', to=settings.AUTH_USER_MODEL, verbose_name='desbloqueado por')),
                ('qa_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot_releases', to='qa.qareview', verbose_name='revisão QA')),
            ],
            options={
                'verbose_name': 'liberação de lote',
                'verbose_name_plural': 'liberações de lote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchRecordChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=180, verbose_name='item de checklist')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('blocked', 'Bloqueado'), ('not_applicable', 'Não aplicável')], default='pending', max_length=24, verbose_name='status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('comments', models.TextField(blank=True, verbose_name='comentários')),
                ('evidence_reference', models.CharField(blank=True, max_length=255, verbose_name='evidência')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_qa_checklist_items', to=settings.AUTH_USER_MODEL, verbose_name='concluído por')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_checklist_items', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='qa.qareview', verbose_name='revisão QA')),
            ],
            options={
                'verbose_name': 'item de checklist de batch record',
                'verbose_name_plural': 'itens de checklist de batch record',
                'ordering': ['review__review_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('block_number', models.CharField(blank=True, max_length=80, verbose_name='bloqueio')),
                ('target_type', models.CharField(choices=[('lot', 'Lote'), ('product', 'Item/produto'), ('supplier', 'Fornecedor'), ('equipment', 'Equipamento'), ('document', 'Documento'), ('process', 'Processo')], max_length=24, verbose_name='tipo de alvo')),
                ('equipment_reference', models.CharField(blank=True, max_length=120, verbose_name='equipamento')),
                ('process_reference', models.CharField(blank=True, max_length=120, verbose_name='processo')),
                ('document_reference', models.CharField(blank=True, max_length=120, verbose_name='documento')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('unblocked', 'Desbloqueado'), ('cancelled', 'Cancelado')], default='active', max_length=24, verbose_name='status')),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='bloqueado em')),
                ('unblock_reason', models.TextField(blank=True, verbose_name='motivo do desbloqueio')),
                ('unblocked_at', models.DateTimeField(blank=True, null=True, verbose_name='desbloqueado em')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_qa_blocks', to=settings.AUTH_USER_MODEL, verbose_name='bloqueado por')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_blocks', to='masters.product', verbose_name='item/produto')),
                ('quality_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_blocks', to='quality.qualitydocument', verbose_name='documento de qualidade')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_blocks', to='inventory.stocklot', verbose_name='lote')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_blocks', to='masters.businesspartner', verbose_name='fornecedor')),
                ('unblocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_qa_blocks', to=settings.AUTH_USER_MODEL, verbose_name='desbloqueado por')),
            ],
            options={
                'verbose_name': 'bloqueio QA',
                'verbose_name_plural': 'bloqueios QA',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='código')),
                ('title', models.CharField(max_length=180, verbose_name='treinamento')),
                ('document_reference', models.CharField(blank=True, max_length=120, verbose_name='documento relacionado')),
                ('required_role', models.CharField(blank=True, max_length=120, verbose_name='função obrigatória')),
                ('area', models.CharField(blank=True, max_length=120, verbose_name='área')),
                ('process', models.CharField(blank=True, max_length=120, verbose_name='processo')),
                ('validity_days', models.PositiveIntegerField(default=365, verbose_name='validade em dias')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='obrigatório')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('area_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.businessarea', verbose_name='área normalizada')),
                ('process_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.businessprocess', verbose_name='processo normalizado')),
                ('role_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.organizationalrole', verbose_name='função normalizada')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targeted_training_requirements', to=settings.AUTH_USER_MODEL, verbose_name='usuário alvo')),
            ],
            options={
                'verbose_name': 'requisito de treinamento',
                'verbose_name_plural': 'requisitos de treinamento',
                'ordering': ['code'],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('planned', 'Planejado'), ('completed', 'Concluído'), ('expired', 'Expirado'), ('revoked', 'Revogado')], default='planned', max_length=24, verbose_name='status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válido até')),
                ('evidence_reference', models.CharField(blank=True, max_length=255, verbose_name='evidência')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_training_records', to=settings.AUTH_USER_MODEL, verbose_name='instrutor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_records', to='qa.trainingrequirement', verbose_name='requisito')),
            ],
            options={
                'verbose_name': 'registro de treinamento',
                'verbose_name_plural': 'registros de treinamento',
                'ordering': ['-completed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CriticalActivityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('activity_code', models.CharField(max_length=80, verbose_name='atividade')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('required_role', models.CharField(blank=True, max_length=120, verbose_name='função')),
                ('area', models.CharField(blank=True, max_length=120, verbose_name='área')),
                ('process', models.CharField(blank=True, max_length=120, verbose_name='processo')),
                ('enforce_training', models.BooleanField(default=True, verbose_name='bloquear sem treinamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('area_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.businessarea', verbose_name='área normalizada')),
                ('process_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.businessprocess', verbose_name='processo normalizado')),
                ('role_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.organizationalrole', verbose_name='função normalizada')),
                ('training_requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='critical_activity_rules', to='qa.trainingrequirement', verbose_name='treinamento obrigatório')),
            ],
            options={
                'verbose_name': 'regra de atividade crítica',
                'verbose_name_plural': 'regras de atividades críticas',
                'ordering': ['activity_code'],
            },
        ),
        migrations.AddIndex(
            model_name='qareview',
            index=models.Index(fields=['review_type', 'status'], name='qa_qareview_review__0ad048_idx'),
        ),
        migrations.AddIndex(
            model_name='qareview',
            index=models.Index(fields=['stock_lot'], name='qa_qareview_stock_l_488109_idx'),
        ),
        migrations.AddIndex(
            model_name='qareview',
            index=models.Index(fields=['production_order'], name='qa_qareview_product_a2c86f_idx'),
        ),
        migrations.AddIndex(
            model_name='qareview',
            index=models.Index(fields=['quality_document'], name='qa_qareview_quality_c76e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='qareview',
            index=models.Index(fields=['review_number'], name='qa_qareview_review__d2f7ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='qareview',
            constraint=models.UniqueConstraint(fields=('review_number',), name='unique_qa_review_number'),
        ),
        migrations.AddIndex(
            model_name='lotrelease',
            index=models.Index(fields=['release_status'], name='qa_lotrelea_release_819ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='lotrelease',
            index=models.Index(fields=['product'], name='qa_lotrelea_product_dda6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='lotrelease',
            index=models.Index(fields=['stock_lot'], name='qa_lotrelea_stock_l_f066f4_idx'),
        ),
        migrations.AddIndex(
            model_name='lotrelease',
            index=models.Index(fields=['release_number'], name='qa_lotrelea_release_73fb5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='lotrelease',
            constraint=models.UniqueConstraint(fields=('release_number',), name='unique_lot_release_number'),
        ),
        migrations.AddConstraint(
            model_name='lotrelease',
            constraint=models.UniqueConstraint(fields=('stock_lot',), name='unique_lot_release_lot'),
        ),
        migrations.AddIndex(
            model_name='batchrecordchecklistitem',
            index=models.Index(fields=['review', 'status'], name='qa_batchrec_review__6ac49e_idx'),
        ),
        migrations.AddIndex(
            model_name='batchrecordchecklistitem',
            index=models.Index(fields=['responsible', 'due_date'], name='qa_batchrec_respons_1c64ac_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityblock',
            index=models.Index(fields=['target_type', 'status'], name='qa_qualityb_target__2d8478_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityblock',
            index=models.Index(fields=['product'], name='qa_qualityb_product_8cf124_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityblock',
            index=models.Index(fields=['stock_lot'], name='qa_qualityb_stock_l_b27921_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityblock',
            index=models.Index(fields=['supplier'], name='qa_qualityb_supplie_b06c43_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityblock',
            index=models.Index(fields=['block_number'], name='qa_qualityb_block_n_a3c237_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityblock',
            constraint=models.UniqueConstraint(fields=('block_number',), name='unique_quality_block_number'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['is_active', 'is_mandatory'], name='qa_training_is_acti_3cfed6_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['area', 'process'], name='qa_training_area_031622_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['code'], name='qa_training_code_14e602_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingrequirement',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_training_requirement_code'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['requirement', 'status'], name='qa_training_require_f0b5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['user', 'valid_until'], name='qa_training_user_id_59d4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='criticalactivityrule',
            index=models.Index(fields=['is_active', 'enforce_training'], name='qa_critical_is_acti_2cb2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='criticalactivityrule',
            index=models.Index(fields=['activity_code'], name='qa_critical_activit_15dd98_idx'),
        ),
        migrations.AddConstraint(
            model_name='criticalactivityrule',
            constraint=models.UniqueConstraint(fields=('activity_code',), name='unique_critical_activity_code'),
        ),
    ]
