# Generated by Django 6.0.8 on 2026-08-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityblock',
            name='equipment_reference',
        ),
        migrations.AlterField(
            model_name='qualityblock',
            name='target_type',
            field=models.CharField(choices=[('lot', 'Lote'), ('product', 'Item/produto'), ('supplier', 'Fornecedor'), ('document', 'Documento'), ('process', 'Processo')], max_length=24, verbose_name='tipo de alvo'),
        ),
    ]
