# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('inventory', '0002_remove_stockbalance_unique_tenant_stock_balance_address_status_and_more'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('production', '0002_remove_productionorder_unique_tenant_production_order_number_and_more'),
        ('qa', '0002_criticalactivityrule_area_ref_and_more'),
        ('quality', '0003_remove_analyticalspecification_unique_tenant_qc_spec_product_lot_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='criticalactivityrule',
            name='unique_tenant_critical_activity_code',
        ),
        migrations.RemoveConstraint(
            model_name='lotrelease',
            name='unique_tenant_lot_release_number',
        ),
        migrations.RemoveConstraint(
            model_name='lotrelease',
            name='unique_tenant_lot_release_lot',
        ),
        migrations.RemoveConstraint(
            model_name='qareview',
            name='unique_tenant_qa_review_number',
        ),
        migrations.RemoveConstraint(
            model_name='qualityblock',
            name='unique_tenant_quality_block_number',
        ),
        migrations.RemoveConstraint(
            model_name='trainingrequirement',
            name='unique_tenant_training_requirement_code',
        ),
        migrations.RemoveIndex(
            model_name='batchrecordchecklistitem',
            name='qa_batchrec_tenant__a1e415_idx',
        ),
        migrations.RemoveIndex(
            model_name='batchrecordchecklistitem',
            name='qa_batchrec_tenant__c1bc3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='criticalactivityrule',
            name='qa_critical_tenant__1aaded_idx',
        ),
        migrations.RemoveIndex(
            model_name='lotrelease',
            name='qa_lotrelea_tenant__1628b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='lotrelease',
            name='qa_lotrelea_tenant__e7ef79_idx',
        ),
        migrations.RemoveIndex(
            model_name='lotrelease',
            name='qa_lotrelea_tenant__cb4af8_idx',
        ),
        migrations.RemoveIndex(
            model_name='qareview',
            name='qa_qareview_tenant__21c5cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='qareview',
            name='qa_qareview_tenant__a5ae98_idx',
        ),
        migrations.RemoveIndex(
            model_name='qareview',
            name='qa_qareview_tenant__803e1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='qareview',
            name='qa_qareview_tenant__bfad30_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityblock',
            name='qa_qualityb_tenant__e20ead_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityblock',
            name='qa_qualityb_tenant__91a34d_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityblock',
            name='qa_qualityb_tenant__520098_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityblock',
            name='qa_qualityb_tenant__d551e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingrecord',
            name='qa_training_tenant__a902ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingrecord',
            name='qa_training_tenant__44c2a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingrequirement',
            name='qa_training_tenant__458718_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingrequirement',
            name='qa_training_tenant__c528d2_idx',
        ),
        migrations.RemoveField(
            model_name='batchrecordchecklistitem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='criticalactivityrule',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='lotrelease',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='qareview',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='qualityblock',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='trainingrecord',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='trainingrequirement',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='batchrecordchecklistitem',
            index=models.Index(fields=['review', 'status'], name='qa_batchrec_review__6ac49e_idx'),
        ),
        migrations.AddIndex(
            model_name='batchrecordchecklistitem',
            index=models.Index(fields=['responsible', 'due_date'], name='qa_batchrec_respons_1c64ac_idx'),
        ),
        migrations.AddIndex(
            model_name='criticalactivityrule',
            index=models.Index(fields=['is_active', 'enforce_training'], name='qa_critical_is_acti_2cb2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='lotrelease',
            index=models.Index(fields=['release_status'], name='qa_lotrelea_release_819ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='lotrelease',
            index=models.Index(fields=['product'], name='qa_lotrelea_product_dda6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='lotrelease',
            index=models.Index(fields=['stock_lot'], name='qa_lotrelea_stock_l_f066f4_idx'),
        ),
        migrations.AddIndex(
            model_name='qareview',
            index=models.Index(fields=['review_type', 'status'], name='qa_qareview_review__0ad048_idx'),
        ),
        migrations.AddIndex(
            model_name='qareview',
            index=models.Index(fields=['stock_lot'], name='qa_qareview_stock_l_488109_idx'),
        ),
        migrations.AddIndex(
            model_name='qareview',
            index=models.Index(fields=['production_order'], name='qa_qareview_product_a2c86f_idx'),
        ),
        migrations.AddIndex(
            model_name='qareview',
            index=models.Index(fields=['quality_document'], name='qa_qareview_quality_c76e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityblock',
            index=models.Index(fields=['target_type', 'status'], name='qa_qualityb_target__2d8478_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityblock',
            index=models.Index(fields=['product'], name='qa_qualityb_product_8cf124_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityblock',
            index=models.Index(fields=['stock_lot'], name='qa_qualityb_stock_l_b27921_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityblock',
            index=models.Index(fields=['supplier'], name='qa_qualityb_supplie_b06c43_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['requirement', 'status'], name='qa_training_require_f0b5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['user', 'valid_until'], name='qa_training_user_id_59d4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['is_active', 'is_mandatory'], name='qa_training_is_acti_3cfed6_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['area', 'process'], name='qa_training_area_031622_idx'),
        ),
        migrations.AddConstraint(
            model_name='criticalactivityrule',
            constraint=models.UniqueConstraint(fields=('activity_code',), name='unique_critical_activity_code'),
        ),
        migrations.AddConstraint(
            model_name='lotrelease',
            constraint=models.UniqueConstraint(fields=('release_number',), name='unique_lot_release_number'),
        ),
        migrations.AddConstraint(
            model_name='lotrelease',
            constraint=models.UniqueConstraint(fields=('stock_lot',), name='unique_lot_release_lot'),
        ),
        migrations.AddConstraint(
            model_name='qareview',
            constraint=models.UniqueConstraint(fields=('review_number',), name='unique_qa_review_number'),
        ),
        migrations.AddConstraint(
            model_name='qualityblock',
            constraint=models.UniqueConstraint(fields=('block_number',), name='unique_quality_block_number'),
        ),
        migrations.AddConstraint(
            model_name='trainingrequirement',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_training_requirement_code'),
        ),
    ]
