# Generated by Django 5.2.16 on 2026-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_remove_criticalactivityrule_unique_tenant_critical_activity_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrequirement',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
    ]
