# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLotGenealogy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('relation_type', models.CharField(choices=[('consumed_in_production', 'Consumido na produção'), ('generated_from_production', 'Gerado na produção'), ('rework', 'Retrabalho'), ('return', 'Devolução')], max_length=32, verbose_name='tipo de relação')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade')),
                ('document_reference', models.CharField(blank=True, max_length=120, verbose_name='documento de referência')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'genealogia de lote',
                'verbose_name_plural': 'genealogias de lote',
                'ordering': ['output_lot__lot_number', 'input_lot__lot_number'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('movement_number', models.CharField(blank=True, max_length=80, verbose_name='movimento')),
                ('movement_type', models.CharField(choices=[('receipt', 'Entrada'), ('issue', 'Saída'), ('transfer', 'Transferência'), ('adjustment', 'Ajuste'), ('inventory_count', 'Inventário'), ('reservation', 'Reserva'), ('release_reservation', 'Liberação de reserva'), ('return', 'Devolução'), ('loss', 'Perda'), ('segregation', 'Segregação'), ('disposal', 'Descarte'), ('production_receipt', 'Entrada de produção'), ('shipment', 'Expedição')], max_length=32, verbose_name='tipo')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade')),
                ('quality_status', models.CharField(choices=[('quarantine', 'Quarentena'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('blocked', 'Bloqueado'), ('reserved', 'Reservado'), ('under_analysis', 'Em análise'), ('returned', 'Devolvido'), ('segregated', 'Segregado'), ('expired', 'Vencido')], max_length=24, verbose_name='status de qualidade')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data do movimento')),
                ('document_reference', models.CharField(blank=True, max_length=120, verbose_name='documento de referência')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('adjustment_reason', models.TextField(blank=True, verbose_name='justificativa do ajuste')),
            ],
            options={
                'verbose_name': 'movimento de estoque',
                'verbose_name_plural': 'movimentos de estoque',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quality_status', models.CharField(choices=[('quarantine', 'Quarentena'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('blocked', 'Bloqueado'), ('reserved', 'Reservado'), ('under_analysis', 'Em análise'), ('returned', 'Devolvido'), ('segregated', 'Segregado'), ('expired', 'Vencido')], max_length=24, verbose_name='status de qualidade')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade')),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade reservada')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='masters.storagelocation', verbose_name='localização')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='masters.product', verbose_name='produto')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='masters.unitofmeasure', verbose_name='unidade')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='masters.warehouse', verbose_name='almoxarifado')),
            ],
            options={
                'verbose_name': 'saldo de estoque',
                'verbose_name_plural': 'saldos de estoque',
                'ordering': ['warehouse__name', 'location__code', 'product__code', 'lot__lot_number'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('lot_number', models.CharField(max_length=80, verbose_name='lote')),
                ('sublot_number', models.CharField(blank=True, max_length=80, verbose_name='sublote')),
                ('quality_status', models.CharField(choices=[('quarantine', 'Quarentena'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('blocked', 'Bloqueado'), ('reserved', 'Reservado'), ('under_analysis', 'Em análise'), ('returned', 'Devolvido'), ('segregated', 'Segregado'), ('expired', 'Vencido')], default='quarantine', max_length=24, verbose_name='status de qualidade')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='data de fabricação')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='masters.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'lote de estoque',
                'verbose_name_plural': 'lotes de estoque',
                'ordering': ['product__code', 'lot_number', 'sublot_number'],
            },
        ),
    ]
