# Generated by Django 6.0.7 on 2026-07-07 18:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('procurement', '0001_initial'),
        ('production', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('lot_number', models.CharField(max_length=80, verbose_name='lote')),
                ('sublot_number', models.CharField(blank=True, max_length=80, verbose_name='sublote')),
                ('quality_status', models.CharField(choices=[('quarantine', 'Quarentena'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('blocked', 'Bloqueado'), ('reserved', 'Reservado'), ('under_analysis', 'Em análise'), ('returned', 'Devolvido'), ('segregated', 'Segregado'), ('expired', 'Vencido')], default='quarantine', max_length=24, verbose_name='status de qualidade')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='data de fabricação')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='masters.product', verbose_name='produto')),
                ('source_production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='production.productionorder', verbose_name='ordem de produção')),
                ('source_purchase_receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='procurement.purchasereceiptitem', verbose_name='item de recebimento')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplied_stock_lots', to='masters.businesspartner', verbose_name='fornecedor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'lote de estoque',
                'verbose_name_plural': 'lotes de estoque',
                'ordering': ['product__code', 'lot_number', 'sublot_number'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quality_status', models.CharField(choices=[('quarantine', 'Quarentena'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('blocked', 'Bloqueado'), ('reserved', 'Reservado'), ('under_analysis', 'Em análise'), ('returned', 'Devolvido'), ('segregated', 'Segregado'), ('expired', 'Vencido')], max_length=24, verbose_name='status de qualidade')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade')),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade reservada')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='masters.storagelocation', verbose_name='localização')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='masters.product', verbose_name='produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='masters.unitofmeasure', verbose_name='unidade')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='masters.warehouse', verbose_name='almoxarifado')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.stocklot', verbose_name='lote')),
            ],
            options={
                'verbose_name': 'saldo de estoque',
                'verbose_name_plural': 'saldos de estoque',
                'ordering': ['warehouse__name', 'location__code', 'product__code', 'lot__lot_number'],
            },
        ),
        migrations.CreateModel(
            name='StockLotGenealogy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('relation_type', models.CharField(choices=[('consumed_in_production', 'Consumido na produção'), ('generated_from_production', 'Gerado na produção'), ('rework', 'Retrabalho'), ('return', 'Devolução')], max_length=32, verbose_name='tipo de relação')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade')),
                ('document_reference', models.CharField(blank=True, max_length=120, verbose_name='documento de referência')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('input_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_genealogy_links', to='inventory.stocklot', verbose_name='lote de entrada')),
                ('output_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_genealogy_links', to='inventory.stocklot', verbose_name='lote de saída')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_genealogy_links', to='production.productionorder', verbose_name='ordem de produção')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_genealogy_links', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'genealogia de lote',
                'verbose_name_plural': 'genealogias de lote',
                'ordering': ['output_lot__lot_number', 'input_lot__lot_number'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('movement_number', models.CharField(blank=True, max_length=80, verbose_name='movimento')),
                ('movement_type', models.CharField(choices=[('receipt', 'Entrada'), ('issue', 'Saída'), ('transfer', 'Transferência'), ('adjustment', 'Ajuste'), ('inventory_count', 'Inventário'), ('reservation', 'Reserva'), ('release_reservation', 'Liberação de reserva'), ('return', 'Devolução'), ('loss', 'Perda'), ('segregation', 'Segregação'), ('disposal', 'Descarte'), ('production_receipt', 'Entrada de produção'), ('shipment', 'Expedição')], max_length=32, verbose_name='tipo')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade')),
                ('quality_status', models.CharField(choices=[('quarantine', 'Quarentena'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('blocked', 'Bloqueado'), ('reserved', 'Reservado'), ('under_analysis', 'Em análise'), ('returned', 'Devolvido'), ('segregated', 'Segregado'), ('expired', 'Vencido')], max_length=24, verbose_name='status de qualidade')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data do movimento')),
                ('document_reference', models.CharField(blank=True, max_length=120, verbose_name='documento de referência')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('adjustment_reason', models.TextField(blank=True, verbose_name='justificativa do ajuste')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_stock_movements', to='masters.storagelocation', verbose_name='localização origem')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_stock_movements', to='masters.warehouse', verbose_name='almoxarifado origem')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.stocklot', verbose_name='lote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='masters.product', verbose_name='produto')),
                ('related_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_movements', to='inventory.stockmovement', verbose_name='movimento relacionado')),
                ('source_material_consumption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='production.materialconsumption', verbose_name='consumo de produção')),
                ('source_production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='production.productionorder', verbose_name='ordem de produção')),
                ('source_purchase_receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='procurement.purchasereceiptitem', verbose_name='item de recebimento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_stock_movements', to='masters.storagelocation', verbose_name='localização destino')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_stock_movements', to='masters.warehouse', verbose_name='almoxarifado destino')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'movimento de estoque',
                'verbose_name_plural': 'movimentos de estoque',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['tenant', 'product'], name='inventory_s_tenant__381501_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['tenant', 'quality_status'], name='inventory_s_tenant__c5e3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['lot_number'], name='inventory_s_lot_num_0ca5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['expiry_date'], name='inventory_s_expiry__cf6e69_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'lot_number', 'sublot_number'), name='unique_tenant_product_lot_sublot'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['tenant', 'product', 'quality_status'], name='inventory_s_tenant__b9aa4f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['tenant', 'warehouse', 'location'], name='inventory_s_tenant__ddecc2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['tenant', 'lot'], name='inventory_s_tenant__f1ef24_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'lot', 'warehouse', 'location', 'quality_status'), name='unique_tenant_stock_balance_address_status'),
        ),
        migrations.AddIndex(
            model_name='stocklotgenealogy',
            index=models.Index(fields=['tenant', 'input_lot'], name='inventory_s_tenant__814949_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklotgenealogy',
            index=models.Index(fields=['tenant', 'output_lot'], name='inventory_s_tenant__9ce363_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklotgenealogy',
            index=models.Index(fields=['relation_type'], name='inventory_s_relatio_e01bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'movement_type'], name='inventory_s_tenant__2cbf2f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'product', 'movement_date'], name='inventory_s_tenant__e46874_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'lot'], name='inventory_s_tenant__a7e3f2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_number'], name='inventory_s_movemen_0f2675_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('tenant', 'movement_number'), name='unique_tenant_stock_movement_number'),
        ),
    ]
