# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('procurement', '0004_remove_purchaseorder_unique_tenant_purchase_order_number_and_more'),
        ('production', '0002_remove_productionorder_unique_tenant_production_order_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockbalance',
            name='unique_tenant_stock_balance_address_status',
        ),
        migrations.RemoveConstraint(
            model_name='stocklot',
            name='unique_tenant_product_lot_sublot',
        ),
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='unique_tenant_stock_movement_number',
        ),
        migrations.RemoveIndex(
            model_name='stockbalance',
            name='inventory_s_tenant__b9aa4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockbalance',
            name='inventory_s_tenant__ddecc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockbalance',
            name='inventory_s_tenant__f1ef24_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocklot',
            name='inventory_s_tenant__381501_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocklot',
            name='inventory_s_tenant__c5e3b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocklotgenealogy',
            name='inventory_s_tenant__814949_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocklotgenealogy',
            name='inventory_s_tenant__9ce363_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='inventory_s_tenant__2cbf2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='inventory_s_tenant__e46874_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='inventory_s_tenant__a7e3f2_idx',
        ),
        migrations.RemoveField(
            model_name='stockbalance',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='stocklot',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='stocklotgenealogy',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['product', 'quality_status'], name='inventory_s_product_5f47ea_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['warehouse', 'location'], name='inventory_s_warehou_1bb769_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['lot'], name='inventory_s_lot_id_13db60_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['product'], name='inventory_s_product_c0893e_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['quality_status'], name='inventory_s_quality_3714f8_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklotgenealogy',
            index=models.Index(fields=['input_lot'], name='inventory_s_input_l_e08412_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklotgenealogy',
            index=models.Index(fields=['output_lot'], name='inventory_s_output__cf2371_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'movement_date'], name='inventory_s_product_c6681e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['lot'], name='inventory_s_lot_id_609185_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('product', 'lot', 'warehouse', 'location', 'quality_status'), name='unique_stock_balance_address_status'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.UniqueConstraint(fields=('product', 'lot_number', 'sublot_number'), name='unique_product_lot_sublot'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('movement_number',), name='unique_stock_movement_number'),
        ),
    ]
