# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        ('procurement', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='source_production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='production.productionorder', verbose_name='ordem de produção'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='source_purchase_receipt_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='procurement.purchasereceiptitem', verbose_name='item de recebimento'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplied_stock_lots', to='masters.businesspartner', verbose_name='fornecedor'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.stocklot', verbose_name='lote'),
        ),
        migrations.AddField(
            model_name='stocklotgenealogy',
            name='input_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_genealogy_links', to='inventory.stocklot', verbose_name='lote de entrada'),
        ),
        migrations.AddField(
            model_name='stocklotgenealogy',
            name='output_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_genealogy_links', to='inventory.stocklot', verbose_name='lote de saída'),
        ),
        migrations.AddField(
            model_name='stocklotgenealogy',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_genealogy_links', to='production.productionorder', verbose_name='ordem de produção'),
        ),
        migrations.AddField(
            model_name='stocklotgenealogy',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_genealogy_links', to='masters.unitofmeasure', verbose_name='unidade'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_stock_movements', to='masters.storagelocation', verbose_name='localização origem'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_stock_movements', to='masters.warehouse', verbose_name='almoxarifado origem'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.stocklot', verbose_name='lote'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='masters.product', verbose_name='produto'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='related_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_movements', to='inventory.stockmovement', verbose_name='movimento relacionado'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_material_consumption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='production.materialconsumption', verbose_name='consumo de produção'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='production.productionorder', verbose_name='ordem de produção'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_purchase_receipt_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='procurement.purchasereceiptitem', verbose_name='item de recebimento'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_stock_movements', to='masters.storagelocation', verbose_name='localização destino'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_stock_movements', to='masters.warehouse', verbose_name='almoxarifado destino'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='masters.unitofmeasure', verbose_name='unidade'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['product'], name='inventory_s_product_c0893e_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['quality_status'], name='inventory_s_quality_3714f8_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['lot_number'], name='inventory_s_lot_num_0ca5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['expiry_date'], name='inventory_s_expiry__cf6e69_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.UniqueConstraint(fields=('product', 'lot_number', 'sublot_number'), name='unique_product_lot_sublot'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['product', 'quality_status'], name='inventory_s_product_5f47ea_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['warehouse', 'location'], name='inventory_s_warehou_1bb769_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['lot'], name='inventory_s_lot_id_13db60_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('product', 'lot', 'warehouse', 'location', 'quality_status'), name='unique_stock_balance_address_status'),
        ),
        migrations.AddIndex(
            model_name='stocklotgenealogy',
            index=models.Index(fields=['input_lot'], name='inventory_s_input_l_e08412_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklotgenealogy',
            index=models.Index(fields=['output_lot'], name='inventory_s_output__cf2371_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklotgenealogy',
            index=models.Index(fields=['relation_type'], name='inventory_s_relatio_e01bd5_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklotgenealogy',
            constraint=models.UniqueConstraint(fields=('input_lot', 'output_lot', 'production_order', 'relation_type'), name='unique_production_lot_genealogy', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'movement_date'], name='inventory_s_product_c6681e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['lot'], name='inventory_s_lot_id_609185_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_number'], name='inventory_s_movemen_0f2675_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('movement_number',), name='unique_stock_movement_number'),
        ),
    ]
