# Generated by Django 5.2.16 on 2026-07-27 21:48

from django.db import migrations, models
from django.db.models import Count


GENEALOGY_KEY = (
    'input_lot_id',
    'output_lot_id',
    'production_order_id',
    'relation_type',
)


def preflight_duplicate_genealogy(apps, schema_editor):
    StockLotGenealogy = apps.get_model('inventory', 'StockLotGenealogy')
    database_alias = schema_editor.connection.alias
    queryset = StockLotGenealogy.objects.using(database_alias)
    duplicate_groups = list(
        queryset.values(*GENEALOGY_KEY)
        .annotate(record_count=Count('pk'))
        .filter(record_count__gt=1)
        .order_by(*GENEALOGY_KEY)
    )
    if not duplicate_groups:
        return

    details = []
    for group in duplicate_groups:
        criteria = {field: group[field] for field in GENEALOGY_KEY}
        record_ids = list(
            queryset.filter(**criteria).order_by('pk').values_list('pk', flat=True)
        )
        key_description = ', '.join(f'{field}={criteria[field]}' for field in GENEALOGY_KEY)
        details.append(f'chave ({key_description}); IDs={record_ids}')

    raise RuntimeError(
        'A migration inventory.0003 não pode criar '
        'unique_production_lot_genealogy porque existem evidências históricas duplicadas: '
        f'{" | ".join(details)}. Faça o saneamento explícito dos registros indicados, '
        'preservando a trilha regulatória, e execute a migration novamente.'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_stockbalance_unique_tenant_stock_balance_address_status_and_more'),
        ('masters', '0006_businesspartner_country_ref_site_country_ref'),
        ('production', '0005_constrain_production_output_status'),
    ]

    operations = [
        migrations.RunPython(
            preflight_duplicate_genealogy,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='stocklotgenealogy',
            constraint=models.UniqueConstraint(
                fields=('input_lot', 'output_lot', 'production_order', 'relation_type'),
                name='unique_production_lot_genealogy',
                nulls_distinct=False,
            ),
        ),
    ]
