# Generated by Django 6.0.7 on 2026-07-08 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('module', models.CharField(choices=[('production', 'Produção'), ('mrp', 'MRP'), ('inventory', 'Estoque'), ('traceability', 'Rastreabilidade'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('quality', 'Qualidade'), ('audit', 'Auditoria'), ('capa', 'CAPA'), ('deviations', 'Desvios'), ('risks', 'Riscos'), ('regulatory', 'Regulatório'), ('pharmacovigilance', 'Farmacovigilância')], max_length=32, verbose_name='módulo')),
                ('profile_role', models.CharField(blank=True, choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('quality', 'Qualidade'), ('production', 'Produção'), ('regulatory', 'Regulatório'), ('finance', 'Financeiro'), ('viewer', 'Leitura')], max_length=32, verbose_name='perfil')),
                ('layout', models.JSONField(blank=True, default=dict, verbose_name='layout')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'dashboard',
                'verbose_name_plural': 'dashboards',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('module', models.CharField(choices=[('production', 'Produção'), ('mrp', 'MRP'), ('inventory', 'Estoque'), ('traceability', 'Rastreabilidade'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('quality', 'Qualidade'), ('audit', 'Auditoria'), ('capa', 'CAPA'), ('deviations', 'Desvios'), ('risks', 'Riscos'), ('regulatory', 'Regulatório'), ('pharmacovigilance', 'Farmacovigilância')], max_length=32, verbose_name='módulo')),
                ('category', models.CharField(choices=[('operational', 'Operacional'), ('management', 'Gerencial'), ('indicator', 'Indicador'), ('regulatory', 'Regulatório'), ('audit', 'Auditoria')], max_length=32, verbose_name='categoria')),
                ('allowed_export_formats', models.JSONField(default=list, verbose_name='formatos permitidos')),
                ('default_filters', models.JSONField(blank=True, default=dict, verbose_name='filtros padrão')),
                ('required_filters', models.JSONField(blank=True, default=list, verbose_name='filtros obrigatórios')),
                ('query_config', models.JSONField(blank=True, default=dict, verbose_name='configuração de consulta')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_report_definitions', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'definição de relatório',
                'verbose_name_plural': 'definições de relatórios',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('widget_type', models.CharField(choices=[('kpi', 'KPI'), ('chart', 'Gráfico'), ('table', 'Tabela'), ('list', 'Lista')], max_length=24, verbose_name='tipo')),
                ('module', models.CharField(choices=[('production', 'Produção'), ('mrp', 'MRP'), ('inventory', 'Estoque'), ('traceability', 'Rastreabilidade'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('quality', 'Qualidade'), ('audit', 'Auditoria'), ('capa', 'CAPA'), ('deviations', 'Desvios'), ('risks', 'Riscos'), ('regulatory', 'Regulatório'), ('pharmacovigilance', 'Farmacovigilância')], max_length=32, verbose_name='módulo')),
                ('position_row', models.PositiveIntegerField(default=1, verbose_name='linha')),
                ('position_column', models.PositiveIntegerField(default=1, verbose_name='coluna')),
                ('width', models.PositiveIntegerField(default=4, verbose_name='largura')),
                ('height', models.PositiveIntegerField(default=2, verbose_name='altura')),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='configuração')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.dashboardworkspace', verbose_name='dashboard')),
                ('report_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_widgets', to='reports.reportdefinition', verbose_name='relatório')),
            ],
            options={
                'verbose_name': 'widget de dashboard',
                'verbose_name_plural': 'widgets de dashboard',
                'ordering': ['dashboard', 'position_row', 'position_column'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('execution_number', models.CharField(blank=True, max_length=80, verbose_name='execução')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filtros')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'XLSX'), ('csv', 'CSV')], max_length=12, verbose_name='formato')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=24, verbose_name='status')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='solicitado em')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('result_reference', models.CharField(blank=True, max_length=255, verbose_name='referência do arquivo')),
                ('content_hash', models.CharField(blank=True, max_length=128, verbose_name='hash do conteúdo')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='linhas')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('celery_task_name', models.CharField(blank=True, max_length=160, verbose_name='tarefa Celery')),
                ('celery_task_id', models.CharField(blank=True, max_length=160, verbose_name='id da tarefa Celery')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='reports.reportdefinition', verbose_name='relatório')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_report_executions', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'execução de relatório',
                'verbose_name_plural': 'execuções de relatórios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('channel', models.CharField(choices=[('internal', 'Interna'), ('email', 'Email')], default='internal', max_length=24, verbose_name='canal')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('failed', 'Falhou')], default='pending', max_length=24, verbose_name='status')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.reportexecution', verbose_name='execução')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'notificação de relatório',
                'verbose_name_plural': 'notificações de relatórios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('cron', 'Cron')], max_length=24, verbose_name='frequência')),
                ('cron_expression', models.CharField(blank=True, max_length=120, verbose_name='expressão cron')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filtros')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'XLSX'), ('csv', 'CSV')], max_length=12, verbose_name='formato')),
                ('next_run_at', models.DateTimeField(verbose_name='próxima execução')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='última execução')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='reports.reportdefinition', verbose_name='relatório')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_report_schedules', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('recipients', models.ManyToManyField(blank=True, related_name='report_schedules', to=settings.AUTH_USER_MODEL, verbose_name='destinatários')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'agendamento de relatório',
                'verbose_name_plural': 'agendamentos de relatórios',
                'ordering': ['next_run_at', 'name'],
            },
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='reports.reportschedule', verbose_name='agendamento'),
        ),
        migrations.AddIndex(
            model_name='dashboardworkspace',
            index=models.Index(fields=['tenant', 'module', 'profile_role', 'is_active'], name='reports_das_tenant__7f513e_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardworkspace',
            index=models.Index(fields=['tenant', 'owner'], name='reports_das_tenant__70dad2_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardworkspace',
            index=models.Index(fields=['code'], name='reports_das_code_512943_idx'),
        ),
        migrations.AddConstraint(
            model_name='dashboardworkspace',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_dashboard_workspace_code'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['tenant', 'module', 'category', 'is_active'], name='reports_rep_tenant__f226b3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['tenant', 'owner'], name='reports_rep_tenant__e9d86c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['code'], name='reports_rep_code_b4d162_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportdefinition',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_report_definition_code'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['tenant', 'dashboard', 'module'], name='reports_das_tenant__2e74a9_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['tenant', 'widget_type'], name='reports_das_tenant__f7974c_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['tenant', 'report_definition'], name='reports_das_tenant__441608_idx'),
        ),
        migrations.AddIndex(
            model_name='reportnotification',
            index=models.Index(fields=['tenant', 'execution', 'status'], name='reports_rep_tenant__ea5084_idx'),
        ),
        migrations.AddIndex(
            model_name='reportnotification',
            index=models.Index(fields=['tenant', 'recipient', 'status'], name='reports_rep_tenant__e886bc_idx'),
        ),
        migrations.AddIndex(
            model_name='reportnotification',
            index=models.Index(fields=['tenant', 'channel'], name='reports_rep_tenant__04ceac_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportnotification',
            constraint=models.UniqueConstraint(fields=('tenant', 'execution', 'recipient', 'channel'), name='unique_tenant_report_notification_recipient'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['tenant', 'definition', 'is_active'], name='reports_rep_tenant__4109d6_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['tenant', 'frequency', 'next_run_at'], name='reports_rep_tenant__ea697d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['tenant', 'owner'], name='reports_rep_tenant__53bedd_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['tenant', 'definition', 'status'], name='reports_rep_tenant__a0332f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['tenant', 'schedule'], name='reports_rep_tenant__da794d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['tenant', 'requested_by'], name='reports_rep_tenant__8ee13a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['tenant', 'requested_at'], name='reports_rep_tenant__70966d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['tenant', 'export_format'], name='reports_rep_tenant__b12680_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportexecution',
            constraint=models.UniqueConstraint(fields=('tenant', 'execution_number'), name='unique_tenant_report_execution_number'),
        ),
    ]
