# Generated by Django 6.0.7 on 2026-07-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo normalizado'),
        ),
        migrations.AddField(
            model_name='dashboardworkspace',
            name='module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo normalizado'),
        ),
        migrations.AddField(
            model_name='dashboardworkspace',
            name='role_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.organizationalrole', verbose_name='perfil normalizado'),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo normalizado'),
        ),
    ]
