# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('reports', '0002_dashboardwidget_module_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dashboardworkspace',
            name='unique_tenant_dashboard_workspace_code',
        ),
        migrations.RemoveConstraint(
            model_name='reportdefinition',
            name='unique_tenant_report_definition_code',
        ),
        migrations.RemoveConstraint(
            model_name='reportexecution',
            name='unique_tenant_report_execution_number',
        ),
        migrations.RemoveConstraint(
            model_name='reportnotification',
            name='unique_tenant_report_notification_recipient',
        ),
        migrations.RemoveIndex(
            model_name='dashboardwidget',
            name='reports_das_tenant__2e74a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='dashboardwidget',
            name='reports_das_tenant__f7974c_idx',
        ),
        migrations.RemoveIndex(
            model_name='dashboardwidget',
            name='reports_das_tenant__441608_idx',
        ),
        migrations.RemoveIndex(
            model_name='dashboardworkspace',
            name='reports_das_tenant__7f513e_idx',
        ),
        migrations.RemoveIndex(
            model_name='dashboardworkspace',
            name='reports_das_tenant__70dad2_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportdefinition',
            name='reports_rep_tenant__f226b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportdefinition',
            name='reports_rep_tenant__e9d86c_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportexecution',
            name='reports_rep_tenant__a0332f_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportexecution',
            name='reports_rep_tenant__da794d_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportexecution',
            name='reports_rep_tenant__8ee13a_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportexecution',
            name='reports_rep_tenant__70966d_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportexecution',
            name='reports_rep_tenant__b12680_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportnotification',
            name='reports_rep_tenant__ea5084_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportnotification',
            name='reports_rep_tenant__e886bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportnotification',
            name='reports_rep_tenant__04ceac_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportschedule',
            name='reports_rep_tenant__4109d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportschedule',
            name='reports_rep_tenant__ea697d_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportschedule',
            name='reports_rep_tenant__53bedd_idx',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='dashboardworkspace',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='reportdefinition',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='reportexecution',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='reportnotification',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='reportschedule',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['dashboard', 'module'], name='reports_das_dashboa_b4f340_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['widget_type'], name='reports_das_widget__103de8_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['report_definition'], name='reports_das_report__fdda9d_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardworkspace',
            index=models.Index(fields=['module', 'profile_role', 'is_active'], name='reports_das_module_fd4309_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardworkspace',
            index=models.Index(fields=['owner'], name='reports_das_owner_i_b13a41_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['module', 'category', 'is_active'], name='reports_rep_module_20f18a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['owner'], name='reports_rep_owner_i_5a76a2_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['definition', 'status'], name='reports_rep_definit_971b47_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['schedule'], name='reports_rep_schedul_03ccb7_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['requested_by'], name='reports_rep_request_02a5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['requested_at'], name='reports_rep_request_8c4d51_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['export_format'], name='reports_rep_export__62a861_idx'),
        ),
        migrations.AddIndex(
            model_name='reportnotification',
            index=models.Index(fields=['execution', 'status'], name='reports_rep_executi_bef7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportnotification',
            index=models.Index(fields=['recipient', 'status'], name='reports_rep_recipie_ffee53_idx'),
        ),
        migrations.AddIndex(
            model_name='reportnotification',
            index=models.Index(fields=['channel'], name='reports_rep_channel_2efb87_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['definition', 'is_active'], name='reports_rep_definit_b24f44_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['frequency', 'next_run_at'], name='reports_rep_frequen_d38daa_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['owner'], name='reports_rep_owner_i_92023a_idx'),
        ),
        migrations.AddConstraint(
            model_name='dashboardworkspace',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_dashboard_workspace_code'),
        ),
        migrations.AddConstraint(
            model_name='reportdefinition',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_report_definition_code'),
        ),
        migrations.AddConstraint(
            model_name='reportexecution',
            constraint=models.UniqueConstraint(fields=('execution_number',), name='unique_report_execution_number'),
        ),
        migrations.AddConstraint(
            model_name='reportnotification',
            constraint=models.UniqueConstraint(fields=('execution', 'recipient', 'channel'), name='unique_report_notification_recipient'),
        ),
    ]
