# Generated by Django 5.2.16 on 2026-07-28

import django.db.models.deletion
from django.db import migrations, models


MODULE_CHOICES = [
    ('production', 'Produção'),
    ('mrp', 'MRP'),
    ('procurement', 'Compras'),
    ('inventory', 'Estoque'),
    ('traceability', 'Rastreabilidade'),
    ('costing', 'Custos'),
    ('finance', 'Financeiro'),
    ('fiscal', 'Fiscal'),
    ('quality', 'Qualidade'),
    ('audit', 'Auditoria'),
    ('capa', 'CAPA'),
    ('deviations', 'Desvios'),
    ('risks', 'Riscos'),
    ('regulatory', 'Regulatório'),
    ('pharmacovigilance', 'Farmacovigilância'),
]


class Migration(migrations.Migration):

    dependencies = [
        (
            'files',
            '0004_remove_protectedfile_unique_tenant_protected_file_number_and_more',
        ),
        (
            'reports',
            '0003_remove_dashboardworkspace_unique_tenant_dashboard_workspace_code_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdefinition',
            name='executor_key',
            field=models.CharField(
                blank=True,
                max_length=120,
                verbose_name='executor registrado',
            ),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='filter_schema',
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name='esquema de filtros',
            ),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='is_system_managed',
            field=models.BooleanField(
                default=False,
                verbose_name='gerenciado pelo sistema',
            ),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='required_permission',
            field=models.CharField(
                blank=True,
                max_length=120,
                verbose_name='permissão de domínio exigida',
            ),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='result_file',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='report_executions',
                to='files.protectedfile',
                verbose_name='arquivo gerado',
            ),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='module',
            field=models.CharField(
                choices=MODULE_CHOICES,
                max_length=32,
                verbose_name='módulo',
            ),
        ),
        migrations.AlterField(
            model_name='dashboardworkspace',
            name='module',
            field=models.CharField(
                choices=MODULE_CHOICES,
                max_length=32,
                verbose_name='módulo',
            ),
        ),
        migrations.AlterField(
            model_name='reportdefinition',
            name='module',
            field=models.CharField(
                choices=MODULE_CHOICES,
                max_length=32,
                verbose_name='módulo',
            ),
        ),
    ]
