# Generated by Django 5.2.16 on 2026-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_seed_curated_report_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardworkspace',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='reportdefinition',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
    ]
