# Generated by Django 6.0.7 on 2026-07-07 20:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('masters', '0001_initial'),
        ('procurement', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('legal_name', models.CharField(max_length=255, verbose_name='razão social')),
                ('document', models.CharField(max_length=32, verbose_name='CNPJ/CPF')),
                ('state_registration', models.CharField(blank=True, max_length=40, verbose_name='inscrição estadual')),
                ('municipal_registration', models.CharField(blank=True, max_length=40, verbose_name='inscrição municipal')),
                ('tax_regime', models.CharField(choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real'), ('exempt', 'Isento')], max_length=32, verbose_name='regime tributário')),
                ('city', models.CharField(max_length=120, verbose_name='município')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'empresa fiscal',
                'verbose_name_plural': 'empresas fiscais',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('document_type', models.CharField(choices=[('inbound', 'Entrada'), ('outbound', 'Saída')], max_length=24, verbose_name='tipo')),
                ('operation_type', models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venda'), ('service', 'Serviço'), ('return', 'Devolução'), ('transfer', 'Transferência'), ('other', 'Outra')], max_length=24, verbose_name='operação')),
                ('number', models.CharField(max_length=80, verbose_name='número')),
                ('series', models.CharField(max_length=20, verbose_name='série')),
                ('issue_date', models.DateField(verbose_name='emissão')),
                ('operation_date', models.DateField(verbose_name='operação')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('under_review', 'Em conferência'), ('reviewed', 'Conferida'), ('approved', 'Aprovada'), ('posted', 'Lançada'), ('cancelled', 'Cancelada')], default='draft', max_length=24, verbose_name='status')),
                ('total_products', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='total produtos')),
                ('total_taxes', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='total impostos')),
                ('retained_taxes', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='retenções')),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='total da nota')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='conferida em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='lançada em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_fiscal_documents', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='fiscal.fiscalcompany', verbose_name='empresa')),
                ('financial_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='finance.financialtitle', verbose_name='título financeiro')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='masters.businesspartner', verbose_name='parceiro')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_fiscal_documents', to=settings.AUTH_USER_MODEL, verbose_name='lançada por')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='procurement.purchaseorder', verbose_name='pedido de compra')),
                ('purchase_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='procurement.purchasereceipt', verbose_name='recebimento')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_fiscal_documents', to=settings.AUTH_USER_MODEL, verbose_name='conferida por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'documento fiscal',
                'verbose_name_plural': 'documentos fiscais',
                'ordering': ['-issue_date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='FiscalBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('book_type', models.CharField(choices=[('inbound', 'Livro de entradas'), ('outbound', 'Livro de saídas'), ('service', 'Livro de serviços')], max_length=24, verbose_name='livro')),
                ('entry_date', models.DateField(verbose_name='data de escrituração')),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='valor total')),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='valor impostos')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_entries', to='fiscal.fiscaldocument', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'livro fiscal',
                'verbose_name_plural': 'livros fiscais',
                'ordering': ['-entry_date', 'document__number'],
            },
        ),
        migrations.CreateModel(
            name='FiscalMunicipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ibge_code', models.CharField(max_length=16, verbose_name='código IBGE')),
                ('name', models.CharField(max_length=120, verbose_name='município')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'município fiscal',
                'verbose_name_plural': 'municípios fiscais',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FiscalNCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=12, verbose_name='NCM')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('cest', models.CharField(blank=True, max_length=16, verbose_name='CEST')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'NCM',
                'verbose_name_plural': 'NCMs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('obligation_type', models.CharField(choices=[('sped_fiscal', 'SPED Fiscal'), ('sped_contrib', 'SPED Contribuições'), ('gia', 'GIA'), ('dctf', 'DCTF'), ('municipal', 'Obrigação municipal'), ('other', 'Outra')], max_length=32, verbose_name='obrigação')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='mês')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('submitted', 'Entregue'), ('accepted', 'Aceita'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='open', max_length=24, verbose_name='status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='entregue em')),
                ('protocol_number', models.CharField(blank=True, max_length=80, verbose_name='protocolo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_fiscal_obligations', to=settings.AUTH_USER_MODEL, verbose_name='entregue por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'obrigação fiscal',
                'verbose_name_plural': 'obrigações fiscais',
                'ordering': ['due_date', 'obligation_type'],
            },
        ),
        migrations.CreateModel(
            name='FiscalOperationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=8, verbose_name='CFOP')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('direction', models.CharField(choices=[('inbound', 'Entrada'), ('outbound', 'Saída'), ('both', 'Entrada e saída')], max_length=16, verbose_name='direção')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'CFOP',
                'verbose_name_plural': 'CFOPs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=20, verbose_name='código')),
                ('description', models.CharField(max_length=120, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'unidade fiscal',
                'verbose_name_plural': 'unidades fiscais',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('line_number', models.PositiveIntegerField(verbose_name='linha')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='valor unitário')),
                ('discount_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='desconto')),
                ('freight_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='frete')),
                ('insurance_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='seguro')),
                ('other_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='outras despesas')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fiscal.fiscaldocument', verbose_name='documento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_document_items', to='masters.product', verbose_name='produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('ncm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_document_items', to='fiscal.fiscalncm', verbose_name='NCM')),
                ('cfop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_document_items', to='fiscal.fiscaloperationcode', verbose_name='CFOP')),
                ('fiscal_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_document_items', to='fiscal.fiscalunit', verbose_name='unidade fiscal')),
            ],
            options={
                'verbose_name': 'item de documento fiscal',
                'verbose_name_plural': 'itens de documentos fiscais',
                'ordering': ['document', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='TaxAssessmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='mês')),
                ('tax_kind', models.CharField(choices=[('icms', 'ICMS'), ('ipi', 'IPI'), ('pis', 'PIS'), ('cofins', 'COFINS'), ('iss', 'ISS'), ('irrf', 'IRRF'), ('inss', 'INSS'), ('csll', 'CSLL'), ('retention', 'Retenção')], max_length=24, verbose_name='tributo')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('calculated', 'Calculada'), ('closed', 'Fechada'), ('reopened', 'Reaberta')], default='open', max_length=24, verbose_name='status')),
                ('debit_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='débitos')),
                ('credit_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='créditos')),
                ('retained_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='retenções')),
                ('balance_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='saldo')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='calculada em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechada em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_tax_assessments', to=settings.AUTH_USER_MODEL, verbose_name='fechada por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'apuração fiscal',
                'verbose_name_plural': 'apurações fiscais',
                'ordering': ['-period_year', '-period_month', 'tax_kind'],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('tax_kind', models.CharField(choices=[('icms', 'ICMS'), ('ipi', 'IPI'), ('pis', 'PIS'), ('cofins', 'COFINS'), ('iss', 'ISS'), ('irrf', 'IRRF'), ('inss', 'INSS'), ('csll', 'CSLL'), ('retention', 'Retenção')], max_length=24, verbose_name='tributo')),
                ('rate_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9, verbose_name='alíquota (%)')),
                ('reduction_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9, verbose_name='redução (%)')),
                ('retention_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9, verbose_name='retenção (%)')),
                ('effective_from', models.DateField(verbose_name='vigência inicial')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='vigência final')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovada'), ('obsolete', 'Obsoleta')], default='draft', max_length=24, verbose_name='status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_tax_rules', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('cfop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rules', to='fiscal.fiscaloperationcode', verbose_name='CFOP')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_rules', to='fiscal.fiscalcompany', verbose_name='empresa')),
                ('ncm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rules', to='fiscal.fiscalncm', verbose_name='NCM')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_rules', to='masters.businesspartner', verbose_name='parceiro')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_rules', to='masters.product', verbose_name='produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'regra tributária',
                'verbose_name_plural': 'regras tributárias',
                'ordering': ['tax_kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FiscalTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tax_kind', models.CharField(choices=[('icms', 'ICMS'), ('ipi', 'IPI'), ('pis', 'PIS'), ('cofins', 'COFINS'), ('iss', 'ISS'), ('irrf', 'IRRF'), ('inss', 'INSS'), ('csll', 'CSLL'), ('retention', 'Retenção')], max_length=24, verbose_name='tributo')),
                ('base_amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='base')),
                ('rate_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9, verbose_name='alíquota (%)')),
                ('reduction_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9, verbose_name='redução (%)')),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='valor')),
                ('is_retained', models.BooleanField(default=False, verbose_name='retido')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='fiscal.fiscaldocument', verbose_name='documento')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='fiscal.fiscaldocumentitem', verbose_name='item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('tax_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_taxes', to='fiscal.taxrule', verbose_name='regra tributária')),
            ],
            options={
                'verbose_name': 'imposto do documento',
                'verbose_name_plural': 'impostos dos documentos',
                'ordering': ['document', 'tax_kind'],
            },
        ),
        migrations.CreateModel(
            name='TaxSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=8, verbose_name='código')),
                ('tax_kind', models.CharField(choices=[('icms', 'ICMS'), ('ipi', 'IPI'), ('pis', 'PIS'), ('cofins', 'COFINS'), ('iss', 'ISS'), ('irrf', 'IRRF'), ('inss', 'INSS'), ('csll', 'CSLL'), ('retention', 'Retenção')], max_length=24, verbose_name='tributo')),
                ('regime_kind', models.CharField(choices=[('cst', 'CST'), ('csosn', 'CSOSN')], max_length=16, verbose_name='regime do código')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'CST/CSOSN',
                'verbose_name_plural': 'CST/CSOSN',
                'ordering': ['tax_kind', 'regime_kind', 'code'],
            },
        ),
        migrations.AddField(
            model_name='taxrule',
            name='tax_situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rules', to='fiscal.taxsituation', verbose_name='CST/CSOSN'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentitem',
            name='tax_situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_document_items', to='fiscal.taxsituation', verbose_name='CST/CSOSN'),
        ),
        migrations.CreateModel(
            name='FiscalAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('entity_name', models.CharField(max_length=120, verbose_name='entidade')),
                ('object_id', models.CharField(max_length=80, verbose_name='objeto')),
                ('action', models.CharField(max_length=80, verbose_name='ação')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='detalhes')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'auditoria fiscal',
                'verbose_name_plural': 'auditorias fiscais',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'entity_name', 'object_id'], name='fiscal_fisc_tenant__b12621_idx'), models.Index(fields=['tenant', 'action'], name='fiscal_fisc_tenant__848e2c_idx'), models.Index(fields=['created_at'], name='fiscal_fisc_created_5284e4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fiscalcompany',
            index=models.Index(fields=['tenant', 'tax_regime', 'is_active'], name='fiscal_fisc_tenant__47c6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalcompany',
            index=models.Index(fields=['document'], name='fiscal_fisc_documen_988437_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalcompany',
            index=models.Index(fields=['state', 'city'], name='fiscal_fisc_state_d61015_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalcompany',
            constraint=models.UniqueConstraint(fields=('tenant', 'document'), name='unique_tenant_fiscal_company_document'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['tenant', 'document_type', 'status'], name='fiscal_fisc_tenant__b62907_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['tenant', 'operation_type'], name='fiscal_fisc_tenant__1a333e_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['tenant', 'issue_date'], name='fiscal_fisc_tenant__07985a_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['tenant', 'partner'], name='fiscal_fisc_tenant__410f71_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['number', 'series'], name='fiscal_fisc_number_81875a_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.UniqueConstraint(fields=('tenant', 'document_type', 'number', 'series', 'partner'), name='unique_tenant_fiscal_document_number'),
        ),
        migrations.AddIndex(
            model_name='fiscalbookentry',
            index=models.Index(fields=['tenant', 'book_type', 'entry_date'], name='fiscal_fisc_tenant__ef8b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalbookentry',
            index=models.Index(fields=['tenant', 'document'], name='fiscal_fisc_tenant__e5ac59_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalbookentry',
            constraint=models.UniqueConstraint(fields=('tenant', 'document', 'book_type'), name='unique_tenant_document_book_entry'),
        ),
        migrations.AddIndex(
            model_name='fiscalmunicipality',
            index=models.Index(fields=['tenant', 'state', 'is_active'], name='fiscal_fisc_tenant__a3382e_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalmunicipality',
            index=models.Index(fields=['ibge_code'], name='fiscal_fisc_ibge_co_559dca_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalmunicipality',
            constraint=models.UniqueConstraint(fields=('tenant', 'ibge_code'), name='unique_tenant_fiscal_municipality_ibge'),
        ),
        migrations.AddIndex(
            model_name='fiscalncm',
            index=models.Index(fields=['tenant', 'is_active'], name='fiscal_fisc_tenant__9b580f_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalncm',
            index=models.Index(fields=['code'], name='fiscal_fisc_code_90ff79_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalncm',
            index=models.Index(fields=['cest'], name='fiscal_fisc_cest_bca12f_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalncm',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_fiscal_ncm_code'),
        ),
        migrations.AddIndex(
            model_name='fiscalobligation',
            index=models.Index(fields=['tenant', 'status', 'due_date'], name='fiscal_fisc_tenant__6cb91d_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalobligation',
            index=models.Index(fields=['tenant', 'obligation_type'], name='fiscal_fisc_tenant__939444_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalobligation',
            constraint=models.UniqueConstraint(fields=('tenant', 'obligation_type', 'period_year', 'period_month'), name='unique_tenant_fiscal_obligation_period'),
        ),
        migrations.AddIndex(
            model_name='fiscaloperationcode',
            index=models.Index(fields=['tenant', 'direction', 'is_active'], name='fiscal_fisc_tenant__df2c14_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaloperationcode',
            index=models.Index(fields=['code'], name='fiscal_fisc_code_b273bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscaloperationcode',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_cfop_code'),
        ),
        migrations.AddIndex(
            model_name='fiscalunit',
            index=models.Index(fields=['tenant', 'is_active'], name='fiscal_fisc_tenant__e9fa87_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalunit',
            index=models.Index(fields=['code'], name='fiscal_fisc_code_4d9e8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalunit',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_fiscal_unit_code'),
        ),
        migrations.AddIndex(
            model_name='taxassessmentperiod',
            index=models.Index(fields=['tenant', 'period_year', 'period_month'], name='fiscal_taxa_tenant__107914_idx'),
        ),
        migrations.AddIndex(
            model_name='taxassessmentperiod',
            index=models.Index(fields=['tenant', 'tax_kind', 'status'], name='fiscal_taxa_tenant__93d00a_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxassessmentperiod',
            constraint=models.UniqueConstraint(fields=('tenant', 'period_year', 'period_month', 'tax_kind'), name='unique_tenant_tax_assessment_period'),
        ),
        migrations.AddIndex(
            model_name='fiscaltax',
            index=models.Index(fields=['tenant', 'document', 'tax_kind'], name='fiscal_fisc_tenant__196dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaltax',
            index=models.Index(fields=['tenant', 'tax_kind', 'is_retained'], name='fiscal_fisc_tenant__7ea5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaltax',
            index=models.Index(fields=['tenant', 'item'], name='fiscal_fisc_tenant__8abf4e_idx'),
        ),
        migrations.AddIndex(
            model_name='taxsituation',
            index=models.Index(fields=['tenant', 'tax_kind', 'is_active'], name='fiscal_taxs_tenant__5ed59c_idx'),
        ),
        migrations.AddIndex(
            model_name='taxsituation',
            index=models.Index(fields=['code'], name='fiscal_taxs_code_97ac63_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxsituation',
            constraint=models.UniqueConstraint(fields=('tenant', 'tax_kind', 'regime_kind', 'code'), name='unique_tenant_tax_situation'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['tenant', 'tax_kind', 'status'], name='fiscal_taxr_tenant__32abae_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['tenant', 'ncm', 'cfop'], name='fiscal_taxr_tenant__55d187_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['tenant', 'effective_from', 'effective_to'], name='fiscal_taxr_tenant__3c97ce_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentitem',
            index=models.Index(fields=['tenant', 'document'], name='fiscal_fisc_tenant__ef99d5_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentitem',
            index=models.Index(fields=['tenant', 'product'], name='fiscal_fisc_tenant__701362_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentitem',
            index=models.Index(fields=['tenant', 'ncm', 'cfop'], name='fiscal_fisc_tenant__7641ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocumentitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'document', 'line_number'), name='unique_tenant_fiscal_document_line'),
        ),
    ]
