# Generated by Django 6.0.7 on 2026-07-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalcompany',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='município normalizado'),
        ),
        migrations.AddField(
            model_name='fiscalcompany',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF normalizada'),
        ),
        migrations.AddField(
            model_name='fiscalmunicipality',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='município normalizado'),
        ),
        migrations.AddField(
            model_name='fiscalmunicipality',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF normalizada'),
        ),
    ]
