# Generated by Django 6.0.7 on 2026-07-10 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_protectedfile_encrypted_at_and_more'),
        ('finance', '0001_initial'),
        ('fiscal', '0002_fiscalcompany_city_ref_fiscalcompany_state_ref_and_more'),
        ('masters', '0002_businesspartner_city_ref_businesspartner_state_ref'),
        ('procurement', '0002_purchaseorder_currency_ref_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='destinatário')),
                ('subject', models.CharField(max_length=255, verbose_name='assunto')),
                ('body', models.TextField(verbose_name='corpo')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='scheduled', max_length=24, verbose_name='status')),
                ('scheduled_at', models.DateTimeField(verbose_name='agendado para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='falhou em')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('last_error', models.TextField(blank=True, verbose_name='último erro')),
            ],
            options={
                'verbose_name': 'envio de NF-e por e-mail',
                'verbose_name_plural': 'envios de NF-e por e-mail',
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiscalEmissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('event_type', models.CharField(choices=[('validation_failed', 'Validação falhou'), ('sent', 'Transmitida'), ('authorized', 'Autorizada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada'), ('status_checked', 'Status consultado'), ('email_scheduled', 'E-mail agendado'), ('email_sent', 'E-mail enviado'), ('email_failed', 'E-mail falhou'), ('error', 'Erro')], max_length=40, verbose_name='tipo de evento')),
                ('provider', models.CharField(blank=True, max_length=80, verbose_name='provedor')),
                ('status', models.CharField(blank=True, max_length=40, verbose_name='status externo')),
                ('access_key', models.CharField(blank=True, max_length=64, verbose_name='chave de acesso')),
                ('protocol', models.CharField(blank=True, max_length=80, verbose_name='protocolo')),
                ('message', models.TextField(blank=True, verbose_name='mensagem')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='contexto seguro')),
            ],
            options={
                'verbose_name': 'evento de emissão fiscal',
                'verbose_name_plural': 'eventos de emissão fiscal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='fiscaldocument',
            options={'ordering': ['-issue_date', 'number'], 'permissions': [('issue_fiscaldocument', 'Pode emitir NF-e'), ('cancel_fiscaldocument', 'Pode cancelar NF-e'), ('send_email_fiscaldocument', 'Pode enviar NF-e por e-mail'), ('download_fiscaldocument', 'Pode baixar XML/DANFE fiscal')], 'verbose_name': 'documento fiscal', 'verbose_name_plural': 'documentos fiscais'},
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='access_key',
            field=models.CharField(blank=True, max_length=64, verbose_name='chave de acesso'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='authorization_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='autorizada em'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='authorization_protocol',
            field=models.CharField(blank=True, max_length=80, verbose_name='protocolo de autorização'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='cancel_protocol',
            field=models.CharField(blank=True, max_length=80, verbose_name='protocolo de cancelamento'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancelada em'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='electronic_model',
            field=models.CharField(choices=[('55', 'NF-e modelo 55')], default='55', max_length=4, verbose_name='modelo eletrônico'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='emission_status',
            field=models.CharField(choices=[('not_sent', 'Não enviada'), ('validating', 'Validando'), ('sent', 'Transmitida'), ('authorized', 'Autorizada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada'), ('error', 'Erro')], default='not_sent', max_length=24, verbose_name='status de emissão'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='environment',
            field=models.CharField(choices=[('homologation', 'Homologação'), ('production', 'Produção')], default='homologation', max_length=24, verbose_name='ambiente fiscal'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='rejection_code',
            field=models.CharField(blank=True, max_length=24, verbose_name='código de rejeição'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='motivo de rejeição'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['tenant', 'emission_status'], name='fiscal_fisc_tenant__bc01fd_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['access_key'], name='fiscal_fisc_access__fee9d3_idx'),
        ),
        migrations.AddField(
            model_name='fiscalemaildelivery',
            name='danfe_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_danfe_email_deliveries', to='files.protectedfile', verbose_name='DANFE protegido'),
        ),
        migrations.AddField(
            model_name='fiscalemaildelivery',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_deliveries', to='fiscal.fiscaldocument', verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='fiscalemaildelivery',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_fiscal_email_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por'),
        ),
        migrations.AddField(
            model_name='fiscalemaildelivery',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='fiscalemaildelivery',
            name='xml_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_xml_email_deliveries', to='files.protectedfile', verbose_name='XML protegido'),
        ),
        migrations.AddField(
            model_name='fiscalemissionevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_emission_events', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='fiscalemissionevent',
            name='danfe_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_danfe_emission_events', to='files.protectedfile', verbose_name='DANFE protegido'),
        ),
        migrations.AddField(
            model_name='fiscalemissionevent',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_events', to='fiscal.fiscaldocument', verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='fiscalemissionevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='fiscalemissionevent',
            name='xml_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_xml_emission_events', to='files.protectedfile', verbose_name='XML protegido'),
        ),
        migrations.AddIndex(
            model_name='fiscalemaildelivery',
            index=models.Index(fields=['tenant', 'document', 'status'], name='fiscal_fisc_tenant__f8d9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalemaildelivery',
            index=models.Index(fields=['tenant', 'status', 'scheduled_at'], name='fiscal_fisc_tenant__8376db_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalemaildelivery',
            index=models.Index(fields=['recipient_email'], name='fiscal_fisc_recipie_8458ed_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalemissionevent',
            index=models.Index(fields=['tenant', 'document', 'event_type'], name='fiscal_fisc_tenant__9534f4_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalemissionevent',
            index=models.Index(fields=['tenant', 'event_type', 'created_at'], name='fiscal_fisc_tenant__2eb58e_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalemissionevent',
            index=models.Index(fields=['access_key'], name='fiscal_fisc_access__d889b2_idx'),
        ),
    ]
