# Generated by Django 6.0.7 on 2026-07-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_fiscalemaildelivery_fiscalemissionevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalcompany',
            name='complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='fiscalcompany',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=120, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='fiscalcompany',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='logradouro'),
        ),
        migrations.AddField(
            model_name='fiscalcompany',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='fiscalcompany',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP'),
        ),
    ]
