# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('files', '0004_remove_protectedfile_unique_tenant_protected_file_number_and_more'),
        ('finance', '0002_remove_chartofaccount_unique_tenant_chart_account_code_and_more'),
        ('fiscal', '0004_add_zipcode_and_address'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('procurement', '0004_remove_purchaseorder_unique_tenant_purchase_order_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fiscalbookentry',
            name='unique_tenant_document_book_entry',
        ),
        migrations.RemoveConstraint(
            model_name='fiscalcompany',
            name='unique_tenant_fiscal_company_document',
        ),
        migrations.RemoveConstraint(
            model_name='fiscaldocument',
            name='unique_tenant_fiscal_document_number',
        ),
        migrations.RemoveConstraint(
            model_name='fiscaldocumentitem',
            name='unique_tenant_fiscal_document_line',
        ),
        migrations.RemoveConstraint(
            model_name='fiscalmunicipality',
            name='unique_tenant_fiscal_municipality_ibge',
        ),
        migrations.RemoveConstraint(
            model_name='fiscalncm',
            name='unique_tenant_fiscal_ncm_code',
        ),
        migrations.RemoveConstraint(
            model_name='fiscalobligation',
            name='unique_tenant_fiscal_obligation_period',
        ),
        migrations.RemoveConstraint(
            model_name='fiscaloperationcode',
            name='unique_tenant_cfop_code',
        ),
        migrations.RemoveConstraint(
            model_name='fiscalunit',
            name='unique_tenant_fiscal_unit_code',
        ),
        migrations.RemoveConstraint(
            model_name='taxassessmentperiod',
            name='unique_tenant_tax_assessment_period',
        ),
        migrations.RemoveConstraint(
            model_name='taxsituation',
            name='unique_tenant_tax_situation',
        ),
        migrations.RemoveIndex(
            model_name='fiscalaudittrail',
            name='fiscal_fisc_tenant__b12621_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalaudittrail',
            name='fiscal_fisc_tenant__848e2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalbookentry',
            name='fiscal_fisc_tenant__ef8b0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalbookentry',
            name='fiscal_fisc_tenant__e5ac59_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalcompany',
            name='fiscal_fisc_tenant__47c6f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscaldocument',
            name='fiscal_fisc_tenant__b62907_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscaldocument',
            name='fiscal_fisc_tenant__1a333e_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscaldocument',
            name='fiscal_fisc_tenant__07985a_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscaldocument',
            name='fiscal_fisc_tenant__410f71_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscaldocument',
            name='fiscal_fisc_tenant__bc01fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscaldocumentitem',
            name='fiscal_fisc_tenant__ef99d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscaldocumentitem',
            name='fiscal_fisc_tenant__701362_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscaldocumentitem',
            name='fiscal_fisc_tenant__7641ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalemaildelivery',
            name='fiscal_fisc_tenant__f8d9a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalemaildelivery',
            name='fiscal_fisc_tenant__8376db_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalemissionevent',
            name='fiscal_fisc_tenant__9534f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalemissionevent',
            name='fiscal_fisc_tenant__2eb58e_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalmunicipality',
            name='fiscal_fisc_tenant__a3382e_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalncm',
            name='fiscal_fisc_tenant__9b580f_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalobligation',
            name='fiscal_fisc_tenant__6cb91d_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalobligation',
            name='fiscal_fisc_tenant__939444_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscaloperationcode',
            name='fiscal_fisc_tenant__df2c14_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscaltax',
            name='fiscal_fisc_tenant__196dd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscaltax',
            name='fiscal_fisc_tenant__7ea5bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscaltax',
            name='fiscal_fisc_tenant__8abf4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalunit',
            name='fiscal_fisc_tenant__e9fa87_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxassessmentperiod',
            name='fiscal_taxa_tenant__107914_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxassessmentperiod',
            name='fiscal_taxa_tenant__93d00a_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxrule',
            name='fiscal_taxr_tenant__32abae_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxrule',
            name='fiscal_taxr_tenant__55d187_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxrule',
            name='fiscal_taxr_tenant__3c97ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxsituation',
            name='fiscal_taxs_tenant__5ed59c_idx',
        ),
        migrations.RemoveField(
            model_name='fiscalaudittrail',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fiscalbookentry',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fiscalcompany',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fiscaldocument',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fiscaldocumentitem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fiscalemaildelivery',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fiscalemissionevent',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fiscalmunicipality',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fiscalncm',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fiscalobligation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fiscaloperationcode',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fiscaltax',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fiscalunit',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='taxassessmentperiod',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='taxrule',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='taxsituation',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='fiscalaudittrail',
            index=models.Index(fields=['entity_name', 'object_id'], name='fiscal_fisc_entity__bbe6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalaudittrail',
            index=models.Index(fields=['action'], name='fiscal_fisc_action_ea345c_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalbookentry',
            index=models.Index(fields=['book_type', 'entry_date'], name='fiscal_fisc_book_ty_ba3328_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalbookentry',
            index=models.Index(fields=['document'], name='fiscal_fisc_documen_13020c_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalcompany',
            index=models.Index(fields=['tax_regime', 'is_active'], name='fiscal_fisc_tax_reg_9c709d_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['document_type', 'status'], name='fiscal_fisc_documen_43b6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['operation_type'], name='fiscal_fisc_operati_8bd1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['emission_status'], name='fiscal_fisc_emissio_e3f96b_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['issue_date'], name='fiscal_fisc_issue_d_39b193_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['partner'], name='fiscal_fisc_partner_2949e8_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentitem',
            index=models.Index(fields=['document'], name='fiscal_fisc_documen_3222ad_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentitem',
            index=models.Index(fields=['product'], name='fiscal_fisc_product_18bcf5_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentitem',
            index=models.Index(fields=['ncm', 'cfop'], name='fiscal_fisc_ncm_id_53a067_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalemaildelivery',
            index=models.Index(fields=['document', 'status'], name='fiscal_fisc_documen_5de1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalemaildelivery',
            index=models.Index(fields=['status', 'scheduled_at'], name='fiscal_fisc_status_142e51_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalemissionevent',
            index=models.Index(fields=['document', 'event_type'], name='fiscal_fisc_documen_281373_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalemissionevent',
            index=models.Index(fields=['event_type', 'created_at'], name='fiscal_fisc_event_t_c17539_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalmunicipality',
            index=models.Index(fields=['state', 'is_active'], name='fiscal_fisc_state_c1867c_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalncm',
            index=models.Index(fields=['is_active'], name='fiscal_fisc_is_acti_977c14_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalobligation',
            index=models.Index(fields=['status', 'due_date'], name='fiscal_fisc_status_6f8b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalobligation',
            index=models.Index(fields=['obligation_type'], name='fiscal_fisc_obligat_63a2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaloperationcode',
            index=models.Index(fields=['direction', 'is_active'], name='fiscal_fisc_directi_739ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaltax',
            index=models.Index(fields=['document', 'tax_kind'], name='fiscal_fisc_documen_85eebe_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaltax',
            index=models.Index(fields=['tax_kind', 'is_retained'], name='fiscal_fisc_tax_kin_bc6ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaltax',
            index=models.Index(fields=['item'], name='fiscal_fisc_item_id_04db05_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalunit',
            index=models.Index(fields=['is_active'], name='fiscal_fisc_is_acti_7cc920_idx'),
        ),
        migrations.AddIndex(
            model_name='taxassessmentperiod',
            index=models.Index(fields=['period_year', 'period_month'], name='fiscal_taxa_period__3570a2_idx'),
        ),
        migrations.AddIndex(
            model_name='taxassessmentperiod',
            index=models.Index(fields=['tax_kind', 'status'], name='fiscal_taxa_tax_kin_91bb41_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['tax_kind', 'status'], name='fiscal_taxr_tax_kin_d27d16_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['ncm', 'cfop'], name='fiscal_taxr_ncm_id_b935d9_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['effective_from', 'effective_to'], name='fiscal_taxr_effecti_23262f_idx'),
        ),
        migrations.AddIndex(
            model_name='taxsituation',
            index=models.Index(fields=['tax_kind', 'is_active'], name='fiscal_taxs_tax_kin_a2c5de_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalbookentry',
            constraint=models.UniqueConstraint(fields=('document', 'book_type'), name='unique_document_book_entry'),
        ),
        migrations.AddConstraint(
            model_name='fiscalcompany',
            constraint=models.UniqueConstraint(fields=('document',), name='unique_fiscal_company_document'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.UniqueConstraint(fields=('document_type', 'number', 'series', 'partner'), name='unique_fiscal_document_number'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocumentitem',
            constraint=models.UniqueConstraint(fields=('document', 'line_number'), name='unique_fiscal_document_line'),
        ),
        migrations.AddConstraint(
            model_name='fiscalmunicipality',
            constraint=models.UniqueConstraint(fields=('ibge_code',), name='unique_fiscal_municipality_ibge'),
        ),
        migrations.AddConstraint(
            model_name='fiscalncm',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_fiscal_ncm_code'),
        ),
        migrations.AddConstraint(
            model_name='fiscalobligation',
            constraint=models.UniqueConstraint(fields=('obligation_type', 'period_year', 'period_month'), name='unique_fiscal_obligation_period'),
        ),
        migrations.AddConstraint(
            model_name='fiscaloperationcode',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_cfop_code'),
        ),
        migrations.AddConstraint(
            model_name='fiscalunit',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_fiscal_unit_code'),
        ),
        migrations.AddConstraint(
            model_name='taxassessmentperiod',
            constraint=models.UniqueConstraint(fields=('period_year', 'period_month', 'tax_kind'), name='unique_tax_assessment_period'),
        ),
        migrations.AddConstraint(
            model_name='taxsituation',
            constraint=models.UniqueConstraint(fields=('tax_kind', 'regime_kind', 'code'), name='unique_tax_situation'),
        ),
    ]
