# Generated by Django 5.2.16 on 2026-07-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('fiscal', '0005_remove_fiscalbookentry_unique_tenant_document_book_entry_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fiscalcompany',
            name='fiscal_fisc_state_d61015_idx',
        ),
        migrations.RemoveIndex(
            model_name='fiscalmunicipality',
            name='fiscal_fisc_state_c1867c_idx',
        ),
        migrations.AlterField(
            model_name='fiscalcompany',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='município'),
        ),
        migrations.AlterField(
            model_name='fiscalcompany',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='fiscalmunicipality',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='município'),
        ),
        migrations.AlterField(
            model_name='fiscalmunicipality',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddIndex(
            model_name='fiscalcompany',
            index=models.Index(fields=['state_ref', 'city_ref'], name='fiscal_fisc_state_r_16b628_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalmunicipality',
            index=models.Index(fields=['state_ref', 'is_active'], name='fiscal_fisc_state_r_930220_idx'),
        ),
    ]
