# Generated by Django 5.2.16 on 2026-07-22 17:34

import django.db.models.deletion
from django.db import migrations, models


def validate_legacy_location(apps, schema_editor):
    checks = (
        ('FiscalCompany', 'city', 'city_ref'),
        ('FiscalCompany', 'state', 'state_ref'),
        ('FiscalMunicipality', 'state', 'state_ref'),
    )
    invalid_locations = []

    for model_name, legacy_field, normalized_field in checks:
        model = apps.get_model('fiscal', model_name)
        has_unmigrated_location = (
            model.objects.filter(
                **{
                    f'{legacy_field}__isnull': False,
                    f'{normalized_field}__isnull': True,
                }
            )
            .exclude(**{legacy_field: ''})
            .exists()
        )
        if has_unmigrated_location:
            invalid_locations.append(f'{model_name}.{legacy_field}')

    if invalid_locations:
        raise RuntimeError(
            'Preencha as referências normalizadas antes de remover os campos legados: '
            + ', '.join(invalid_locations)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('fiscal', '0006_remove_fiscalcompany_fiscal_fisc_state_d61015_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalmunicipality',
            options={'ordering': ['state_ref__name', 'name'], 'verbose_name': 'município fiscal', 'verbose_name_plural': 'municípios fiscais'},
        ),
        migrations.RunPython(validate_legacy_location, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='fiscalcompany',
            name='city',
        ),
        migrations.RemoveField(
            model_name='fiscalcompany',
            name='state',
        ),
        migrations.RemoveField(
            model_name='fiscalmunicipality',
            name='state',
        ),
        migrations.AlterField(
            model_name='fiscalcompany',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='fiscalcompany',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='fiscalmunicipality',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='fiscalmunicipality',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF'),
        ),
    ]
