# Generated by Django 5.2.16 on 2026-07-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0006_stateprovince_country'),
        ('fiscal', '0007_alter_fiscalmunicipality_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalcompany',
            name='country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliary.country', verbose_name='país'),
        ),
        migrations.AddField(
            model_name='fiscalmunicipality',
            name='country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliary.country', verbose_name='país'),
        ),
    ]
