# Generated by Django 6.0.8 on 2026-08-25 17:08

import base.sequences
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('document_type', models.CharField(choices=[('sop', 'POP'), ('work_instruction', 'Instrução de trabalho'), ('specification', 'Especificação'), ('method', 'Método'), ('protocol', 'Protocolo'), ('report', 'Relatório'), ('form', 'Formulário'), ('record', 'Registro'), ('policy', 'Política'), ('manual', 'Manual'), ('dossier', 'Dossiê')], max_length=32, verbose_name='tipo')),
                ('code', models.CharField(blank=True, max_length=80, verbose_name='código')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('area', models.CharField(max_length=120, verbose_name='área')),
                ('version', models.CharField(default='1.0', max_length=40, verbose_name='versão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('reviewed', 'Revisado'), ('approved', 'Aprovado'), ('published', 'Publicado'), ('obsolete', 'Obsoleto'), ('cancelled', 'Cancelado'), ('archived', 'Arquivado')], default='draft', max_length=24, verbose_name='status')),
                ('effective_from', models.DateField(verbose_name='vigência inicial')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('content', models.TextField(blank=True, verbose_name='conteúdo')),
                ('change_summary', models.TextField(verbose_name='histórico/justificativa da versão')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submetido em')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisado em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('obsoleted_at', models.DateTimeField(blank=True, null=True, verbose_name='obsoletado em')),
                ('obsolete_reason', models.TextField(blank=True, verbose_name='motivo da obsolescência')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='arquivado em')),
                ('archive_reason', models.TextField(blank=True, verbose_name='motivo do arquivamento')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_controlled_documents', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_controlled_documents', to=settings.AUTH_USER_MODEL, verbose_name='arquivado por')),
                ('area_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.businessarea', verbose_name='área normalizada')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_controlled_documents', to=settings.AUTH_USER_MODEL, verbose_name='cancelado por')),
                ('obsoleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obsoleted_controlled_documents', to=settings.AUTH_USER_MODEL, verbose_name='obsoletado por')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_controlled_documents', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_controlled_documents', to=settings.AUTH_USER_MODEL, verbose_name='publicado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_controlled_documents', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_controlled_documents', to=settings.AUTH_USER_MODEL, verbose_name='submetido por')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='documents.controlleddocument', verbose_name='substitui')),
            ],
            options={
                'verbose_name': 'documento controlado',
                'verbose_name_plural': 'documentos controlados',
                'ordering': ['code', '-created_at'],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(choices=[('reviewer', 'Revisor'), ('approver', 'Aprovador')], max_length=24, verbose_name='papel')),
                ('decision', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=24, verbose_name='decisão')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidido em')),
                ('comments', models.TextField(blank=True, verbose_name='comentários')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='documents.controlleddocument', verbose_name='documento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_approvals', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'aprovação documental',
                'verbose_name_plural': 'aprovações documentais',
                'ordering': ['document__code', 'role', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('file_name', models.CharField(max_length=180, verbose_name='arquivo')),
                ('file_reference', models.CharField(max_length=255, verbose_name='referência do arquivo')),
                ('content_hash', models.CharField(max_length=128, verbose_name='hash do conteúdo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.controlleddocument', verbose_name='documento')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_document_attachments', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'anexo documental',
                'verbose_name_plural': 'anexos documentais',
                'ordering': ['document__code', 'file_name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('action', models.CharField(choices=[('created', 'Criado'), ('submitted', 'Submetido'), ('reviewed', 'Revisado'), ('approved', 'Aprovado'), ('published', 'Publicado'), ('obsoleted', 'Obsoletado'), ('cancelled', 'Cancelado'), ('archived', 'Arquivado'), ('revision_created', 'Nova revisão criada'), ('read_confirmed', 'Leitura confirmada')], max_length=32, verbose_name='ação')),
                ('reason', models.TextField(blank=True, verbose_name='justificativa')),
                ('snapshot', models.TextField(verbose_name='registro congelado')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='ator')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_trail', to='documents.controlleddocument', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'trilha de auditoria documental',
                'verbose_name_plural': 'trilhas de auditoria documentais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='prazo de leitura')),
                ('status', models.CharField(choices=[('assigned', 'Distribuído'), ('confirmed', 'Leitura confirmada'), ('overdue', 'Vencido'), ('cancelled', 'Cancelado')], default='assigned', max_length=24, verbose_name='status')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('confirmation_text', models.TextField(blank=True, verbose_name='texto da confirmação')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_document_distributions', to=settings.AUTH_USER_MODEL, verbose_name='confirmado por')),
                ('distributed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_document_distributions', to=settings.AUTH_USER_MODEL, verbose_name='distribuído por')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='documents.controlleddocument', verbose_name='documento')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_distributions', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
            ],
            options={
                'verbose_name': 'distribuição documental',
                'verbose_name_plural': 'distribuições documentais',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('relationship_type', models.CharField(choices=[('references', 'Referencia'), ('supersedes', 'Substitui'), ('impacts', 'Impacta'), ('supports', 'Suporta'), ('replaces', 'Troca')], max_length=24, verbose_name='tipo de relação')),
                ('external_reference', models.CharField(blank=True, max_length=120, verbose_name='referência externa')),
                ('rationale', models.TextField(blank=True, verbose_name='justificativa')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relationships', to='documents.controlleddocument', verbose_name='documento relacionado')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='documents.controlleddocument', verbose_name='documento origem')),
            ],
            options={
                'verbose_name': 'relacionamento documental',
                'verbose_name_plural': 'relacionamentos documentais',
                'ordering': ['source_document__code', 'relationship_type'],
            },
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['document_type', 'status'], name='documents_c_documen_4b423f_idx'),
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['code'], name='documents_c_code_c583db_idx'),
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['area'], name='documents_c_area_a3409e_idx'),
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['effective_from', 'valid_until'], name='documents_c_effecti_c94c3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='controlleddocument',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_document_code_version'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['document', 'role', 'decision'], name='documents_d_documen_f890b3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['user'], name='documents_d_user_id_f2cb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['document'], name='documents_d_documen_9e5dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['content_hash'], name='documents_d_content_e275ec_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaudittrail',
            index=models.Index(fields=['document', 'action'], name='documents_d_documen_f63b19_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaudittrail',
            index=models.Index(fields=['actor'], name='documents_d_actor_i_c481d5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaudittrail',
            index=models.Index(fields=['created_at'], name='documents_d_created_2e09a6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdistribution',
            index=models.Index(fields=['document', 'status'], name='documents_d_documen_fa8f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdistribution',
            index=models.Index(fields=['recipient', 'status'], name='documents_d_recipie_aa9d46_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdistribution',
            index=models.Index(fields=['due_date'], name='documents_d_due_dat_4e7752_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentdistribution',
            constraint=models.UniqueConstraint(fields=('document', 'recipient'), name='unique_document_distribution_recipient'),
        ),
        migrations.AddIndex(
            model_name='documentrelationship',
            index=models.Index(fields=['source_document', 'relationship_type'], name='documents_d_source__5f8b04_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrelationship',
            index=models.Index(fields=['related_document'], name='documents_d_related_f47d4a_idx'),
        ),
    ]
