# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('documents', '0002_controlleddocument_area_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='controlleddocument',
            name='unique_tenant_document_code_version',
        ),
        migrations.RemoveConstraint(
            model_name='documentdistribution',
            name='unique_tenant_document_distribution_recipient',
        ),
        migrations.RemoveIndex(
            model_name='controlleddocument',
            name='documents_c_tenant__211a46_idx',
        ),
        migrations.RemoveIndex(
            model_name='controlleddocument',
            name='documents_c_tenant__c7a232_idx',
        ),
        migrations.RemoveIndex(
            model_name='controlleddocument',
            name='documents_c_tenant__a751c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='controlleddocument',
            name='documents_c_tenant__0b276e_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentapproval',
            name='documents_d_tenant__5c69b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentapproval',
            name='documents_d_tenant__c3117f_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentattachment',
            name='documents_d_tenant__1bcabc_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentaudittrail',
            name='documents_d_tenant__66d470_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentaudittrail',
            name='documents_d_tenant__cf0d0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentdistribution',
            name='documents_d_tenant__0d3776_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentdistribution',
            name='documents_d_tenant__92c1e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentdistribution',
            name='documents_d_tenant__d103a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentrelationship',
            name='documents_d_tenant__31aafc_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentrelationship',
            name='documents_d_tenant__068b03_idx',
        ),
        migrations.RemoveField(
            model_name='controlleddocument',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='documentapproval',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='documentattachment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='documentaudittrail',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='documentdistribution',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='documentrelationship',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['document_type', 'status'], name='documents_c_documen_4b423f_idx'),
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['code'], name='documents_c_code_c583db_idx'),
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['area'], name='documents_c_area_a3409e_idx'),
        ),
        migrations.AddIndex(
            model_name='controlleddocument',
            index=models.Index(fields=['effective_from', 'valid_until'], name='documents_c_effecti_c94c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['document', 'role', 'decision'], name='documents_d_documen_f890b3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['user'], name='documents_d_user_id_f2cb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['document'], name='documents_d_documen_9e5dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaudittrail',
            index=models.Index(fields=['document', 'action'], name='documents_d_documen_f63b19_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaudittrail',
            index=models.Index(fields=['actor'], name='documents_d_actor_i_c481d5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdistribution',
            index=models.Index(fields=['document', 'status'], name='documents_d_documen_fa8f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdistribution',
            index=models.Index(fields=['recipient', 'status'], name='documents_d_recipie_aa9d46_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdistribution',
            index=models.Index(fields=['due_date'], name='documents_d_due_dat_4e7752_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrelationship',
            index=models.Index(fields=['source_document', 'relationship_type'], name='documents_d_source__5f8b04_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrelationship',
            index=models.Index(fields=['related_document'], name='documents_d_related_f47d4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='controlleddocument',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_document_code_version'),
        ),
        migrations.AddConstraint(
            model_name='documentdistribution',
            constraint=models.UniqueConstraint(fields=('document', 'recipient'), name='unique_document_distribution_recipient'),
        ),
    ]
