# Generated by Django 5.2.16 on 2026-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_controlleddocument_unique_tenant_document_code_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlleddocument',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
    ]
