# Generated by Django 6.0.8 on 2026-08-25 17:08

import base.sequences
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('batch_size', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='tamanho do lote')),
                ('expected_yield_percent', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='rendimento esperado (%)')),
                ('material_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo de materiais')),
                ('loss_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='perda (%)')),
                ('labor_hours', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='horas de mão de obra')),
                ('labor_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='taxa de mão de obra')),
                ('machine_hours', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='horas máquina')),
                ('machine_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='taxa máquina')),
                ('third_party_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo terceiros')),
                ('analysis_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo análises')),
                ('overhead_rate_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='overhead (%)')),
                ('indirect_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo indireto')),
                ('tax_rate_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='impostos (%)')),
                ('capacity_factor_percent', models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=7, verbose_name='fator de capacidade (%)')),
                ('simulated_total_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo simulado total')),
                ('simulated_unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo simulado unitário')),
                ('assumptions', models.TextField(blank=True, verbose_name='premissas')),
            ],
            options={
                'verbose_name': 'simulação de custo',
                'verbose_name_plural': 'simulações de custo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyCostClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='mês')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('validated', 'Validado'), ('closed', 'Fechado'), ('reopened', 'Reaberto')], default='open', max_length=24, verbose_name='status')),
                ('validation_notes', models.TextField(blank=True, verbose_name='observações de validação')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechado em')),
            ],
            options={
                'verbose_name': 'fechamento mensal de custo',
                'verbose_name_plural': 'fechamentos mensais de custo',
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='ProductionCostCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('period_start', models.DateField(verbose_name='início do período')),
                ('period_end', models.DateField(verbose_name='fim do período')),
                ('planned_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo planejado')),
                ('actual_material_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='material real')),
                ('actual_loss_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='perda real')),
                ('actual_labor_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='mão de obra real')),
                ('actual_machine_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='máquina real')),
                ('actual_third_party_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='terceiros real')),
                ('actual_analysis_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='análises real')),
                ('actual_overhead_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='overhead real')),
                ('actual_indirect_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='indireto real')),
                ('non_quality_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo de não qualidade')),
                ('rework_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo de retrabalho')),
                ('total_actual_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo real total')),
                ('variance_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='variação')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'captura de custo de produção',
                'verbose_name_plural': 'capturas de custo de produção',
                'ordering': ['-period_start', 'production_order__order_number'],
            },
        ),
        migrations.CreateModel(
            name='StandardCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('version', models.CharField(max_length=40, verbose_name='versão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('obsolete', 'Obsoleto')], default='draft', max_length=24, verbose_name='status')),
                ('effective_from', models.DateField(verbose_name='vigente a partir de')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='vigente até')),
                ('standard_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade padrão')),
                ('material_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo material')),
                ('loss_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo perdas')),
                ('labor_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo mão de obra')),
                ('machine_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo máquina')),
                ('third_party_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo terceiros')),
                ('analysis_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo análises')),
                ('overhead_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo overhead')),
                ('indirect_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo indireto')),
                ('tax_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo impostos')),
                ('total_standard_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo padrão total')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'custo padrão',
                'verbose_name_plural': 'custos padrão',
                'ordering': ['product__code', '-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('category', models.CharField(choices=[('material', 'Material'), ('loss', 'Perda'), ('labor', 'Mão de obra'), ('machine', 'Hora máquina'), ('third_party', 'Terceiros'), ('analysis', 'Análises'), ('overhead', 'Overhead'), ('indirect', 'Indireto'), ('tax', 'Impostos'), ('non_quality', 'Não qualidade')], max_length=32, verbose_name='categoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'elemento de custo',
                'verbose_name_plural': 'elementos de custo',
                'ordering': ['category', 'code'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='costing_cos_categor_0c79c0_idx'), models.Index(fields=['code'], name='costing_cos_code_a416c7_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_cost_element_code')],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CostReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('report_type', models.CharField(choices=[('margin', 'Margem'), ('lot_cost', 'Custo por lote'), ('product_cost', 'Custo por produto'), ('non_quality', 'Não qualidade'), ('deviation_rework', 'Desvios e retrabalho')], max_length=32, verbose_name='tipo de relatório')),
                ('period_start', models.DateField(verbose_name='início do período')),
                ('period_end', models.DateField(verbose_name='fim do período')),
                ('revenue_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='receita')),
                ('cost_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo')),
                ('margin_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='margem')),
                ('margin_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9, verbose_name='margem (%)')),
                ('non_quality_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo de não qualidade')),
                ('deviation_impact', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='impacto de desvios')),
                ('rework_impact', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='impacto de retrabalho')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='gerado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_report_snapshots', to='masters.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'snapshot de relatório de custo',
                'verbose_name_plural': 'snapshots de relatórios de custo',
                'ordering': ['-generated_at'],
            },
        ),
    ]
