# Generated by Django 6.0.7 on 2026-07-07 19:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulations', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        ('production', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('center_type', models.CharField(choices=[('production', 'Produção'), ('quality', 'Qualidade'), ('maintenance', 'Manutenção'), ('administrative', 'Administrativo'), ('warehouse', 'Almoxarifado'), ('overhead', 'Overhead')], max_length=32, verbose_name='tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'centro de custo',
                'verbose_name_plural': 'centros de custo',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CostElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('category', models.CharField(choices=[('material', 'Material'), ('loss', 'Perda'), ('labor', 'Mão de obra'), ('machine', 'Hora máquina'), ('third_party', 'Terceiros'), ('analysis', 'Análises'), ('overhead', 'Overhead'), ('indirect', 'Indireto'), ('tax', 'Impostos'), ('non_quality', 'Não qualidade')], max_length=32, verbose_name='categoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'elemento de custo',
                'verbose_name_plural': 'elementos de custo',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CostReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('report_type', models.CharField(choices=[('margin', 'Margem'), ('lot_cost', 'Custo por lote'), ('product_cost', 'Custo por produto'), ('non_quality', 'Não qualidade'), ('deviation_rework', 'Desvios e retrabalho')], max_length=32, verbose_name='tipo de relatório')),
                ('period_start', models.DateField(verbose_name='início do período')),
                ('period_end', models.DateField(verbose_name='fim do período')),
                ('revenue_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='receita')),
                ('cost_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo')),
                ('margin_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='margem')),
                ('margin_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9, verbose_name='margem (%)')),
                ('non_quality_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo de não qualidade')),
                ('deviation_impact', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='impacto de desvios')),
                ('rework_impact', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='impacto de retrabalho')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='gerado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_report_snapshots', to='masters.product', verbose_name='produto')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_report_snapshots', to='production.productionorder', verbose_name='ordem de produção')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_report_snapshots', to='inventory.stocklot', verbose_name='lote')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'snapshot de relatório de custo',
                'verbose_name_plural': 'snapshots de relatórios de custo',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='CostSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('batch_size', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='tamanho do lote')),
                ('expected_yield_percent', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='rendimento esperado (%)')),
                ('material_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo de materiais')),
                ('loss_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='perda (%)')),
                ('labor_hours', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='horas de mão de obra')),
                ('labor_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='taxa de mão de obra')),
                ('machine_hours', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='horas máquina')),
                ('machine_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='taxa máquina')),
                ('third_party_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo terceiros')),
                ('analysis_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo análises')),
                ('overhead_rate_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='overhead (%)')),
                ('indirect_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo indireto')),
                ('tax_rate_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='impostos (%)')),
                ('capacity_factor_percent', models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=7, verbose_name='fator de capacidade (%)')),
                ('simulated_total_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo simulado total')),
                ('simulated_unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo simulado unitário')),
                ('assumptions', models.TextField(blank=True, verbose_name='premissas')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_simulations', to='costing.costcenter', verbose_name='centro de custo')),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_simulations', to='formulations.masterformula', verbose_name='fórmula')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_simulations', to='masters.product', verbose_name='produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'simulação de custo',
                'verbose_name_plural': 'simulações de custo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyCostClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='mês')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('validated', 'Validado'), ('closed', 'Fechado'), ('reopened', 'Reaberto')], default='open', max_length=24, verbose_name='status')),
                ('validation_notes', models.TextField(blank=True, verbose_name='observações de validação')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechado em')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_cost_periods', to=settings.AUTH_USER_MODEL, verbose_name='fechado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'fechamento mensal de custo',
                'verbose_name_plural': 'fechamentos mensais de custo',
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='ProductionCostCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('period_start', models.DateField(verbose_name='início do período')),
                ('period_end', models.DateField(verbose_name='fim do período')),
                ('planned_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo planejado')),
                ('actual_material_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='material real')),
                ('actual_loss_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='perda real')),
                ('actual_labor_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='mão de obra real')),
                ('actual_machine_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='máquina real')),
                ('actual_third_party_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='terceiros real')),
                ('actual_analysis_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='análises real')),
                ('actual_overhead_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='overhead real')),
                ('actual_indirect_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='indireto real')),
                ('non_quality_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo de não qualidade')),
                ('rework_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo de retrabalho')),
                ('total_actual_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo real total')),
                ('variance_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='variação')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_cost_captures', to='costing.costcenter', verbose_name='centro de custo')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_captures', to='production.productionorder', verbose_name='ordem de produção')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'captura de custo de produção',
                'verbose_name_plural': 'capturas de custo de produção',
                'ordering': ['-period_start', 'production_order__order_number'],
            },
        ),
        migrations.CreateModel(
            name='StandardCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('version', models.CharField(max_length=40, verbose_name='versão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('obsolete', 'Obsoleto')], default='draft', max_length=24, verbose_name='status')),
                ('effective_from', models.DateField(verbose_name='vigente a partir de')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='vigente até')),
                ('standard_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade padrão')),
                ('material_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo material')),
                ('loss_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo perdas')),
                ('labor_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo mão de obra')),
                ('machine_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo máquina')),
                ('third_party_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo terceiros')),
                ('analysis_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo análises')),
                ('overhead_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo overhead')),
                ('indirect_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo indireto')),
                ('tax_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo impostos')),
                ('total_standard_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='custo padrão total')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_standard_costs', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_costs', to='costing.costcenter', verbose_name='centro de custo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_costs', to='masters.product', verbose_name='produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_costs', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'custo padrão',
                'verbose_name_plural': 'custos padrão',
                'ordering': ['product__code', '-effective_from', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['tenant', 'center_type', 'is_active'], name='costing_cos_tenant__2b89cd_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['code'], name='costing_cos_code_587b4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_cost_center_code'),
        ),
        migrations.AddIndex(
            model_name='costelement',
            index=models.Index(fields=['tenant', 'category', 'is_active'], name='costing_cos_tenant__25b902_idx'),
        ),
        migrations.AddIndex(
            model_name='costelement',
            index=models.Index(fields=['code'], name='costing_cos_code_a416c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='costelement',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_cost_element_code'),
        ),
        migrations.AddIndex(
            model_name='costreportsnapshot',
            index=models.Index(fields=['tenant', 'report_type'], name='costing_cos_tenant__ad0cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='costreportsnapshot',
            index=models.Index(fields=['tenant', 'product'], name='costing_cos_tenant__8d7d53_idx'),
        ),
        migrations.AddIndex(
            model_name='costreportsnapshot',
            index=models.Index(fields=['tenant', 'period_start', 'period_end'], name='costing_cos_tenant__5914df_idx'),
        ),
        migrations.AddIndex(
            model_name='costsimulation',
            index=models.Index(fields=['tenant', 'product'], name='costing_cos_tenant__7fc42d_idx'),
        ),
        migrations.AddIndex(
            model_name='costsimulation',
            index=models.Index(fields=['tenant', 'formula'], name='costing_cos_tenant__2b6eba_idx'),
        ),
        migrations.AddIndex(
            model_name='costsimulation',
            index=models.Index(fields=['tenant', 'cost_center'], name='costing_cos_tenant__de86c4_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycostclosing',
            index=models.Index(fields=['tenant', 'status'], name='costing_mon_tenant__5fdb41_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycostclosing',
            index=models.Index(fields=['tenant', 'period_year', 'period_month'], name='costing_mon_tenant__aabc72_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlycostclosing',
            constraint=models.UniqueConstraint(fields=('tenant', 'period_year', 'period_month'), name='unique_tenant_cost_period'),
        ),
        migrations.AddIndex(
            model_name='productioncostcapture',
            index=models.Index(fields=['tenant', 'production_order'], name='costing_pro_tenant__5ddf78_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncostcapture',
            index=models.Index(fields=['tenant', 'cost_center'], name='costing_pro_tenant__d5ef2a_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncostcapture',
            index=models.Index(fields=['tenant', 'period_start', 'period_end'], name='costing_pro_tenant__d4df1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='productioncostcapture',
            constraint=models.UniqueConstraint(fields=('tenant', 'production_order', 'cost_center', 'period_start', 'period_end'), name='unique_tenant_order_center_cost_period'),
        ),
        migrations.AddIndex(
            model_name='standardcost',
            index=models.Index(fields=['tenant', 'product', 'status'], name='costing_sta_tenant__5ee5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='standardcost',
            index=models.Index(fields=['tenant', 'cost_center', 'status'], name='costing_sta_tenant__89e4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='standardcost',
            index=models.Index(fields=['tenant', 'effective_from'], name='costing_sta_tenant__0208b0_idx'),
        ),
        migrations.AddIndex(
            model_name='standardcost',
            index=models.Index(fields=['version'], name='costing_sta_version_17b186_idx'),
        ),
        migrations.AddConstraint(
            model_name='standardcost',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'version'), name='unique_tenant_product_cost_version'),
        ),
    ]
