# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0001_initial'),
        ('formulations', '0002_remove_manufacturingroute_unique_tenant_route_product_version_and_more'),
        ('inventory', '0002_remove_stockbalance_unique_tenant_stock_balance_address_status_and_more'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('production', '0002_remove_productionorder_unique_tenant_production_order_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='costcenter',
            name='unique_tenant_cost_center_code',
        ),
        migrations.RemoveConstraint(
            model_name='costelement',
            name='unique_tenant_cost_element_code',
        ),
        migrations.RemoveConstraint(
            model_name='monthlycostclosing',
            name='unique_tenant_cost_period',
        ),
        migrations.RemoveConstraint(
            model_name='productioncostcapture',
            name='unique_tenant_order_center_cost_period',
        ),
        migrations.RemoveConstraint(
            model_name='standardcost',
            name='unique_tenant_product_cost_version',
        ),
        migrations.RemoveIndex(
            model_name='costcenter',
            name='costing_cos_tenant__2b89cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='costelement',
            name='costing_cos_tenant__25b902_idx',
        ),
        migrations.RemoveIndex(
            model_name='costreportsnapshot',
            name='costing_cos_tenant__ad0cf9_idx',
        ),
        migrations.RemoveIndex(
            model_name='costreportsnapshot',
            name='costing_cos_tenant__8d7d53_idx',
        ),
        migrations.RemoveIndex(
            model_name='costreportsnapshot',
            name='costing_cos_tenant__5914df_idx',
        ),
        migrations.RemoveIndex(
            model_name='costsimulation',
            name='costing_cos_tenant__7fc42d_idx',
        ),
        migrations.RemoveIndex(
            model_name='costsimulation',
            name='costing_cos_tenant__2b6eba_idx',
        ),
        migrations.RemoveIndex(
            model_name='costsimulation',
            name='costing_cos_tenant__de86c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlycostclosing',
            name='costing_mon_tenant__5fdb41_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlycostclosing',
            name='costing_mon_tenant__aabc72_idx',
        ),
        migrations.RemoveIndex(
            model_name='productioncostcapture',
            name='costing_pro_tenant__5ddf78_idx',
        ),
        migrations.RemoveIndex(
            model_name='productioncostcapture',
            name='costing_pro_tenant__d5ef2a_idx',
        ),
        migrations.RemoveIndex(
            model_name='productioncostcapture',
            name='costing_pro_tenant__d4df1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='standardcost',
            name='costing_sta_tenant__5ee5d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='standardcost',
            name='costing_sta_tenant__89e4ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='standardcost',
            name='costing_sta_tenant__0208b0_idx',
        ),
        migrations.RemoveField(
            model_name='costcenter',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='costelement',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='costreportsnapshot',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='costsimulation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='monthlycostclosing',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='productioncostcapture',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='standardcost',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['center_type', 'is_active'], name='costing_cos_center__d27b26_idx'),
        ),
        migrations.AddIndex(
            model_name='costelement',
            index=models.Index(fields=['category', 'is_active'], name='costing_cos_categor_0c79c0_idx'),
        ),
        migrations.AddIndex(
            model_name='costreportsnapshot',
            index=models.Index(fields=['report_type'], name='costing_cos_report__477350_idx'),
        ),
        migrations.AddIndex(
            model_name='costreportsnapshot',
            index=models.Index(fields=['product'], name='costing_cos_product_e4f6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='costreportsnapshot',
            index=models.Index(fields=['period_start', 'period_end'], name='costing_cos_period__6ed2db_idx'),
        ),
        migrations.AddIndex(
            model_name='costsimulation',
            index=models.Index(fields=['product'], name='costing_cos_product_8fabb9_idx'),
        ),
        migrations.AddIndex(
            model_name='costsimulation',
            index=models.Index(fields=['formula'], name='costing_cos_formula_513335_idx'),
        ),
        migrations.AddIndex(
            model_name='costsimulation',
            index=models.Index(fields=['cost_center'], name='costing_cos_cost_ce_9f29bd_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycostclosing',
            index=models.Index(fields=['status'], name='costing_mon_status_8a9bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycostclosing',
            index=models.Index(fields=['period_year', 'period_month'], name='costing_mon_period__51c963_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncostcapture',
            index=models.Index(fields=['production_order'], name='costing_pro_product_94aa8e_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncostcapture',
            index=models.Index(fields=['cost_center'], name='costing_pro_cost_ce_d9cc94_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncostcapture',
            index=models.Index(fields=['period_start', 'period_end'], name='costing_pro_period__feeea3_idx'),
        ),
        migrations.AddIndex(
            model_name='standardcost',
            index=models.Index(fields=['product', 'status'], name='costing_sta_product_f8cd9b_idx'),
        ),
        migrations.AddIndex(
            model_name='standardcost',
            index=models.Index(fields=['cost_center', 'status'], name='costing_sta_cost_ce_63aa1c_idx'),
        ),
        migrations.AddIndex(
            model_name='standardcost',
            index=models.Index(fields=['effective_from'], name='costing_sta_effecti_8bb6e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_cost_center_code'),
        ),
        migrations.AddConstraint(
            model_name='costelement',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_cost_element_code'),
        ),
        migrations.AddConstraint(
            model_name='monthlycostclosing',
            constraint=models.UniqueConstraint(fields=('period_year', 'period_month'), name='unique_cost_period'),
        ),
        migrations.AddConstraint(
            model_name='productioncostcapture',
            constraint=models.UniqueConstraint(fields=('production_order', 'cost_center', 'period_start', 'period_end'), name='unique_order_center_cost_period'),
        ),
        migrations.AddConstraint(
            model_name='standardcost',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='unique_product_cost_version'),
        ),
    ]
