# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0001_initial'),
        ('formulations', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costreportsnapshot',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_report_snapshots', to='production.productionorder', verbose_name='ordem de produção'),
        ),
        migrations.AddField(
            model_name='costreportsnapshot',
            name='stock_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_report_snapshots', to='inventory.stocklot', verbose_name='lote'),
        ),
        migrations.AddField(
            model_name='costsimulation',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_simulations', to='formulations.masterformula', verbose_name='fórmula'),
        ),
        migrations.AddField(
            model_name='costsimulation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_simulations', to='masters.product', verbose_name='produto'),
        ),
        migrations.AddField(
            model_name='monthlycostclosing',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_cost_periods', to=settings.AUTH_USER_MODEL, verbose_name='fechado por'),
        ),
        migrations.AddField(
            model_name='productioncostcapture',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_captures', to='production.productionorder', verbose_name='ordem de produção'),
        ),
        migrations.AddField(
            model_name='standardcost',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_standard_costs', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por'),
        ),
        migrations.AddField(
            model_name='standardcost',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_costs', to='masters.product', verbose_name='produto'),
        ),
        migrations.AddField(
            model_name='standardcost',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_costs', to='masters.unitofmeasure', verbose_name='unidade'),
        ),
        migrations.AddIndex(
            model_name='costreportsnapshot',
            index=models.Index(fields=['report_type'], name='costing_cos_report__477350_idx'),
        ),
        migrations.AddIndex(
            model_name='costreportsnapshot',
            index=models.Index(fields=['product'], name='costing_cos_product_e4f6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='costreportsnapshot',
            index=models.Index(fields=['period_start', 'period_end'], name='costing_cos_period__6ed2db_idx'),
        ),
        migrations.AddIndex(
            model_name='costsimulation',
            index=models.Index(fields=['product'], name='costing_cos_product_8fabb9_idx'),
        ),
        migrations.AddIndex(
            model_name='costsimulation',
            index=models.Index(fields=['formula'], name='costing_cos_formula_513335_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycostclosing',
            index=models.Index(fields=['status'], name='costing_mon_status_8a9bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycostclosing',
            index=models.Index(fields=['period_year', 'period_month'], name='costing_mon_period__51c963_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlycostclosing',
            constraint=models.UniqueConstraint(fields=('period_year', 'period_month'), name='unique_cost_period'),
        ),
        migrations.AddIndex(
            model_name='productioncostcapture',
            index=models.Index(fields=['production_order'], name='costing_pro_product_94aa8e_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncostcapture',
            index=models.Index(fields=['period_start', 'period_end'], name='costing_pro_period__feeea3_idx'),
        ),
        migrations.AddConstraint(
            model_name='productioncostcapture',
            constraint=models.UniqueConstraint(fields=('production_order', 'period_start', 'period_end'), name='unique_order_cost_period'),
        ),
        migrations.AddIndex(
            model_name='standardcost',
            index=models.Index(fields=['product', 'status'], name='costing_sta_product_f8cd9b_idx'),
        ),
        migrations.AddIndex(
            model_name='standardcost',
            index=models.Index(fields=['effective_from'], name='costing_sta_effecti_8bb6e7_idx'),
        ),
        migrations.AddIndex(
            model_name='standardcost',
            index=models.Index(fields=['version'], name='costing_sta_version_17b186_idx'),
        ),
        migrations.AddConstraint(
            model_name='standardcost',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='unique_product_cost_version'),
        ),
        migrations.AddConstraint(
            model_name='standardcost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), ('approved_at__isnull', False), _connector='OR'), name='standard_cost_approved_at_required'),
        ),
    ]
