# Generated by Django 5.2.16 on 2026-08-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0004_standard_cost_state_machine'),
        ('finance', '0003_remove_financialtitle_cost_center'),
        ('production', '0007_alter_productionorder_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productioncostcapture',
            name='unique_order_center_cost_period',
        ),
        migrations.RemoveIndex(
            model_name='costsimulation',
            name='costing_cos_cost_ce_9f29bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='productioncostcapture',
            name='costing_pro_cost_ce_d9cc94_idx',
        ),
        migrations.RemoveIndex(
            model_name='standardcost',
            name='costing_sta_cost_ce_63aa1c_idx',
        ),
        migrations.RemoveField(
            model_name='productioncostcapture',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='costsimulation',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='standardcost',
            name='cost_center',
        ),
        migrations.AddConstraint(
            model_name='productioncostcapture',
            constraint=models.UniqueConstraint(fields=('production_order', 'period_start', 'period_end'), name='unique_order_cost_period'),
        ),
        migrations.DeleteModel(
            name='CostCenter',
        ),
    ]
