SEED_SOURCES = [
    {
        'code': 'ANVISA-RDC-752-2022',
        'title': 'RDC Anvisa nº 752/2022 - Regularização de produtos de higiene, cosméticos e perfumes',
        'source_type': 'regulation',
        'publisher': 'Anvisa',
        'jurisdiction': 'BR',
        'version': 'RDC 752/2022',
        'url': 'https://www.gov.br/anvisa/pt-br/assuntos/cosmeticos/regularizacao-de-produtos',
        'is_official': True,
        'license_note': 'Fonte pública oficial da Anvisa.',
    },
    {
        'code': 'ANVISA-RDC-907-2024',
        'title': 'RDC Anvisa nº 907/2024 - Produtos sujeitos a registro',
        'source_type': 'regulation',
        'publisher': 'Anvisa',
        'jurisdiction': 'BR',
        'version': 'RDC 907/2024',
        'url': 'https://www.gov.br/anvisa/pt-br/comunicacao/campanhas/estetica/consulta-de-cosmeticos',
        'is_official': True,
        'license_note': 'Fonte pública oficial da Anvisa.',
    },
    {
        'code': 'ANVISA-RDC-894-2024',
        'title': 'RDC Anvisa nº 894/2024 - Boas Práticas de Cosmetovigilância',
        'source_type': 'regulation',
        'publisher': 'Anvisa',
        'jurisdiction': 'BR',
        'version': 'RDC 894/2024',
        'url': 'https://www.gov.br/anvisa/pt-br/assuntos/fiscalizacao-e-monitoramento/cosmetovigilancia/legislacao-e-orientacoes-em-cosmetovigilancia',
        'is_official': True,
        'license_note': 'Fonte pública oficial da Anvisa.',
    },
    {
        'code': 'ANVISA-INCI-RDC-646-2022',
        'title': 'Composição em português e nomenclatura INCI de cosméticos',
        'source_type': 'regulation',
        'publisher': 'Anvisa',
        'jurisdiction': 'BR',
        'version': 'RDC 646/2022, alterada pela RDC 773/2023',
        'url': 'https://www.gov.br/anvisa/pt-br/assuntos/cosmeticos/traducao',
        'is_official': True,
        'license_note': 'Fonte pública oficial da Anvisa.',
    },
    {
        'code': 'ISO-22716-REFERENCE',
        'title': 'ISO 22716 - Boas práticas de fabricação de cosméticos',
        'source_type': 'book_reference',
        'publisher': 'ISO',
        'jurisdiction': 'International',
        'version': 'ISO 22716:2007',
        'url': 'https://www.iso.org/standard/36437.html',
        'is_official': True,
        'license_note': 'Referência protegida por direitos autorais; ingerir somente metadados.',
        'metadata': {'metadata_only': True},
    },
    {
        'code': 'ISPE-GAMP-5-REFERENCE',
        'title': 'GAMP 5 - A Risk-Based Approach to Compliant GxP Computerized Systems',
        'source_type': 'book_reference',
        'publisher': 'ISPE',
        'jurisdiction': 'GxP',
        'version': '2nd edition reference',
        'url': 'https://ispe.org/publications/guidance-documents/gamp-5',
        'is_official': False,
        'license_note': 'Referencia bibliografica protegida por direitos autorais. Nao ingerir conteudo integral sem permissao.',
        'metadata': {'metadata_only': True},
    },
    {
        'code': 'RGN-ERP-HELP-INTEGRATIONS',
        'title': 'Ajuda do ERP - Integrações e impressão local',
        'source_type': 'system_manual',
        'publisher': 'RGN Farma System',
        'jurisdiction': 'BR',
        'version': '9eef55f',
        'url': 'https://rgnfarmasystem.rgnsystems.com.br/app/integrations/',
        'is_official': True,
        'chat_eligible': True,
        'metadata': {'local_path': 'docs/architecture/integrations.md'},
    },
    {
        'code': 'RGN-ERP-HELP-INVENTORY-LABELS',
        'title': 'Ajuda do ERP - Etiquetas de lote',
        'source_type': 'system_manual',
        'publisher': 'RGN Farma System',
        'jurisdiction': 'BR',
        'version': '9eef55f',
        'url': 'https://rgnfarmasystem.rgnsystems.com.br/app/inventory/lots/',
        'is_official': True,
        'chat_eligible': True,
        'metadata': {'local_path': 'docs/architecture/inventory-labels.md'},
    },
    {
        'code': 'RGN-ERP-HELP-LOCAL-PRINTING',
        'title': 'Ajuda do ERP - Agente de impressão Windows',
        'source_type': 'system_manual',
        'publisher': 'RGN Farma System',
        'jurisdiction': 'BR',
        'version': '9eef55f',
        'url': 'https://rgnfarmasystem.rgnsystems.com.br/app/integrations/local-printing/',
        'is_official': True,
        'chat_eligible': True,
        'metadata': {'local_path': 'docs/operations/local-print-agent-windows.md'},
    },
]
