SEED_SOURCES = [
    {
        'code': 'ANVISA-RDC-658-2022',
        'title': 'RDC Anvisa no 658/2022 - Boas Praticas de Fabricacao de Medicamentos',
        'source_type': 'regulation',
        'publisher': 'Anvisa / DOU',
        'jurisdiction': 'BR',
        'version': 'RDC 658/2022',
        'url': 'https://www.in.gov.br/en/web/dou/-/resolucao-rdc-n-658-de-30-de-marco-de-2022-389846242',
        'is_official': True,
        'license_note': 'Fonte oficial publica do Diario Oficial da Uniao.',
    },
    {
        'code': 'ANVISA-RDC-972-2025',
        'title': 'RDC Anvisa no 972/2025 - Alteracao da RDC 658/2022',
        'source_type': 'regulation',
        'publisher': 'AnvisaLegis',
        'jurisdiction': 'BR',
        'version': 'RDC 972/2025',
        'url': 'https://anvisalegis.datalegis.net/action/ActionDatalegis.php?acao=abrirTextoAto&cod_menu=9431&cod_modulo=310&link=S&numeroAto=00000972&orgao=RDC%2FDC%2FANVISA%2FMS&seqAto=000&tipo=RDC&valorAno=2025',
        'is_official': True,
        'license_note': 'Fonte publica de legislacao sanitaria.',
    },
    {
        'code': 'ANVISA-IN-134-2022',
        'title': 'IN Anvisa no 134/2022 - Sistemas computadorizados em BPF',
        'source_type': 'regulation',
        'publisher': 'Anvisa / DOU',
        'jurisdiction': 'BR',
        'version': 'IN 134/2022',
        'url': 'https://www.in.gov.br/web/dou/-/instrucao-normativa-in-n-134-de-30-de-marco-de-2022-389839479',
        'is_official': True,
        'license_note': 'Fonte oficial publica do Diario Oficial da Uniao.',
    },
    {
        'code': 'ANVISA-RDC-406-2020',
        'title': 'RDC Anvisa no 406/2020 - Boas Praticas de Farmacovigilancia',
        'source_type': 'regulation',
        'publisher': 'AnvisaLegis',
        'jurisdiction': 'BR',
        'version': 'RDC 406/2020',
        'url': 'https://anvisalegis.datalegis.net/action/ActionDatalegis.php?acao=abrirTextoAto&cod_menu=8542&cod_modulo=310&link=S&numeroAto=00000406&orgao=RDC%2FDC%2FANVISA%2FMS&seqAto=000&tipo=RDC&valorAno=2020',
        'is_official': True,
        'license_note': 'Fonte publica de legislacao sanitaria.',
    },
    {
        'code': 'ANVISA-FARMACOPEIA-BRASILEIRA-8',
        'title': 'Farmacopeia Brasileira 8a edicao - RDC Anvisa no 1.026/2026',
        'source_type': 'pharmacopoeia',
        'publisher': 'Anvisa',
        'jurisdiction': 'BR',
        'version': '8a edicao',
        'url': 'https://www.gov.br/anvisa/pt-br/assuntos/farmacopeia/farmacopeia-brasileira',
        'is_official': True,
        'license_note': 'Conteudo oficial disponibilizado pela Anvisa e Biblioteca Digital Anvisa.',
        'metadata': {
            'collection_url': 'https://bibliotecadigital.anvisa.gov.br/jspui/handle/anvisa/11932',
            'volume_i_url': 'https://bibliotecadigital.anvisa.gov.br/jspui/handle/anvisa/21035',
        },
    },
    {
        'code': 'ICH-Q9-R1-2022',
        'title': 'ICH Q9(R1) - Quality Risk Management',
        'source_type': 'guideline',
        'publisher': 'ICH',
        'jurisdiction': 'ICH',
        'version': 'Step 4, 2022',
        'url': 'https://database.ich.org/sites/default/files/ICH_Q9%28R1%29_Guideline_Step4_2022_1219.pdf',
        'is_official': True,
        'license_note': 'Fonte oficial publica do ICH.',
    },
    {
        'code': 'ICH-Q10',
        'title': 'ICH Q10 - Pharmaceutical Quality System',
        'source_type': 'guideline',
        'publisher': 'ICH',
        'jurisdiction': 'ICH',
        'version': 'Step 4',
        'url': 'https://database.ich.org/sites/default/files/Q10%20Guideline.pdf',
        'is_official': True,
        'license_note': 'Fonte oficial publica do ICH.',
    },
    {
        'code': 'PICS-PE-009-17-PART-I',
        'title': 'PIC/S PE 009-17 - GMP Guide Part I',
        'source_type': 'guideline',
        'publisher': 'PIC/S',
        'jurisdiction': 'PIC/S',
        'version': 'PE 009-17 Part I',
        'url': 'https://picscheme.org/docview/6606',
        'is_official': True,
        'license_note': 'Fonte oficial PIC/S. Uso interno autorizado quando a fonte e reconhecida.',
    },
    {
        'code': 'WHO-TRS-986-ANNEX-2',
        'title': 'WHO GMP for pharmaceutical products - Main principles',
        'source_type': 'guideline',
        'publisher': 'WHO',
        'jurisdiction': 'WHO',
        'version': 'TRS 986 Annex 2',
        'url': 'https://www.who.int/publications/m/item/trs986-annex2',
        'is_official': True,
        'license_note': 'Fonte oficial publica da WHO.',
    },
    {
        'code': 'FDA-21-CFR-210',
        'title': '21 CFR Part 210 - Current Good Manufacturing Practice',
        'source_type': 'regulation',
        'publisher': 'eCFR',
        'jurisdiction': 'US',
        'version': 'Current',
        'url': 'https://www.ecfr.gov/current/title-21/chapter-I/subchapter-C/part-210',
        'is_official': True,
        'license_note': 'Fonte oficial publica eCFR.',
    },
    {
        'code': 'FDA-21-CFR-211',
        'title': '21 CFR Part 211 - CGMP for Finished Pharmaceuticals',
        'source_type': 'regulation',
        'publisher': 'eCFR',
        'jurisdiction': 'US',
        'version': 'Current',
        'url': 'https://www.ecfr.gov/current/title-21/chapter-I/subchapter-C/part-211',
        'is_official': True,
        'license_note': 'Fonte oficial publica eCFR.',
    },
    {
        'code': 'ISPE-GAMP-5-REFERENCE',
        'title': 'GAMP 5 - A Risk-Based Approach to Compliant GxP Computerized Systems',
        'source_type': 'book_reference',
        'publisher': 'ISPE',
        'jurisdiction': 'GxP',
        'version': '2nd edition reference',
        'url': 'https://ispe.org/publications/guidance-documents/gamp-5',
        'is_official': False,
        'license_note': 'Referencia bibliografica protegida por direitos autorais. Nao ingerir conteudo integral sem permissao.',
        'metadata': {'metadata_only': True},
    },
]
