# Generated by Django 6.0.7 on 2026-07-08 13:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoScenarioLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('scenario', models.CharField(choices=[('base_master_data', 'Cadastros base'), ('quality_deviation', 'Desvio de qualidade'), ('capa_workflow', 'Workflow CAPA'), ('finance_fiscal', 'Financeiro e fiscal'), ('full_demo', 'Demonstracao completa')], max_length=40, verbose_name='cenario')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('succeeded', 'Concluido'), ('failed', 'Falhou')], default='pending', max_length=24, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluido em')),
                ('records_created', models.JSONField(blank=True, default=dict, verbose_name='registros criados ou atualizados')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_demo_scenario_loads', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'carga de cenario demo',
                'verbose_name_plural': 'cargas de cenarios demo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'scenario', 'status'], name='governance__tenant__baa413_idx'), models.Index(fields=['tenant', 'requested_by'], name='governance__tenant__9ea989_idx'), models.Index(fields=['tenant', 'started_at'], name='governance__tenant__57600d_idx')],
            },
        ),
        migrations.CreateModel(
            name='GovernanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('log_type', models.CharField(choices=[('technical', 'Tecnico'), ('functional', 'Funcional'), ('security', 'Seguranca'), ('parameter', 'Parametro'), ('module', 'Modulo'), ('demo_load', 'Carga demo')], max_length=24, verbose_name='tipo de log')),
                ('severity', models.CharField(choices=[('info', 'Informacao'), ('warning', 'Alerta'), ('error', 'Erro'), ('critical', 'Critico')], default='info', max_length=16, verbose_name='severidade')),
                ('module', models.CharField(choices=[('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('governance', 'Governanca')], max_length=40, verbose_name='modulo')),
                ('action', models.CharField(max_length=120, verbose_name='acao')),
                ('target_model', models.CharField(blank=True, max_length=120, verbose_name='modelo alvo')),
                ('target_record_id', models.CharField(blank=True, max_length=120, verbose_name='registro alvo')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('safe_context', models.JSONField(blank=True, default=dict, verbose_name='contexto seguro')),
                ('request_id', models.CharField(blank=True, max_length=120, verbose_name='request id')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ocorrido em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='governance_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'log de governanca',
                'verbose_name_plural': 'logs de governanca',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'log_type', 'severity', 'occurred_at'], name='governance__tenant__4f28fa_idx'), models.Index(fields=['tenant', 'module', 'action'], name='governance__tenant__8403c9_idx'), models.Index(fields=['tenant', 'user'], name='governance__tenant__d97fa5_idx'), models.Index(fields=['target_model', 'target_record_id'], name='governance__target__2e86a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='GovernanceCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('catalog_type', models.CharField(choices=[('document_type', 'Tipo de documento'), ('deviation_type', 'Tipo de desvio'), ('capa_category', 'Categoria de CAPA'), ('status', 'Status'), ('criticality', 'Criticidade'), ('workflow_step', 'Etapa de workflow'), ('block_reason', 'Motivo de bloqueio'), ('lot_status', 'Status de lote'), ('inventory_reason', 'Motivo de estoque')], max_length=40, verbose_name='tipo de catalogo')),
                ('module', models.CharField(choices=[('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('governance', 'Governanca')], max_length=40, verbose_name='modulo')),
                ('code', models.CharField(max_length=80, verbose_name='codigo')),
                ('label', models.CharField(max_length=180, verbose_name='rotulo')),
                ('value', models.CharField(max_length=120, verbose_name='valor')),
                ('color', models.CharField(blank=True, max_length=40, verbose_name='cor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='governance.governancecatalogitem', verbose_name='item pai')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'item de catalogo de governanca',
                'verbose_name_plural': 'itens de catalogo de governanca',
                'ordering': ['catalog_type', 'module', 'order', 'code'],
                'indexes': [models.Index(fields=['tenant', 'catalog_type', 'module', 'is_active'], name='governance__tenant__93400a_idx'), models.Index(fields=['tenant', 'code'], name='governance__tenant__8f3566_idx'), models.Index(fields=['tenant', 'parent'], name='governance__tenant__673bcd_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'catalog_type', 'module', 'code'), name='unique_tenant_governance_catalog_code')],
            },
        ),
        migrations.CreateModel(
            name='GovernanceParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('module', 'Modulo'), ('workflow', 'Workflow'), ('retention', 'Retencao'), ('alert', 'Alerta'), ('approval', 'Alcada'), ('inventory', 'Estoque'), ('quality', 'Qualidade')], max_length=24, verbose_name='escopo')),
                ('module', models.CharField(choices=[('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('governance', 'Governanca')], max_length=40, verbose_name='modulo')),
                ('key', models.CharField(max_length=120, verbose_name='chave')),
                ('value_type', models.CharField(choices=[('string', 'Texto'), ('integer', 'Inteiro'), ('decimal', 'Decimal'), ('boolean', 'Booleano'), ('json', 'JSON'), ('days', 'Dias'), ('choice', 'Escolha')], max_length=24, verbose_name='tipo de valor')),
                ('value', models.JSONField(default=dict, verbose_name='valor')),
                ('default_value', models.JSONField(blank=True, default=dict, verbose_name='valor padrao')),
                ('rules', models.JSONField(blank=True, default=dict, verbose_name='regras')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_governance_parameters', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'parametro de governanca',
                'verbose_name_plural': 'parametros de governanca',
                'ordering': ['scope', 'module', 'key'],
                'indexes': [models.Index(fields=['tenant', 'scope', 'module', 'is_active'], name='governance__tenant__ad75ff_idx'), models.Index(fields=['tenant', 'key'], name='governance__tenant__e0bb54_idx'), models.Index(fields=['tenant', 'updated_by'], name='governance__tenant__9bf200_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'scope', 'module', 'key'), name='unique_tenant_governance_parameter')],
            },
        ),
        migrations.CreateModel(
            name='TenantModuleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('module', models.CharField(choices=[('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('governance', 'Governanca')], max_length=40, verbose_name='modulo')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('suspended', 'Suspenso'), ('disabled', 'Desativado')], default='active', max_length=24, verbose_name='status')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='habilitado')),
                ('menu_label', models.CharField(blank=True, max_length=120, verbose_name='rotulo de menu')),
                ('menu_order', models.PositiveIntegerField(default=0, verbose_name='ordem de menu')),
                ('permission_groups', models.JSONField(blank=True, default=list, verbose_name='grupos de permissao')),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='configuracao')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='ativado em')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='desativado em')),
                ('deactivation_reason', models.TextField(blank=True, verbose_name='motivo de desativacao')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_module_settings', to=settings.AUTH_USER_MODEL, verbose_name='ativado por')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_module_settings', to=settings.AUTH_USER_MODEL, verbose_name='desativado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'configuracao de modulo',
                'verbose_name_plural': 'configuracoes de modulos',
                'ordering': ['menu_order', 'module'],
                'indexes': [models.Index(fields=['tenant', 'module', 'status', 'is_enabled'], name='governance__tenant__2e8367_idx'), models.Index(fields=['tenant', 'menu_order'], name='governance__tenant__0f50ba_idx'), models.Index(fields=['tenant', 'activated_by'], name='governance__tenant__f73302_idx'), models.Index(fields=['tenant', 'deactivated_by'], name='governance__tenant__7749d1_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'module'), name='unique_tenant_module_setting')],
            },
        ),
    ]
