# Generated by Django 6.0.8 on 2026-08-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governanceauditlog',
            name='module',
            field=models.CharField(choices=[('auxiliary', 'Cadastros auxiliares'), ('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('recalls', 'Recall'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
        migrations.AlterField(
            model_name='governancecatalogitem',
            name='module',
            field=models.CharField(choices=[('auxiliary', 'Cadastros auxiliares'), ('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('recalls', 'Recall'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
        migrations.AlterField(
            model_name='governanceparameter',
            name='module',
            field=models.CharField(choices=[('auxiliary', 'Cadastros auxiliares'), ('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('recalls', 'Recall'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
    ]
