# Generated by Django 6.0.7 on 2026-07-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governanceauditlog',
            name='module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='modulo normalizado'),
        ),
        migrations.AddField(
            model_name='governanceauditlog',
            name='severity_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='severidade normalizada'),
        ),
        migrations.AddField(
            model_name='governanceauditlog',
            name='target_model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model alvo normalizado'),
        ),
        migrations.AddField(
            model_name='governancecatalogitem',
            name='module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='modulo normalizado'),
        ),
        migrations.AddField(
            model_name='governanceparameter',
            name='module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='modulo normalizado'),
        ),
        migrations.AddField(
            model_name='tenantmodulesetting',
            name='module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='modulo normalizado'),
        ),
    ]
