# Generated by Django 6.0.7 on 2026-07-11 20:25

from django.db import migrations, models
from django.utils import timezone


MODULES = (
    'masters',
    'formulations',
    'production',
    'planning',
    'procurement',
    'inventory',
    'costing',
    'finance',
    'fiscal',
    'crm',
    'quality',
    'qa',
    'documents',
    'deviations',
    'capa',
    'changes',
    'audits',
    'risks',
    'regulatory',
    'pharmacovigilance',
    'recalls',
    'maintenance',
    'training',
    'files',
    'reports',
    'workflow',
    'integrations',
    'ai_agents',
    'knowledge',
    'governance',
    'compliance',
)


def backfill_tenant_module_contracts(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    TenantModuleSetting = apps.get_model('governance', 'TenantModuleSetting')
    now = timezone.now()
    for tenant in Tenant.objects.iterator():
        for position, module in enumerate(MODULES, start=1):
            TenantModuleSetting.objects.get_or_create(
                tenant_id=tenant.pk,
                module=module,
                defaults={
                    'status': 'active',
                    'is_enabled': True,
                    'menu_order': position * 10,
                    'activated_at': now,
                },
            )
        Tenant.objects.filter(pk=tenant.pk).update(module_contract_enforced=True)


def mark_contracts_as_legacy(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    Tenant.objects.update(module_contract_enforced=False)


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_governanceauditlog_module_ref_and_more'),
        ('tenants', '0002_tenant_module_contract_enforced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governanceauditlog',
            name='module',
            field=models.CharField(choices=[('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('knowledge', 'Conhecimento RAG'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
        migrations.AlterField(
            model_name='governancecatalogitem',
            name='module',
            field=models.CharField(choices=[('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('knowledge', 'Conhecimento RAG'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
        migrations.AlterField(
            model_name='governanceparameter',
            name='module',
            field=models.CharField(choices=[('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('knowledge', 'Conhecimento RAG'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
        migrations.AlterField(
            model_name='tenantmodulesetting',
            name='module',
            field=models.CharField(choices=[('masters', 'Cadastros mestres'), ('formulations', 'Formulas e roteiros'), ('production', 'Producao'), ('planning', 'PCP, MPS e MRP'), ('procurement', 'Compras'), ('inventory', 'Estoque'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('crm', 'CRM'), ('quality', 'Controle de qualidade'), ('qa', 'Garantia da qualidade'), ('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('changes', 'Mudancas'), ('audits', 'Auditorias'), ('risks', 'Riscos'), ('regulatory', 'Regulatorio'), ('pharmacovigilance', 'Farmacovigilancia'), ('recalls', 'Recall'), ('maintenance', 'Manutencao'), ('training', 'Treinamentos'), ('files', 'Arquivos'), ('reports', 'Relatorios'), ('workflow', 'Workflow'), ('integrations', 'Integracoes'), ('ai_agents', 'Agentes de IA'), ('knowledge', 'Conhecimento RAG'), ('governance', 'Governanca'), ('compliance', 'Compliance transversal')], max_length=40, verbose_name='modulo'),
        ),
        migrations.RunPython(backfill_tenant_module_contracts, mark_contracts_as_legacy),
    ]
