# Generated by Django 5.2.2 on 2026-07-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_alter_governanceauditlog_module_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantmodulesetting',
            options={'ordering': ['menu_order', 'module'], 'verbose_name': 'configuração de módulo', 'verbose_name_plural': 'configurações de módulos'},
        ),
    ]
