# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('governance', '0004_alter_tenantmodulesetting_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='governancecatalogitem',
            name='unique_tenant_governance_catalog_code',
        ),
        migrations.RemoveConstraint(
            model_name='governanceparameter',
            name='unique_tenant_governance_parameter',
        ),
        migrations.RemoveConstraint(
            model_name='tenantmodulesetting',
            name='unique_tenant_module_setting',
        ),
        migrations.RemoveIndex(
            model_name='demoscenarioload',
            name='governance__tenant__baa413_idx',
        ),
        migrations.RemoveIndex(
            model_name='demoscenarioload',
            name='governance__tenant__9ea989_idx',
        ),
        migrations.RemoveIndex(
            model_name='demoscenarioload',
            name='governance__tenant__57600d_idx',
        ),
        migrations.RemoveIndex(
            model_name='governanceauditlog',
            name='governance__tenant__4f28fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='governanceauditlog',
            name='governance__tenant__8403c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='governanceauditlog',
            name='governance__tenant__d97fa5_idx',
        ),
        migrations.RemoveIndex(
            model_name='governancecatalogitem',
            name='governance__tenant__93400a_idx',
        ),
        migrations.RemoveIndex(
            model_name='governancecatalogitem',
            name='governance__tenant__8f3566_idx',
        ),
        migrations.RemoveIndex(
            model_name='governancecatalogitem',
            name='governance__tenant__673bcd_idx',
        ),
        migrations.RemoveIndex(
            model_name='governanceparameter',
            name='governance__tenant__ad75ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='governanceparameter',
            name='governance__tenant__e0bb54_idx',
        ),
        migrations.RemoveIndex(
            model_name='governanceparameter',
            name='governance__tenant__9bf200_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantmodulesetting',
            name='governance__tenant__2e8367_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantmodulesetting',
            name='governance__tenant__0f50ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantmodulesetting',
            name='governance__tenant__f73302_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantmodulesetting',
            name='governance__tenant__7749d1_idx',
        ),
        migrations.RemoveField(
            model_name='demoscenarioload',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='governanceauditlog',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='governancecatalogitem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='governanceparameter',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenantmodulesetting',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='demoscenarioload',
            index=models.Index(fields=['scenario', 'status'], name='governance__scenari_20ed47_idx'),
        ),
        migrations.AddIndex(
            model_name='demoscenarioload',
            index=models.Index(fields=['requested_by'], name='governance__request_c2e629_idx'),
        ),
        migrations.AddIndex(
            model_name='demoscenarioload',
            index=models.Index(fields=['started_at'], name='governance__started_592a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='governanceauditlog',
            index=models.Index(fields=['log_type', 'severity', 'occurred_at'], name='governance__log_typ_0918d7_idx'),
        ),
        migrations.AddIndex(
            model_name='governanceauditlog',
            index=models.Index(fields=['module', 'action'], name='governance__module_8ce9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='governanceauditlog',
            index=models.Index(fields=['user'], name='governance__user_id_6595f2_idx'),
        ),
        migrations.AddIndex(
            model_name='governancecatalogitem',
            index=models.Index(fields=['catalog_type', 'module', 'is_active'], name='governance__catalog_c8a54a_idx'),
        ),
        migrations.AddIndex(
            model_name='governancecatalogitem',
            index=models.Index(fields=['code'], name='governance__code_39c348_idx'),
        ),
        migrations.AddIndex(
            model_name='governancecatalogitem',
            index=models.Index(fields=['parent'], name='governance__parent__0e0d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='governanceparameter',
            index=models.Index(fields=['scope', 'module', 'is_active'], name='governance__scope_369aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='governanceparameter',
            index=models.Index(fields=['key'], name='governance__key_5d198c_idx'),
        ),
        migrations.AddIndex(
            model_name='governanceparameter',
            index=models.Index(fields=['updated_by'], name='governance__updated_383311_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmodulesetting',
            index=models.Index(fields=['module', 'status', 'is_enabled'], name='governance__module_6ba021_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmodulesetting',
            index=models.Index(fields=['menu_order'], name='governance__menu_or_65ea24_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmodulesetting',
            index=models.Index(fields=['activated_by'], name='governance__activat_48a5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmodulesetting',
            index=models.Index(fields=['deactivated_by'], name='governance__deactiv_95084e_idx'),
        ),
        migrations.AddConstraint(
            model_name='governancecatalogitem',
            constraint=models.UniqueConstraint(fields=('catalog_type', 'module', 'code'), name='unique_governance_catalog_code'),
        ),
        migrations.AddConstraint(
            model_name='governanceparameter',
            constraint=models.UniqueConstraint(fields=('scope', 'module', 'key'), name='unique_governance_parameter'),
        ),
        migrations.AddConstraint(
            model_name='tenantmodulesetting',
            constraint=models.UniqueConstraint(fields=('module',), name='unique_module_setting'),
        ),
    ]
