# Generated by Django 5.2.16 on 2026-07-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_remove_governancecatalogitem_unique_tenant_governance_catalog_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantModuleSetting',
        ),
    ]
