# Generated by Django 5.2.16 on 2026-07-21 14:02

import django.db.models.deletion
import governance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('governance', '0006_delete_tenantmodulesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='nome fantasia')),
                ('legal_name', models.CharField(max_length=255, verbose_name='razão social')),
                ('document', models.CharField(max_length=32, verbose_name='CNPJ/CPF')),
                ('state_registration', models.CharField(blank=True, max_length=40, verbose_name='inscrição estadual')),
                ('municipal_registration', models.CharField(blank=True, max_length=40, verbose_name='inscrição municipal')),
                ('tax_regime', models.CharField(blank=True, choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real'), ('exempt', 'Isento')], max_length=32, verbose_name='regime tributário')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail institucional')),
                ('website', models.URLField(blank=True, verbose_name='site')),
                ('zipcode', models.CharField(blank=True, max_length=20, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='logradouro')),
                ('street_number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='município')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('logo', models.ImageField(blank=True, upload_to=governance.models.institution_logo_path, verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('city_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='município normalizado')),
                ('state_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF normalizada')),
            ],
            options={
                'verbose_name': 'dados da instituição',
                'verbose_name_plural': 'dados da instituição',
                'ordering': ['legal_name'],
            },
        ),
    ]
