# Generated by Django 5.2.16 on 2026-07-22 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('fiscal', '0005_remove_fiscalbookentry_unique_tenant_document_book_entry_and_more'),
        ('governance', '0007_institutionsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('full_name', models.CharField(max_length=255, verbose_name='nome completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('profession', models.CharField(choices=[('pharmacist', 'Farmacêutico')], default='pharmacist', max_length=32, verbose_name='profissão')),
                ('council', models.CharField(choices=[('CRF', 'Conselho Regional de Farmácia')], default='CRF', max_length=16, verbose_name='conselho profissional')),
                ('council_registration_number', models.CharField(max_length=40, verbose_name='número de inscrição no conselho')),
                ('registration_type', models.CharField(choices=[('definitive', 'Definitiva'), ('provisional', 'Provisória'), ('secondary', 'Secundária'), ('specialist', 'Especialista/outro')], default='definitive', max_length=24, verbose_name='tipo de inscrição')),
                ('registration_status', models.CharField(choices=[('active', 'Ativa'), ('suspended', 'Suspensa'), ('cancelled', 'Cancelada'), ('expired', 'Vencida'), ('pending', 'Pendente')], default='active', max_length=24, verbose_name='status da inscrição')),
                ('responsibility_type', models.CharField(choices=[('primary', 'Responsável técnico principal'), ('substitute', 'Responsável técnico substituto'), ('assistant', 'Assistente técnico')], default='primary', max_length=24, verbose_name='tipo de responsabilidade')),
                ('start_date', models.DateField(verbose_name='data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('weekly_workload_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='carga horária semanal')),
                ('work_schedule', models.JSONField(blank=True, default=dict, verbose_name='grade/horário de assistência farmacêutica')),
                ('regularity_certificate_number', models.CharField(blank=True, max_length=80, verbose_name='número da certidão de regularidade')),
                ('regularity_certificate_issued_at', models.DateField(blank=True, null=True, verbose_name='data de emissão da certidão')),
                ('regularity_certificate_valid_until', models.DateField(blank=True, null=True, verbose_name='validade da certidão')),
                ('certificate_file_reference', models.CharField(blank=True, max_length=255, verbose_name='arquivo/referência da certidão')),
                ('verification_url', models.URLField(blank=True, verbose_name='URL de verificação')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verificado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('council_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF do conselho')),
                ('fiscal_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technical_responsibles', to='fiscal.fiscalcompany', verbose_name='empresa fiscal')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_responsibles', to='governance.institutionsettings', verbose_name='instituição')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technical_responsibilities', to=settings.AUTH_USER_MODEL, verbose_name='usuário vinculado')),
            ],
            options={
                'verbose_name': 'responsável técnico',
                'verbose_name_plural': 'responsáveis técnicos',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['institution', 'is_active'], name='governance__institu_f6f3eb_idx'), models.Index(fields=['fiscal_company', 'is_active'], name='governance__fiscal__0b86f6_idx'), models.Index(fields=['user'], name='governance__user_id_eb8aa8_idx'), models.Index(fields=['cpf'], name='governance__cpf_1a49ab_idx'), models.Index(fields=['council', 'council_registration_number'], name='governance__council_f6117b_idx'), models.Index(fields=['registration_status', 'is_active'], name='governance__registr_044bf1_idx'), models.Index(fields=['responsibility_type', 'is_active'], name='governance__respons_3a90be_idx'), models.Index(fields=['regularity_certificate_valid_until'], name='governance__regular_606827_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fiscal_company__isnull', True), ('is_active', True), ('responsibility_type', 'primary')), fields=('institution',), name='unique_active_primary_technical_responsible_institution'), models.UniqueConstraint(condition=models.Q(('fiscal_company__isnull', False), ('is_active', True), ('responsibility_type', 'primary')), fields=('institution', 'fiscal_company'), name='unique_active_primary_technical_responsible_company')],
            },
        ),
    ]
