# Generated by Django 6.0.7 on 2026-07-07 20:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('start_date', models.DateField(verbose_name='início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('budget_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='orçamento')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='draft', max_length=24, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'campanha comercial',
                'verbose_name_plural': 'campanhas comerciais',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='cargo/função')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('is_primary', models.BooleanField(default=False, verbose_name='contato principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_contacts', to='masters.businesspartner', verbose_name='cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'contato de cliente',
                'verbose_name_plural': 'contatos de clientes',
                'ordering': ['customer__legal_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'grupo econômico',
                'verbose_name_plural': 'grupos econômicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('qualified', 'Qualificada'), ('proposal', 'Proposta'), ('negotiation', 'Negociação'), ('won', 'Ganha'), ('lost', 'Perdida')], default='lead', max_length=24, verbose_name='etapa')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='previsão de fechamento')),
                ('probability_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9, verbose_name='probabilidade (%)')),
                ('estimated_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='valor estimado')),
                ('won_at', models.DateTimeField(blank=True, null=True, verbose_name='ganha em')),
                ('lost_at', models.DateTimeField(blank=True, null=True, verbose_name='perdida em')),
                ('loss_reason', models.TextField(blank=True, verbose_name='motivo da perda')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.campaign', verbose_name='campanha')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.customercontact', verbose_name='contato')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='masters.businesspartner', verbose_name='cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'oportunidade',
                'verbose_name_plural': 'oportunidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('interaction_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Telefone'), ('meeting', 'Reunião'), ('visit', 'Visita'), ('task', 'Tarefa'), ('note', 'Observação')], max_length=24, verbose_name='tipo')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ocorrida em')),
                ('subject', models.CharField(max_length=180, verbose_name='assunto')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='crm.customercontact', verbose_name='contato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_interactions', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_interactions', to='masters.businesspartner', verbose_name='cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='crm.opportunity', verbose_name='oportunidade')),
            ],
            options={
                'verbose_name': 'interação com cliente',
                'verbose_name_plural': 'interações com clientes',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('channel_type', models.CharField(choices=[('direct', 'Venda direta'), ('distributor', 'Distribuidor'), ('ecommerce', 'E-commerce'), ('tender', 'Licitação'), ('representative', 'Representante'), ('partner', 'Parceiro'), ('other', 'Outro')], max_length=24, verbose_name='tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'canal de venda',
                'verbose_name_plural': 'canais de venda',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.saleschannel', verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='crm.saleschannel', verbose_name='canal'),
        ),
        migrations.CreateModel(
            name='SalesContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('contract_number', models.CharField(blank=True, max_length=80, verbose_name='contrato')),
                ('start_date', models.DateField(verbose_name='início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='draft', max_length=24, verbose_name='status')),
                ('contract_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='valor do contrato')),
                ('payment_terms_days', models.PositiveIntegerField(default=0, verbose_name='prazo de pagamento em dias')),
                ('regulatory_requirements', models.TextField(blank=True, verbose_name='requisitos regulatórios')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_sales_contracts', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_contracts', to='masters.businesspartner', verbose_name='cliente')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.opportunity', verbose_name='oportunidade')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'contrato comercial',
                'verbose_name_plural': 'contratos comerciais',
                'ordering': ['-start_date', 'contract_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('order_number', models.CharField(blank=True, max_length=80, verbose_name='pedido')),
                ('requested_delivery_date', models.DateField(verbose_name='data solicitada de entrega')),
                ('payment_terms_days', models.PositiveIntegerField(default=0, verbose_name='prazo de pagamento em dias')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('blocked', 'Bloqueado'), ('fulfilled', 'Atendido'), ('cancelled', 'Cancelado')], default='draft', max_length=24, verbose_name='status')),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='valor total')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('block_reason', models.TextField(blank=True, verbose_name='motivo de bloqueio')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.saleschannel', verbose_name='canal')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.salescontract', verbose_name='contrato')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='masters.businesspartner', verbose_name='cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'pedido de venda',
                'verbose_name_plural': 'pedidos de venda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('complaint_number', models.CharField(blank=True, max_length=80, verbose_name='reclamação')),
                ('quality_reference', models.CharField(blank=True, max_length=80, verbose_name='referência da qualidade')),
                ('capa_reference', models.CharField(blank=True, max_length=80, verbose_name='referência CAPA')),
                ('description', models.TextField(verbose_name='descrição')),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=24, verbose_name='criticidade')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('under_investigation', 'Em investigação'), ('closed', 'Encerrada'), ('cancelled', 'Cancelada')], default='open', max_length=32, verbose_name='status')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='recebida em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrada em')),
                ('resolution', models.TextField(blank=True, verbose_name='resolução')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_customer_complaints', to=settings.AUTH_USER_MODEL, verbose_name='encerrada por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaints', to='masters.businesspartner', verbose_name='cliente')),
                ('fiscal_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaints', to='fiscal.fiscaldocument', verbose_name='documento fiscal')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaints', to='masters.product', verbose_name='produto')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaints', to='inventory.stocklot', verbose_name='lote')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='crm.customercontact', verbose_name='contato')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaints', to='crm.salesorder', verbose_name='pedido de venda')),
            ],
            options={
                'verbose_name': 'reclamação de cliente',
                'verbose_name_plural': 'reclamações de clientes',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='preço unitário')),
                ('discount_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9, verbose_name='desconto (%)')),
                ('promised_date', models.DateField(blank=True, null=True, verbose_name='data prometida')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.salesorder', verbose_name='pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_items', to='masters.product', verbose_name='produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'item de pedido de venda',
                'verbose_name_plural': 'itens de pedidos de venda',
                'ordering': ['order', 'product__code'],
            },
        ),
        migrations.CreateModel(
            name='SalesProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('proposal_number', models.CharField(blank=True, max_length=80, verbose_name='proposta')),
                ('valid_until', models.DateField(verbose_name='válida até')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='draft', max_length=24, verbose_name='status')),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='valor total')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='aceita em')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='rejeitada em')),
                ('rejected_reason', models.TextField(blank=True, verbose_name='motivo da rejeição')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_proposals', to='masters.businesspartner', verbose_name='cliente')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='crm.opportunity', verbose_name='oportunidade')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'proposta comercial',
                'verbose_name_plural': 'propostas comerciais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='salesorder',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.salesproposal', verbose_name='proposta'),
        ),
        migrations.AddField(
            model_name='salescontract',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.salesproposal', verbose_name='proposta'),
        ),
        migrations.CreateModel(
            name='SalesProposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='preço unitário')),
                ('discount_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9, verbose_name='desconto (%)')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_proposal_items', to='masters.product', verbose_name='produto')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.salesproposal', verbose_name='proposta')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'item de proposta',
                'verbose_name_plural': 'itens de propostas',
                'ordering': ['proposal', 'product__code'],
            },
        ),
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('territory', models.CharField(blank=True, max_length=120, verbose_name='território')),
                ('commission_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=9, verbose_name='comissão (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_representative_profiles', to='masters.businesspartner', verbose_name='parceiro')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_representative_profiles', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'representante comercial',
                'verbose_name_plural': 'representantes comerciais',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='salesorder',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.salesrepresentative', verbose_name='representante'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.salesrepresentative', verbose_name='representante'),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('credit_limit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='limite de crédito')),
                ('credit_hold', models.BooleanField(default=False, verbose_name='bloqueio de crédito')),
                ('regulatory_hold', models.BooleanField(default=False, verbose_name='bloqueio regulatório')),
                ('payment_terms_days', models.PositiveIntegerField(default=0, verbose_name='prazo comercial em dias')),
                ('price_list_code', models.CharField(blank=True, max_length=40, verbose_name='tabela de preço')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_profiles', to='masters.businesspartner', verbose_name='cliente')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_profiles', to='crm.customergroup', verbose_name='grupo econômico')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('default_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_profiles', to='crm.saleschannel', verbose_name='canal padrão')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_profiles', to='crm.salesrepresentative', verbose_name='representante')),
            ],
            options={
                'verbose_name': 'perfil comercial do cliente',
                'verbose_name_plural': 'perfis comerciais de clientes',
                'ordering': ['customer__legal_name'],
            },
        ),
        migrations.AddIndex(
            model_name='customercontact',
            index=models.Index(fields=['tenant', 'customer', 'is_active'], name='crm_custome_tenant__f8dd54_idx'),
        ),
        migrations.AddIndex(
            model_name='customercontact',
            index=models.Index(fields=['tenant', 'is_primary'], name='crm_custome_tenant__a25cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='customergroup',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_custome_tenant__073001_idx'),
        ),
        migrations.AddIndex(
            model_name='customergroup',
            index=models.Index(fields=['code'], name='crm_custome_code_1f0ace_idx'),
        ),
        migrations.AddConstraint(
            model_name='customergroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_customer_group_code'),
        ),
        migrations.AddIndex(
            model_name='customerinteraction',
            index=models.Index(fields=['tenant', 'customer', 'occurred_at'], name='crm_custome_tenant__8bd4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinteraction',
            index=models.Index(fields=['tenant', 'interaction_type'], name='crm_custome_tenant__b4db94_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinteraction',
            index=models.Index(fields=['tenant', 'opportunity'], name='crm_custome_tenant__9cddc2_idx'),
        ),
        migrations.AddIndex(
            model_name='saleschannel',
            index=models.Index(fields=['tenant', 'channel_type', 'is_active'], name='crm_salesch_tenant__68eb9d_idx'),
        ),
        migrations.AddIndex(
            model_name='saleschannel',
            index=models.Index(fields=['code'], name='crm_salesch_code_401b6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleschannel',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_sales_channel_code'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'status'], name='crm_campaig_tenant__f09ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'start_date', 'end_date'], name='crm_campaig_tenant__447e7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_campaign_code'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['tenant', 'status', 'severity'], name='crm_custome_tenant__4fe176_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['tenant', 'customer'], name='crm_custome_tenant__cc7ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['tenant', 'product'], name='crm_custome_tenant__580f80_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['tenant', 'stock_lot'], name='crm_custome_tenant__cf026b_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['complaint_number'], name='crm_custome_complai_94859d_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercomplaint',
            constraint=models.UniqueConstraint(fields=('tenant', 'complaint_number'), name='unique_tenant_customer_complaint_number'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['tenant', 'order'], name='crm_salesor_tenant__12faa3_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['tenant', 'product'], name='crm_salesor_tenant__2dda6f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesproposal',
            index=models.Index(fields=['tenant', 'status'], name='crm_salespr_tenant__0030cc_idx'),
        ),
        migrations.AddIndex(
            model_name='salesproposal',
            index=models.Index(fields=['tenant', 'customer'], name='crm_salespr_tenant__990eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='salesproposal',
            index=models.Index(fields=['proposal_number'], name='crm_salespr_proposa_67d53b_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesproposal',
            constraint=models.UniqueConstraint(fields=('tenant', 'proposal_number'), name='unique_tenant_sales_proposal_number'),
        ),
        migrations.AddIndex(
            model_name='salescontract',
            index=models.Index(fields=['tenant', 'status'], name='crm_salesco_tenant__fc9ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='salescontract',
            index=models.Index(fields=['tenant', 'customer'], name='crm_salesco_tenant__0b690c_idx'),
        ),
        migrations.AddIndex(
            model_name='salescontract',
            index=models.Index(fields=['tenant', 'start_date', 'end_date'], name='crm_salesco_tenant__d4106c_idx'),
        ),
        migrations.AddIndex(
            model_name='salescontract',
            index=models.Index(fields=['contract_number'], name='crm_salesco_contrac_bdceac_idx'),
        ),
        migrations.AddConstraint(
            model_name='salescontract',
            constraint=models.UniqueConstraint(fields=('tenant', 'contract_number'), name='unique_tenant_sales_contract_number'),
        ),
        migrations.AddIndex(
            model_name='salesproposalitem',
            index=models.Index(fields=['tenant', 'proposal'], name='crm_salespr_tenant__3a5a17_idx'),
        ),
        migrations.AddIndex(
            model_name='salesproposalitem',
            index=models.Index(fields=['tenant', 'product'], name='crm_salespr_tenant__8de7a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesproposalitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'proposal', 'product'), name='unique_tenant_sales_proposal_item_product'),
        ),
        migrations.AddIndex(
            model_name='salesrepresentative',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_salesre_tenant__5f7a61_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrepresentative',
            index=models.Index(fields=['code'], name='crm_salesre_code_093def_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesrepresentative',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_sales_representative_code'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'status'], name='crm_salesor_tenant__2a054a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'customer'], name='crm_salesor_tenant__8c5521_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'requested_delivery_date'], name='crm_salesor_tenant__ceece7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_number'], name='crm_salesor_order_n_34272d_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'order_number'), name='unique_tenant_sales_order_number'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['tenant', 'stage'], name='crm_opportu_tenant__acca04_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['tenant', 'customer'], name='crm_opportu_tenant__a8e5ce_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['tenant', 'expected_close_date'], name='crm_opportu_tenant__0a7899_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['tenant', 'campaign'], name='crm_opportu_tenant__f910de_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['tenant', 'is_active'], name='crm_custome_tenant__5bcd34_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['tenant', 'credit_hold', 'regulatory_hold'], name='crm_custome_tenant__8c00f6_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['tenant', 'group'], name='crm_custome_tenant__0de73b_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'customer'), name='unique_tenant_customer_profile_partner'),
        ),
    ]
