# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('crm', '0001_initial'),
        ('fiscal', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='fiscal_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaints', to='fiscal.fiscaldocument', verbose_name='documento fiscal'),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaints', to='masters.product', verbose_name='produto'),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='severity_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='criticidade normalizada'),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF'),
        ),
    ]
