# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('crm', '0002_initial'),
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='stock_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaints', to='inventory.stocklot', verbose_name='lote'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_contacts', to='masters.businesspartner', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='role_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.organizationalrole', verbose_name='cargo/função normalizado'),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='crm.customercontact', verbose_name='contato'),
        ),
        migrations.AddIndex(
            model_name='customergroup',
            index=models.Index(fields=['is_active'], name='crm_custome_is_acti_49596b_idx'),
        ),
        migrations.AddIndex(
            model_name='customergroup',
            index=models.Index(fields=['code'], name='crm_custome_code_1f0ace_idx'),
        ),
        migrations.AddConstraint(
            model_name='customergroup',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_customer_group_code'),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='crm.customercontact', verbose_name='contato'),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_interactions', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_interactions', to='masters.businesspartner', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_profiles', to='masters.businesspartner', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_profiles', to='crm.customergroup', verbose_name='grupo econômico'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.campaign', verbose_name='campanha'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.customercontact', verbose_name='contato'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='masters.businesspartner', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='crm.opportunity', verbose_name='oportunidade'),
        ),
        migrations.AddIndex(
            model_name='saleschannel',
            index=models.Index(fields=['channel_type', 'is_active'], name='crm_salesch_channel_c7ae97_idx'),
        ),
        migrations.AddIndex(
            model_name='saleschannel',
            index=models.Index(fields=['code'], name='crm_salesch_code_401b6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleschannel',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_sales_channel_code'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.saleschannel', verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='default_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_profiles', to='crm.saleschannel', verbose_name='canal padrão'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='crm.saleschannel', verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='salescontract',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_sales_contracts', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por'),
        ),
        migrations.AddField(
            model_name='salescontract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_contracts', to='masters.businesspartner', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='salescontract',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.opportunity', verbose_name='oportunidade'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.saleschannel', verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.salescontract', verbose_name='contrato'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='masters.businesspartner', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliary.country', verbose_name='país'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaints', to='crm.salesorder', verbose_name='pedido de venda'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.salesorder', verbose_name='pedido'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_items', to='masters.product', verbose_name='produto'),
        ),
        migrations.AddField(
            model_name='salesproposal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_proposals', to='masters.businesspartner', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='salesproposal',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='crm.opportunity', verbose_name='oportunidade'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.salesproposal', verbose_name='proposta'),
        ),
        migrations.AddField(
            model_name='salescontract',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.salesproposal', verbose_name='proposta'),
        ),
        migrations.AddField(
            model_name='salesproposalitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_proposal_items', to='masters.product', verbose_name='produto'),
        ),
        migrations.AddField(
            model_name='salesproposalitem',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.salesproposal', verbose_name='proposta'),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_representative_profiles', to='masters.businesspartner', verbose_name='parceiro'),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_representative_profiles', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.salesrepresentative', verbose_name='representante'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.salesrepresentative', verbose_name='representante'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_profiles', to='crm.salesrepresentative', verbose_name='representante'),
        ),
        migrations.AddIndex(
            model_name='customercontact',
            index=models.Index(fields=['customer', 'is_active'], name='crm_custome_custome_0f5c02_idx'),
        ),
        migrations.AddIndex(
            model_name='customercontact',
            index=models.Index(fields=['is_primary'], name='crm_custome_is_prim_e15395_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinteraction',
            index=models.Index(fields=['customer', 'occurred_at'], name='crm_custome_custome_7eb97c_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinteraction',
            index=models.Index(fields=['interaction_type'], name='crm_custome_interac_75bbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinteraction',
            index=models.Index(fields=['opportunity'], name='crm_custome_opportu_fc1b79_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='crm_campaig_status_650d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'end_date'], name='crm_campaig_start_d_d0e61d_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_campaign_code'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['status', 'severity'], name='crm_custome_status_0f6347_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['customer'], name='crm_custome_custome_7edc11_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['product'], name='crm_custome_product_23ff8d_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['stock_lot'], name='crm_custome_stock_l_2adb71_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['complaint_number'], name='crm_custome_complai_94859d_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercomplaint',
            constraint=models.UniqueConstraint(fields=('complaint_number',), name='unique_customer_complaint_number'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['order'], name='crm_salesor_order_i_12be75_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['product'], name='crm_salesor_product_e0f5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesproposal',
            index=models.Index(fields=['status'], name='crm_salespr_status_6475d6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesproposal',
            index=models.Index(fields=['customer'], name='crm_salespr_custome_ecbec0_idx'),
        ),
        migrations.AddIndex(
            model_name='salesproposal',
            index=models.Index(fields=['proposal_number'], name='crm_salespr_proposa_67d53b_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesproposal',
            constraint=models.UniqueConstraint(fields=('proposal_number',), name='unique_sales_proposal_number'),
        ),
        migrations.AddIndex(
            model_name='salescontract',
            index=models.Index(fields=['status'], name='crm_salesco_status_9f0144_idx'),
        ),
        migrations.AddIndex(
            model_name='salescontract',
            index=models.Index(fields=['customer'], name='crm_salesco_custome_585761_idx'),
        ),
        migrations.AddIndex(
            model_name='salescontract',
            index=models.Index(fields=['start_date', 'end_date'], name='crm_salesco_start_d_0ba7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='salescontract',
            index=models.Index(fields=['contract_number'], name='crm_salesco_contrac_bdceac_idx'),
        ),
        migrations.AddConstraint(
            model_name='salescontract',
            constraint=models.UniqueConstraint(fields=('contract_number',), name='unique_sales_contract_number'),
        ),
        migrations.AddIndex(
            model_name='salesproposalitem',
            index=models.Index(fields=['proposal'], name='crm_salespr_proposa_a4fc34_idx'),
        ),
        migrations.AddIndex(
            model_name='salesproposalitem',
            index=models.Index(fields=['product'], name='crm_salespr_product_2c0c9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesproposalitem',
            constraint=models.UniqueConstraint(fields=('proposal', 'product'), name='unique_sales_proposal_item_product'),
        ),
        migrations.AddIndex(
            model_name='salesrepresentative',
            index=models.Index(fields=['is_active'], name='crm_salesre_is_acti_125180_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrepresentative',
            index=models.Index(fields=['code'], name='crm_salesre_code_093def_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesrepresentative',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_sales_representative_code'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='crm_salesor_status_0f6e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer'], name='crm_salesor_custome_5bf83c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['requested_delivery_date'], name='crm_salesor_request_9453e4_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_number'], name='crm_salesor_order_n_34272d_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('order_number',), name='unique_sales_order_number'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage'], name='crm_opportu_stage_610f02_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['customer'], name='crm_opportu_custome_aa3a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['expected_close_date'], name='crm_opportu_expecte_b650f1_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['campaign'], name='crm_opportu_campaig_726718_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['is_active'], name='crm_custome_is_acti_34fb3f_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['credit_hold', 'regulatory_hold'], name='crm_custome_credit__c9f554_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['group'], name='crm_custome_group_i_df2db3_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.UniqueConstraint(fields=('customer',), name='unique_customer_profile_partner'),
        ),
    ]
