# Generated by Django 6.0.7 on 2026-07-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0002_populate_auxiliary_references'),
        ('crm', '0002_customercomplaint_severity_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='cidade de origem'),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='cidade de origem normalizada'),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='state',
            field=models.CharField(blank=True, max_length=80, verbose_name='UF de origem'),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF de origem normalizada'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='cidade de entrega'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='cidade de entrega normalizada'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_neighborhood',
            field=models.CharField(blank=True, max_length=120, verbose_name='bairro de entrega'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=80, verbose_name='UF de entrega'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF de entrega normalizada'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='logradouro de entrega'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_zipcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP de entrega'),
        ),
    ]
