# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('crm', '0003_customercomplaint_city_customercomplaint_city_ref_and_more'),
        ('fiscal', '0004_add_zipcode_and_address'),
        ('inventory', '0002_remove_stockbalance_unique_tenant_stock_balance_address_status_and_more'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campaign',
            name='unique_tenant_campaign_code',
        ),
        migrations.RemoveConstraint(
            model_name='customercomplaint',
            name='unique_tenant_customer_complaint_number',
        ),
        migrations.RemoveConstraint(
            model_name='customergroup',
            name='unique_tenant_customer_group_code',
        ),
        migrations.RemoveConstraint(
            model_name='customerprofile',
            name='unique_tenant_customer_profile_partner',
        ),
        migrations.RemoveConstraint(
            model_name='saleschannel',
            name='unique_tenant_sales_channel_code',
        ),
        migrations.RemoveConstraint(
            model_name='salescontract',
            name='unique_tenant_sales_contract_number',
        ),
        migrations.RemoveConstraint(
            model_name='salesorder',
            name='unique_tenant_sales_order_number',
        ),
        migrations.RemoveConstraint(
            model_name='salesproposal',
            name='unique_tenant_sales_proposal_number',
        ),
        migrations.RemoveConstraint(
            model_name='salesproposalitem',
            name='unique_tenant_sales_proposal_item_product',
        ),
        migrations.RemoveConstraint(
            model_name='salesrepresentative',
            name='unique_tenant_sales_representative_code',
        ),
        migrations.RemoveIndex(
            model_name='campaign',
            name='crm_campaig_tenant__f09ba5_idx',
        ),
        migrations.RemoveIndex(
            model_name='campaign',
            name='crm_campaig_tenant__447e7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='customercomplaint',
            name='crm_custome_tenant__4fe176_idx',
        ),
        migrations.RemoveIndex(
            model_name='customercomplaint',
            name='crm_custome_tenant__cc7ccb_idx',
        ),
        migrations.RemoveIndex(
            model_name='customercomplaint',
            name='crm_custome_tenant__580f80_idx',
        ),
        migrations.RemoveIndex(
            model_name='customercomplaint',
            name='crm_custome_tenant__cf026b_idx',
        ),
        migrations.RemoveIndex(
            model_name='customercontact',
            name='crm_custome_tenant__f8dd54_idx',
        ),
        migrations.RemoveIndex(
            model_name='customercontact',
            name='crm_custome_tenant__a25cf1_idx',
        ),
        migrations.RemoveIndex(
            model_name='customergroup',
            name='crm_custome_tenant__073001_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerinteraction',
            name='crm_custome_tenant__8bd4f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerinteraction',
            name='crm_custome_tenant__b4db94_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerinteraction',
            name='crm_custome_tenant__9cddc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerprofile',
            name='crm_custome_tenant__5bcd34_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerprofile',
            name='crm_custome_tenant__8c00f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerprofile',
            name='crm_custome_tenant__0de73b_idx',
        ),
        migrations.RemoveIndex(
            model_name='opportunity',
            name='crm_opportu_tenant__acca04_idx',
        ),
        migrations.RemoveIndex(
            model_name='opportunity',
            name='crm_opportu_tenant__a8e5ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='opportunity',
            name='crm_opportu_tenant__0a7899_idx',
        ),
        migrations.RemoveIndex(
            model_name='opportunity',
            name='crm_opportu_tenant__f910de_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleschannel',
            name='crm_salesch_tenant__68eb9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='salescontract',
            name='crm_salesco_tenant__fc9ea4_idx',
        ),
        migrations.RemoveIndex(
            model_name='salescontract',
            name='crm_salesco_tenant__0b690c_idx',
        ),
        migrations.RemoveIndex(
            model_name='salescontract',
            name='crm_salesco_tenant__d4106c_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesorder',
            name='crm_salesor_tenant__2a054a_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesorder',
            name='crm_salesor_tenant__8c5521_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesorder',
            name='crm_salesor_tenant__ceece7_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesorderitem',
            name='crm_salesor_tenant__12faa3_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesorderitem',
            name='crm_salesor_tenant__2dda6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesproposal',
            name='crm_salespr_tenant__0030cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesproposal',
            name='crm_salespr_tenant__990eaa_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesproposalitem',
            name='crm_salespr_tenant__3a5a17_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesproposalitem',
            name='crm_salespr_tenant__8de7a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesrepresentative',
            name='crm_salesre_tenant__5f7a61_idx',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='customercomplaint',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='customercontact',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='customergroup',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='customerinteraction',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='saleschannel',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='salescontract',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='salesproposal',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='salesproposalitem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='salesrepresentative',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='crm_campaig_status_650d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'end_date'], name='crm_campaig_start_d_d0e61d_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['status', 'severity'], name='crm_custome_status_0f6347_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['customer'], name='crm_custome_custome_7edc11_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['product'], name='crm_custome_product_23ff8d_idx'),
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['stock_lot'], name='crm_custome_stock_l_2adb71_idx'),
        ),
        migrations.AddIndex(
            model_name='customercontact',
            index=models.Index(fields=['customer', 'is_active'], name='crm_custome_custome_0f5c02_idx'),
        ),
        migrations.AddIndex(
            model_name='customercontact',
            index=models.Index(fields=['is_primary'], name='crm_custome_is_prim_e15395_idx'),
        ),
        migrations.AddIndex(
            model_name='customergroup',
            index=models.Index(fields=['is_active'], name='crm_custome_is_acti_49596b_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinteraction',
            index=models.Index(fields=['customer', 'occurred_at'], name='crm_custome_custome_7eb97c_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinteraction',
            index=models.Index(fields=['interaction_type'], name='crm_custome_interac_75bbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinteraction',
            index=models.Index(fields=['opportunity'], name='crm_custome_opportu_fc1b79_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['is_active'], name='crm_custome_is_acti_34fb3f_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['credit_hold', 'regulatory_hold'], name='crm_custome_credit__c9f554_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['group'], name='crm_custome_group_i_df2db3_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage'], name='crm_opportu_stage_610f02_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['customer'], name='crm_opportu_custome_aa3a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['expected_close_date'], name='crm_opportu_expecte_b650f1_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['campaign'], name='crm_opportu_campaig_726718_idx'),
        ),
        migrations.AddIndex(
            model_name='saleschannel',
            index=models.Index(fields=['channel_type', 'is_active'], name='crm_salesch_channel_c7ae97_idx'),
        ),
        migrations.AddIndex(
            model_name='salescontract',
            index=models.Index(fields=['status'], name='crm_salesco_status_9f0144_idx'),
        ),
        migrations.AddIndex(
            model_name='salescontract',
            index=models.Index(fields=['customer'], name='crm_salesco_custome_585761_idx'),
        ),
        migrations.AddIndex(
            model_name='salescontract',
            index=models.Index(fields=['start_date', 'end_date'], name='crm_salesco_start_d_0ba7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='crm_salesor_status_0f6e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer'], name='crm_salesor_custome_5bf83c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['requested_delivery_date'], name='crm_salesor_request_9453e4_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['order'], name='crm_salesor_order_i_12be75_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['product'], name='crm_salesor_product_e0f5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesproposal',
            index=models.Index(fields=['status'], name='crm_salespr_status_6475d6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesproposal',
            index=models.Index(fields=['customer'], name='crm_salespr_custome_ecbec0_idx'),
        ),
        migrations.AddIndex(
            model_name='salesproposalitem',
            index=models.Index(fields=['proposal'], name='crm_salespr_proposa_a4fc34_idx'),
        ),
        migrations.AddIndex(
            model_name='salesproposalitem',
            index=models.Index(fields=['product'], name='crm_salespr_product_2c0c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrepresentative',
            index=models.Index(fields=['is_active'], name='crm_salesre_is_acti_125180_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_campaign_code'),
        ),
        migrations.AddConstraint(
            model_name='customercomplaint',
            constraint=models.UniqueConstraint(fields=('complaint_number',), name='unique_customer_complaint_number'),
        ),
        migrations.AddConstraint(
            model_name='customergroup',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_customer_group_code'),
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.UniqueConstraint(fields=('customer',), name='unique_customer_profile_partner'),
        ),
        migrations.AddConstraint(
            model_name='saleschannel',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_sales_channel_code'),
        ),
        migrations.AddConstraint(
            model_name='salescontract',
            constraint=models.UniqueConstraint(fields=('contract_number',), name='unique_sales_contract_number'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('order_number',), name='unique_sales_order_number'),
        ),
        migrations.AddConstraint(
            model_name='salesproposal',
            constraint=models.UniqueConstraint(fields=('proposal_number',), name='unique_sales_proposal_number'),
        ),
        migrations.AddConstraint(
            model_name='salesproposalitem',
            constraint=models.UniqueConstraint(fields=('proposal', 'product'), name='unique_sales_proposal_item_product'),
        ),
        migrations.AddConstraint(
            model_name='salesrepresentative',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_sales_representative_code'),
        ),
    ]
