# Generated by Django 5.2.16 on 2026-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_customercomplaint_country_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
    ]
