# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        ('procurement', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('version', models.CharField(max_length=40, verbose_name='versão')),
                ('method_code', models.CharField(max_length=80, verbose_name='código do método')),
                ('method_name', models.CharField(max_length=160, verbose_name='método')),
                ('parameter_name', models.CharField(max_length=160, verbose_name='parâmetro')),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='limite inferior')),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='limite superior')),
                ('alert_lower_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='alerta inferior')),
                ('alert_upper_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='alerta superior')),
                ('action_lower_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='ação inferior')),
                ('action_upper_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='ação superior')),
                ('trend_lower_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='tendência inferior')),
                ('trend_upper_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='tendência superior')),
                ('acceptance_criteria', models.TextField(blank=True, verbose_name='critério de aceitação')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovada'), ('obsolete', 'Obsoleta')], default='draft', max_length=24, verbose_name='status')),
                ('effective_from', models.DateField(verbose_name='vigência inicial')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='vigência final')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_analytical_specifications', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytical_specifications', to='masters.product', verbose_name='produto')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytical_specifications', to='inventory.stocklot', verbose_name='lote')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytical_specifications', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'especificação analítica',
                'verbose_name_plural': 'especificações analíticas',
                'ordering': ['product__code', 'parameter_name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='QualityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('analysis_number', models.CharField(blank=True, max_length=80, verbose_name='análise')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em execução'), ('completed', 'Concluída'), ('reviewed', 'Revisada'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=24, verbose_name='status')),
                ('method_reference', models.CharField(blank=True, max_length=120, verbose_name='método executado')),
                ('equipment_code', models.CharField(blank=True, max_length=80, verbose_name='equipamento')),
                ('reagent_lot', models.CharField(blank=True, max_length=80, verbose_name='lote do reagente')),
                ('standard_lot', models.CharField(blank=True, max_length=80, verbose_name='lote do padrão')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciada em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisada em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('rejected_reason', models.TextField(blank=True, verbose_name='motivo da rejeição')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_analyses_as_analyst', to=settings.AUTH_USER_MODEL, verbose_name='analista')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_analyses_as_approver', to=settings.AUTH_USER_MODEL, verbose_name='aprovador')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_analyses_as_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='revisor')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='quality.analyticalspecification', verbose_name='especificação')),
            ],
            options={
                'verbose_name': 'análise de qualidade',
                'verbose_name_plural': 'análises de qualidade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('parameter_name', models.CharField(max_length=160, verbose_name='parâmetro')),
                ('result_type', models.CharField(choices=[('quantitative', 'Quantitativo'), ('qualitative', 'Qualitativo')], max_length=24, verbose_name='tipo')),
                ('numeric_result', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='resultado numérico')),
                ('text_result', models.CharField(blank=True, max_length=255, verbose_name='resultado textual')),
                ('result_status', models.CharField(choices=[('pending', 'Pendente'), ('compliant', 'Conforme'), ('alert_limit', 'Limite de alerta'), ('action_limit', 'Limite de ação'), ('out_of_trend', 'OOT'), ('out_of_specification', 'OOS')], default='pending', max_length=32, verbose_name='status do resultado')),
                ('attachment_reference', models.CharField(blank=True, max_length=255, verbose_name='anexo')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registrado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality.qualityanalysis', verbose_name='análise')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_quality_results', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='quality.analyticalspecification', verbose_name='especificação')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_results', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'resultado analítico',
                'verbose_name_plural': 'resultados analíticos',
                'ordering': ['analysis__analysis_number', 'parameter_name'],
            },
        ),
        migrations.CreateModel(
            name='QualitySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('sample_number', models.CharField(blank=True, max_length=80, verbose_name='amostra')),
                ('sample_type', models.CharField(choices=[('receipt', 'Recebimento'), ('production', 'Produção'), ('stability', 'Estabilidade'), ('validation', 'Validação'), ('complaint', 'Reclamação'), ('investigation', 'Investigação'), ('environmental', 'Monitoramento ambiental')], max_length=32, verbose_name='tipo')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14, verbose_name='quantidade')),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('collected', 'Coletada'), ('received', 'Recebida'), ('in_analysis', 'Em análise'), ('reviewed', 'Revisada'), ('approved', 'Aprovada'), ('rejected', 'Reprovada'), ('cancelled', 'Cancelada')], default='requested', max_length=24, verbose_name='status')),
                ('collection_point', models.CharField(blank=True, max_length=180, verbose_name='ponto de coleta')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='coletada em')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='recebida em')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciada em')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisada em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='reprovada em')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motivo da reprovação')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_quality_samples', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collected_quality_samples', to=settings.AUTH_USER_MODEL, verbose_name='coletada por')),
                ('collection_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_samples', to='masters.site', verbose_name='unidade/planta de coleta')),
                ('customer_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_samples', to='crm.customercomplaint', verbose_name='reclamação de cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_samples', to='masters.product', verbose_name='produto')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_quality_samples', to=settings.AUTH_USER_MODEL, verbose_name='recebida por')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_quality_samples', to=settings.AUTH_USER_MODEL, verbose_name='reprovada por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_quality_samples', to=settings.AUTH_USER_MODEL, verbose_name='revisada por')),
                ('source_production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_samples', to='production.productionorder', verbose_name='ordem de produção')),
                ('source_purchase_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_samples', to='procurement.purchasereceipt', verbose_name='recebimento de compra')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_samples', to='quality.analyticalspecification', verbose_name='especificação')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_quality_samples', to=settings.AUTH_USER_MODEL, verbose_name='iniciada por')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_samples', to='inventory.stocklot', verbose_name='lote')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_samples', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'amostra de qualidade',
                'verbose_name_plural': 'amostras de qualidade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('document_number', models.CharField(blank=True, max_length=80, verbose_name='documento')),
                ('document_type', models.CharField(choices=[('certificate_of_analysis', 'Certificado de análise'), ('analytical_report', 'Laudo analítico'), ('release_label', 'Etiqueta de liberação'), ('release_report', 'Relatório de liberação')], max_length=40, verbose_name='tipo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('issued', 'Emitido'), ('cancelled', 'Cancelado')], default='draft', max_length=24, verbose_name='status')),
                ('summary', models.TextField(blank=True, verbose_name='resumo')),
                ('conclusion', models.TextField(verbose_name='conclusão')),
                ('attachment_reference', models.CharField(blank=True, max_length=255, verbose_name='arquivo emitido')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='emitido em')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válido até')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_quality_documents', to=settings.AUTH_USER_MODEL, verbose_name='emitido por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_documents', to='masters.product', verbose_name='produto')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_documents', to='inventory.stocklot', verbose_name='lote')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_documents', to='quality.qualitysample', verbose_name='amostra')),
            ],
            options={
                'verbose_name': 'documento de qualidade',
                'verbose_name_plural': 'documentos de qualidade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='qualityanalysis',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='quality.qualitysample', verbose_name='amostra'),
        ),
        migrations.CreateModel(
            name='LaboratoryInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('investigation_number', models.CharField(blank=True, max_length=80, verbose_name='investigação')),
                ('investigation_type', models.CharField(choices=[('laboratory', 'Investigação laboratorial'), ('repeat', 'Repetição justificada'), ('retest', 'Reteste'), ('resampling', 'Reamostragem')], max_length=24, verbose_name='tipo')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em andamento'), ('concluded', 'Concluída'), ('cancelled', 'Cancelada')], default='open', max_length=24, verbose_name='status')),
                ('justification', models.TextField(verbose_name='justificativa')),
                ('root_cause', models.TextField(blank=True, verbose_name='causa raiz')),
                ('conclusion', models.TextField(blank=True, verbose_name='conclusão')),
                ('repeat_justification', models.TextField(blank=True, verbose_name='justificativa de repetição')),
                ('retest_justification', models.TextField(blank=True, verbose_name='justificativa de reteste')),
                ('resampling_justification', models.TextField(blank=True, verbose_name='justificativa de reamostragem')),
                ('repeat_approved', models.BooleanField(default=False, verbose_name='repetição aprovada')),
                ('retest_approved', models.BooleanField(default=False, verbose_name='reteste aprovado')),
                ('resampling_approved', models.BooleanField(default=False, verbose_name='reamostragem aprovada')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='aberta em')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciada em')),
                ('concluded_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('concluded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concluded_laboratory_investigations', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opened_laboratory_investigations', to=settings.AUTH_USER_MODEL, verbose_name='aberta por')),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investigations', to='quality.qualityanalysis', verbose_name='análise')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investigations', to='quality.qualityresult', verbose_name='resultado')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigations', to='quality.qualitysample', verbose_name='amostra')),
            ],
            options={
                'verbose_name': 'investigação laboratorial',
                'verbose_name_plural': 'investigações laboratoriais',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddIndex(
            model_name='analyticalspecification',
            index=models.Index(fields=['product', 'status'], name='quality_ana_product_dfecde_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticalspecification',
            index=models.Index(fields=['stock_lot'], name='quality_ana_stock_l_1de0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticalspecification',
            index=models.Index(fields=['method_code'], name='quality_ana_method__328963_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticalspecification',
            index=models.Index(fields=['effective_from', 'effective_to'], name='quality_ana_effecti_711c48_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticalspecification',
            constraint=models.UniqueConstraint(fields=('product', 'stock_lot', 'version', 'method_code', 'parameter_name'), name='unique_qc_spec_product_lot_version'),
        ),
        migrations.AddIndex(
            model_name='qualityresult',
            index=models.Index(fields=['analysis'], name='quality_qua_analysi_788e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityresult',
            index=models.Index(fields=['specification'], name='quality_qua_specifi_de43e5_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityresult',
            index=models.Index(fields=['result_status'], name='quality_qua_result__a04c74_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityresult',
            index=models.Index(fields=['parameter_name'], name='quality_qua_paramet_01817d_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitysample',
            index=models.Index(fields=['sample_type', 'status'], name='quality_qua_sample__0b1df7_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitysample',
            index=models.Index(fields=['product'], name='quality_qua_product_5867eb_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitysample',
            index=models.Index(fields=['stock_lot'], name='quality_qua_stock_l_d78e14_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitysample',
            index=models.Index(fields=['sample_number'], name='quality_qua_sample__da3ea1_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualitysample',
            constraint=models.UniqueConstraint(fields=('sample_number',), name='unique_quality_sample_number'),
        ),
        migrations.AddIndex(
            model_name='qualitydocument',
            index=models.Index(fields=['document_type', 'status'], name='quality_qua_documen_874a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitydocument',
            index=models.Index(fields=['sample'], name='quality_qua_sample__99f274_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitydocument',
            index=models.Index(fields=['product'], name='quality_qua_product_6f0bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitydocument',
            index=models.Index(fields=['stock_lot'], name='quality_qua_stock_l_9929fc_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitydocument',
            index=models.Index(fields=['document_number'], name='quality_qua_documen_ec1101_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualitydocument',
            constraint=models.UniqueConstraint(fields=('document_number',), name='unique_quality_document_number'),
        ),
        migrations.AddIndex(
            model_name='qualityanalysis',
            index=models.Index(fields=['sample', 'status'], name='quality_qua_sample__5b489a_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityanalysis',
            index=models.Index(fields=['specification'], name='quality_qua_specifi_23c15c_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityanalysis',
            index=models.Index(fields=['analysis_number'], name='quality_qua_analysi_ea4585_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualityanalysis',
            constraint=models.UniqueConstraint(fields=('analysis_number',), name='unique_quality_analysis_number'),
        ),
        migrations.AddIndex(
            model_name='laboratoryinvestigation',
            index=models.Index(fields=['status', 'investigation_type'], name='quality_lab_status_4a2c49_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryinvestigation',
            index=models.Index(fields=['sample'], name='quality_lab_sample__0b7c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryinvestigation',
            index=models.Index(fields=['result'], name='quality_lab_result__564b89_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryinvestigation',
            index=models.Index(fields=['investigation_number'], name='quality_lab_investi_5a5d49_idx'),
        ),
        migrations.AddConstraint(
            model_name='laboratoryinvestigation',
            constraint=models.UniqueConstraint(fields=('investigation_number',), name='unique_lab_investigation_number'),
        ),
    ]
