# Generated by Django 6.0.7 on 2026-07-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_add_zipcode_and_address'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitysample',
            name='collection_point',
            field=models.CharField(blank=True, max_length=180, verbose_name='ponto de coleta'),
        ),
        migrations.AddField(
            model_name='qualitysample',
            name='collection_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_samples', to='masters.site', verbose_name='unidade/planta de coleta'),
        ),
    ]
