# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_campaign_unique_tenant_campaign_code_and_more'),
        ('inventory', '0002_remove_stockbalance_unique_tenant_stock_balance_address_status_and_more'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('procurement', '0004_remove_purchaseorder_unique_tenant_purchase_order_number_and_more'),
        ('production', '0002_remove_productionorder_unique_tenant_production_order_number_and_more'),
        ('quality', '0002_qualitysample_collection_point_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analyticalspecification',
            name='unique_tenant_qc_spec_product_lot_version',
        ),
        migrations.RemoveConstraint(
            model_name='laboratoryinvestigation',
            name='unique_tenant_lab_investigation_number',
        ),
        migrations.RemoveConstraint(
            model_name='qualityanalysis',
            name='unique_tenant_quality_analysis_number',
        ),
        migrations.RemoveConstraint(
            model_name='qualitydocument',
            name='unique_tenant_quality_document_number',
        ),
        migrations.RemoveConstraint(
            model_name='qualitysample',
            name='unique_tenant_quality_sample_number',
        ),
        migrations.RemoveIndex(
            model_name='analyticalspecification',
            name='quality_ana_tenant__303dd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='analyticalspecification',
            name='quality_ana_tenant__2c6b16_idx',
        ),
        migrations.RemoveIndex(
            model_name='analyticalspecification',
            name='quality_ana_tenant__e9ddfb_idx',
        ),
        migrations.RemoveIndex(
            model_name='analyticalspecification',
            name='quality_ana_tenant__83905c_idx',
        ),
        migrations.RemoveIndex(
            model_name='laboratoryinvestigation',
            name='quality_lab_tenant__b9e71b_idx',
        ),
        migrations.RemoveIndex(
            model_name='laboratoryinvestigation',
            name='quality_lab_tenant__4e35fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='laboratoryinvestigation',
            name='quality_lab_tenant__c1d699_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityanalysis',
            name='quality_qua_tenant__a22366_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityanalysis',
            name='quality_qua_tenant__86130d_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualitydocument',
            name='quality_qua_tenant__4d3bc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualitydocument',
            name='quality_qua_tenant__5c0717_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualitydocument',
            name='quality_qua_tenant__b3e18d_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualitydocument',
            name='quality_qua_tenant__3c16c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityresult',
            name='quality_qua_tenant__3c9487_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityresult',
            name='quality_qua_tenant__5edd02_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityresult',
            name='quality_qua_tenant__24c16e_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualitysample',
            name='quality_qua_tenant__3a8c9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualitysample',
            name='quality_qua_tenant__3f7bfd_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualitysample',
            name='quality_qua_tenant__1289f2_idx',
        ),
        migrations.RemoveField(
            model_name='analyticalspecification',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='laboratoryinvestigation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='qualityanalysis',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='qualitydocument',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='qualityresult',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='qualitysample',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='analyticalspecification',
            index=models.Index(fields=['product', 'status'], name='quality_ana_product_dfecde_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticalspecification',
            index=models.Index(fields=['stock_lot'], name='quality_ana_stock_l_1de0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticalspecification',
            index=models.Index(fields=['method_code'], name='quality_ana_method__328963_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticalspecification',
            index=models.Index(fields=['effective_from', 'effective_to'], name='quality_ana_effecti_711c48_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryinvestigation',
            index=models.Index(fields=['status', 'investigation_type'], name='quality_lab_status_4a2c49_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryinvestigation',
            index=models.Index(fields=['sample'], name='quality_lab_sample__0b7c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryinvestigation',
            index=models.Index(fields=['result'], name='quality_lab_result__564b89_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityanalysis',
            index=models.Index(fields=['sample', 'status'], name='quality_qua_sample__5b489a_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityanalysis',
            index=models.Index(fields=['specification'], name='quality_qua_specifi_23c15c_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitydocument',
            index=models.Index(fields=['document_type', 'status'], name='quality_qua_documen_874a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitydocument',
            index=models.Index(fields=['sample'], name='quality_qua_sample__99f274_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitydocument',
            index=models.Index(fields=['product'], name='quality_qua_product_6f0bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitydocument',
            index=models.Index(fields=['stock_lot'], name='quality_qua_stock_l_9929fc_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityresult',
            index=models.Index(fields=['analysis'], name='quality_qua_analysi_788e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityresult',
            index=models.Index(fields=['specification'], name='quality_qua_specifi_de43e5_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityresult',
            index=models.Index(fields=['result_status'], name='quality_qua_result__a04c74_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitysample',
            index=models.Index(fields=['sample_type', 'status'], name='quality_qua_sample__0b1df7_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitysample',
            index=models.Index(fields=['product'], name='quality_qua_product_5867eb_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitysample',
            index=models.Index(fields=['stock_lot'], name='quality_qua_stock_l_d78e14_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticalspecification',
            constraint=models.UniqueConstraint(fields=('product', 'stock_lot', 'version', 'method_code', 'parameter_name'), name='unique_qc_spec_product_lot_version'),
        ),
        migrations.AddConstraint(
            model_name='laboratoryinvestigation',
            constraint=models.UniqueConstraint(fields=('investigation_number',), name='unique_lab_investigation_number'),
        ),
        migrations.AddConstraint(
            model_name='qualityanalysis',
            constraint=models.UniqueConstraint(fields=('analysis_number',), name='unique_quality_analysis_number'),
        ),
        migrations.AddConstraint(
            model_name='qualitydocument',
            constraint=models.UniqueConstraint(fields=('document_number',), name='unique_quality_document_number'),
        ),
        migrations.AddConstraint(
            model_name='qualitysample',
            constraint=models.UniqueConstraint(fields=('sample_number',), name='unique_quality_sample_number'),
        ),
    ]
