# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('asset_code', models.CharField(blank=True, max_length=80, verbose_name='código do ativo')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('asset_type', models.CharField(choices=[('equipment', 'Equipamento'), ('instrument', 'Instrumento'), ('production_line', 'Linha'), ('room', 'Sala'), ('utility', 'Utilidade'), ('critical_component', 'Componente crítico')], max_length=32, verbose_name='tipo')),
                ('area', models.CharField(blank=True, max_length=120, verbose_name='área')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='localização')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='fabricante')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='modelo')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='número de série')),
                ('is_critical', models.BooleanField(default=False, verbose_name='crítico')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('available', 'Disponível'), ('under_maintenance', 'Em manutenção'), ('under_calibration', 'Em calibração'), ('cleaning', 'Em limpeza'), ('sanitization', 'Em sanitização'), ('blocked', 'Interditado'), ('decommissioned', 'Desativado')], default='draft', max_length=32, verbose_name='status')),
                ('qualification_status', models.CharField(choices=[('pending', 'Pendente'), ('qualified', 'Qualificado'), ('expired', 'Vencido'), ('not_required', 'Não aplicável')], default='pending', max_length=24, verbose_name='status de qualificação')),
                ('qualification_valid_until', models.DateField(blank=True, null=True, verbose_name='qualificação válida até')),
                ('calibration_required', models.BooleanField(default=False, verbose_name='exige calibração')),
                ('calibration_status', models.CharField(choices=[('not_required', 'Não aplicável'), ('valid', 'Válida'), ('due', 'A vencer'), ('expired', 'Vencida')], default='not_required', max_length=24, verbose_name='status de calibração')),
                ('calibration_valid_until', models.DateField(blank=True, null=True, verbose_name='calibração válida até')),
                ('cleaning_required', models.BooleanField(default=False, verbose_name='exige limpeza')),
                ('sanitization_required', models.BooleanField(default=False, verbose_name='exige sanitização')),
                ('blocked_reason', models.TextField(blank=True, verbose_name='motivo de interdição')),
                ('blocked_at', models.DateTimeField(blank=True, null=True, verbose_name='interditado em')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='liberado em')),
                ('area_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.businessarea', verbose_name='área normalizada')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blocked_assets', to=settings.AUTH_USER_MODEL, verbose_name='interditado por')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_assets', to=settings.AUTH_USER_MODEL, verbose_name='liberado por')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_assets', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assets', to='masters.site', verbose_name='unidade/planta')),
            ],
            options={
                'verbose_name': 'equipamento ou ativo crítico',
                'verbose_name_plural': 'equipamentos e ativos críticos',
                'ordering': ['asset_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('used_at', models.DateTimeField(verbose_name='usado em')),
                ('usage_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade de uso')),
                ('usage_unit', models.CharField(max_length=40, verbose_name='unidade de uso')),
                ('event_reference', models.CharField(blank=True, max_length=120, verbose_name='referência do evento')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_logs', to='maintenance.equipmentasset', verbose_name='ativo')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('source_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_usage_logs', to='inventory.stocklot', verbose_name='lote')),
            ],
            options={
                'verbose_name': 'uso de equipamento',
                'verbose_name_plural': 'usos de equipamentos',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMetricReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('report_type', models.CharField(choices=[('availability', 'Disponibilidade'), ('downtime', 'Paradas'), ('mtbf', 'MTBF'), ('mttr', 'MTTR'), ('due_dates', 'Vencimentos')], max_length=24, verbose_name='tipo de relatório')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('period_start', models.DateTimeField(verbose_name='início do período')),
                ('period_end', models.DateTimeField(verbose_name='fim do período')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('generated', 'Gerado')], default='draft', max_length=24, verbose_name='status')),
                ('availability_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='disponibilidade %')),
                ('downtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='horas paradas')),
                ('mtbf_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='MTBF horas')),
                ('mttr_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='MTTR horas')),
                ('overdue_orders', models.PositiveIntegerField(default=0, verbose_name='ordens atrasadas')),
                ('due_soon_orders', models.PositiveIntegerField(default=0, verbose_name='ordens a vencer')),
                ('content_reference', models.CharField(blank=True, max_length=255, verbose_name='referência do relatório')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='gerado em')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metric_reports', to='maintenance.equipmentasset', verbose_name='ativo')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_maintenance_metric_reports', to=settings.AUTH_USER_MODEL, verbose_name='gerado por')),
            ],
            options={
                'verbose_name': 'indicador de manutenção',
                'verbose_name_plural': 'indicadores de manutenção',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('order_number', models.CharField(blank=True, max_length=80, verbose_name='ordem')),
                ('order_type', models.CharField(choices=[('preventive_maintenance', 'Manutenção preventiva'), ('corrective_maintenance', 'Manutenção corretiva'), ('calibration', 'Calibração'), ('qualification', 'Qualificação'), ('cleaning', 'Limpeza'), ('sanitization', 'Sanitização')], max_length=32, verbose_name='tipo')),
                ('trigger_type', models.CharField(choices=[('time', 'Tempo'), ('usage', 'Uso'), ('event', 'Evento'), ('lot', 'Lote'), ('rule', 'Regra configurável')], max_length=24, verbose_name='gatilho')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em execução'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='open', max_length=24, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=24, verbose_name='prioridade')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('description', models.TextField(verbose_name='descrição')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciada em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('completion_summary', models.TextField(blank=True, verbose_name='resumo de conclusão')),
                ('evidence_reference', models.CharField(blank=True, max_length=255, verbose_name='referência da evidência')),
                ('content_hash', models.CharField(blank=True, max_length=128, verbose_name='hash da evidência')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_orders', to='maintenance.equipmentasset', verbose_name='ativo')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_maintenance_orders', to=settings.AUTH_USER_MODEL, verbose_name='cancelada por')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_maintenance_orders', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opened_maintenance_orders', to=settings.AUTH_USER_MODEL, verbose_name='aberta por')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_maintenance_orders', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('source_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_orders', to='inventory.stocklot', verbose_name='lote')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_maintenance_orders', to=settings.AUTH_USER_MODEL, verbose_name='iniciada por')),
            ],
            options={
                'verbose_name': 'ordem de manutenção e calibração',
                'verbose_name_plural': 'ordens de manutenção e calibração',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('downtime_type', models.CharField(choices=[('planned', 'Planejada'), ('unplanned', 'Não planejada'), ('maintenance', 'Manutenção'), ('calibration', 'Calibração'), ('cleaning', 'Limpeza')], max_length=24, verbose_name='tipo de parada')),
                ('started_at', models.DateTimeField(verbose_name='iniciada em')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrada em')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='duração em horas')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtimes', to='maintenance.equipmentasset', verbose_name='ativo')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='downtimes', to='maintenance.maintenanceorder', verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'parada de equipamento',
                'verbose_name_plural': 'paradas de equipamentos',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('plan_type', models.CharField(choices=[('preventive_maintenance', 'Manutenção preventiva'), ('corrective_maintenance', 'Manutenção corretiva'), ('calibration', 'Calibração'), ('qualification', 'Qualificação'), ('cleaning', 'Limpeza'), ('sanitization', 'Sanitização')], max_length=32, verbose_name='tipo de plano')),
                ('trigger_type', models.CharField(choices=[('time', 'Tempo'), ('usage', 'Uso'), ('event', 'Evento'), ('lot', 'Lote'), ('rule', 'Regra configurável')], max_length=24, verbose_name='gatilho')),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='intervalo em dias')),
                ('usage_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='limite de uso')),
                ('usage_unit', models.CharField(blank=True, max_length=40, verbose_name='unidade de uso')),
                ('event_name', models.CharField(blank=True, max_length=120, verbose_name='evento')),
                ('lot_rule', models.CharField(blank=True, max_length=160, verbose_name='regra por lote')),
                ('rule_expression', models.TextField(blank=True, verbose_name='regra configurável')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='próximo vencimento')),
                ('description', models.TextField(verbose_name='descrição')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='maintenance.equipmentasset', verbose_name='ativo')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_maintenance_plans', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'plano de manutenção e calibração',
                'verbose_name_plural': 'planos de manutenção e calibração',
                'ordering': ['asset__asset_code', 'plan_type', 'next_due_date'],
            },
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='maintenance.maintenanceplan', verbose_name='plano'),
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['asset_type', 'status'], name='maintenance_asset_t_6fe280_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['qualification_status'], name='maintenance_qualifi_57344b_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['calibration_status'], name='maintenance_calibra_2f132f_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['calibration_valid_until'], name='maintenance_calibra_53decb_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['qualification_valid_until'], name='maintenance_qualifi_b1b530_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['responsible'], name='maintenance_respons_90b200_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['asset_code'], name='maintenance_asset_c_b78e5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentasset',
            constraint=models.UniqueConstraint(fields=('asset_code',), name='unique_equipment_asset_code'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['asset', 'used_at'], name='maintenance_asset_i_f041d3_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['source_lot'], name='maintenance_source__97f2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['event_reference'], name='maintenance_event_r_206ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancemetricreport',
            index=models.Index(fields=['asset', 'report_type'], name='maintenance_asset_i_b01c67_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancemetricreport',
            index=models.Index(fields=['status'], name='maintenance_status_e8d933_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancemetricreport',
            index=models.Index(fields=['period_start', 'period_end'], name='maintenance_period__790a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancemetricreport',
            index=models.Index(fields=['generated_by'], name='maintenance_generat_01a0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdowntime',
            index=models.Index(fields=['asset', 'started_at'], name='maintenance_asset_i_bbf1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdowntime',
            index=models.Index(fields=['downtime_type'], name='maintenance_downtim_e520e2_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdowntime',
            index=models.Index(fields=['order'], name='maintenance_order_i_5bd6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['asset', 'active'], name='maintenance_asset_i_64290f_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['plan_type', 'trigger_type'], name='maintenance_plan_ty_d97a23_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['next_due_date'], name='maintenance_next_du_b64446_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['responsible'], name='maintenance_respons_2c4bce_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceorder',
            index=models.Index(fields=['asset', 'status'], name='maintenance_asset_i_f4c435_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceorder',
            index=models.Index(fields=['plan'], name='maintenance_plan_id_080555_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceorder',
            index=models.Index(fields=['order_type', 'trigger_type'], name='maintenance_order_t_21e50c_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceorder',
            index=models.Index(fields=['due_date'], name='maintenance_due_dat_740544_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceorder',
            index=models.Index(fields=['responsible'], name='maintenance_respons_1f0f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceorder',
            index=models.Index(fields=['order_number'], name='maintenance_order_n_25285f_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceorder',
            constraint=models.UniqueConstraint(fields=('order_number',), name='unique_maintenance_order_number'),
        ),
    ]
