# Generated by Django 6.0.7 on 2026-07-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_equipmentasset_area_ref'),
        ('masters', '0003_add_zipcode_and_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentasset',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assets', to='masters.site', verbose_name='unidade/planta'),
        ),
    ]
