# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('inventory', '0002_remove_stockbalance_unique_tenant_stock_balance_address_status_and_more'),
        ('maintenance', '0003_equipmentasset_site'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipmentasset',
            name='unique_tenant_equipment_asset_code',
        ),
        migrations.RemoveConstraint(
            model_name='maintenanceorder',
            name='unique_tenant_maintenance_order_number',
        ),
        migrations.RemoveIndex(
            model_name='equipmentasset',
            name='maintenance_tenant__7ecd27_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentasset',
            name='maintenance_tenant__907442_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentasset',
            name='maintenance_tenant__0d34df_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentasset',
            name='maintenance_tenant__2a59ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentasset',
            name='maintenance_tenant__42a626_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentasset',
            name='maintenance_tenant__21e9bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentdowntime',
            name='maintenance_tenant__63260d_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentdowntime',
            name='maintenance_tenant__45f61c_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentdowntime',
            name='maintenance_tenant__818637_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentusagelog',
            name='maintenance_tenant__db08de_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentusagelog',
            name='maintenance_tenant__0b07ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipmentusagelog',
            name='maintenance_tenant__56d96a_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenancemetricreport',
            name='maintenance_tenant__49aa65_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenancemetricreport',
            name='maintenance_tenant__739f6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenancemetricreport',
            name='maintenance_tenant__3aebad_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenancemetricreport',
            name='maintenance_tenant__464f3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceorder',
            name='maintenance_tenant__d11e9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceorder',
            name='maintenance_tenant__68870a_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceorder',
            name='maintenance_tenant__197e95_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceorder',
            name='maintenance_tenant__e32e53_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceorder',
            name='maintenance_tenant__820089_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceplan',
            name='maintenance_tenant__8861d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceplan',
            name='maintenance_tenant__7f2820_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceplan',
            name='maintenance_tenant__45ee57_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceplan',
            name='maintenance_tenant__4a3a9f_idx',
        ),
        migrations.RemoveField(
            model_name='equipmentasset',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='equipmentdowntime',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='equipmentusagelog',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='maintenancemetricreport',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='maintenanceorder',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['asset_type', 'status'], name='maintenance_asset_t_6fe280_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['qualification_status'], name='maintenance_qualifi_57344b_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['calibration_status'], name='maintenance_calibra_2f132f_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['calibration_valid_until'], name='maintenance_calibra_53decb_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['qualification_valid_until'], name='maintenance_qualifi_b1b530_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentasset',
            index=models.Index(fields=['responsible'], name='maintenance_respons_90b200_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdowntime',
            index=models.Index(fields=['asset', 'started_at'], name='maintenance_asset_i_bbf1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdowntime',
            index=models.Index(fields=['downtime_type'], name='maintenance_downtim_e520e2_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdowntime',
            index=models.Index(fields=['order'], name='maintenance_order_i_5bd6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['asset', 'used_at'], name='maintenance_asset_i_f041d3_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['source_lot'], name='maintenance_source__97f2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['event_reference'], name='maintenance_event_r_206ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancemetricreport',
            index=models.Index(fields=['asset', 'report_type'], name='maintenance_asset_i_b01c67_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancemetricreport',
            index=models.Index(fields=['status'], name='maintenance_status_e8d933_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancemetricreport',
            index=models.Index(fields=['period_start', 'period_end'], name='maintenance_period__790a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancemetricreport',
            index=models.Index(fields=['generated_by'], name='maintenance_generat_01a0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceorder',
            index=models.Index(fields=['asset', 'status'], name='maintenance_asset_i_f4c435_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceorder',
            index=models.Index(fields=['plan'], name='maintenance_plan_id_080555_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceorder',
            index=models.Index(fields=['order_type', 'trigger_type'], name='maintenance_order_t_21e50c_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceorder',
            index=models.Index(fields=['due_date'], name='maintenance_due_dat_740544_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceorder',
            index=models.Index(fields=['responsible'], name='maintenance_respons_1f0f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['asset', 'active'], name='maintenance_asset_i_64290f_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['plan_type', 'trigger_type'], name='maintenance_plan_ty_d97a23_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['next_due_date'], name='maintenance_next_du_b64446_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['responsible'], name='maintenance_respons_2c4bce_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentasset',
            constraint=models.UniqueConstraint(fields=('asset_code',), name='unique_equipment_asset_code'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceorder',
            constraint=models.UniqueConstraint(fields=('order_number',), name='unique_maintenance_order_number'),
        ),
    ]
