# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClientApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='codigo')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('client_id', models.CharField(max_length=120, verbose_name='client id')),
                ('secret_hash', models.CharField(blank=True, max_length=255, verbose_name='hash do segredo')),
                ('scopes', models.JSONField(default=list, verbose_name='escopos')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('suspended', 'Suspenso'), ('revoked', 'Revogado')], default='active', max_length=32, verbose_name='status')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='ultimo uso em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_api_client_applications', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'cliente de API',
                'verbose_name_plural': 'clientes de API',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='id da requisicao')),
                ('api_version', models.CharField(db_index=True, default='legacy', max_length=32, verbose_name='versao da API')),
                ('method', models.CharField(max_length=16, verbose_name='metodo')),
                ('path', models.CharField(max_length=500, verbose_name='caminho')),
                ('endpoint_name', models.CharField(blank=True, max_length=180, verbose_name='endpoint')),
                ('status_code', models.PositiveIntegerField(db_index=True, verbose_name='status HTTP')),
                ('outcome', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro')], max_length=16, verbose_name='resultado')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP remoto')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='duracao ms')),
                ('safe_context', models.JSONField(blank=True, default=dict, verbose_name='contexto seguro')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_call_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('client_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_call_logs', to='integrations.apiclientapplication', verbose_name='cliente de API')),
            ],
            options={
                'verbose_name': 'log de chamada de API',
                'verbose_name_plural': 'logs de chamadas de API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='codigo')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('provider_type', models.CharField(choices=[('erp', 'ERP externo'), ('fiscal_system', 'Sistema fiscal'), ('laboratory', 'Laboratorio'), ('equipment', 'Equipamento'), ('email_provider', 'Provedor de email'), ('openai', 'OpenAI'), ('bi', 'BI')], max_length=32, verbose_name='tipo de provedor')),
                ('base_url', models.URLField(blank=True, max_length=500, verbose_name='URL base')),
                ('auth_type', models.CharField(choices=[('none', 'Sem autenticacao'), ('api_key', 'API key'), ('oauth2', 'OAuth2'), ('basic', 'Basic auth'), ('token', 'Token')], default='none', max_length=32, verbose_name='tipo de autenticacao')),
                ('secret_reference', models.CharField(blank=True, max_length=255, verbose_name='referencia segura do segredo')),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='configuracao segura')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('error', 'Erro'), ('archived', 'Arquivado')], default='draft', max_length=32, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True, verbose_name='ultimo teste em')),
                ('last_error', models.TextField(blank=True, verbose_name='ultimo erro')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_connectors', to=settings.AUTH_USER_MODEL, verbose_name='responsavel')),
            ],
            options={
                'verbose_name': 'conector de integração',
                'verbose_name_plural': 'conectores de integração',
                'ordering': ['provider_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('event_type', models.CharField(choices=[('configured', 'Configurado'), ('activated', 'Ativado'), ('suspended', 'Suspenso'), ('test_success', 'Teste com sucesso'), ('test_failure', 'Teste com falha'), ('secret_rotated', 'Segredo rotacionado'), ('call_logged', 'Chamada registrada'), ('error', 'Erro')], max_length=32, verbose_name='tipo de evento')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ocorrido em')),
                ('message', models.TextField(blank=True, verbose_name='mensagem')),
                ('safe_context', models.JSONField(blank=True, default=dict, verbose_name='contexto seguro')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_events', to=settings.AUTH_USER_MODEL, verbose_name='ator')),
                ('api_client_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='integrations.apiclientapplication', verbose_name='cliente de API')),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='integrations.integrationconnector', verbose_name='conector')),
            ],
            options={
                'verbose_name': 'evento de integração',
                'verbose_name_plural': 'eventos de integração',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='apiclientapplication',
            index=models.Index(fields=['status'], name='integration_status_b708b2_idx'),
        ),
        migrations.AddIndex(
            model_name='apiclientapplication',
            index=models.Index(fields=['created_by'], name='integration_created_5c242b_idx'),
        ),
        migrations.AddIndex(
            model_name='apiclientapplication',
            index=models.Index(fields=['client_id'], name='integration_client__4732dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='apiclientapplication',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_api_client_code'),
        ),
        migrations.AddConstraint(
            model_name='apiclientapplication',
            constraint=models.UniqueConstraint(fields=('client_id',), name='unique_api_client_id'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['api_version', 'path'], name='integration_api_ver_bbb11a_idx'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['user', 'status_code'], name='integration_user_id_f8d4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['outcome', 'status_code'], name='integration_outcome_6416bb_idx'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['request_id'], name='integration_request_bcf73a_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconnector',
            index=models.Index(fields=['provider_type', 'status', 'is_active'], name='integration_provide_04ffea_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconnector',
            index=models.Index(fields=['responsible'], name='integration_respons_201069_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconnector',
            index=models.Index(fields=['code'], name='integration_code_2d5182_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationconnector',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_integration_connector_code'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='integration_event_t_724d02_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['connector', 'occurred_at'], name='integration_connect_fa839b_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['api_client_application', 'occurred_at'], name='integration_api_cli_be119a_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['actor', 'occurred_at'], name='integration_actor_i_c7522b_idx'),
        ),
    ]
