# Generated by Django 5.2.2 on 2026-07-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationconnector',
            options={'ordering': ['provider_type', 'code'], 'verbose_name': 'conector de integração', 'verbose_name_plural': 'conectores de integração'},
        ),
        migrations.AlterModelOptions(
            name='integrationevent',
            options={'ordering': ['-occurred_at'], 'verbose_name': 'evento de integração', 'verbose_name_plural': 'eventos de integração'},
        ),
    ]
