# Generated by Django 6.0.8 on 2026-08-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPrinterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(default='Argox principal', max_length=120, verbose_name='nome')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='IP ou hostname')),
                ('port', models.PositiveIntegerField(default=9100, verbose_name='porta TCP')),
                ('protocol', models.CharField(choices=[('tspl2', 'Argox TSPL2')], default='tspl2', max_length=16, verbose_name='protocolo')),
                ('width_mm', models.PositiveSmallIntegerField(default=40, verbose_name='largura (mm)')),
                ('height_mm', models.PositiveSmallIntegerField(default=30, verbose_name='altura (mm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'configuração de impressora de etiquetas',
                'verbose_name_plural': 'configurações de impressoras de etiquetas',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_label_printer')],
            },
        ),
    ]
