# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integrationconnector_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apiclientapplication',
            name='unique_tenant_api_client_code',
        ),
        migrations.RemoveConstraint(
            model_name='apiclientapplication',
            name='unique_tenant_api_client_id',
        ),
        migrations.RemoveConstraint(
            model_name='integrationconnector',
            name='unique_tenant_integration_connector_code',
        ),
        migrations.RemoveIndex(
            model_name='apicalllog',
            name='integration_tenant__aa0efe_idx',
        ),
        migrations.RemoveIndex(
            model_name='apicalllog',
            name='integration_tenant__a3677e_idx',
        ),
        migrations.RemoveIndex(
            model_name='apicalllog',
            name='integration_tenant__7aef09_idx',
        ),
        migrations.RemoveIndex(
            model_name='apiclientapplication',
            name='integration_tenant__6d9812_idx',
        ),
        migrations.RemoveIndex(
            model_name='apiclientapplication',
            name='integration_tenant__6091a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='integrationconnector',
            name='integration_tenant__f1a8c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='integrationconnector',
            name='integration_tenant__7c6872_idx',
        ),
        migrations.RemoveIndex(
            model_name='integrationevent',
            name='integration_tenant__c282c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='integrationevent',
            name='integration_tenant__64457b_idx',
        ),
        migrations.RemoveIndex(
            model_name='integrationevent',
            name='integration_tenant__504d2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='integrationevent',
            name='integration_tenant__af487e_idx',
        ),
        migrations.RemoveField(
            model_name='apicalllog',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='apiclientapplication',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='integrationconnector',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='integrationevent',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['api_version', 'path'], name='integration_api_ver_bbb11a_idx'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['user', 'status_code'], name='integration_user_id_f8d4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['outcome', 'status_code'], name='integration_outcome_6416bb_idx'),
        ),
        migrations.AddIndex(
            model_name='apiclientapplication',
            index=models.Index(fields=['status'], name='integration_status_b708b2_idx'),
        ),
        migrations.AddIndex(
            model_name='apiclientapplication',
            index=models.Index(fields=['created_by'], name='integration_created_5c242b_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconnector',
            index=models.Index(fields=['provider_type', 'status', 'is_active'], name='integration_provide_04ffea_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconnector',
            index=models.Index(fields=['responsible'], name='integration_respons_201069_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='integration_event_t_724d02_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['connector', 'occurred_at'], name='integration_connect_fa839b_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['api_client_application', 'occurred_at'], name='integration_api_cli_be119a_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['actor', 'occurred_at'], name='integration_actor_i_c7522b_idx'),
        ),
        migrations.AddConstraint(
            model_name='apiclientapplication',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_api_client_code'),
        ),
        migrations.AddConstraint(
            model_name='apiclientapplication',
            constraint=models.UniqueConstraint(fields=('client_id',), name='unique_api_client_id'),
        ),
        migrations.AddConstraint(
            model_name='integrationconnector',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_integration_connector_code'),
        ),
    ]
