# Generated by Django 6.0.8 on 2026-08-25 17:08

import base.sequences
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('agent_type', models.CharField(choices=[('summary', 'Resumo'), ('classification', 'Classificação'), ('document_search', 'Busca documental'), ('root_cause', 'Causa raiz'), ('action_suggestion', 'Sugestão de ação'), ('risk_insight', 'Insight de risco'), ('regulatory_review', 'Revisão regulatória'), ('process_insight', 'Insight de processo'), ('workflow_gate', 'Controle de workflow'), ('compliance_check', 'Verificação de conformidade')], max_length=32, verbose_name='tipo de agente')),
                ('source_module', models.CharField(choices=[('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('audits', 'Auditorias'), ('complaints', 'Reclamações'), ('risks', 'Riscos'), ('qa', 'Análise de Qualidade'), ('production', 'Produção'), ('general', 'Geral')], max_length=32, verbose_name='módulo principal')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('local', 'Local determinístico')], default='openai', max_length=32, verbose_name='provedor')),
                ('model_name', models.CharField(default='gpt-5.5-mini', max_length=120, verbose_name='modelo')),
                ('system_prompt', models.TextField(verbose_name='prompt de sistema')),
                ('allowed_source_modules', models.JSONField(default=list, verbose_name='módulos permitidos')),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='configuração')),
                ('requires_human_review', models.BooleanField(default=True, verbose_name='exige revisão humana')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_ai_agent_profiles', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('source_module_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo principal normalizado')),
            ],
            options={
                'verbose_name': 'perfil de agente de IA',
                'verbose_name_plural': 'perfis de agentes de IA',
                'ordering': ['source_module', 'code'],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AIAgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('run_number', models.CharField(blank=True, max_length=80, verbose_name='execução')),
                ('source_module', models.CharField(choices=[('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('audits', 'Auditorias'), ('complaints', 'Reclamações'), ('risks', 'Riscos'), ('qa', 'Análise de Qualidade'), ('production', 'Produção'), ('general', 'Geral')], max_length=32, verbose_name='módulo de origem')),
                ('source_model', models.CharField(max_length=120, verbose_name='modelo de origem')),
                ('source_record_id', models.CharField(max_length=120, verbose_name='id do registro')),
                ('execution_mode', models.CharField(choices=[('sync', 'Síncrono'), ('async', 'Assíncrono')], default='sync', max_length=16, verbose_name='modo de execução')),
                ('celery_task_name', models.CharField(blank=True, max_length=180, verbose_name='task Celery')),
                ('task_id', models.CharField(blank=True, max_length=180, verbose_name='id da task')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('queued', 'Enfileirado'), ('running', 'Executando'), ('succeeded', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='draft', max_length=24, verbose_name='status')),
                ('graph_engine', models.CharField(blank=True, max_length=80, verbose_name='engine do grafo')),
                ('prompt_text', models.TextField(verbose_name='prompt')),
                ('model_name', models.CharField(max_length=120, verbose_name='modelo')),
                ('input_payload', models.JSONField(default=dict, verbose_name='entrada')),
                ('output_payload', models.JSONField(blank=True, default=dict, verbose_name='saída estruturada')),
                ('output_text', models.TextField(blank=True, verbose_name='saída textual')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='ai_agents.aiagentprofile', verbose_name='agente')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_ai_agent_runs', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
                ('source_model_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model de origem normalizado')),
                ('source_module_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo de origem normalizado')),
            ],
            options={
                'verbose_name': 'execução de agente de IA',
                'verbose_name_plural': 'execuções de agentes de IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsightSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('suggestion_type', models.CharField(choices=[('root_cause', 'Causa raiz'), ('action', 'Ação'), ('attention', 'Ponto de atenção'), ('risk', 'Risco'), ('inconsistency', 'Inconsistência'), ('summary', 'Resumo'), ('classification', 'Classificação')], max_length=32, verbose_name='tipo de sugestão')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0.70'), max_digits=5, verbose_name='confiança')),
                ('status', models.CharField(choices=[('pending_review', 'Pendente de revisão'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('applied', 'Aplicada')], default='pending_review', max_length=24, verbose_name='status')),
                ('source_module', models.CharField(choices=[('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('audits', 'Auditorias'), ('complaints', 'Reclamações'), ('risks', 'Riscos'), ('qa', 'Análise de Qualidade'), ('production', 'Produção'), ('general', 'Geral')], max_length=32, verbose_name='módulo de origem')),
                ('source_model', models.CharField(max_length=120, verbose_name='modelo de origem')),
                ('source_record_id', models.CharField(max_length=120, verbose_name='id do registro')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisado em')),
                ('review_comments', models.TextField(blank=True, verbose_name='comentários da revisão')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_ai_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='ai_agents.aiagentrun', verbose_name='execução')),
                ('source_model_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model de origem normalizado')),
                ('source_module_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo de origem normalizado')),
            ],
            options={
                'verbose_name': 'sugestão de IA',
                'verbose_name_plural': 'sugestões de IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPromptAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('prompt_text', models.TextField(verbose_name='prompt')),
                ('model_name', models.CharField(max_length=120, verbose_name='modelo')),
                ('input_payload', models.JSONField(default=dict, verbose_name='entrada')),
                ('output_payload', models.JSONField(blank=True, default=dict, verbose_name='saída estruturada')),
                ('output_text', models.TextField(blank=True, verbose_name='saída textual')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('queued', 'Enfileirado'), ('running', 'Executando'), ('succeeded', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], max_length=24, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ocorrido em')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='ai_agents.aiagentprofile', verbose_name='agente')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='ai_agents.aiagentrun', verbose_name='execução')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_prompt_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'auditoria de prompt de IA',
                'verbose_name_plural': 'auditorias de prompts de IA',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiagentprofile',
            index=models.Index(fields=['agent_type', 'is_active'], name='ai_agents_a_agent_t_6e5c96_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagentprofile',
            index=models.Index(fields=['source_module'], name='ai_agents_a_source__0edee5_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagentprofile',
            index=models.Index(fields=['created_by'], name='ai_agents_a_created_316413_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagentprofile',
            index=models.Index(fields=['code'], name='ai_agents_a_code_034450_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiagentprofile',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_ai_agent_profile_code'),
        ),
        migrations.AddIndex(
            model_name='aiagentrun',
            index=models.Index(fields=['status', 'created_at'], name='ai_agents_a_status_f27819_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagentrun',
            index=models.Index(fields=['source_module', 'source_model', 'source_record_id'], name='ai_agents_a_source__a19c22_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagentrun',
            index=models.Index(fields=['agent'], name='ai_agents_a_agent_i_c3a90b_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagentrun',
            index=models.Index(fields=['requested_by'], name='ai_agents_a_request_9b0a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagentrun',
            index=models.Index(fields=['run_number'], name='ai_agents_a_run_num_2994a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiagentrun',
            constraint=models.UniqueConstraint(fields=('run_number',), name='unique_ai_agent_run_number'),
        ),
        migrations.AddIndex(
            model_name='aiinsightsuggestion',
            index=models.Index(fields=['status', 'suggestion_type'], name='ai_agents_a_status_419e52_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsightsuggestion',
            index=models.Index(fields=['source_module', 'source_model', 'source_record_id'], name='ai_agents_a_source__59e964_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsightsuggestion',
            index=models.Index(fields=['reviewed_by'], name='ai_agents_a_reviewe_310d71_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsightsuggestion',
            index=models.Index(fields=['run'], name='ai_agents_a_run_id_b891da_idx'),
        ),
        migrations.AddIndex(
            model_name='aipromptauditlog',
            index=models.Index(fields=['status', 'occurred_at'], name='ai_agents_a_status_93d451_idx'),
        ),
        migrations.AddIndex(
            model_name='aipromptauditlog',
            index=models.Index(fields=['agent', 'occurred_at'], name='ai_agents_a_agent_i_4468c9_idx'),
        ),
        migrations.AddIndex(
            model_name='aipromptauditlog',
            index=models.Index(fields=['run'], name='ai_agents_a_run_id_45769a_idx'),
        ),
        migrations.AddIndex(
            model_name='aipromptauditlog',
            index=models.Index(fields=['user', 'occurred_at'], name='ai_agents_a_user_id_96e1c0_idx'),
        ),
    ]
