# Generated by Django 6.0.7 on 2026-07-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0001_initial'),
        ('auxiliary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagentprofile',
            name='source_module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo principal normalizado'),
        ),
        migrations.AddField(
            model_name='aiagentrun',
            name='source_model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model de origem normalizado'),
        ),
        migrations.AddField(
            model_name='aiagentrun',
            name='source_module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo de origem normalizado'),
        ),
        migrations.AddField(
            model_name='aiinsightsuggestion',
            name='source_model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model de origem normalizado'),
        ),
        migrations.AddField(
            model_name='aiinsightsuggestion',
            name='source_module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo de origem normalizado'),
        ),
    ]
