# Generated by Django 5.2.2 on 2026-07-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0002_aiagentprofile_source_module_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagentprofile',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('local', 'Local determinístico')], default='openai', max_length=32, verbose_name='provedor'),
        ),
    ]
