# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0003_alter_aiagentprofile_provider'),
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aiagentprofile',
            name='unique_tenant_ai_agent_profile_code',
        ),
        migrations.RemoveConstraint(
            model_name='aiagentrun',
            name='unique_tenant_ai_agent_run_number',
        ),
        migrations.RemoveIndex(
            model_name='aiagentprofile',
            name='ai_agents_a_tenant__2682b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiagentprofile',
            name='ai_agents_a_tenant__1271bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiagentprofile',
            name='ai_agents_a_tenant__a4c875_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiagentrun',
            name='ai_agents_a_tenant__250a9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiagentrun',
            name='ai_agents_a_tenant__c83e4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiagentrun',
            name='ai_agents_a_tenant__3fe23a_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiagentrun',
            name='ai_agents_a_tenant__d07846_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiinsightsuggestion',
            name='ai_agents_a_tenant__4c8188_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiinsightsuggestion',
            name='ai_agents_a_tenant__49fe06_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiinsightsuggestion',
            name='ai_agents_a_tenant__faa168_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiinsightsuggestion',
            name='ai_agents_a_tenant__5429e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='aipromptauditlog',
            name='ai_agents_a_tenant__d03b91_idx',
        ),
        migrations.RemoveIndex(
            model_name='aipromptauditlog',
            name='ai_agents_a_tenant__1a9f6e_idx',
        ),
        migrations.RemoveIndex(
            model_name='aipromptauditlog',
            name='ai_agents_a_tenant__50766e_idx',
        ),
        migrations.RemoveIndex(
            model_name='aipromptauditlog',
            name='ai_agents_a_tenant__e15c35_idx',
        ),
        migrations.RemoveField(
            model_name='aiagentprofile',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='aiagentrun',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='aiinsightsuggestion',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='aipromptauditlog',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='aiagentprofile',
            index=models.Index(fields=['agent_type', 'is_active'], name='ai_agents_a_agent_t_6e5c96_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagentprofile',
            index=models.Index(fields=['source_module'], name='ai_agents_a_source__0edee5_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagentprofile',
            index=models.Index(fields=['created_by'], name='ai_agents_a_created_316413_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagentrun',
            index=models.Index(fields=['status', 'created_at'], name='ai_agents_a_status_f27819_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagentrun',
            index=models.Index(fields=['source_module', 'source_model', 'source_record_id'], name='ai_agents_a_source__a19c22_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagentrun',
            index=models.Index(fields=['agent'], name='ai_agents_a_agent_i_c3a90b_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagentrun',
            index=models.Index(fields=['requested_by'], name='ai_agents_a_request_9b0a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsightsuggestion',
            index=models.Index(fields=['status', 'suggestion_type'], name='ai_agents_a_status_419e52_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsightsuggestion',
            index=models.Index(fields=['source_module', 'source_model', 'source_record_id'], name='ai_agents_a_source__59e964_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsightsuggestion',
            index=models.Index(fields=['reviewed_by'], name='ai_agents_a_reviewe_310d71_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsightsuggestion',
            index=models.Index(fields=['run'], name='ai_agents_a_run_id_b891da_idx'),
        ),
        migrations.AddIndex(
            model_name='aipromptauditlog',
            index=models.Index(fields=['status', 'occurred_at'], name='ai_agents_a_status_93d451_idx'),
        ),
        migrations.AddIndex(
            model_name='aipromptauditlog',
            index=models.Index(fields=['agent', 'occurred_at'], name='ai_agents_a_agent_i_4468c9_idx'),
        ),
        migrations.AddIndex(
            model_name='aipromptauditlog',
            index=models.Index(fields=['run'], name='ai_agents_a_run_id_45769a_idx'),
        ),
        migrations.AddIndex(
            model_name='aipromptauditlog',
            index=models.Index(fields=['user', 'occurred_at'], name='ai_agents_a_user_id_96e1c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiagentprofile',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_ai_agent_profile_code'),
        ),
        migrations.AddConstraint(
            model_name='aiagentrun',
            constraint=models.UniqueConstraint(fields=('run_number',), name='unique_ai_agent_run_number'),
        ),
    ]
