# Generated by Django 5.2.16 on 2026-07-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0004_remove_aiagentprofile_unique_tenant_ai_agent_profile_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagentprofile',
            name='agent_type',
            field=models.CharField(choices=[('summary', 'Resumo'), ('classification', 'Classificação'), ('document_search', 'Busca documental'), ('root_cause', 'Causa raiz'), ('action_suggestion', 'Sugestão de ação'), ('risk_insight', 'Insight de risco'), ('regulatory_review', 'Revisão regulatória'), ('process_insight', 'Insight de processo'), ('workflow_gate', 'Controle de workflow'), ('compliance_check', 'Verificação de conformidade')], max_length=32, verbose_name='tipo de agente'),
        ),
        migrations.AlterField(
            model_name='aiagentprofile',
            name='source_module',
            field=models.CharField(choices=[('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('audits', 'Auditorias'), ('complaints', 'Reclamações'), ('risks', 'Riscos'), ('regulatory', 'Regulatório'), ('pharmacovigilance', 'Farmacovigilância'), ('qa', 'Análise de Qualidade'), ('production', 'Produção'), ('general', 'Geral')], max_length=32, verbose_name='módulo principal'),
        ),
        migrations.AlterField(
            model_name='aiagentrun',
            name='source_module',
            field=models.CharField(choices=[('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('audits', 'Auditorias'), ('complaints', 'Reclamações'), ('risks', 'Riscos'), ('regulatory', 'Regulatório'), ('pharmacovigilance', 'Farmacovigilância'), ('qa', 'Análise de Qualidade'), ('production', 'Produção'), ('general', 'Geral')], max_length=32, verbose_name='módulo de origem'),
        ),
        migrations.AlterField(
            model_name='aiinsightsuggestion',
            name='source_module',
            field=models.CharField(choices=[('documents', 'Documentos'), ('deviations', 'Desvios'), ('capa', 'CAPA'), ('audits', 'Auditorias'), ('complaints', 'Reclamações'), ('risks', 'Riscos'), ('regulatory', 'Regulatório'), ('pharmacovigilance', 'Farmacovigilância'), ('qa', 'Análise de Qualidade'), ('production', 'Produção'), ('general', 'Geral')], max_length=32, verbose_name='módulo de origem'),
        ),
    ]
