# Generated by Django 5.2.16 on 2026-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0005_alter_aiagentprofile_agent_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagentprofile',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
    ]
