# Generated by Django 6.0.7 on 2026-07-08 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0001_initial'),
        ('changes', '0001_initial'),
        ('deviations', '0001_initial'),
        ('documents', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('dossier_number', models.CharField(blank=True, max_length=80, verbose_name='dossiê')),
                ('dossier_type', models.CharField(choices=[('registration', 'Registro'), ('post_registration', 'Pós-registro'), ('renewal', 'Renovação'), ('variation', 'Variação'), ('inspection', 'Inspeção')], max_length=32, verbose_name='tipo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('authority', models.CharField(default='ANVISA', max_length=120, verbose_name='autoridade sanitária')),
                ('subject', models.TextField(verbose_name='assunto')),
                ('due_date', models.DateField(verbose_name='prazo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Submetido'), ('under_review', 'Em análise'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('closed', 'Encerrado'), ('cancelled', 'Cancelado')], default='draft', max_length=32, verbose_name='status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submetido em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrado em')),
                ('closure_summary', models.TextField(blank=True, verbose_name='resumo de encerramento')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_regulatory_dossiers', to=settings.AUTH_USER_MODEL, verbose_name='encerrado por')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_regulatory_dossiers', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_regulatory_dossiers', to=settings.AUTH_USER_MODEL, verbose_name='submetido por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'dossiê regulatório',
                'verbose_name_plural': 'dossiês regulatórios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('commitment_number', models.CharField(blank=True, max_length=80, verbose_name='compromisso')),
                ('description', models.TextField(verbose_name='descrição')),
                ('due_date', models.DateField(verbose_name='prazo')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='open', max_length=24, verbose_name='status')),
                ('completion_summary', models.TextField(blank=True, verbose_name='resumo de conclusão')),
                ('evidence_reference', models.CharField(blank=True, max_length=255, verbose_name='evidência')),
                ('content_hash', models.CharField(blank=True, max_length=128, verbose_name='hash do conteúdo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_regulatory_commitments', to=settings.AUTH_USER_MODEL, verbose_name='concluído por')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_regulatory_commitments', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='regulatory.regulatorydossier', verbose_name='dossiê')),
            ],
            options={
                'verbose_name': 'compromisso regulatório',
                'verbose_name_plural': 'compromissos regulatórios',
                'ordering': ['dossier__dossier_number', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('link_type', models.CharField(choices=[('product', 'Produto'), ('presentation', 'Apresentação'), ('lot', 'Lote'), ('document', 'Documento'), ('change', 'Mudança'), ('deviation', 'Desvio'), ('capa', 'CAPA'), ('study', 'Estudo'), ('supplier', 'Fornecedor'), ('manufacturer', 'Fabricante')], max_length=24, verbose_name='tipo de vínculo')),
                ('reference_code', models.CharField(blank=True, max_length=120, verbose_name='referência')),
                ('description', models.TextField(verbose_name='descrição')),
                ('capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_links', to='capa.caparecord', verbose_name='CAPA')),
                ('change_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_links', to='changes.changecontrol', verbose_name='mudança')),
                ('deviation_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_links', to='deviations.qualityevent', verbose_name='desvio')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_links', to='documents.controlleddocument', verbose_name='documento')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='regulatory.regulatorydossier', verbose_name='dossiê')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_links', to='masters.businesspartner', verbose_name='parceiro')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_links', to='masters.product', verbose_name='produto')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_links', to='inventory.stocklot', verbose_name='lote')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'vínculo regulatório',
                'verbose_name_plural': 'vínculos regulatórios',
                'ordering': ['dossier__dossier_number', 'link_type'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryPetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('petition_number', models.CharField(blank=True, max_length=80, verbose_name='petição')),
                ('petition_type', models.CharField(choices=[('initial_registration', 'Registro inicial'), ('post_registration', 'Pós-registro'), ('renewal', 'Renovação'), ('requirement_response', 'Resposta de exigência'), ('commitment', 'Compromisso'), ('other', 'Outro')], max_length=32, verbose_name='tipo')),
                ('subject', models.CharField(max_length=180, verbose_name='assunto')),
                ('protocol_number', models.CharField(blank=True, max_length=120, verbose_name='protocolo')),
                ('response_due_date', models.DateField(blank=True, null=True, verbose_name='prazo de resposta')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Submetida'), ('under_review', 'Em análise'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('closed', 'Encerrada'), ('cancelled', 'Cancelada')], default='draft', max_length=32, verbose_name='status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submetida em')),
                ('response_summary', models.TextField(blank=True, verbose_name='resumo da resposta')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='respondida em')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to='regulatory.regulatorydossier', verbose_name='dossiê')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responded_regulatory_petitions', to=settings.AUTH_USER_MODEL, verbose_name='respondida por')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_regulatory_petitions', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_regulatory_petitions', to=settings.AUTH_USER_MODEL, verbose_name='submetida por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'petição regulatória',
                'verbose_name_plural': 'petições regulatórias',
                'ordering': ['dossier__dossier_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('regulatory_code', models.CharField(blank=True, max_length=80, verbose_name='código regulatório')),
                ('presentation', models.CharField(max_length=180, verbose_name='apresentação')),
                ('registration_holder', models.CharField(max_length=180, verbose_name='detentor do registro')),
                ('therapeutic_class', models.CharField(max_length=140, verbose_name='classe terapêutica')),
                ('dosage_form', models.CharField(max_length=120, verbose_name='forma farmacêutica')),
                ('strength', models.CharField(max_length=80, verbose_name='concentração')),
                ('route', models.CharField(max_length=80, verbose_name='via de administração')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('cancelled', 'Cancelado')], default='draft', max_length=24, verbose_name='status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_products', to='masters.product', verbose_name='produto')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_regulatory_products', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'produto regulatório',
                'verbose_name_plural': 'produtos regulatórios',
                'ordering': ['regulatory_code'],
            },
        ),
        migrations.AddField(
            model_name='regulatorydossier',
            name='regulatory_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='regulatory.regulatoryproduct', verbose_name='produto regulatório'),
        ),
        migrations.CreateModel(
            name='RegulatoryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('registration_number', models.CharField(max_length=80, verbose_name='número de registro')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('pending_renewal', 'Renovação pendente'), ('expired', 'Vencido'), ('suspended', 'Suspenso'), ('cancelled', 'Cancelado')], default='pending', max_length=32, verbose_name='status')),
                ('valid_from', models.DateField(verbose_name='vigência inicial')),
                ('valid_until', models.DateField(verbose_name='vigência final')),
                ('next_renewal_due_date', models.DateField(verbose_name='prazo de renovação')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='regulatory.regulatorydossier', verbose_name='dossiê')),
                ('regulatory_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='regulatory.regulatoryproduct', verbose_name='produto regulatório')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_regulatory_registrations', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'registro regulatório',
                'verbose_name_plural': 'registros regulatórios',
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('report_type', models.CharField(choices=[('anvisa_dossier', 'Dossiê ANVISA'), ('audit', 'Auditoria'), ('inspection', 'Inspeção'), ('renewal', 'Renovação'), ('summary', 'Resumo')], max_length=32, verbose_name='tipo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('generated', 'Gerado')], default='draft', max_length=24, verbose_name='status')),
                ('content_reference', models.CharField(blank=True, max_length=255, verbose_name='conteúdo gerado')),
                ('total_requirements', models.PositiveIntegerField(default=0, verbose_name='exigências totais')),
                ('open_commitments', models.PositiveIntegerField(default=0, verbose_name='compromissos abertos')),
                ('evidence_count', models.PositiveIntegerField(default=0, verbose_name='evidências')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='gerado em')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='regulatory.regulatorydossier', verbose_name='dossiê')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_regulatory_reports', to=settings.AUTH_USER_MODEL, verbose_name='gerado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'relatório regulatório',
                'verbose_name_plural': 'relatórios regulatórios',
                'ordering': ['dossier__dossier_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('requirement_number', models.CharField(blank=True, max_length=80, verbose_name='exigência')),
                ('description', models.TextField(verbose_name='descrição')),
                ('received_at', models.DateField(verbose_name='recebida em')),
                ('response_due_date', models.DateField(verbose_name='prazo de resposta')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('answered', 'Respondida'), ('closed', 'Encerrada'), ('cancelled', 'Cancelada')], default='open', max_length=24, verbose_name='status')),
                ('response_summary', models.TextField(blank=True, verbose_name='resumo da resposta')),
                ('evidence_reference', models.CharField(blank=True, max_length=255, verbose_name='evidência')),
                ('content_hash', models.CharField(blank=True, max_length=128, verbose_name='hash do conteúdo')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='respondida em')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answered_regulatory_requirements', to=settings.AUTH_USER_MODEL, verbose_name='respondida por')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='regulatory.regulatorydossier', verbose_name='dossiê')),
                ('petition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='regulatory.regulatorypetition', verbose_name='petição')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_regulatory_requirements', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'exigência regulatória',
                'verbose_name_plural': 'exigências regulatórias',
                'ordering': ['dossier__dossier_number', 'response_due_date'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('file_reference', models.CharField(max_length=255, verbose_name='arquivo')),
                ('content_hash', models.CharField(max_length=128, verbose_name='hash do conteúdo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='regulatory.regulatorycommitment', verbose_name='compromisso')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='regulatory.regulatorydossier', verbose_name='dossiê')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_regulatory_evidences', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
                ('petition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='regulatory.regulatorypetition', verbose_name='petição')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='regulatory.regulatoryrequirement', verbose_name='exigência')),
            ],
            options={
                'verbose_name': 'evidência regulatória',
                'verbose_name_plural': 'evidências regulatórias',
                'ordering': ['dossier__dossier_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('alert_type', models.CharField(choices=[('registration_expiry', 'Vencimento de registro'), ('renewal_due', 'Renovação'), ('commitment_due', 'Compromisso'), ('requirement_due', 'Exigência'), ('response_due', 'Prazo de resposta')], max_length=32, verbose_name='tipo')),
                ('severity', models.CharField(choices=[('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=24, verbose_name='severidade')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('sent', 'Enviado'), ('acknowledged', 'Reconhecido')], default='open', max_length=24, verbose_name='status')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='reconhecido em')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_regulatory_alerts', to=settings.AUTH_USER_MODEL, verbose_name='reconhecido por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='regulatory.regulatorycommitment', verbose_name='compromisso')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='regulatory.regulatorydossier', verbose_name='dossiê')),
                ('petition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='regulatory.regulatorypetition', verbose_name='petição')),
                ('regulatory_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='regulatory.regulatoryproduct', verbose_name='produto regulatório')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='regulatory.regulatoryregistration', verbose_name='registro')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='regulatory.regulatoryrequirement', verbose_name='exigência')),
            ],
            options={
                'verbose_name': 'alerta regulatório',
                'verbose_name_plural': 'alertas regulatórios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='regulatorycommitment',
            index=models.Index(fields=['tenant', 'dossier', 'status'], name='regulatory__tenant__4a8b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorycommitment',
            index=models.Index(fields=['tenant', 'responsible', 'due_date'], name='regulatory__tenant__2be3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorycommitment',
            index=models.Index(fields=['commitment_number'], name='regulatory__commitm_4b22df_idx'),
        ),
        migrations.AddConstraint(
            model_name='regulatorycommitment',
            constraint=models.UniqueConstraint(fields=('tenant', 'commitment_number'), name='unique_tenant_regulatory_commitment_number'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['tenant', 'dossier', 'link_type'], name='regulatory__tenant__911a60_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['tenant', 'product'], name='regulatory__tenant__dd4171_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['tenant', 'stock_lot'], name='regulatory__tenant__8c4314_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['tenant', 'document'], name='regulatory__tenant__ac7d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['tenant', 'change_control'], name='regulatory__tenant__211f50_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['tenant', 'deviation_event'], name='regulatory__tenant__6c995e_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['tenant', 'capa'], name='regulatory__tenant__755e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['tenant', 'partner'], name='regulatory__tenant__4801a0_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorypetition',
            index=models.Index(fields=['tenant', 'dossier', 'status'], name='regulatory__tenant__2485cc_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorypetition',
            index=models.Index(fields=['tenant', 'petition_type', 'status'], name='regulatory__tenant__36cbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorypetition',
            index=models.Index(fields=['tenant', 'response_due_date'], name='regulatory__tenant__e49c00_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorypetition',
            index=models.Index(fields=['petition_number'], name='regulatory__petitio_b33604_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorypetition',
            index=models.Index(fields=['protocol_number'], name='regulatory__protoco_5af8f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='regulatorypetition',
            constraint=models.UniqueConstraint(fields=('tenant', 'petition_number'), name='unique_tenant_regulatory_petition_number'),
        ),
        migrations.AddIndex(
            model_name='regulatoryproduct',
            index=models.Index(fields=['tenant', 'product', 'status'], name='regulatory__tenant__778ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryproduct',
            index=models.Index(fields=['tenant', 'responsible'], name='regulatory__tenant__5107a3_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryproduct',
            index=models.Index(fields=['regulatory_code'], name='regulatory__regulat_4805cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='regulatoryproduct',
            constraint=models.UniqueConstraint(fields=('tenant', 'regulatory_code'), name='unique_tenant_regulatory_product_code'),
        ),
        migrations.AddConstraint(
            model_name='regulatoryproduct',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'presentation'), name='unique_tenant_product_presentation'),
        ),
        migrations.AddIndex(
            model_name='regulatorydossier',
            index=models.Index(fields=['tenant', 'regulatory_product', 'status'], name='regulatory__tenant__dc1725_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorydossier',
            index=models.Index(fields=['tenant', 'dossier_type', 'status'], name='regulatory__tenant__26a5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorydossier',
            index=models.Index(fields=['tenant', 'responsible'], name='regulatory__tenant__ab7375_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorydossier',
            index=models.Index(fields=['tenant', 'due_date'], name='regulatory__tenant__ff62fe_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorydossier',
            index=models.Index(fields=['dossier_number'], name='regulatory__dossier_0af2db_idx'),
        ),
        migrations.AddConstraint(
            model_name='regulatorydossier',
            constraint=models.UniqueConstraint(fields=('tenant', 'dossier_number'), name='unique_tenant_regulatory_dossier_number'),
        ),
        migrations.AddIndex(
            model_name='regulatoryregistration',
            index=models.Index(fields=['tenant', 'regulatory_product', 'status'], name='regulatory__tenant__8dc374_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryregistration',
            index=models.Index(fields=['tenant', 'valid_until'], name='regulatory__tenant__9823a9_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryregistration',
            index=models.Index(fields=['tenant', 'next_renewal_due_date'], name='regulatory__tenant__ed8aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryregistration',
            index=models.Index(fields=['registration_number'], name='regulatory__registr_74db20_idx'),
        ),
        migrations.AddConstraint(
            model_name='regulatoryregistration',
            constraint=models.UniqueConstraint(fields=('tenant', 'registration_number'), name='unique_tenant_registration_number'),
        ),
        migrations.AddIndex(
            model_name='regulatoryreport',
            index=models.Index(fields=['tenant', 'dossier', 'status'], name='regulatory__tenant__db38b3_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryreport',
            index=models.Index(fields=['tenant', 'report_type'], name='regulatory__tenant__cab210_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryreport',
            index=models.Index(fields=['tenant', 'generated_at'], name='regulatory__tenant__ea0e05_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryrequirement',
            index=models.Index(fields=['tenant', 'dossier', 'status'], name='regulatory__tenant__9f5272_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryrequirement',
            index=models.Index(fields=['tenant', 'petition'], name='regulatory__tenant__6a8c94_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryrequirement',
            index=models.Index(fields=['tenant', 'responsible', 'response_due_date'], name='regulatory__tenant__5fbaa9_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryrequirement',
            index=models.Index(fields=['requirement_number'], name='regulatory__require_91cf63_idx'),
        ),
        migrations.AddConstraint(
            model_name='regulatoryrequirement',
            constraint=models.UniqueConstraint(fields=('tenant', 'requirement_number'), name='unique_tenant_regulatory_requirement_number'),
        ),
        migrations.AddIndex(
            model_name='regulatoryevidence',
            index=models.Index(fields=['tenant', 'dossier'], name='regulatory__tenant__7bc98f_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryevidence',
            index=models.Index(fields=['tenant', 'petition'], name='regulatory__tenant__38bb46_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryevidence',
            index=models.Index(fields=['tenant', 'requirement'], name='regulatory__tenant__fd8152_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryevidence',
            index=models.Index(fields=['tenant', 'commitment'], name='regulatory__tenant__ffada4_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryevidence',
            index=models.Index(fields=['content_hash'], name='regulatory__content_96fd6f_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['tenant', 'alert_type', 'status'], name='regulatory__tenant__614460_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['tenant', 'regulatory_product'], name='regulatory__tenant__79a4bf_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['tenant', 'dossier'], name='regulatory__tenant__2a74b9_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['tenant', 'registration'], name='regulatory__tenant__697dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['tenant', 'petition'], name='regulatory__tenant__c60dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['tenant', 'requirement'], name='regulatory__tenant__bbdaa2_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['tenant', 'commitment'], name='regulatory__tenant__27f7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['tenant', 'due_date'], name='regulatory__tenant__5911f7_idx'),
        ),
    ]
