# Generated by Django 6.0.7 on 2026-07-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_add_zipcode_and_address'),
        ('regulatory', '0002_regulatoryalert_severity_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatoryproduct',
            name='manufacturer_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_products_as_manufacturer', to='masters.businesspartner', verbose_name='fabricante (parceiro)'),
        ),
        migrations.AddField(
            model_name='regulatoryproduct',
            name='registration_holder_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_products_as_holder', to='masters.businesspartner', verbose_name='detentor do registro (parceiro)'),
        ),
    ]
