# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('capa', '0002_remove_capaapproval_unique_tenant_capa_approval_role_user_and_more'),
        ('changes', '0003_remove_changeapproval_unique_tenant_change_approval_role_user_and_more'),
        ('deviations', '0003_remove_deviationapproval_unique_tenant_deviation_approval_role_user_and_more'),
        ('documents', '0003_remove_controlleddocument_unique_tenant_document_code_version_and_more'),
        ('inventory', '0002_remove_stockbalance_unique_tenant_stock_balance_address_status_and_more'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('regulatory', '0003_regulatoryproduct_manufacturer_partner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='regulatorycommitment',
            name='unique_tenant_regulatory_commitment_number',
        ),
        migrations.RemoveConstraint(
            model_name='regulatorydossier',
            name='unique_tenant_regulatory_dossier_number',
        ),
        migrations.RemoveConstraint(
            model_name='regulatorypetition',
            name='unique_tenant_regulatory_petition_number',
        ),
        migrations.RemoveConstraint(
            model_name='regulatoryproduct',
            name='unique_tenant_regulatory_product_code',
        ),
        migrations.RemoveConstraint(
            model_name='regulatoryproduct',
            name='unique_tenant_product_presentation',
        ),
        migrations.RemoveConstraint(
            model_name='regulatoryregistration',
            name='unique_tenant_registration_number',
        ),
        migrations.RemoveConstraint(
            model_name='regulatoryrequirement',
            name='unique_tenant_regulatory_requirement_number',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryalert',
            name='regulatory__tenant__614460_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryalert',
            name='regulatory__tenant__79a4bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryalert',
            name='regulatory__tenant__2a74b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryalert',
            name='regulatory__tenant__697dc3_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryalert',
            name='regulatory__tenant__c60dc7_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryalert',
            name='regulatory__tenant__bbdaa2_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryalert',
            name='regulatory__tenant__27f7ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryalert',
            name='regulatory__tenant__5911f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorycommitment',
            name='regulatory__tenant__4a8b1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorycommitment',
            name='regulatory__tenant__2be3ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorydossier',
            name='regulatory__tenant__dc1725_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorydossier',
            name='regulatory__tenant__26a5bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorydossier',
            name='regulatory__tenant__ab7375_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorydossier',
            name='regulatory__tenant__ff62fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryevidence',
            name='regulatory__tenant__7bc98f_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryevidence',
            name='regulatory__tenant__38bb46_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryevidence',
            name='regulatory__tenant__fd8152_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryevidence',
            name='regulatory__tenant__ffada4_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorylink',
            name='regulatory__tenant__911a60_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorylink',
            name='regulatory__tenant__dd4171_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorylink',
            name='regulatory__tenant__8c4314_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorylink',
            name='regulatory__tenant__ac7d1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorylink',
            name='regulatory__tenant__211f50_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorylink',
            name='regulatory__tenant__6c995e_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorylink',
            name='regulatory__tenant__755e1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorylink',
            name='regulatory__tenant__4801a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorypetition',
            name='regulatory__tenant__2485cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorypetition',
            name='regulatory__tenant__36cbc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatorypetition',
            name='regulatory__tenant__e49c00_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryproduct',
            name='regulatory__tenant__778ed1_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryproduct',
            name='regulatory__tenant__5107a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryregistration',
            name='regulatory__tenant__8dc374_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryregistration',
            name='regulatory__tenant__9823a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryregistration',
            name='regulatory__tenant__ed8aa8_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryreport',
            name='regulatory__tenant__db38b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryreport',
            name='regulatory__tenant__cab210_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryreport',
            name='regulatory__tenant__ea0e05_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryrequirement',
            name='regulatory__tenant__9f5272_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryrequirement',
            name='regulatory__tenant__6a8c94_idx',
        ),
        migrations.RemoveIndex(
            model_name='regulatoryrequirement',
            name='regulatory__tenant__5fbaa9_idx',
        ),
        migrations.RemoveField(
            model_name='regulatoryalert',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='regulatorycommitment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='regulatorydossier',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='regulatoryevidence',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='regulatorylink',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='regulatorypetition',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='regulatoryproduct',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='regulatoryregistration',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='regulatoryreport',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='regulatoryrequirement',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['alert_type', 'status'], name='regulatory__alert_t_eb96a0_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['regulatory_product'], name='regulatory__regulat_a873d6_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['dossier'], name='regulatory__dossier_48775b_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['registration'], name='regulatory__registr_3a300a_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['petition'], name='regulatory__petitio_18d098_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['requirement'], name='regulatory__require_a68d42_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['commitment'], name='regulatory__commitm_9fe8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryalert',
            index=models.Index(fields=['due_date'], name='regulatory__due_dat_de0caf_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorycommitment',
            index=models.Index(fields=['dossier', 'status'], name='regulatory__dossier_e18252_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorycommitment',
            index=models.Index(fields=['responsible', 'due_date'], name='regulatory__respons_220f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorydossier',
            index=models.Index(fields=['regulatory_product', 'status'], name='regulatory__regulat_e67eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorydossier',
            index=models.Index(fields=['dossier_type', 'status'], name='regulatory__dossier_35ecaa_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorydossier',
            index=models.Index(fields=['responsible'], name='regulatory__respons_af5c87_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorydossier',
            index=models.Index(fields=['due_date'], name='regulatory__due_dat_9cb09b_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryevidence',
            index=models.Index(fields=['dossier'], name='regulatory__dossier_72f7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryevidence',
            index=models.Index(fields=['petition'], name='regulatory__petitio_316e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryevidence',
            index=models.Index(fields=['requirement'], name='regulatory__require_fb929f_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryevidence',
            index=models.Index(fields=['commitment'], name='regulatory__commitm_ab05c7_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['dossier', 'link_type'], name='regulatory__dossier_06d41f_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['product'], name='regulatory__product_95eeae_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['stock_lot'], name='regulatory__stock_l_312c82_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['document'], name='regulatory__documen_4ea5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['change_control'], name='regulatory__change__2ad4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['deviation_event'], name='regulatory__deviati_1ff489_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['capa'], name='regulatory__capa_id_128722_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorylink',
            index=models.Index(fields=['partner'], name='regulatory__partner_207ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorypetition',
            index=models.Index(fields=['dossier', 'status'], name='regulatory__dossier_2f4d93_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorypetition',
            index=models.Index(fields=['petition_type', 'status'], name='regulatory__petitio_e4a620_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatorypetition',
            index=models.Index(fields=['response_due_date'], name='regulatory__respons_a12e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryproduct',
            index=models.Index(fields=['product', 'status'], name='regulatory__product_4d22f3_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryproduct',
            index=models.Index(fields=['responsible'], name='regulatory__respons_3052f5_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryregistration',
            index=models.Index(fields=['regulatory_product', 'status'], name='regulatory__regulat_dc261f_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryregistration',
            index=models.Index(fields=['valid_until'], name='regulatory__valid_u_c67533_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryregistration',
            index=models.Index(fields=['next_renewal_due_date'], name='regulatory__next_re_d5b803_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryreport',
            index=models.Index(fields=['dossier', 'status'], name='regulatory__dossier_dac52f_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryreport',
            index=models.Index(fields=['report_type'], name='regulatory__report__cb4526_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryreport',
            index=models.Index(fields=['generated_at'], name='regulatory__generat_f616bb_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryrequirement',
            index=models.Index(fields=['dossier', 'status'], name='regulatory__dossier_cf2590_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryrequirement',
            index=models.Index(fields=['petition'], name='regulatory__petitio_328f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='regulatoryrequirement',
            index=models.Index(fields=['responsible', 'response_due_date'], name='regulatory__respons_b8bc85_idx'),
        ),
        migrations.AddConstraint(
            model_name='regulatorycommitment',
            constraint=models.UniqueConstraint(fields=('commitment_number',), name='unique_regulatory_commitment_number'),
        ),
        migrations.AddConstraint(
            model_name='regulatorydossier',
            constraint=models.UniqueConstraint(fields=('dossier_number',), name='unique_regulatory_dossier_number'),
        ),
        migrations.AddConstraint(
            model_name='regulatorypetition',
            constraint=models.UniqueConstraint(fields=('petition_number',), name='unique_regulatory_petition_number'),
        ),
        migrations.AddConstraint(
            model_name='regulatoryproduct',
            constraint=models.UniqueConstraint(fields=('regulatory_code',), name='unique_regulatory_product_code'),
        ),
        migrations.AddConstraint(
            model_name='regulatoryproduct',
            constraint=models.UniqueConstraint(fields=('product', 'presentation'), name='unique_product_presentation'),
        ),
        migrations.AddConstraint(
            model_name='regulatoryregistration',
            constraint=models.UniqueConstraint(fields=('registration_number',), name='unique_registration_number'),
        ),
        migrations.AddConstraint(
            model_name='regulatoryrequirement',
            constraint=models.UniqueConstraint(fields=('requirement_number',), name='unique_regulatory_requirement_number'),
        ),
    ]
