# Generated by Django 6.0.7 on 2026-07-08 09:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('finance', '0001_initial'),
        ('fiscal', '0001_initial'),
        ('quality', '0001_initial'),
        ('regulatory', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('file_number', models.CharField(blank=True, max_length=80, verbose_name='número do arquivo')),
                ('source_module', models.CharField(choices=[('operational', 'Operacional'), ('financial', 'Financeiro'), ('fiscal', 'Fiscal'), ('quality', 'Qualidade'), ('regulatory', 'Regulatório'), ('administrative', 'Administrativo')], max_length=32, verbose_name='módulo de origem')),
                ('source_model', models.CharField(max_length=120, verbose_name='modelo de origem')),
                ('source_record_id', models.CharField(max_length=80, verbose_name='registro de origem')),
                ('file_type', models.CharField(choices=[('document', 'Documento'), ('fiscal_document', 'Documento fiscal'), ('certificate', 'Certificado'), ('report', 'Relatório'), ('evidence', 'Evidência'), ('image', 'Imagem'), ('contract', 'Contrato'), ('other', 'Outro')], max_length=32, verbose_name='tipo de arquivo')),
                ('origin', models.CharField(choices=[('upload', 'Upload'), ('system', 'Sistema'), ('integration', 'Integração'), ('email', 'Email'), ('scanner', 'Scanner')], max_length=32, verbose_name='origem')),
                ('criticality', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=24, verbose_name='criticidade')),
                ('confidentiality', models.CharField(choices=[('public_internal', 'Público interno'), ('internal', 'Interno'), ('restricted', 'Restrito'), ('confidential', 'Confidencial')], default='internal', max_length=32, verbose_name='sigilo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('file_name', models.CharField(max_length=180, verbose_name='nome do arquivo')),
                ('file_reference', models.CharField(max_length=255, verbose_name='referência protegida')),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='MIME type')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='tamanho em bytes')),
                ('content_hash', models.CharField(max_length=128, verbose_name='hash do conteúdo')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='enviado em')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('superseded', 'Substituído'), ('expired', 'Expirado'), ('deleted', 'Excluído')], default='active', max_length=24, verbose_name='status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluído em')),
                ('deletion_reason', models.TextField(blank=True, verbose_name='motivo da exclusão')),
                ('controlled_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_files', to='documents.controlleddocument', verbose_name='documento controlado')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_protected_files', to=settings.AUTH_USER_MODEL, verbose_name='excluído por')),
                ('financial_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_files', to='finance.financialtitle', verbose_name='título financeiro')),
                ('fiscal_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_files', to='fiscal.fiscaldocument', verbose_name='documento fiscal')),
                ('quality_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_files', to='quality.qualitydocument', verbose_name='documento de qualidade')),
                ('regulatory_dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_files', to='regulatory.regulatorydossier', verbose_name='dossiê regulatório')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_files', to='files.protectedfile', verbose_name='substituído por')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_protected_files', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='files.protectedfile', verbose_name='substitui')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_protected_files', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'arquivo protegido',
                'verbose_name_plural': 'arquivos protegidos',
                'ordering': ['-created_at', 'file_number'],
            },
        ),
        migrations.CreateModel(
            name='ProtectedFileAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('rule_type', models.CharField(choices=[('user', 'Usuário'), ('role', 'Papel'), ('module', 'Módulo'), ('record', 'Registro')], max_length=24, verbose_name='tipo de regra')),
                ('role', models.CharField(blank=True, choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('quality', 'Qualidade'), ('production', 'Produção'), ('regulatory', 'Regulatório'), ('finance', 'Financeiro'), ('viewer', 'Leitura')], max_length=32, verbose_name='papel')),
                ('source_module', models.CharField(blank=True, choices=[('operational', 'Operacional'), ('financial', 'Financeiro'), ('fiscal', 'Fiscal'), ('quality', 'Qualidade'), ('regulatory', 'Regulatório'), ('administrative', 'Administrativo')], max_length=32, verbose_name='módulo')),
                ('source_model', models.CharField(blank=True, max_length=120, verbose_name='modelo de origem')),
                ('source_record_id', models.CharField(blank=True, max_length=80, verbose_name='registro de origem')),
                ('permission', models.CharField(choices=[('view', 'Visualizar'), ('download', 'Baixar'), ('manage', 'Gerenciar')], max_length=24, verbose_name='permissão')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('protected_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='files.protectedfile', verbose_name='arquivo protegido')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protected_file_access_rules', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'regra de acesso a arquivo',
                'verbose_name_plural': 'regras de acesso a arquivos',
                'ordering': ['protected_file', 'rule_type', 'permission'],
            },
        ),
        migrations.CreateModel(
            name='SecureFileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('token', models.CharField(blank=True, max_length=128, unique=True, verbose_name='token')),
                ('purpose', models.CharField(choices=[('download', 'Download'), ('view', 'Visualização')], max_length=24, verbose_name='finalidade')),
                ('expires_at', models.DateTimeField(verbose_name='expira em')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='usos máximos')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='usos realizados')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='revogado')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revogado em')),
                ('revocation_reason', models.TextField(blank=True, verbose_name='motivo da revogação')),
                ('protected_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_links', to='files.protectedfile', verbose_name='arquivo protegido')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_secure_file_links', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_secure_file_links', to=settings.AUTH_USER_MODEL, verbose_name='revogado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'link seguro de arquivo',
                'verbose_name_plural': 'links seguros de arquivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProtectedFileAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('view', 'Visualização'), ('replace', 'Substituição'), ('delete', 'Exclusão'), ('expire', 'Expiração'), ('link_generated', 'Link gerado'), ('link_revoked', 'Link revogado'), ('access_denied', 'Acesso negado')], max_length=32, verbose_name='ação')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ocorrido em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='detalhes')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_file_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('protected_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='files.protectedfile', verbose_name='arquivo protegido')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('secure_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trail', to='files.securefilelink', verbose_name='link seguro')),
            ],
            options={
                'verbose_name': 'auditoria de arquivo protegido',
                'verbose_name_plural': 'auditorias de arquivos protegidos',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['tenant', 'source_module', 'source_model', 'source_record_id'], name='files_prote_tenant__b0a011_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['tenant', 'file_type', 'status'], name='files_prote_tenant__aaaafd_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['tenant', 'criticality', 'confidentiality'], name='files_prote_tenant__2b4815_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['tenant', 'valid_until'], name='files_prote_tenant__bd822a_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['tenant', 'uploaded_by'], name='files_prote_tenant__3d49da_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['content_hash'], name='files_prote_content_1f90a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='protectedfile',
            constraint=models.UniqueConstraint(fields=('tenant', 'file_number'), name='unique_tenant_protected_file_number'),
        ),
        migrations.AddConstraint(
            model_name='protectedfile',
            constraint=models.UniqueConstraint(fields=('tenant', 'content_hash', 'file_reference'), name='unique_tenant_protected_file_hash_reference'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['tenant', 'protected_file', 'is_active'], name='files_prote_tenant__2af4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['tenant', 'rule_type', 'permission'], name='files_prote_tenant__13329e_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['tenant', 'user'], name='files_prote_tenant__dfb85b_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['tenant', 'role'], name='files_prote_tenant__051446_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['tenant', 'source_module', 'source_model', 'source_record_id'], name='files_prote_tenant__f33bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='securefilelink',
            index=models.Index(fields=['tenant', 'protected_file', 'purpose'], name='files_secur_tenant__8aee83_idx'),
        ),
        migrations.AddIndex(
            model_name='securefilelink',
            index=models.Index(fields=['tenant', 'requested_by'], name='files_secur_tenant__2ad2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='securefilelink',
            index=models.Index(fields=['tenant', 'expires_at'], name='files_secur_tenant__d1954b_idx'),
        ),
        migrations.AddIndex(
            model_name='securefilelink',
            index=models.Index(fields=['token'], name='files_secur_token_b2d13c_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaudittrail',
            index=models.Index(fields=['tenant', 'protected_file', 'action'], name='files_prote_tenant__1449d3_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaudittrail',
            index=models.Index(fields=['tenant', 'actor'], name='files_prote_tenant__f5c102_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaudittrail',
            index=models.Index(fields=['tenant', 'occurred_at'], name='files_prote_tenant__617449_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaudittrail',
            index=models.Index(fields=['action'], name='files_prote_action_438415_idx'),
        ),
    ]
