# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('documents', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedFileAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('rule_type', models.CharField(choices=[('user', 'Usuário'), ('role', 'Papel'), ('module', 'Módulo'), ('record', 'Registro')], max_length=24, verbose_name='tipo de regra')),
                ('role', models.CharField(blank=True, choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('quality', 'Qualidade'), ('production', 'Produção'), ('regulatory', 'Regulatório'), ('finance', 'Financeiro'), ('viewer', 'Leitura')], max_length=32, verbose_name='papel')),
                ('source_module', models.CharField(blank=True, choices=[('operational', 'Operacional'), ('financial', 'Financeiro'), ('fiscal', 'Fiscal'), ('quality', 'Qualidade'), ('regulatory', 'Regulatório'), ('administrative', 'Administrativo')], max_length=32, verbose_name='módulo')),
                ('source_model', models.CharField(blank=True, max_length=120, verbose_name='modelo de origem')),
                ('source_record_id', models.CharField(blank=True, max_length=80, verbose_name='registro de origem')),
                ('permission', models.CharField(choices=[('view', 'Visualizar'), ('download', 'Baixar'), ('manage', 'Gerenciar')], max_length=24, verbose_name='permissão')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'regra de acesso a arquivo',
                'verbose_name_plural': 'regras de acesso a arquivos',
                'ordering': ['protected_file', 'rule_type', 'permission'],
            },
        ),
        migrations.CreateModel(
            name='ProtectedFileAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('view', 'Visualização'), ('replace', 'Substituição'), ('delete', 'Exclusão'), ('expire', 'Expiração'), ('link_generated', 'Link gerado'), ('link_revoked', 'Link revogado'), ('access_denied', 'Acesso negado')], max_length=32, verbose_name='ação')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ocorrido em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='detalhes')),
            ],
            options={
                'verbose_name': 'auditoria de arquivo protegido',
                'verbose_name_plural': 'auditorias de arquivos protegidos',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecureFileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('token', models.CharField(blank=True, max_length=128, unique=True, verbose_name='token')),
                ('purpose', models.CharField(choices=[('download', 'Download'), ('view', 'Visualização')], max_length=24, verbose_name='finalidade')),
                ('expires_at', models.DateTimeField(verbose_name='expira em')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='usos máximos')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='usos realizados')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='revogado')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revogado em')),
                ('revocation_reason', models.TextField(blank=True, verbose_name='motivo da revogação')),
            ],
            options={
                'verbose_name': 'link seguro de arquivo',
                'verbose_name_plural': 'links seguros de arquivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProtectedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('file_number', models.CharField(blank=True, max_length=80, verbose_name='número do arquivo')),
                ('source_module', models.CharField(choices=[('operational', 'Operacional'), ('financial', 'Financeiro'), ('fiscal', 'Fiscal'), ('quality', 'Qualidade'), ('regulatory', 'Regulatório'), ('administrative', 'Administrativo')], max_length=32, verbose_name='módulo de origem')),
                ('source_model', models.CharField(max_length=120, verbose_name='modelo de origem')),
                ('source_record_id', models.CharField(max_length=80, verbose_name='registro de origem')),
                ('file_type', models.CharField(choices=[('document', 'Documento'), ('fiscal_document', 'Documento fiscal'), ('certificate', 'Certificado'), ('report', 'Relatório'), ('evidence', 'Evidência'), ('image', 'Imagem'), ('contract', 'Contrato'), ('other', 'Outro')], max_length=32, verbose_name='tipo de arquivo')),
                ('origin', models.CharField(choices=[('upload', 'Upload'), ('system', 'Sistema'), ('integration', 'Integração'), ('email', 'Email'), ('scanner', 'Scanner')], max_length=32, verbose_name='origem')),
                ('criticality', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=24, verbose_name='criticidade')),
                ('confidentiality', models.CharField(choices=[('public_internal', 'Público interno'), ('internal', 'Interno'), ('restricted', 'Restrito'), ('confidential', 'Confidencial')], default='internal', max_length=32, verbose_name='sigilo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('file_name', models.CharField(max_length=180, verbose_name='nome do arquivo')),
                ('file_reference', models.CharField(max_length=255, verbose_name='referência protegida')),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='MIME type')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='tamanho em bytes')),
                ('content_hash', models.CharField(max_length=128, verbose_name='hash do conteúdo')),
                ('encryption_algorithm', models.CharField(choices=[('none', 'Sem criptografia'), ('aes-256-gcm', 'AES-256-GCM')], default='none', max_length=32, verbose_name='algoritmo de criptografia')),
                ('encryption_key_id', models.CharField(blank=True, max_length=80, verbose_name='id da chave de criptografia')),
                ('encrypted_at', models.DateTimeField(blank=True, null=True, verbose_name='criptografado em')),
                ('encrypted_size', models.PositiveBigIntegerField(default=0, verbose_name='tamanho criptografado em bytes')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='enviado em')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('superseded', 'Substituído'), ('expired', 'Expirado'), ('deleted', 'Excluído')], default='active', max_length=24, verbose_name='status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluído em')),
                ('deletion_reason', models.TextField(blank=True, verbose_name='motivo da exclusão')),
                ('controlled_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_files', to='documents.controlleddocument', verbose_name='documento controlado')),
                ('criticality_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='criticidade normalizada')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_protected_files', to=settings.AUTH_USER_MODEL, verbose_name='excluído por')),
                ('financial_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_files', to='finance.financialtitle', verbose_name='título financeiro')),
            ],
            options={
                'verbose_name': 'arquivo protegido',
                'verbose_name_plural': 'arquivos protegidos',
                'ordering': ['-created_at', 'file_number'],
            },
        ),
    ]
