# Generated by Django 6.0.7 on 2026-07-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedfile',
            name='criticality_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='criticidade normalizada'),
        ),
        migrations.AddField(
            model_name='protectedfile',
            name='source_model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model de origem normalizado'),
        ),
        migrations.AddField(
            model_name='protectedfile',
            name='source_module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo de origem normalizado'),
        ),
        migrations.AddField(
            model_name='protectedfileaccessrule',
            name='source_model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model de origem normalizado'),
        ),
        migrations.AddField(
            model_name='protectedfileaccessrule',
            name='source_module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo normalizado'),
        ),
    ]
