# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedfile',
            name='fiscal_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_files', to='fiscal.fiscaldocument', verbose_name='documento fiscal'),
        ),
    ]
