# Generated by Django 6.0.7 on 2026-07-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_protectedfile_criticality_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedfile',
            name='encrypted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='criptografado em'),
        ),
        migrations.AddField(
            model_name='protectedfile',
            name='encrypted_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='tamanho criptografado em bytes'),
        ),
        migrations.AddField(
            model_name='protectedfile',
            name='encryption_algorithm',
            field=models.CharField(choices=[('none', 'Sem criptografia'), ('aes-256-gcm', 'AES-256-GCM')], default='none', max_length=32, verbose_name='algoritmo de criptografia'),
        ),
        migrations.AddField(
            model_name='protectedfile',
            name='encryption_key_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='id da chave de criptografia'),
        ),
    ]
