# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('files', '0002_initial'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedfile',
            name='quality_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_files', to='quality.qualitydocument', verbose_name='documento de qualidade'),
        ),
        migrations.AddField(
            model_name='protectedfile',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_files', to='files.protectedfile', verbose_name='substituído por'),
        ),
        migrations.AddField(
            model_name='protectedfile',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_protected_files', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
        migrations.AddField(
            model_name='protectedfile',
            name='source_model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model de origem normalizado'),
        ),
        migrations.AddField(
            model_name='protectedfile',
            name='source_module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo de origem normalizado'),
        ),
        migrations.AddField(
            model_name='protectedfile',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='files.protectedfile', verbose_name='substitui'),
        ),
        migrations.AddField(
            model_name='protectedfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_protected_files', to=settings.AUTH_USER_MODEL, verbose_name='enviado por'),
        ),
        migrations.AddField(
            model_name='protectedfileaccessrule',
            name='protected_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='files.protectedfile', verbose_name='arquivo protegido'),
        ),
        migrations.AddField(
            model_name='protectedfileaccessrule',
            name='source_model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model de origem normalizado'),
        ),
        migrations.AddField(
            model_name='protectedfileaccessrule',
            name='source_module_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo normalizado'),
        ),
        migrations.AddField(
            model_name='protectedfileaccessrule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protected_file_access_rules', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='protectedfileaudittrail',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protected_file_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='protectedfileaudittrail',
            name='protected_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='files.protectedfile', verbose_name='arquivo protegido'),
        ),
        migrations.AddField(
            model_name='securefilelink',
            name='protected_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_links', to='files.protectedfile', verbose_name='arquivo protegido'),
        ),
        migrations.AddField(
            model_name='securefilelink',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_secure_file_links', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por'),
        ),
        migrations.AddField(
            model_name='securefilelink',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_secure_file_links', to=settings.AUTH_USER_MODEL, verbose_name='revogado por'),
        ),
        migrations.AddField(
            model_name='protectedfileaudittrail',
            name='secure_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trail', to='files.securefilelink', verbose_name='link seguro'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['source_module', 'source_model', 'source_record_id'], name='files_prote_source__f2a030_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['file_type', 'status'], name='files_prote_file_ty_db43b1_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['criticality', 'confidentiality'], name='files_prote_critica_67604c_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['valid_until'], name='files_prote_valid_u_de0be2_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['uploaded_by'], name='files_prote_uploade_f3b5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['content_hash'], name='files_prote_content_1f90a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='protectedfile',
            constraint=models.UniqueConstraint(fields=('file_number',), name='unique_protected_file_number'),
        ),
        migrations.AddConstraint(
            model_name='protectedfile',
            constraint=models.UniqueConstraint(fields=('content_hash', 'file_reference'), name='unique_protected_file_hash_reference'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['protected_file', 'is_active'], name='files_prote_protect_30305d_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['rule_type', 'permission'], name='files_prote_rule_ty_470ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['user'], name='files_prote_user_id_69701a_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['role'], name='files_prote_role_e68bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['source_module', 'source_model', 'source_record_id'], name='files_prote_source__d84468_idx'),
        ),
        migrations.AddIndex(
            model_name='securefilelink',
            index=models.Index(fields=['protected_file', 'purpose'], name='files_secur_protect_16636d_idx'),
        ),
        migrations.AddIndex(
            model_name='securefilelink',
            index=models.Index(fields=['requested_by'], name='files_secur_request_2a0e14_idx'),
        ),
        migrations.AddIndex(
            model_name='securefilelink',
            index=models.Index(fields=['expires_at'], name='files_secur_expires_5b6d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='securefilelink',
            index=models.Index(fields=['token'], name='files_secur_token_b2d13c_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaudittrail',
            index=models.Index(fields=['protected_file', 'action'], name='files_prote_protect_d3c23d_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaudittrail',
            index=models.Index(fields=['actor'], name='files_prote_actor_i_a01fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaudittrail',
            index=models.Index(fields=['occurred_at'], name='files_prote_occurre_186a80_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaudittrail',
            index=models.Index(fields=['action'], name='files_prote_action_438415_idx'),
        ),
    ]
