# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('documents', '0003_remove_controlleddocument_unique_tenant_document_code_version_and_more'),
        ('files', '0003_protectedfile_encrypted_at_and_more'),
        ('finance', '0002_remove_chartofaccount_unique_tenant_chart_account_code_and_more'),
        ('fiscal', '0004_add_zipcode_and_address'),
        ('quality', '0003_remove_analyticalspecification_unique_tenant_qc_spec_product_lot_version_and_more'),
        ('regulatory', '0004_remove_regulatorycommitment_unique_tenant_regulatory_commitment_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='protectedfile',
            name='unique_tenant_protected_file_number',
        ),
        migrations.RemoveConstraint(
            model_name='protectedfile',
            name='unique_tenant_protected_file_hash_reference',
        ),
        migrations.RemoveIndex(
            model_name='protectedfile',
            name='files_prote_tenant__b0a011_idx',
        ),
        migrations.RemoveIndex(
            model_name='protectedfile',
            name='files_prote_tenant__aaaafd_idx',
        ),
        migrations.RemoveIndex(
            model_name='protectedfile',
            name='files_prote_tenant__2b4815_idx',
        ),
        migrations.RemoveIndex(
            model_name='protectedfile',
            name='files_prote_tenant__bd822a_idx',
        ),
        migrations.RemoveIndex(
            model_name='protectedfile',
            name='files_prote_tenant__3d49da_idx',
        ),
        migrations.RemoveIndex(
            model_name='protectedfileaccessrule',
            name='files_prote_tenant__2af4f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='protectedfileaccessrule',
            name='files_prote_tenant__13329e_idx',
        ),
        migrations.RemoveIndex(
            model_name='protectedfileaccessrule',
            name='files_prote_tenant__dfb85b_idx',
        ),
        migrations.RemoveIndex(
            model_name='protectedfileaccessrule',
            name='files_prote_tenant__051446_idx',
        ),
        migrations.RemoveIndex(
            model_name='protectedfileaccessrule',
            name='files_prote_tenant__f33bf8_idx',
        ),
        migrations.RemoveIndex(
            model_name='protectedfileaudittrail',
            name='files_prote_tenant__1449d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='protectedfileaudittrail',
            name='files_prote_tenant__f5c102_idx',
        ),
        migrations.RemoveIndex(
            model_name='protectedfileaudittrail',
            name='files_prote_tenant__617449_idx',
        ),
        migrations.RemoveIndex(
            model_name='securefilelink',
            name='files_secur_tenant__8aee83_idx',
        ),
        migrations.RemoveIndex(
            model_name='securefilelink',
            name='files_secur_tenant__2ad2b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='securefilelink',
            name='files_secur_tenant__d1954b_idx',
        ),
        migrations.RemoveField(
            model_name='protectedfile',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='protectedfileaccessrule',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='protectedfileaudittrail',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='securefilelink',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['source_module', 'source_model', 'source_record_id'], name='files_prote_source__f2a030_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['file_type', 'status'], name='files_prote_file_ty_db43b1_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['criticality', 'confidentiality'], name='files_prote_critica_67604c_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['valid_until'], name='files_prote_valid_u_de0be2_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfile',
            index=models.Index(fields=['uploaded_by'], name='files_prote_uploade_f3b5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['protected_file', 'is_active'], name='files_prote_protect_30305d_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['rule_type', 'permission'], name='files_prote_rule_ty_470ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['user'], name='files_prote_user_id_69701a_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['role'], name='files_prote_role_e68bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaccessrule',
            index=models.Index(fields=['source_module', 'source_model', 'source_record_id'], name='files_prote_source__d84468_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaudittrail',
            index=models.Index(fields=['protected_file', 'action'], name='files_prote_protect_d3c23d_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaudittrail',
            index=models.Index(fields=['actor'], name='files_prote_actor_i_a01fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='protectedfileaudittrail',
            index=models.Index(fields=['occurred_at'], name='files_prote_occurre_186a80_idx'),
        ),
        migrations.AddIndex(
            model_name='securefilelink',
            index=models.Index(fields=['protected_file', 'purpose'], name='files_secur_protect_16636d_idx'),
        ),
        migrations.AddIndex(
            model_name='securefilelink',
            index=models.Index(fields=['requested_by'], name='files_secur_request_2a0e14_idx'),
        ),
        migrations.AddIndex(
            model_name='securefilelink',
            index=models.Index(fields=['expires_at'], name='files_secur_expires_5b6d0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='protectedfile',
            constraint=models.UniqueConstraint(fields=('file_number',), name='unique_protected_file_number'),
        ),
        migrations.AddConstraint(
            model_name='protectedfile',
            constraint=models.UniqueConstraint(fields=('content_hash', 'file_reference'), name='unique_protected_file_hash_reference'),
        ),
    ]
