# Generated by Django 6.0.8 on 2026-08-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='IdentifierSequence',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name='criado em'
                    ),
                ),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                (
                    'namespace',
                    models.CharField(
                        max_length=180, primary_key=True, serialize=False, verbose_name='namespace'
                    ),
                ),
                ('value', models.PositiveBigIntegerField(default=0, verbose_name='último valor')),
            ],
            options={
                'verbose_name': 'sequência de identificador',
                'verbose_name_plural': 'sequências de identificadores',
                'ordering': ['namespace'],
            },
        ),
    ]
