# Generated by Django 6.0.7 on 2026-07-07 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('deviations', '0001_initial'),
        ('quality', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapaAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('action_type', models.CharField(choices=[('corrective', 'Corretiva'), ('preventive', 'Preventiva')], max_length=24, verbose_name='tipo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('due_date', models.DateField(verbose_name='prazo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=24, verbose_name='status')),
                ('evidence_required', models.BooleanField(default=True, verbose_name='exige evidência')),
                ('completion_notes', models.TextField(blank=True, verbose_name='observações de conclusão')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_capa_actions', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capa_actions', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'ação CAPA',
                'verbose_name_plural': 'ações CAPA',
                'ordering': ['capa__capa_number', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='CapaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('capa_number', models.CharField(blank=True, max_length=80, verbose_name='CAPA')),
                ('source_type', models.CharField(choices=[('deviation', 'Desvio'), ('audit', 'Auditoria'), ('complaint', 'Reclamação'), ('risk', 'Risco'), ('oos_oot', 'OOS/OOT'), ('change', 'Mudança'), ('improvement', 'Melhoria')], max_length=24, verbose_name='origem')),
                ('source_reference', models.CharField(blank=True, max_length=120, verbose_name='referência de origem')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('root_cause', models.TextField(verbose_name='causa raiz')),
                ('action_plan', models.TextField(verbose_name='plano de ação')),
                ('due_date', models.DateField(verbose_name='prazo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('open', 'Aberta'), ('in_progress', 'Em andamento'), ('pending_effectiveness', 'Aguardando eficácia'), ('pending_approval', 'Aguardando aprovação'), ('closed', 'Encerrada'), ('cancelled', 'Cancelada')], default='draft', max_length=32, verbose_name='status')),
                ('requires_effectiveness_check', models.BooleanField(default=True, verbose_name='exige eficácia')),
                ('effectiveness_criteria', models.TextField(blank=True, verbose_name='critério de eficácia')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='aberta em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrada em')),
                ('closure_summary', models.TextField(blank=True, verbose_name='resumo de encerramento')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_capas', to=settings.AUTH_USER_MODEL, verbose_name='encerrada por')),
                ('customer_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capa_records', to='crm.customercomplaint', verbose_name='reclamação')),
                ('deviation_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capa_records', to='deviations.qualityevent', verbose_name='desvio/não conformidade')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opened_capas', to=settings.AUTH_USER_MODEL, verbose_name='aberta por')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_capas', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('quality_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capa_records', to='quality.qualityresult', verbose_name='resultado OOS/OOT')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'CAPA',
                'verbose_name_plural': 'CAPAs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapaEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('file_reference', models.CharField(max_length=255, verbose_name='arquivo')),
                ('content_hash', models.CharField(max_length=128, verbose_name='hash do conteúdo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='capa.capaaction', verbose_name='ação')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_capa_evidences', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='capa.caparecord', verbose_name='CAPA')),
            ],
            options={
                'verbose_name': 'evidência CAPA',
                'verbose_name_plural': 'evidências CAPA',
                'ordering': ['capa__capa_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CapaApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(choices=[('qa', 'Garantia da Qualidade'), ('owner', 'Responsável'), ('regulatory', 'Regulatório'), ('responsible_area', 'Área responsável')], max_length=32, verbose_name='papel')),
                ('required', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('decision', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=24, verbose_name='decisão')),
                ('comments', models.TextField(blank=True, verbose_name='comentários')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidido em')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capa_approvals', to=settings.AUTH_USER_MODEL, verbose_name='aprovador')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_capa_approvals', to=settings.AUTH_USER_MODEL, verbose_name='decidido por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='capa.caparecord', verbose_name='CAPA')),
            ],
            options={
                'verbose_name': 'aprovação CAPA',
                'verbose_name_plural': 'aprovações CAPA',
                'ordering': ['capa__capa_number', 'role'],
            },
        ),
        migrations.AddField(
            model_name='capaaction',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='capa.caparecord', verbose_name='CAPA'),
        ),
        migrations.CreateModel(
            name='EffectivenessCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criteria', models.TextField(verbose_name='critérios')),
                ('planned_date', models.DateField(verbose_name='data planejada')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('effective', 'Eficaz'), ('ineffective', 'Ineficaz')], default='pending', max_length=24, verbose_name='status')),
                ('result', models.TextField(blank=True, verbose_name='resultado')),
                ('evidence_reference', models.CharField(blank=True, max_length=255, verbose_name='evidência')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verificado em')),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_checks', to='capa.caparecord', verbose_name='CAPA')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_capa_effectiveness', to=settings.AUTH_USER_MODEL, verbose_name='verificado por')),
            ],
            options={
                'verbose_name': 'verificação de eficácia CAPA',
                'verbose_name_plural': 'verificações de eficácia CAPA',
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='CapaNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('notification_type', models.CharField(choices=[('due_soon', 'Prazo próximo'), ('overdue', 'Atrasada'), ('approval_required', 'Aprovação pendente'), ('effectiveness_due', 'Eficácia pendente')], max_length=32, verbose_name='tipo')),
                ('due_date', models.DateField(verbose_name='data de referência')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('acknowledged', 'Ciente')], default='pending', max_length=24, verbose_name='status')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='capa.capaaction', verbose_name='ação')),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='capa.capaapproval', verbose_name='aprovação')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capa_notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='capa.caparecord', verbose_name='CAPA')),
                ('effectiveness_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='capa.effectivenesscheck', verbose_name='verificação de eficácia')),
            ],
            options={
                'verbose_name': 'notificação CAPA',
                'verbose_name_plural': 'notificações CAPA',
                'ordering': ['due_date', 'notification_type'],
            },
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['tenant', 'source_type', 'status'], name='capa_capare_tenant__4dff45_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['tenant', 'due_date'], name='capa_capare_tenant__beb6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['tenant', 'owner'], name='capa_capare_tenant__5c6bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['tenant', 'deviation_event'], name='capa_capare_tenant__fcfb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['tenant', 'customer_complaint'], name='capa_capare_tenant__4db780_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['tenant', 'quality_result'], name='capa_capare_tenant__060885_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['capa_number'], name='capa_capare_capa_nu_9f47a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='caparecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'capa_number'), name='unique_tenant_capa_number'),
        ),
        migrations.AddIndex(
            model_name='capaevidence',
            index=models.Index(fields=['tenant', 'capa'], name='capa_capaev_tenant__fd5273_idx'),
        ),
        migrations.AddIndex(
            model_name='capaevidence',
            index=models.Index(fields=['tenant', 'action'], name='capa_capaev_tenant__bc17be_idx'),
        ),
        migrations.AddIndex(
            model_name='capaevidence',
            index=models.Index(fields=['content_hash'], name='capa_capaev_content_1b8e50_idx'),
        ),
        migrations.AddIndex(
            model_name='capaapproval',
            index=models.Index(fields=['tenant', 'capa', 'decision'], name='capa_capaap_tenant__bf0760_idx'),
        ),
        migrations.AddIndex(
            model_name='capaapproval',
            index=models.Index(fields=['tenant', 'approver'], name='capa_capaap_tenant__0c8074_idx'),
        ),
        migrations.AddConstraint(
            model_name='capaapproval',
            constraint=models.UniqueConstraint(fields=('tenant', 'capa', 'role', 'approver'), name='unique_tenant_capa_approval_role_user'),
        ),
        migrations.AddIndex(
            model_name='capaaction',
            index=models.Index(fields=['tenant', 'capa', 'status'], name='capa_capaac_tenant__1f3353_idx'),
        ),
        migrations.AddIndex(
            model_name='capaaction',
            index=models.Index(fields=['tenant', 'responsible', 'due_date'], name='capa_capaac_tenant__0d7d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='capaaction',
            index=models.Index(fields=['tenant', 'action_type'], name='capa_capaac_tenant__97d413_idx'),
        ),
        migrations.AddIndex(
            model_name='effectivenesscheck',
            index=models.Index(fields=['tenant', 'capa', 'status'], name='capa_effect_tenant__47e36c_idx'),
        ),
        migrations.AddIndex(
            model_name='effectivenesscheck',
            index=models.Index(fields=['tenant', 'planned_date'], name='capa_effect_tenant__d7a3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='capanotification',
            index=models.Index(fields=['tenant', 'capa', 'notification_type'], name='capa_capano_tenant__60a016_idx'),
        ),
        migrations.AddIndex(
            model_name='capanotification',
            index=models.Index(fields=['tenant', 'recipient', 'status'], name='capa_capano_tenant__8c7ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='capanotification',
            index=models.Index(fields=['tenant', 'due_date'], name='capa_capano_tenant__07c836_idx'),
        ),
    ]
