# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectivenessCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criteria', models.TextField(verbose_name='critérios')),
                ('planned_date', models.DateField(verbose_name='data planejada')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('effective', 'Eficaz'), ('ineffective', 'Ineficaz')], default='pending', max_length=24, verbose_name='status')),
                ('result', models.TextField(blank=True, verbose_name='resultado')),
                ('evidence_reference', models.CharField(blank=True, max_length=255, verbose_name='evidência')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verificado em')),
            ],
            options={
                'verbose_name': 'verificação de eficácia CAPA',
                'verbose_name_plural': 'verificações de eficácia CAPA',
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='CapaAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('action_type', models.CharField(choices=[('corrective', 'Corretiva'), ('preventive', 'Preventiva')], max_length=24, verbose_name='tipo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('due_date', models.DateField(verbose_name='prazo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=24, verbose_name='status')),
                ('evidence_required', models.BooleanField(default=True, verbose_name='exige evidência')),
                ('completion_notes', models.TextField(blank=True, verbose_name='observações de conclusão')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_capa_actions', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capa_actions', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'ação CAPA',
                'verbose_name_plural': 'ações CAPA',
                'ordering': ['capa__capa_number', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='CapaApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(choices=[('qa', 'Garantia da Qualidade'), ('owner', 'Responsável'), ('regulatory', 'Regulatório'), ('responsible_area', 'Área responsável')], max_length=32, verbose_name='papel')),
                ('required', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('decision', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=24, verbose_name='decisão')),
                ('comments', models.TextField(blank=True, verbose_name='comentários')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidido em')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capa_approvals', to=settings.AUTH_USER_MODEL, verbose_name='aprovador')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_capa_approvals', to=settings.AUTH_USER_MODEL, verbose_name='decidido por')),
            ],
            options={
                'verbose_name': 'aprovação CAPA',
                'verbose_name_plural': 'aprovações CAPA',
                'ordering': ['capa__capa_number', 'role'],
            },
        ),
        migrations.CreateModel(
            name='CapaEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('file_reference', models.CharField(max_length=255, verbose_name='arquivo')),
                ('content_hash', models.CharField(max_length=128, verbose_name='hash do conteúdo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='capa.capaaction', verbose_name='ação')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_capa_evidences', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'evidência CAPA',
                'verbose_name_plural': 'evidências CAPA',
                'ordering': ['capa__capa_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CapaNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('notification_type', models.CharField(choices=[('due_soon', 'Prazo próximo'), ('overdue', 'Atrasada'), ('approval_required', 'Aprovação pendente'), ('effectiveness_due', 'Eficácia pendente')], max_length=32, verbose_name='tipo')),
                ('due_date', models.DateField(verbose_name='data de referência')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('acknowledged', 'Ciente')], default='pending', max_length=24, verbose_name='status')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='capa.capaaction', verbose_name='ação')),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='capa.capaapproval', verbose_name='aprovação')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capa_notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
            ],
            options={
                'verbose_name': 'notificação CAPA',
                'verbose_name_plural': 'notificações CAPA',
                'ordering': ['due_date', 'notification_type'],
            },
        ),
        migrations.CreateModel(
            name='CapaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('capa_number', models.CharField(blank=True, max_length=80, verbose_name='CAPA')),
                ('source_type', models.CharField(choices=[('deviation', 'Desvio'), ('audit', 'Auditoria'), ('complaint', 'Reclamação'), ('risk', 'Risco'), ('oos_oot', 'OOS/OOT'), ('change', 'Mudança'), ('improvement', 'Melhoria')], max_length=24, verbose_name='origem')),
                ('source_reference', models.CharField(blank=True, max_length=120, verbose_name='referência de origem')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('root_cause', models.TextField(verbose_name='causa raiz')),
                ('action_plan', models.TextField(verbose_name='plano de ação')),
                ('due_date', models.DateField(verbose_name='prazo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('open', 'Aberta'), ('in_progress', 'Em andamento'), ('pending_effectiveness', 'Aguardando eficácia'), ('pending_approval', 'Aguardando aprovação'), ('closed', 'Encerrada'), ('cancelled', 'Cancelada')], default='draft', max_length=32, verbose_name='status')),
                ('requires_effectiveness_check', models.BooleanField(default=True, verbose_name='exige eficácia')),
                ('effectiveness_criteria', models.TextField(blank=True, verbose_name='critério de eficácia')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='aberta em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrada em')),
                ('closure_summary', models.TextField(blank=True, verbose_name='resumo de encerramento')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_capas', to=settings.AUTH_USER_MODEL, verbose_name='encerrada por')),
            ],
            options={
                'verbose_name': 'CAPA',
                'verbose_name_plural': 'CAPAs',
                'ordering': ['-created_at'],
            },
        ),
    ]
