# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0001_initial'),
        ('crm', '0003_customercomplaint_city_customercomplaint_city_ref_and_more'),
        ('deviations', '0002_qualityevent_area_ref_qualityevent_criticality_ref_and_more'),
        ('quality', '0002_qualitysample_collection_point_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capaapproval',
            name='unique_tenant_capa_approval_role_user',
        ),
        migrations.RemoveConstraint(
            model_name='caparecord',
            name='unique_tenant_capa_number',
        ),
        migrations.RemoveIndex(
            model_name='capaaction',
            name='capa_capaac_tenant__1f3353_idx',
        ),
        migrations.RemoveIndex(
            model_name='capaaction',
            name='capa_capaac_tenant__0d7d2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='capaaction',
            name='capa_capaac_tenant__97d413_idx',
        ),
        migrations.RemoveIndex(
            model_name='capaapproval',
            name='capa_capaap_tenant__bf0760_idx',
        ),
        migrations.RemoveIndex(
            model_name='capaapproval',
            name='capa_capaap_tenant__0c8074_idx',
        ),
        migrations.RemoveIndex(
            model_name='capaevidence',
            name='capa_capaev_tenant__fd5273_idx',
        ),
        migrations.RemoveIndex(
            model_name='capaevidence',
            name='capa_capaev_tenant__bc17be_idx',
        ),
        migrations.RemoveIndex(
            model_name='capanotification',
            name='capa_capano_tenant__60a016_idx',
        ),
        migrations.RemoveIndex(
            model_name='capanotification',
            name='capa_capano_tenant__8c7ed0_idx',
        ),
        migrations.RemoveIndex(
            model_name='capanotification',
            name='capa_capano_tenant__07c836_idx',
        ),
        migrations.RemoveIndex(
            model_name='caparecord',
            name='capa_capare_tenant__4dff45_idx',
        ),
        migrations.RemoveIndex(
            model_name='caparecord',
            name='capa_capare_tenant__beb6f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='caparecord',
            name='capa_capare_tenant__5c6bfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='caparecord',
            name='capa_capare_tenant__fcfb3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='caparecord',
            name='capa_capare_tenant__4db780_idx',
        ),
        migrations.RemoveIndex(
            model_name='caparecord',
            name='capa_capare_tenant__060885_idx',
        ),
        migrations.RemoveIndex(
            model_name='effectivenesscheck',
            name='capa_effect_tenant__47e36c_idx',
        ),
        migrations.RemoveIndex(
            model_name='effectivenesscheck',
            name='capa_effect_tenant__d7a3d6_idx',
        ),
        migrations.RemoveField(
            model_name='capaaction',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='capaapproval',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='capaevidence',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='capanotification',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='caparecord',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='effectivenesscheck',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='capaaction',
            index=models.Index(fields=['capa', 'status'], name='capa_capaac_capa_id_01afa4_idx'),
        ),
        migrations.AddIndex(
            model_name='capaaction',
            index=models.Index(fields=['responsible', 'due_date'], name='capa_capaac_respons_321e02_idx'),
        ),
        migrations.AddIndex(
            model_name='capaaction',
            index=models.Index(fields=['action_type'], name='capa_capaac_action__cddfae_idx'),
        ),
        migrations.AddIndex(
            model_name='capaapproval',
            index=models.Index(fields=['capa', 'decision'], name='capa_capaap_capa_id_779d38_idx'),
        ),
        migrations.AddIndex(
            model_name='capaapproval',
            index=models.Index(fields=['approver'], name='capa_capaap_approve_07c83d_idx'),
        ),
        migrations.AddIndex(
            model_name='capaevidence',
            index=models.Index(fields=['capa'], name='capa_capaev_capa_id_f361a8_idx'),
        ),
        migrations.AddIndex(
            model_name='capaevidence',
            index=models.Index(fields=['action'], name='capa_capaev_action__164335_idx'),
        ),
        migrations.AddIndex(
            model_name='capanotification',
            index=models.Index(fields=['capa', 'notification_type'], name='capa_capano_capa_id_8b40e7_idx'),
        ),
        migrations.AddIndex(
            model_name='capanotification',
            index=models.Index(fields=['recipient', 'status'], name='capa_capano_recipie_dd3d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='capanotification',
            index=models.Index(fields=['due_date'], name='capa_capano_due_dat_d6b85c_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['source_type', 'status'], name='capa_capare_source__41b230_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['due_date'], name='capa_capare_due_dat_b62d61_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['owner'], name='capa_capare_owner_i_3d43fc_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['deviation_event'], name='capa_capare_deviati_eaf646_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['customer_complaint'], name='capa_capare_custome_da1199_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['quality_result'], name='capa_capare_quality_d5dcb6_idx'),
        ),
        migrations.AddIndex(
            model_name='effectivenesscheck',
            index=models.Index(fields=['capa', 'status'], name='capa_effect_capa_id_b28d85_idx'),
        ),
        migrations.AddIndex(
            model_name='effectivenesscheck',
            index=models.Index(fields=['planned_date'], name='capa_effect_planned_db6edf_idx'),
        ),
        migrations.AddConstraint(
            model_name='capaapproval',
            constraint=models.UniqueConstraint(fields=('capa', 'role', 'approver'), name='unique_capa_approval_role_user'),
        ),
        migrations.AddConstraint(
            model_name='caparecord',
            constraint=models.UniqueConstraint(fields=('capa_number',), name='unique_capa_number'),
        ),
    ]
