# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0002_initial'),
        ('deviations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caparecord',
            name='deviation_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capa_records', to='deviations.qualityevent', verbose_name='desvio/não conformidade'),
        ),
        migrations.AddField(
            model_name='caparecord',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opened_capas', to=settings.AUTH_USER_MODEL, verbose_name='aberta por'),
        ),
        migrations.AddField(
            model_name='caparecord',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_capas', to=settings.AUTH_USER_MODEL, verbose_name='responsável'),
        ),
    ]
