# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0003_initial'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caparecord',
            name='quality_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capa_records', to='quality.qualityresult', verbose_name='resultado OOS/OOT'),
        ),
        migrations.AddField(
            model_name='capanotification',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='capa.caparecord', verbose_name='CAPA'),
        ),
        migrations.AddField(
            model_name='capaevidence',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='capa.caparecord', verbose_name='CAPA'),
        ),
        migrations.AddField(
            model_name='capaapproval',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='capa.caparecord', verbose_name='CAPA'),
        ),
        migrations.AddField(
            model_name='capaaction',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='capa.caparecord', verbose_name='CAPA'),
        ),
        migrations.AddField(
            model_name='effectivenesscheck',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_checks', to='capa.caparecord', verbose_name='CAPA'),
        ),
        migrations.AddField(
            model_name='effectivenesscheck',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_capa_effectiveness', to=settings.AUTH_USER_MODEL, verbose_name='verificado por'),
        ),
        migrations.AddField(
            model_name='capanotification',
            name='effectiveness_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='capa.effectivenesscheck', verbose_name='verificação de eficácia'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['source_type', 'status'], name='capa_capare_source__41b230_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['due_date'], name='capa_capare_due_dat_b62d61_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['owner'], name='capa_capare_owner_i_3d43fc_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['deviation_event'], name='capa_capare_deviati_eaf646_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['customer_complaint'], name='capa_capare_custome_da1199_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['quality_result'], name='capa_capare_quality_d5dcb6_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['capa_number'], name='capa_capare_capa_nu_9f47a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='caparecord',
            constraint=models.UniqueConstraint(fields=('capa_number',), name='unique_capa_number'),
        ),
        migrations.AddIndex(
            model_name='capaevidence',
            index=models.Index(fields=['capa'], name='capa_capaev_capa_id_f361a8_idx'),
        ),
        migrations.AddIndex(
            model_name='capaevidence',
            index=models.Index(fields=['action'], name='capa_capaev_action__164335_idx'),
        ),
        migrations.AddIndex(
            model_name='capaevidence',
            index=models.Index(fields=['content_hash'], name='capa_capaev_content_1b8e50_idx'),
        ),
        migrations.AddIndex(
            model_name='capaapproval',
            index=models.Index(fields=['capa', 'decision'], name='capa_capaap_capa_id_779d38_idx'),
        ),
        migrations.AddIndex(
            model_name='capaapproval',
            index=models.Index(fields=['approver'], name='capa_capaap_approve_07c83d_idx'),
        ),
        migrations.AddConstraint(
            model_name='capaapproval',
            constraint=models.UniqueConstraint(fields=('capa', 'role', 'approver'), name='unique_capa_approval_role_user'),
        ),
        migrations.AddIndex(
            model_name='capaaction',
            index=models.Index(fields=['capa', 'status'], name='capa_capaac_capa_id_01afa4_idx'),
        ),
        migrations.AddIndex(
            model_name='capaaction',
            index=models.Index(fields=['responsible', 'due_date'], name='capa_capaac_respons_321e02_idx'),
        ),
        migrations.AddIndex(
            model_name='capaaction',
            index=models.Index(fields=['action_type'], name='capa_capaac_action__cddfae_idx'),
        ),
        migrations.AddIndex(
            model_name='effectivenesscheck',
            index=models.Index(fields=['capa', 'status'], name='capa_effect_capa_id_b28d85_idx'),
        ),
        migrations.AddIndex(
            model_name='effectivenesscheck',
            index=models.Index(fields=['planned_date'], name='capa_effect_planned_db6edf_idx'),
        ),
        migrations.AddIndex(
            model_name='capanotification',
            index=models.Index(fields=['capa', 'notification_type'], name='capa_capano_capa_id_8b40e7_idx'),
        ),
        migrations.AddIndex(
            model_name='capanotification',
            index=models.Index(fields=['recipient', 'status'], name='capa_capano_recipie_dd3d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='capanotification',
            index=models.Index(fields=['due_date'], name='capa_capano_due_dat_d6b85c_idx'),
        ),
    ]
