# Generated by Django 6.0.7 on 2026-07-08 00:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capa', '0001_initial'),
        ('crm', '0001_initial'),
        ('deviations', '0001_initial'),
        ('documents', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masters', '0001_initial'),
        ('regulatory', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacovigilanceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('case_number', models.CharField(blank=True, max_length=80, verbose_name='caso')),
                ('case_type', models.CharField(choices=[('adverse_event', 'Evento adverso'), ('technical_complaint', 'Queixa técnica'), ('suspected_deviation', 'Suspeita de desvio'), ('patient_complaint', 'Reclamação de paciente'), ('safety_notification', 'Notificação de segurança')], max_length=32, verbose_name='tipo')),
                ('source', models.CharField(choices=[('patient', 'Paciente'), ('healthcare_professional', 'Profissional de saúde'), ('customer', 'Cliente'), ('distributor', 'Distribuidor'), ('authority', 'Autoridade sanitária'), ('internal', 'Interna'), ('literature', 'Literatura'), ('other', 'Outra')], max_length=40, verbose_name='fonte')),
                ('patient_identifier_hash', models.CharField(blank=True, max_length=128, verbose_name='hash do paciente anonimizado')),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='idade do paciente')),
                ('patient_gender', models.CharField(blank=True, max_length=32, verbose_name='gênero do paciente')),
                ('country', models.CharField(max_length=80, verbose_name='país')),
                ('seriousness', models.CharField(choices=[('non_serious', 'Não sério'), ('serious', 'Sério')], max_length=24, verbose_name='seriedade')),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=24, verbose_name='gravidade')),
                ('outcome', models.CharField(choices=[('recovered', 'Recuperado'), ('recovering', 'Em recuperação'), ('not_recovered', 'Não recuperado'), ('fatal', 'Fatal'), ('unknown', 'Desconhecido'), ('not_applicable', 'Não aplicável')], max_length=24, verbose_name='desfecho')),
                ('description', models.TextField(verbose_name='descrição')),
                ('event_started_at', models.DateTimeField(blank=True, null=True, verbose_name='início do evento')),
                ('event_reported_at', models.DateTimeField(verbose_name='data do relato')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('triage', 'Triagem'), ('investigation', 'Investigação'), ('pending_actions', 'Ações pendentes'), ('closed', 'Encerrado'), ('cancelled', 'Cancelado')], default='draft', max_length=32, verbose_name='status')),
                ('triaged_at', models.DateTimeField(blank=True, null=True, verbose_name='triado em')),
                ('investigation_started_at', models.DateTimeField(blank=True, null=True, verbose_name='investigação iniciada em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrado em')),
                ('closure_summary', models.TextField(blank=True, verbose_name='resumo de encerramento')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_pharmacovigilance_cases', to=settings.AUTH_USER_MODEL, verbose_name='encerrado por')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacovigilance_cases', to='masters.businesspartner', verbose_name='cliente')),
                ('investigation_started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_pharmacovigilance_investigations', to=settings.AUTH_USER_MODEL, verbose_name='investigação iniciada por')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacovigilance_cases', to='masters.product', verbose_name='produto')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_pharmacovigilance_cases', to=settings.AUTH_USER_MODEL, verbose_name='relatado por')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_pharmacovigilance_cases', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacovigilance_cases', to='inventory.stocklot', verbose_name='lote')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triaged_pharmacovigilance_cases', to=settings.AUTH_USER_MODEL, verbose_name='triado por')),
            ],
            options={
                'verbose_name': 'caso de farmacovigilância',
                'verbose_name_plural': 'casos de farmacovigilância',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacovigilanceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('action_number', models.CharField(blank=True, max_length=80, verbose_name='ação')),
                ('action_type', models.CharField(choices=[('capa', 'CAPA'), ('deviation', 'Desvio'), ('regulatory_notification', 'Notificação regulatória'), ('labeling_change', 'Alteração de bula/rotulagem'), ('recall', 'Recolhimento'), ('communication', 'Comunicação'), ('monitoring', 'Monitoramento'), ('other', 'Outra')], max_length=32, verbose_name='tipo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('due_date', models.DateField(verbose_name='prazo')),
                ('mandatory', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('evidence_required', models.BooleanField(default=True, verbose_name='exige evidência')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=24, verbose_name='status')),
                ('completion_notes', models.TextField(blank=True, verbose_name='notas de conclusão')),
                ('evidence_reference', models.CharField(blank=True, max_length=255, verbose_name='evidência')),
                ('content_hash', models.CharField(blank=True, max_length=128, verbose_name='hash do conteúdo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_pharmacovigilance_actions', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_pharmacovigilance_actions', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='pharmacovigilance.pharmacovigilancecase', verbose_name='caso')),
            ],
            options={
                'verbose_name': 'ação de farmacovigilância',
                'verbose_name_plural': 'ações de farmacovigilância',
                'ordering': ['case__case_number', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='PharmacovigilanceCausalityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('method', models.CharField(choices=[('who_umc', 'WHO-UMC'), ('naranjo', 'Naranjo'), ('expert_judgment', 'Julgamento especialista')], max_length=32, verbose_name='método')),
                ('result', models.CharField(choices=[('certain', 'Certa'), ('probable', 'Provável'), ('possible', 'Possível'), ('unlikely', 'Improvável'), ('unclassified', 'Não classificada')], max_length=24, verbose_name='resultado')),
                ('rationale', models.TextField(verbose_name='justificativa')),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='avaliado em')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessed_pharmacovigilance_causality', to=settings.AUTH_USER_MODEL, verbose_name='avaliado por')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causality_assessments', to='pharmacovigilance.pharmacovigilancecase', verbose_name='caso')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'avaliação de causalidade',
                'verbose_name_plural': 'avaliações de causalidade',
                'ordering': ['case__case_number', '-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacovigilanceClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('category', models.CharField(choices=[('adverse_reaction', 'Reação adversa'), ('quality_defect', 'Defeito de qualidade'), ('medication_error', 'Erro de medicação'), ('lack_of_efficacy', 'Falta de eficácia'), ('off_label_use', 'Uso off-label'), ('overdose', 'Sobredose'), ('other', 'Outra')], max_length=32, verbose_name='categoria')),
                ('seriousness', models.CharField(choices=[('non_serious', 'Não sério'), ('serious', 'Sério')], max_length=24, verbose_name='seriedade')),
                ('expectedness', models.CharField(choices=[('expected', 'Esperado'), ('unexpected', 'Inesperado'), ('unknown', 'Desconhecido')], max_length=24, verbose_name='previsibilidade')),
                ('listedness_reference', models.CharField(blank=True, max_length=180, verbose_name='referência de bula/listagem')),
                ('classified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='classificado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='pharmacovigilance.pharmacovigilancecase', verbose_name='caso')),
                ('classified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classified_pharmacovigilance_cases', to=settings.AUTH_USER_MODEL, verbose_name='classificado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'classificação de farmacovigilância',
                'verbose_name_plural': 'classificações de farmacovigilância',
                'ordering': ['case__case_number', '-classified_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacovigilanceInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('summary', models.TextField(verbose_name='resumo da investigação')),
                ('root_cause', models.TextField(verbose_name='causa raiz')),
                ('conclusion', models.TextField(verbose_name='conclusão')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='open', max_length=24, verbose_name='status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='pharmacovigilance.pharmacovigilancecase', verbose_name='caso')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_pharmacovigilance_investigations', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_pharmacovigilance_investigations', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'investigação de farmacovigilância',
                'verbose_name_plural': 'investigações de farmacovigilância',
                'ordering': ['case__case_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacovigilanceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('link_type', models.CharField(choices=[('complaint', 'Reclamação'), ('deviation', 'Desvio'), ('capa', 'CAPA'), ('recall', 'Recolhimento'), ('lot', 'Lote'), ('customer', 'Cliente'), ('product', 'Produto'), ('regulatory_dossier', 'Dossiê regulatório'), ('document', 'Documento')], max_length=32, verbose_name='tipo de vínculo')),
                ('reference_code', models.CharField(blank=True, max_length=120, verbose_name='referência')),
                ('description', models.TextField(verbose_name='descrição')),
                ('capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacovigilance_links', to='capa.caparecord', verbose_name='CAPA')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pharmacovigilance.pharmacovigilancecase', verbose_name='caso')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacovigilance_links', to='masters.businesspartner', verbose_name='cliente')),
                ('customer_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacovigilance_links', to='crm.customercomplaint', verbose_name='reclamação')),
                ('deviation_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacovigilance_links', to='deviations.qualityevent', verbose_name='desvio')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacovigilance_links', to='documents.controlleddocument', verbose_name='documento')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacovigilance_links', to='masters.product', verbose_name='produto')),
                ('regulatory_dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacovigilance_links', to='regulatory.regulatorydossier', verbose_name='dossiê regulatório')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacovigilance_links', to='inventory.stocklot', verbose_name='lote')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'vínculo de farmacovigilância',
                'verbose_name_plural': 'vínculos de farmacovigilância',
                'ordering': ['case__case_number', 'link_type'],
            },
        ),
        migrations.CreateModel(
            name='PharmacovigilanceSafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('report_type', models.CharField(choices=[('safety_case', 'Relatório individual de segurança'), ('trend', 'Tendência'), ('recurrence', 'Recorrência'), ('indicators', 'Indicadores'), ('regulatory_notification', 'Notificação regulatória')], max_length=32, verbose_name='tipo')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('generated', 'Gerado')], default='draft', max_length=24, verbose_name='status')),
                ('content_reference', models.CharField(blank=True, max_length=255, verbose_name='conteúdo gerado')),
                ('case_count', models.PositiveIntegerField(default=0, verbose_name='casos')),
                ('serious_cases', models.PositiveIntegerField(default=0, verbose_name='casos sérios')),
                ('recurrence_count', models.PositiveIntegerField(default=0, verbose_name='recorrências')),
                ('indicator_summary', models.TextField(blank=True, verbose_name='resumo de indicadores')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='gerado em')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pharmacovigilance.pharmacovigilancecase', verbose_name='caso')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_pharmacovigilance_reports', to=settings.AUTH_USER_MODEL, verbose_name='gerado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'relatório de segurança',
                'verbose_name_plural': 'relatórios de segurança',
                'ordering': ['case__case_number', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['tenant', 'case_type', 'status'], name='pharmacovig_tenant__74f247_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['tenant', 'product'], name='pharmacovig_tenant__59333f_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['tenant', 'stock_lot'], name='pharmacovig_tenant__887421_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['tenant', 'customer'], name='pharmacovig_tenant__846a14_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['tenant', 'seriousness', 'severity'], name='pharmacovig_tenant__c5f413_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['tenant', 'event_reported_at'], name='pharmacovig_tenant__28e174_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['tenant', 'responsible'], name='pharmacovig_tenant__c9045b_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['case_number'], name='pharmacovig_case_nu_82d21e_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacovigilancecase',
            constraint=models.UniqueConstraint(fields=('tenant', 'case_number'), name='unique_tenant_pharmacovigilance_case_number'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceaction',
            index=models.Index(fields=['tenant', 'case', 'status'], name='pharmacovig_tenant__dff9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceaction',
            index=models.Index(fields=['tenant', 'action_type', 'status'], name='pharmacovig_tenant__b0e01f_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceaction',
            index=models.Index(fields=['tenant', 'responsible', 'due_date'], name='pharmacovig_tenant__cf5703_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceaction',
            index=models.Index(fields=['action_number'], name='pharmacovig_action__c645aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacovigilanceaction',
            constraint=models.UniqueConstraint(fields=('tenant', 'action_number'), name='unique_tenant_pharmacovigilance_action_number'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecausalityassessment',
            index=models.Index(fields=['tenant', 'case'], name='pharmacovig_tenant__7905c4_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecausalityassessment',
            index=models.Index(fields=['tenant', 'method'], name='pharmacovig_tenant__c0cc60_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecausalityassessment',
            index=models.Index(fields=['tenant', 'result'], name='pharmacovig_tenant__be034e_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceclassification',
            index=models.Index(fields=['tenant', 'case'], name='pharmacovig_tenant__d634e6_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceclassification',
            index=models.Index(fields=['tenant', 'category'], name='pharmacovig_tenant__be43d2_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceclassification',
            index=models.Index(fields=['tenant', 'seriousness'], name='pharmacovig_tenant__aabf8a_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceclassification',
            index=models.Index(fields=['tenant', 'expectedness'], name='pharmacovig_tenant__77d312_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceinvestigation',
            index=models.Index(fields=['tenant', 'case', 'status'], name='pharmacovig_tenant__824c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceinvestigation',
            index=models.Index(fields=['tenant', 'responsible'], name='pharmacovig_tenant__e7a42b_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['tenant', 'case', 'link_type'], name='pharmacovig_tenant__c1c467_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['tenant', 'customer_complaint'], name='pharmacovig_tenant__7ce7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['tenant', 'deviation_event'], name='pharmacovig_tenant__454f67_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['tenant', 'capa'], name='pharmacovig_tenant__f7a5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['tenant', 'stock_lot'], name='pharmacovig_tenant__4f70b2_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['tenant', 'customer'], name='pharmacovig_tenant__85e537_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['tenant', 'product'], name='pharmacovig_tenant__b304cc_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['tenant', 'regulatory_dossier'], name='pharmacovig_tenant__8f77a5_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['tenant', 'document'], name='pharmacovig_tenant__9d57cc_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['reference_code'], name='pharmacovig_referen_68da07_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancesafetyreport',
            index=models.Index(fields=['tenant', 'case', 'status'], name='pharmacovig_tenant__2ba0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancesafetyreport',
            index=models.Index(fields=['tenant', 'report_type'], name='pharmacovig_tenant__d8c6b0_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancesafetyreport',
            index=models.Index(fields=['tenant', 'generated_at'], name='pharmacovig_tenant__b4fa1e_idx'),
        ),
    ]
