# Generated by Django 6.0.7 on 2026-07-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('pharmacovigilance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacovigilancecase',
            name='country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.country', verbose_name='país normalizado'),
        ),
        migrations.AddField(
            model_name='pharmacovigilancecase',
            name='severity_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='gravidade normalizada'),
        ),
    ]
