# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('capa', '0002_remove_capaapproval_unique_tenant_capa_approval_role_user_and_more'),
        ('crm', '0004_remove_campaign_unique_tenant_campaign_code_and_more'),
        ('deviations', '0003_remove_deviationapproval_unique_tenant_deviation_approval_role_user_and_more'),
        ('documents', '0003_remove_controlleddocument_unique_tenant_document_code_version_and_more'),
        ('inventory', '0002_remove_stockbalance_unique_tenant_stock_balance_address_status_and_more'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('pharmacovigilance', '0003_pharmacovigilancecase_city_and_more'),
        ('regulatory', '0004_remove_regulatorycommitment_unique_tenant_regulatory_commitment_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pharmacovigilanceaction',
            name='unique_tenant_pharmacovigilance_action_number',
        ),
        migrations.RemoveConstraint(
            model_name='pharmacovigilancecase',
            name='unique_tenant_pharmacovigilance_case_number',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilanceaction',
            name='pharmacovig_tenant__dff9a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilanceaction',
            name='pharmacovig_tenant__b0e01f_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilanceaction',
            name='pharmacovig_tenant__cf5703_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancecase',
            name='pharmacovig_tenant__74f247_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancecase',
            name='pharmacovig_tenant__59333f_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancecase',
            name='pharmacovig_tenant__887421_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancecase',
            name='pharmacovig_tenant__846a14_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancecase',
            name='pharmacovig_tenant__c5f413_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancecase',
            name='pharmacovig_tenant__28e174_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancecase',
            name='pharmacovig_tenant__c9045b_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancecausalityassessment',
            name='pharmacovig_tenant__7905c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancecausalityassessment',
            name='pharmacovig_tenant__c0cc60_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancecausalityassessment',
            name='pharmacovig_tenant__be034e_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilanceclassification',
            name='pharmacovig_tenant__d634e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilanceclassification',
            name='pharmacovig_tenant__be43d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilanceclassification',
            name='pharmacovig_tenant__aabf8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilanceclassification',
            name='pharmacovig_tenant__77d312_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilanceinvestigation',
            name='pharmacovig_tenant__824c9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilanceinvestigation',
            name='pharmacovig_tenant__e7a42b_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancelink',
            name='pharmacovig_tenant__c1c467_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancelink',
            name='pharmacovig_tenant__7ce7ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancelink',
            name='pharmacovig_tenant__454f67_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancelink',
            name='pharmacovig_tenant__f7a5f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancelink',
            name='pharmacovig_tenant__4f70b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancelink',
            name='pharmacovig_tenant__85e537_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancelink',
            name='pharmacovig_tenant__b304cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancelink',
            name='pharmacovig_tenant__8f77a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancelink',
            name='pharmacovig_tenant__9d57cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancesafetyreport',
            name='pharmacovig_tenant__2ba0d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancesafetyreport',
            name='pharmacovig_tenant__d8c6b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='pharmacovigilancesafetyreport',
            name='pharmacovig_tenant__b4fa1e_idx',
        ),
        migrations.RemoveField(
            model_name='pharmacovigilanceaction',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='pharmacovigilancecase',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='pharmacovigilancecausalityassessment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='pharmacovigilanceclassification',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='pharmacovigilanceinvestigation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='pharmacovigilancelink',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='pharmacovigilancesafetyreport',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceaction',
            index=models.Index(fields=['case', 'status'], name='pharmacovig_case_id_b4395c_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceaction',
            index=models.Index(fields=['action_type', 'status'], name='pharmacovig_action__e52f05_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceaction',
            index=models.Index(fields=['responsible', 'due_date'], name='pharmacovig_respons_274675_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['case_type', 'status'], name='pharmacovig_case_ty_86d334_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['product'], name='pharmacovig_product_959cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['stock_lot'], name='pharmacovig_stock_l_1a1a68_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['customer'], name='pharmacovig_custome_ce09c5_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['seriousness', 'severity'], name='pharmacovig_serious_db19b7_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['event_reported_at'], name='pharmacovig_event_r_69f07e_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecase',
            index=models.Index(fields=['responsible'], name='pharmacovig_respons_de0b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecausalityassessment',
            index=models.Index(fields=['case'], name='pharmacovig_case_id_b60146_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecausalityassessment',
            index=models.Index(fields=['method'], name='pharmacovig_method_1fd4c8_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancecausalityassessment',
            index=models.Index(fields=['result'], name='pharmacovig_result_328109_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceclassification',
            index=models.Index(fields=['case'], name='pharmacovig_case_id_44df2f_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceclassification',
            index=models.Index(fields=['category'], name='pharmacovig_categor_ed725c_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceclassification',
            index=models.Index(fields=['seriousness'], name='pharmacovig_serious_0e51e8_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceclassification',
            index=models.Index(fields=['expectedness'], name='pharmacovig_expecte_2993bc_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceinvestigation',
            index=models.Index(fields=['case', 'status'], name='pharmacovig_case_id_0fac7e_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilanceinvestigation',
            index=models.Index(fields=['responsible'], name='pharmacovig_respons_dc6c23_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['case', 'link_type'], name='pharmacovig_case_id_8fc0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['customer_complaint'], name='pharmacovig_custome_999a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['deviation_event'], name='pharmacovig_deviati_4c8634_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['capa'], name='pharmacovig_capa_id_1eb90f_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['stock_lot'], name='pharmacovig_stock_l_16b07a_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['customer'], name='pharmacovig_custome_f6f51b_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['product'], name='pharmacovig_product_d1ab46_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['regulatory_dossier'], name='pharmacovig_regulat_517e42_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancelink',
            index=models.Index(fields=['document'], name='pharmacovig_documen_b1b11b_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancesafetyreport',
            index=models.Index(fields=['case', 'status'], name='pharmacovig_case_id_109a28_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancesafetyreport',
            index=models.Index(fields=['report_type'], name='pharmacovig_report__069134_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacovigilancesafetyreport',
            index=models.Index(fields=['generated_at'], name='pharmacovig_generat_76dbb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacovigilanceaction',
            constraint=models.UniqueConstraint(fields=('action_number',), name='unique_pharmacovigilance_action_number'),
        ),
        migrations.AddConstraint(
            model_name='pharmacovigilancecase',
            constraint=models.UniqueConstraint(fields=('case_number',), name='unique_pharmacovigilance_case_number'),
        ),
    ]
