from django.db import models


class OperationalModule(models.TextChoices):
    AUXILIARY = 'auxiliary', 'Cadastros auxiliares'
    MASTERS = 'masters', 'Cadastros mestres'
    FORMULATIONS = 'formulations', 'Formulas e roteiros'
    PRODUCTION = 'production', 'Producao'
    PLANNING = 'planning', 'PCP, MPS e MRP'
    PROCUREMENT = 'procurement', 'Compras'
    INVENTORY = 'inventory', 'Estoque'
    COSTING = 'costing', 'Custos'
    FINANCE = 'finance', 'Financeiro'
    FISCAL = 'fiscal', 'Fiscal'
    CRM = 'crm', 'CRM'
    QUALITY = 'quality', 'Controle de qualidade'
    QA = 'qa', 'Garantia da qualidade'
    DOCUMENTS = 'documents', 'Documentos'
    DEVIATIONS = 'deviations', 'Desvios'
    CAPA = 'capa', 'CAPA'
    CHANGES = 'changes', 'Mudancas'
    AUDITS = 'audits', 'Auditorias'
    RISKS = 'risks', 'Riscos'
    RECALLS = 'recalls', 'Recall'
    MAINTENANCE = 'maintenance', 'Manutencao'
    TRAINING = 'training', 'Treinamentos'
    FILES = 'files', 'Arquivos'
    REPORTS = 'reports', 'Relatorios'
    WORKFLOW = 'workflow', 'Workflow'
    INTEGRATIONS = 'integrations', 'Integracoes'
    AI_AGENTS = 'ai_agents', 'Agentes de IA'
    GOVERNANCE = 'governance', 'Governanca'
    COMPLIANCE = 'compliance', 'Compliance transversal'
