ROTATE_ACTION_LABEL = 'Rotacionar segredo'


ACTION_LABELS = {
    'accept': 'Aceitar',
    'acknowledge': 'Reconhecer',
    'activate': 'Ativar',
    'advance': 'Avançar',
    'answer': 'Responder',
    'apply': 'Aplicar',
    'approve': 'Aprovar',
    'approve_for_implementation': 'Aprovar para implementação',
    'approve_repeat': 'Aprovar repetição',
    'approve_resampling': 'Aprovar nova amostragem',
    'approve_retest': 'Aprovar nova análise',
    'archive': 'Arquivar',
    'authorize': 'Autorizar',
    'block': 'Bloquear',
    'calculate': 'Calcular',
    'calculate_cost': 'Calcular custo',
    'calculate_margin': 'Calcular margem',
    'cancel': 'Cancelar',
    'check_status': 'Consultar situação',
    'close': 'Encerrar',
    'collect': 'Coletar',
    'complete': 'Concluir',
    'complete_execution': 'Concluir execução',
    'conclude': 'Concluir',
    'confirm_read': 'Confirmar leitura',
    'convocate': 'Convocar',
    'create_analysis': 'Criar análise',
    'create_financial_title': 'Criar título financeiro',
    'create_revision': 'Criar revisão',
    'delete_secure': 'Excluir com segurança',
    'enqueue': 'Enfileirar',
    'evaluate': 'Avaliar',
    'evaluate_module': 'Avaliar módulo',
    'execute': 'Executar',
    'expire': 'Expirar',
    'fail': 'Reprovar',
    'from_document': 'Gerar a partir do documento',
    'from_settlement': 'Gerar a partir da liquidação',
    'from_title': 'Gerar a partir do título',
    'generate': 'Gerar',
    'generate_alerts': 'Gerar alertas',
    'generate_link': 'Gerar link',
    'generate_notifications': 'Gerar notificações',
    'generate_order': 'Gerar ordem',
    'inspect': 'Inspecionar',
    'import_xml': 'Importar XML da NF-e',
    'issue': 'Emitir',
    'issue_materials': 'Baixar matérias-primas',
    'mark_lost': 'Marcar como perdida',
    'mark_overdue': 'Marcar como vencido',
    'mark_read': 'Marcar como lida',
    'mark_received': 'Marcar como recebido',
    'mark_sent': 'Marcar como enviado',
    'mark_won': 'Marcar como ganha',
    'obsolete': 'Tornar obsoleto',
    'pause': 'Pausar',
    'post_entry': 'Contabilizar',
    'post_stock': 'Lançar no estoque',
    'publish': 'Publicar',
    'recalculate': 'Recalcular',
    'receive': 'Receber',
    'receive_outputs': 'Receber produtos acabados',
    'reconcile': 'Conciliar',
    'record_regulatory_communication': 'Registrar comunicação regulatória',
    'record_response': 'Registrar resposta',
    'record_return': 'Registrar devolução',
    'record_view': 'Registrar visualização',
    'reject': 'Rejeitar',
    'release': 'Liberar',
    'release_quality': 'Liberar pela qualidade',
    'reopen': 'Reabrir',
    'replace': 'Substituir',
    'reserve_materials': 'Separar matérias-primas',
    'resume': 'Retomar',
    'reverse': 'Estornar',
    'review': 'Revisar',
    'revoke': 'Revogar',
    'rotate_secret': ROTATE_ACTION_LABEL,
    'run': 'Executar',
    'send': 'Enviar',
    'send_email': 'Enviar por e-mail',
    'start': 'Iniciar',
    'start_analysis': 'Iniciar análise',
    'start_implementation': 'Iniciar implementação',
    'start_investigation': 'Iniciar investigação',
    'start_monitoring': 'Iniciar monitoramento',
    'start_treatment': 'Iniciar tratamento',
    'start_triage': 'Iniciar triagem',
    'submit': 'Submeter',
    'submit_for_review': 'Submeter para revisão',
    'suspend': 'Suspender',
    'test_failure': 'Registrar falha no teste',
    'test_success': 'Registrar sucesso no teste',
    'trigger_now': 'Executar agora',
    'unblock': 'Desbloquear',
    'update_progress': 'Atualizar progresso',
    'use': 'Utilizar',
    'validate_period': 'Validar período',
    'verify': 'Verificar',
}
