# Generated by Django 6.0.8 on 2026-08-25 17:08

import base.sequences
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(blank=True, max_length=80, verbose_name='código')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('module', models.CharField(choices=[('production', 'Produção'), ('mrp', 'MRP'), ('inventory', 'Estoque'), ('traceability', 'Rastreabilidade'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('quality', 'Qualidade'), ('audit', 'Auditoria'), ('capa', 'CAPA'), ('deviations', 'Desvios'), ('risks', 'Riscos'), ('administrative', 'Administrativo')], max_length=32, verbose_name='módulo')),
                ('area', models.CharField(blank=True, max_length=120, verbose_name='área')),
                ('profile_role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('quality', 'Qualidade'), ('production', 'Produção'), ('regulatory', 'Regulatório'), ('finance', 'Financeiro'), ('viewer', 'Leitura')], max_length=32, verbose_name='perfil')),
                ('criticality', models.CharField(blank=True, choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=24, verbose_name='criticidade')),
                ('approval_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='alçada')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('area_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.businessarea', verbose_name='área normalizada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_approval_queues', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('criticality_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='criticidade normalizada')),
                ('module_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo normalizado')),
                ('role_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.organizationalrole', verbose_name='perfil normalizado')),
            ],
            options={
                'verbose_name': 'fila de aprovação',
                'verbose_name_plural': 'filas de aprovação',
                'ordering': ['module', 'area', 'code'],
            },
            bases=(base.sequences.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('task_number', models.CharField(blank=True, max_length=80, verbose_name='tarefa')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('source_module', models.CharField(choices=[('production', 'Produção'), ('mrp', 'MRP'), ('inventory', 'Estoque'), ('traceability', 'Rastreabilidade'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('quality', 'Qualidade'), ('audit', 'Auditoria'), ('capa', 'CAPA'), ('deviations', 'Desvios'), ('risks', 'Riscos'), ('administrative', 'Administrativo')], max_length=32, verbose_name='módulo de origem')),
                ('source_model', models.CharField(max_length=120, verbose_name='modelo de origem')),
                ('source_record_id', models.CharField(max_length=80, verbose_name='registro de origem')),
                ('area', models.CharField(blank=True, max_length=120, verbose_name='área')),
                ('criticality', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=24, verbose_name='criticidade')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='valor/alçada')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Reprovada'), ('cancelled', 'Cancelada')], default='pending', max_length=24, verbose_name='status')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='vence em')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidida em')),
                ('decision_comments', models.TextField(blank=True, verbose_name='comentários da decisão')),
                ('area_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.businessarea', verbose_name='área normalizada')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='atribuída a')),
                ('criticality_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='criticidade normalizada')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='decidida por')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workflow.approvalqueue', verbose_name='fila')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='solicitada por')),
                ('source_model_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model de origem normalizado')),
                ('source_module_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo de origem normalizado')),
            ],
            options={
                'verbose_name': 'tarefa de aprovação',
                'verbose_name_plural': 'tarefas de aprovação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AsyncJobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('job_number', models.CharField(blank=True, max_length=80, verbose_name='job')),
                ('task_name', models.CharField(max_length=160, verbose_name='tarefa')),
                ('task_id', models.CharField(blank=True, max_length=160, verbose_name='id da tarefa')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('loading_message', models.CharField(max_length=255, verbose_name='mensagem de carregamento')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='mensagem atual')),
                ('source_module', models.CharField(choices=[('production', 'Produção'), ('mrp', 'MRP'), ('inventory', 'Estoque'), ('traceability', 'Rastreabilidade'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('quality', 'Qualidade'), ('audit', 'Auditoria'), ('capa', 'CAPA'), ('deviations', 'Desvios'), ('risks', 'Riscos'), ('administrative', 'Administrativo')], max_length=32, verbose_name='módulo de origem')),
                ('source_model', models.CharField(blank=True, max_length=120, verbose_name='modelo de origem')),
                ('source_record_id', models.CharField(blank=True, max_length=80, verbose_name='registro de origem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('completed', 'Concluída'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], default='pending', max_length=24, verbose_name='status')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='progresso')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciada em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('result_reference', models.CharField(blank=True, max_length=255, verbose_name='resultado')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_async_jobs', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
                ('source_model_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model de origem normalizado')),
                ('source_module_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo de origem normalizado')),
            ],
            options={
                'verbose_name': 'job assíncrono',
                'verbose_name_plural': 'jobs assíncronos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('file_name', models.CharField(max_length=180, verbose_name='arquivo')),
                ('file_reference', models.CharField(max_length=255, verbose_name='referência')),
                ('content_hash', models.CharField(max_length=128, verbose_name='hash do conteúdo')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflow.approvaltask', verbose_name='tarefa')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_attachments', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'anexo de workflow',
                'verbose_name_plural': 'anexos de workflow',
                'ordering': ['task', 'file_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('comment', models.TextField(verbose_name='comentário')),
                ('is_internal', models.BooleanField(default=True, verbose_name='interno')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_comments', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workflow.approvaltask', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'comentário de workflow',
                'verbose_name_plural': 'comentários de workflow',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('module', models.CharField(blank=True, choices=[('production', 'Produção'), ('mrp', 'MRP'), ('inventory', 'Estoque'), ('traceability', 'Rastreabilidade'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('quality', 'Qualidade'), ('audit', 'Auditoria'), ('capa', 'CAPA'), ('deviations', 'Desvios'), ('risks', 'Riscos'), ('administrative', 'Administrativo')], max_length=32, verbose_name='módulo')),
                ('starts_at', models.DateTimeField(verbose_name='início')),
                ('ends_at', models.DateTimeField(verbose_name='fim')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_delegations_from', to=settings.AUTH_USER_MODEL, verbose_name='substituído')),
                ('module_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo normalizado')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_delegations_to', to=settings.AUTH_USER_MODEL, verbose_name='substituto')),
            ],
            options={
                'verbose_name': 'delegação de workflow',
                'verbose_name_plural': 'delegações de workflow',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('category', models.CharField(choices=[('pending', 'Pendência'), ('approval', 'Aprovação'), ('alert', 'Alerta'), ('due_date', 'Vencimento'), ('delay', 'Atraso'), ('rejection', 'Reprovação'), ('task_completed', 'Tarefa concluída')], max_length=32, verbose_name='categoria')),
                ('channel', models.CharField(choices=[('internal', 'Interna'), ('email', 'Email')], default='internal', max_length=24, verbose_name='canal')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('source_module', models.CharField(choices=[('production', 'Produção'), ('mrp', 'MRP'), ('inventory', 'Estoque'), ('traceability', 'Rastreabilidade'), ('costing', 'Custos'), ('finance', 'Financeiro'), ('fiscal', 'Fiscal'), ('quality', 'Qualidade'), ('audit', 'Auditoria'), ('capa', 'CAPA'), ('deviations', 'Desvios'), ('risks', 'Riscos'), ('administrative', 'Administrativo')], max_length=32, verbose_name='módulo de origem')),
                ('source_model', models.CharField(blank=True, max_length=120, verbose_name='modelo de origem')),
                ('source_record_id', models.CharField(blank=True, max_length=80, verbose_name='registro de origem')),
                ('criticality', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=24, verbose_name='criticidade')),
                ('status', models.CharField(choices=[('unread', 'Não lida'), ('sent', 'Enviada'), ('read', 'Lida'), ('archived', 'Arquivada'), ('failed', 'Falhou')], default='unread', max_length=24, verbose_name='status')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='vence em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lida em')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='arquivada em')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('criticality_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='criticidade normalizada')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
                ('source_model_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodel', verbose_name='model de origem normalizado')),
                ('source_module_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.systemmodule', verbose_name='módulo de origem normalizado')),
            ],
            options={
                'verbose_name': 'notificação de workflow',
                'verbose_name_plural': 'notificações de workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('action', models.CharField(choices=[('created', 'Criado'), ('sent', 'Enviado'), ('read', 'Lido'), ('archived', 'Arquivado'), ('commented', 'Comentado'), ('attached', 'Anexado'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('delegated', 'Delegado'), ('started', 'Iniciado'), ('updated', 'Atualizado'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], max_length=32, verbose_name='ação')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ocorrido em')),
                ('snapshot', models.CharField(max_length=255, verbose_name='snapshot')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='detalhes')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_history', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('async_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflow.asyncjobstatus', verbose_name='job assíncrono')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflow.approvaltask', verbose_name='tarefa')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflow.workflownotification', verbose_name='notificação')),
            ],
            options={
                'verbose_name': 'histórico de workflow',
                'verbose_name_plural': 'históricos de workflow',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalqueue',
            index=models.Index(fields=['module', 'area', 'profile_role', 'is_active'], name='workflow_ap_module_97ad34_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalqueue',
            index=models.Index(fields=['criticality'], name='workflow_ap_critica_829dac_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalqueue',
            index=models.Index(fields=['created_by'], name='workflow_ap_created_fc12e2_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalqueue',
            index=models.Index(fields=['code'], name='workflow_ap_code_566d85_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalqueue',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_approval_queue_code'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['queue', 'status'], name='workflow_ap_queue_i_dbfc79_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['assigned_to', 'status'], name='workflow_ap_assigne_c6f79e_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['requested_by'], name='workflow_ap_request_e15892_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['source_module', 'source_model', 'source_record_id'], name='workflow_ap_source__b2fbf6_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['criticality', 'due_at'], name='workflow_ap_critica_d2105d_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvaltask',
            constraint=models.UniqueConstraint(fields=('task_number',), name='unique_approval_task_number'),
        ),
        migrations.AddIndex(
            model_name='asyncjobstatus',
            index=models.Index(fields=['status', 'requested_by'], name='workflow_as_status_79d1bd_idx'),
        ),
        migrations.AddIndex(
            model_name='asyncjobstatus',
            index=models.Index(fields=['source_module', 'source_model', 'source_record_id'], name='workflow_as_source__717d01_idx'),
        ),
        migrations.AddIndex(
            model_name='asyncjobstatus',
            index=models.Index(fields=['task_name'], name='workflow_as_task_na_a3de88_idx'),
        ),
        migrations.AddIndex(
            model_name='asyncjobstatus',
            index=models.Index(fields=['task_id'], name='workflow_as_task_id_1f9105_idx'),
        ),
        migrations.AddConstraint(
            model_name='asyncjobstatus',
            constraint=models.UniqueConstraint(fields=('job_number',), name='unique_async_job_number'),
        ),
        migrations.AddIndex(
            model_name='workflowattachment',
            index=models.Index(fields=['task'], name='workflow_wo_task_id_48f5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowattachment',
            index=models.Index(fields=['uploaded_by'], name='workflow_wo_uploade_532192_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowattachment',
            index=models.Index(fields=['content_hash'], name='workflow_wo_content_44be4e_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcomment',
            index=models.Index(fields=['task'], name='workflow_wo_task_id_21cda1_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcomment',
            index=models.Index(fields=['author'], name='workflow_wo_author__5b4b18_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdelegation',
            index=models.Index(fields=['from_user', 'to_user', 'is_active'], name='workflow_wo_from_us_4dc17c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdelegation',
            index=models.Index(fields=['module', 'starts_at', 'ends_at'], name='workflow_wo_module_45af25_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['recipient', 'status'], name='workflow_wo_recipie_b52722_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['category', 'criticality'], name='workflow_wo_categor_c09ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['source_module', 'source_model', 'source_record_id'], name='workflow_wo_source__bf23e3_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['due_at'], name='workflow_wo_due_at_325b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['task', 'action'], name='workflow_wo_task_id_c0f008_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['notification', 'action'], name='workflow_wo_notific_d719da_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['async_job', 'action'], name='workflow_wo_async_j_9f1ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['actor'], name='workflow_wo_actor_i_be48f1_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['occurred_at'], name='workflow_wo_occurre_74b915_idx'),
        ),
    ]
