# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('workflow', '0002_approvalqueue_area_ref_approvalqueue_criticality_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvalqueue',
            name='unique_tenant_approval_queue_code',
        ),
        migrations.RemoveConstraint(
            model_name='approvaltask',
            name='unique_tenant_approval_task_number',
        ),
        migrations.RemoveConstraint(
            model_name='asyncjobstatus',
            name='unique_tenant_async_job_number',
        ),
        migrations.RemoveIndex(
            model_name='approvalqueue',
            name='workflow_ap_tenant__00127f_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvalqueue',
            name='workflow_ap_tenant__1a9147_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvalqueue',
            name='workflow_ap_tenant__9b479b_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvaltask',
            name='workflow_ap_tenant__8ea740_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvaltask',
            name='workflow_ap_tenant__1a31c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvaltask',
            name='workflow_ap_tenant__39a04d_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvaltask',
            name='workflow_ap_tenant__3aa6f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvaltask',
            name='workflow_ap_tenant__b524e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='asyncjobstatus',
            name='workflow_as_tenant__59ae83_idx',
        ),
        migrations.RemoveIndex(
            model_name='asyncjobstatus',
            name='workflow_as_tenant__56da23_idx',
        ),
        migrations.RemoveIndex(
            model_name='asyncjobstatus',
            name='workflow_as_tenant__78f389_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowattachment',
            name='workflow_wo_tenant__188ef4_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowattachment',
            name='workflow_wo_tenant__47962a_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowcomment',
            name='workflow_wo_tenant__25eca5_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowcomment',
            name='workflow_wo_tenant__25bcf8_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowdelegation',
            name='workflow_wo_tenant__34cf18_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowdelegation',
            name='workflow_wo_tenant__83fa0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowhistory',
            name='workflow_wo_tenant__ff4803_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowhistory',
            name='workflow_wo_tenant__bd3932_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowhistory',
            name='workflow_wo_tenant__1ee128_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowhistory',
            name='workflow_wo_tenant__46b815_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowhistory',
            name='workflow_wo_tenant__f3c5fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflownotification',
            name='workflow_wo_tenant__4f4667_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflownotification',
            name='workflow_wo_tenant__18aed7_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflownotification',
            name='workflow_wo_tenant__e19d83_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflownotification',
            name='workflow_wo_tenant__b806d3_idx',
        ),
        migrations.RemoveField(
            model_name='approvalqueue',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='approvaltask',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='asyncjobstatus',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='workflowattachment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='workflowcomment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='workflowdelegation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='workflowhistory',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='workflownotification',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='approvalqueue',
            index=models.Index(fields=['module', 'area', 'profile_role', 'is_active'], name='workflow_ap_module_97ad34_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalqueue',
            index=models.Index(fields=['criticality'], name='workflow_ap_critica_829dac_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalqueue',
            index=models.Index(fields=['created_by'], name='workflow_ap_created_fc12e2_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['queue', 'status'], name='workflow_ap_queue_i_dbfc79_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['assigned_to', 'status'], name='workflow_ap_assigne_c6f79e_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['requested_by'], name='workflow_ap_request_e15892_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['source_module', 'source_model', 'source_record_id'], name='workflow_ap_source__b2fbf6_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['criticality', 'due_at'], name='workflow_ap_critica_d2105d_idx'),
        ),
        migrations.AddIndex(
            model_name='asyncjobstatus',
            index=models.Index(fields=['status', 'requested_by'], name='workflow_as_status_79d1bd_idx'),
        ),
        migrations.AddIndex(
            model_name='asyncjobstatus',
            index=models.Index(fields=['source_module', 'source_model', 'source_record_id'], name='workflow_as_source__717d01_idx'),
        ),
        migrations.AddIndex(
            model_name='asyncjobstatus',
            index=models.Index(fields=['task_name'], name='workflow_as_task_na_a3de88_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowattachment',
            index=models.Index(fields=['task'], name='workflow_wo_task_id_48f5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowattachment',
            index=models.Index(fields=['uploaded_by'], name='workflow_wo_uploade_532192_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcomment',
            index=models.Index(fields=['task'], name='workflow_wo_task_id_21cda1_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcomment',
            index=models.Index(fields=['author'], name='workflow_wo_author__5b4b18_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdelegation',
            index=models.Index(fields=['from_user', 'to_user', 'is_active'], name='workflow_wo_from_us_4dc17c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdelegation',
            index=models.Index(fields=['module', 'starts_at', 'ends_at'], name='workflow_wo_module_45af25_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['task', 'action'], name='workflow_wo_task_id_c0f008_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['notification', 'action'], name='workflow_wo_notific_d719da_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['async_job', 'action'], name='workflow_wo_async_j_9f1ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['actor'], name='workflow_wo_actor_i_be48f1_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhistory',
            index=models.Index(fields=['occurred_at'], name='workflow_wo_occurre_74b915_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['recipient', 'status'], name='workflow_wo_recipie_b52722_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['category', 'criticality'], name='workflow_wo_categor_c09ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['source_module', 'source_model', 'source_record_id'], name='workflow_wo_source__bf23e3_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['due_at'], name='workflow_wo_due_at_325b1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalqueue',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_approval_queue_code'),
        ),
        migrations.AddConstraint(
            model_name='approvaltask',
            constraint=models.UniqueConstraint(fields=('task_number',), name='unique_approval_task_number'),
        ),
        migrations.AddConstraint(
            model_name='asyncjobstatus',
            constraint=models.UniqueConstraint(fields=('job_number',), name='unique_async_job_number'),
        ),
    ]
