# Generated by Django 6.0.7 on 2026-07-07 16:01

import django.db.models.deletion
import formulations.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('version', models.PositiveIntegerField(verbose_name='versão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('approved', 'Aprovada'), ('obsolete', 'Obsoleta')], default='draft', max_length=24, verbose_name='status')),
                ('batch_size', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='tamanho do lote')),
                ('expected_yield_percent', models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=7, verbose_name='rendimento esperado %')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='vigente a partir de')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='vigente até')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_formulas', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('batch_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formula_batches', to='masters.unitofmeasure', verbose_name='unidade do lote')),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='formulations.masterformula', verbose_name='copiada de')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='masters.product', verbose_name='produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'fórmula mestra',
                'verbose_name_plural': 'fórmulas mestras',
                'ordering': ['product__code', '-version'],
            },
            bases=(formulations.models.ReleasedVersionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ManufacturingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=80, verbose_name='código')),
                ('version', models.PositiveIntegerField(verbose_name='versão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('approved', 'Aprovado'), ('obsolete', 'Obsoleto')], default='draft', max_length=24, verbose_name='status')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='vigente a partir de')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='vigente até')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='masters.product', verbose_name='produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='formulations.masterformula', verbose_name='fórmula')),
            ],
            options={
                'verbose_name': 'roteiro de fabricação',
                'verbose_name_plural': 'roteiros de fabricação',
                'ordering': ['product__code', '-version'],
            },
            bases=(formulations.models.ReleasedVersionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FormulaComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('line_number', models.PositiveIntegerField(verbose_name='linha')),
                ('role', models.CharField(choices=[('active', 'Ativo'), ('excipient', 'Excipiente'), ('packaging', 'Embalagem'), ('process_aid', 'Auxiliar de processo')], default='excipient', max_length=24, verbose_name='função')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade')),
                ('expected_loss_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='perda prevista %')),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=14, verbose_name='fator de conversão')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formula_components', to='masters.product', verbose_name='material')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formula_components', to='masters.unitofmeasure', verbose_name='unidade')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='formulations.masterformula', verbose_name='fórmula')),
            ],
            options={
                'verbose_name': 'componente da fórmula',
                'verbose_name_plural': 'componentes da fórmula',
                'ordering': ['formula', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='RouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequência')),
                ('operation', models.CharField(max_length=160, verbose_name='operação')),
                ('work_center', models.CharField(max_length=160, verbose_name='centro de trabalho')),
                ('resource', models.CharField(blank=True, max_length=160, verbose_name='recurso')),
                ('equipment_code', models.CharField(blank=True, max_length=80, verbose_name='equipamento')),
                ('setup_time_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='tempo de setup em minutos')),
                ('standard_time_minutes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='tempo padrão em minutos')),
                ('critical_parameters', models.TextField(blank=True, verbose_name='parâmetros críticos')),
                ('instructions', models.TextField(blank=True, verbose_name='instruções')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='formulations.manufacturingroute', verbose_name='roteiro')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'etapa do roteiro',
                'verbose_name_plural': 'etapas do roteiro',
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='masterformula',
            index=models.Index(fields=['tenant', 'status'], name='formulation_tenant__e4ea16_idx'),
        ),
        migrations.AddIndex(
            model_name='masterformula',
            index=models.Index(fields=['tenant', 'product', 'status'], name='formulation_tenant__fd1420_idx'),
        ),
        migrations.AddIndex(
            model_name='masterformula',
            index=models.Index(fields=['code', 'version'], name='formulation_code_399625_idx'),
        ),
        migrations.AddConstraint(
            model_name='masterformula',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'version'), name='unique_tenant_formula_product_version'),
        ),
        migrations.AddConstraint(
            model_name='masterformula',
            constraint=models.UniqueConstraint(fields=('tenant', 'code', 'version'), name='unique_tenant_formula_code_version'),
        ),
        migrations.AddIndex(
            model_name='manufacturingroute',
            index=models.Index(fields=['tenant', 'status'], name='formulation_tenant__c65d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingroute',
            index=models.Index(fields=['tenant', 'product', 'status'], name='formulation_tenant__57804b_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingroute',
            index=models.Index(fields=['code', 'version'], name='formulation_code_a5006f_idx'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingroute',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'version'), name='unique_tenant_route_product_version'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingroute',
            constraint=models.UniqueConstraint(fields=('tenant', 'code', 'version'), name='unique_tenant_route_code_version'),
        ),
        migrations.AddIndex(
            model_name='formulacomponent',
            index=models.Index(fields=['tenant', 'material'], name='formulation_tenant__425ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='formulacomponent',
            index=models.Index(fields=['formula', 'line_number'], name='formulation_formula_93f677_idx'),
        ),
        migrations.AddConstraint(
            model_name='formulacomponent',
            constraint=models.UniqueConstraint(fields=('formula', 'line_number'), name='unique_formula_component_line'),
        ),
        migrations.AddIndex(
            model_name='routestep',
            index=models.Index(fields=['tenant', 'route'], name='formulation_tenant__932f68_idx'),
        ),
        migrations.AddIndex(
            model_name='routestep',
            index=models.Index(fields=['route', 'sequence'], name='formulation_route_i_f1664f_idx'),
        ),
        migrations.AddConstraint(
            model_name='routestep',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='unique_route_step_sequence'),
        ),
    ]
