# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0001_initial'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='manufacturingroute',
            name='unique_tenant_route_product_version',
        ),
        migrations.RemoveConstraint(
            model_name='manufacturingroute',
            name='unique_tenant_route_code_version',
        ),
        migrations.RemoveConstraint(
            model_name='masterformula',
            name='unique_tenant_formula_product_version',
        ),
        migrations.RemoveConstraint(
            model_name='masterformula',
            name='unique_tenant_formula_code_version',
        ),
        migrations.RemoveIndex(
            model_name='formulacomponent',
            name='formulation_tenant__425ad5_idx',
        ),
        migrations.RemoveIndex(
            model_name='manufacturingroute',
            name='formulation_tenant__c65d6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='manufacturingroute',
            name='formulation_tenant__57804b_idx',
        ),
        migrations.RemoveIndex(
            model_name='masterformula',
            name='formulation_tenant__e4ea16_idx',
        ),
        migrations.RemoveIndex(
            model_name='masterformula',
            name='formulation_tenant__fd1420_idx',
        ),
        migrations.RemoveIndex(
            model_name='routestep',
            name='formulation_tenant__932f68_idx',
        ),
        migrations.RemoveField(
            model_name='formulacomponent',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='manufacturingroute',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='masterformula',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='routestep',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='formulacomponent',
            index=models.Index(fields=['material'], name='formulation_materia_2be1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingroute',
            index=models.Index(fields=['status'], name='formulation_status_32372b_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingroute',
            index=models.Index(fields=['product', 'status'], name='formulation_product_a8b45c_idx'),
        ),
        migrations.AddIndex(
            model_name='masterformula',
            index=models.Index(fields=['status'], name='formulation_status_f3d62f_idx'),
        ),
        migrations.AddIndex(
            model_name='masterformula',
            index=models.Index(fields=['product', 'status'], name='formulation_product_91be57_idx'),
        ),
        migrations.AddIndex(
            model_name='routestep',
            index=models.Index(fields=['route'], name='formulation_route_i_be1072_idx'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingroute',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='unique_route_product_version'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingroute',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_route_code_version'),
        ),
        migrations.AddConstraint(
            model_name='masterformula',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='unique_formula_product_version'),
        ),
        migrations.AddConstraint(
            model_name='masterformula',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_formula_code_version'),
        ),
    ]
