# Generated by Django 5.2.16 on 2026-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulations', '0002_remove_manufacturingroute_unique_tenant_route_product_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingroute',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='masterformula',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='código'),
        ),
    ]
