# Generated by Django 6.0.8 on 2026-08-25 17:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('masters', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('order_number', models.CharField(blank=True, max_length=80, verbose_name='pedido')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('sent', 'Enviado'), ('partially_received', 'Parcialmente recebido'), ('received', 'Recebido'), ('cancelled', 'Cancelado'), ('closed', 'Encerrado')], default='draft', max_length=24, verbose_name='status')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='emissão')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='entrega prevista')),
                ('payment_terms', models.CharField(blank=True, max_length=160, verbose_name='condição de pagamento')),
                ('delivery_terms', models.CharField(blank=True, max_length=160, verbose_name='condição de entrega')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='moeda')),
                ('freight_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='frete')),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='valor total')),
                ('delivery_zipcode', models.CharField(blank=True, max_length=20, verbose_name='CEP de entrega')),
                ('delivery_street', models.CharField(blank=True, max_length=200, verbose_name='logradouro de entrega')),
                ('delivery_street_number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('delivery_complement', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('delivery_neighborhood', models.CharField(blank=True, max_length=120, verbose_name='bairro de entrega')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por')),
                ('currency_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.currency', verbose_name='moeda normalizada')),
                ('delivery_city_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='Cidade')),
                ('delivery_country_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliary.country', verbose_name='país')),
                ('delivery_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='masters.site', verbose_name='unidade de entrega')),
                ('delivery_state_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF')),
                ('delivery_term_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.commercialterm', verbose_name='condição de entrega normalizada')),
                ('payment_term_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.commercialterm', verbose_name='condição de pagamento normalizada')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='masters.businesspartner', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'pedido de compra',
                'verbose_name_plural': 'pedidos de compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='preço unitário')),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='impostos')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='entrega prevista')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder', verbose_name='pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='masters.product', verbose_name='item')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'item do pedido de compra',
                'verbose_name_plural': 'itens do pedido de compra',
                'ordering': ['order__order_number', 'product__code'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('receipt_number', models.CharField(blank=True, max_length=80, verbose_name='recebimento')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('received', 'Recebido'), ('quality_released', 'Qualidade liberada'), ('stock_posted', 'Estoque lançado'), ('cancelled', 'Cancelado')], default='draft', max_length=24, verbose_name='status')),
                ('fiscal_document_number', models.CharField(blank=True, max_length=80, verbose_name='documento fiscal')),
                ('fiscal_received_at', models.DateTimeField(blank=True, null=True, verbose_name='recebimento fiscal em')),
                ('physical_received_at', models.DateTimeField(blank=True, null=True, verbose_name='recebimento físico em')),
                ('quality_status', models.CharField(choices=[('pending', 'Pendente'), ('quarantine', 'Quarentena'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=24, verbose_name='status de qualidade')),
                ('stock_entry_status', models.CharField(choices=[('pending', 'Pendente'), ('posted', 'Lançado')], default='pending', max_length=24, verbose_name='entrada em estoque')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='procurement.purchaseorder', verbose_name='pedido')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to=settings.AUTH_USER_MODEL, verbose_name='recebido por')),
            ],
            options={
                'verbose_name': 'recebimento de compra',
                'verbose_name_plural': 'recebimentos de compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('received_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade recebida')),
                ('accepted_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade aceita')),
                ('rejected_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='quantidade rejeitada')),
                ('lot_number', models.CharField(blank=True, max_length=80, verbose_name='lote')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='procurement.purchaseorderitem', verbose_name='item do pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt_items', to='masters.product', verbose_name='item')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchasereceipt', verbose_name='recebimento')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt_items', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'item do recebimento',
                'verbose_name_plural': 'itens do recebimento',
                'ordering': ['receipt__receipt_number', 'product__code'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('requisition_number', models.CharField(blank=True, max_length=80, verbose_name='requisição')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('mrp', 'MRP'), ('stock_minimum', 'Estoque mínimo'), ('maintenance', 'Manutenção'), ('laboratory', 'Laboratório'), ('administrative', 'Administrativa')], default='manual', max_length=24, verbose_name='origem')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Submetida'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada'), ('converted', 'Convertida')], default='draft', max_length=20, verbose_name='status')),
                ('justification', models.TextField(verbose_name='justificativa')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submetida em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='rejeitada em')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motivo da rejeição')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchase_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_purchase_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='rejeitada por')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'requisição de compra',
                'verbose_name_plural': 'requisições de compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.purchaserequisition', verbose_name='requisição'),
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade')),
                ('needed_by', models.DateField(blank=True, null=True, verbose_name='necessário em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('mrp_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisition_items', to='planning.mrpsuggestion', verbose_name='sugestão MRP')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisition_items', to='masters.product', verbose_name='item')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaserequisition', verbose_name='requisição')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisition_items', to='masters.unitofmeasure', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'item da requisição',
                'verbose_name_plural': 'itens da requisição',
                'ordering': ['requisition__requisition_number', 'product__code'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='requisition_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='procurement.purchaserequisitionitem', verbose_name='item da requisição'),
        ),
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('rfq_number', models.CharField(blank=True, max_length=80, verbose_name='cotação')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('quoted', 'Cotada'), ('approved', 'Aprovada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='prazo de resposta')),
                ('terms', models.TextField(blank=True, verbose_name='condições gerais')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_quotation_requests', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_requests', to='procurement.purchaserequisition', verbose_name='requisição')),
            ],
            options={
                'verbose_name': 'cotação',
                'verbose_name_plural': 'cotações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierQualificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('event_type', models.CharField(choices=[('document', 'Documento'), ('audit', 'Auditoria'), ('occurrence', 'Ocorrência'), ('restriction', 'Restrição')], max_length=24, verbose_name='tipo')),
                ('event_date', models.DateField(verbose_name='data do evento')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válido até')),
                ('severity', models.CharField(blank=True, max_length=40, verbose_name='criticidade')),
                ('blocks_purchases', models.BooleanField(default=False, verbose_name='bloqueia compras')),
                ('description', models.TextField(verbose_name='descrição')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolvido em')),
                ('event_zipcode', models.CharField(blank=True, max_length=20, verbose_name='CEP do local')),
                ('event_street', models.CharField(blank=True, max_length=200, verbose_name='logradouro do local')),
                ('event_street_number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('event_complement', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('event_neighborhood', models.CharField(blank=True, max_length=120, verbose_name='bairro do local')),
                ('event_city_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='Cidade')),
                ('event_country_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliary.country', verbose_name='país')),
                ('event_state_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF')),
                ('severity_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='criticidade normalizada')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_qualification_events', to='masters.site', verbose_name='unidade/local')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualification_events', to='masters.businesspartner', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'evento de qualificação de fornecedor',
                'verbose_name_plural': 'eventos de qualificação de fornecedores',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Recebida'), ('selected', 'Selecionada'), ('rejected', 'Rejeitada')], default='submitted', max_length=20, verbose_name='status')),
                ('quoted_quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='quantidade cotada')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='preço unitário')),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='impostos')),
                ('freight_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='frete')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='moeda')),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='prazo em dias')),
                ('payment_terms', models.CharField(blank=True, max_length=160, verbose_name='condição de pagamento')),
                ('delivery_terms', models.CharField(blank=True, max_length=160, verbose_name='condição de entrega')),
                ('supplier_performance_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='desempenho do fornecedor')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='validade da proposta')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('currency_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.currency', verbose_name='moeda normalizada')),
                ('delivery_term_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.commercialterm', verbose_name='condição de entrega normalizada')),
                ('payment_term_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.commercialterm', verbose_name='condição de pagamento normalizada')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='procurement.quotationrequest', verbose_name='cotação')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quotations', to='masters.businesspartner', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'proposta de fornecedor',
                'verbose_name_plural': 'propostas de fornecedores',
                'ordering': ['rfq__rfq_number', 'unit_price', 'lead_time_days'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.supplierquotation', verbose_name='proposta origem'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['status'], name='procurement_status_3e57d3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['order'], name='procurement_order_i_2199bd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['quality_status'], name='procurement_quality_55b0c4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['receipt_number'], name='procurement_receipt_eb12b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceipt',
            constraint=models.UniqueConstraint(fields=('receipt_number',), name='unique_purchase_receipt_number'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptitem',
            index=models.Index(fields=['receipt'], name='procurement_receipt_981260_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptitem',
            index=models.Index(fields=['product'], name='procurement_product_be285c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptitem',
            index=models.Index(fields=['lot_number'], name='procurement_lot_num_bd485f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptitem',
            index=models.Index(fields=['expiry_date'], name='procurement_expiry__3dcc04_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['status'], name='procurement_status_dcf830_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['source'], name='procurement_source_1457d1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['requisition_number'], name='procurement_requisi_8de046_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequisition',
            constraint=models.UniqueConstraint(fields=('requisition_number',), name='unique_purchase_requisition_number'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisitionitem',
            index=models.Index(fields=['requisition'], name='procurement_requisi_66fae9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisitionitem',
            index=models.Index(fields=['product'], name='procurement_product_491046_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisitionitem',
            index=models.Index(fields=['needed_by'], name='procurement_needed__707046_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['order'], name='procurement_order_i_bce418_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['product'], name='procurement_product_4f7e33_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['expected_delivery_date'], name='procurement_expecte_a49792_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationrequest',
            index=models.Index(fields=['status'], name='procurement_status_bd29e8_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationrequest',
            index=models.Index(fields=['requisition'], name='procurement_requisi_3db3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationrequest',
            index=models.Index(fields=['rfq_number'], name='procurement_rfq_num_097e6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotationrequest',
            constraint=models.UniqueConstraint(fields=('rfq_number',), name='unique_rfq_number'),
        ),
        migrations.AddIndex(
            model_name='supplierqualificationevent',
            index=models.Index(fields=['supplier', 'event_type'], name='procurement_supplie_a1f3da_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierqualificationevent',
            index=models.Index(fields=['blocks_purchases'], name='procurement_blocks__da7e46_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierqualificationevent',
            index=models.Index(fields=['valid_until'], name='procurement_valid_u_a3ecc5_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierquotation',
            index=models.Index(fields=['rfq'], name='procurement_rfq_id_130dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierquotation',
            index=models.Index(fields=['supplier'], name='procurement_supplie_c8bb07_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierquotation',
            index=models.Index(fields=['status'], name='procurement_status_2d1593_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierquotation',
            index=models.Index(fields=['valid_until'], name='procurement_valid_u_d2f44c_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotation',
            constraint=models.UniqueConstraint(fields=('rfq', 'supplier'), name='unique_rfq_supplier_quote'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='procurement_status_6b6895_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='procurement_supplie_b6d45e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_number'], name='procurement_order_n_002ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['expected_delivery_date'], name='procurement_expecte_497a17_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('order_number',), name='unique_purchase_order_number'),
        ),
    ]
