# Generated by Django 6.0.7 on 2026-07-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0001_initial'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='currency_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.currency', verbose_name='moeda normalizada'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_term_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.commercialterm', verbose_name='condição de entrega normalizada'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_term_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.commercialterm', verbose_name='condição de pagamento normalizada'),
        ),
        migrations.AddField(
            model_name='supplierqualificationevent',
            name='severity_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.impactlevel', verbose_name='criticidade normalizada'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='currency_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.currency', verbose_name='moeda normalizada'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='delivery_term_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.commercialterm', verbose_name='condição de entrega normalizada'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='payment_term_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.commercialterm', verbose_name='condição de pagamento normalizada'),
        ),
    ]
