# Generated by Django 6.0.8 on 2026-09-01 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_initial'),
        ('masters', '0002_cosmetics_product_taxonomy'),
        ('procurement', '0002_remove_maintenance_requisition_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='nfe_access_key',
            field=models.CharField(blank=True, max_length=44, verbose_name='chave de acesso NF-e'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='nfe_xml_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt_nfe', to='files.protectedfile', verbose_name='XML NF-e protegido'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='nfe_xml_sha256',
            field=models.CharField(blank=True, max_length=64, verbose_name='hash do XML NF-e'),
        ),
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True, verbose_name='fabricação'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptitem',
            index=models.Index(fields=['manufacturing_date'], name='procurement_manufac_8065b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('nfe_access_key', ''), _negated=True), fields=('nfe_access_key',), name='unique_purchase_receipt_nfe_access_key'),
        ),
    ]
