# Generated by Django 6.0.7 on 2026-07-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0002_populate_auxiliary_references'),
        ('masters', '0003_add_zipcode_and_address'),
        ('procurement', '0002_purchaseorder_currency_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='cidade de entrega'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='cidade de entrega normalizada'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_neighborhood',
            field=models.CharField(blank=True, max_length=120, verbose_name='bairro de entrega'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='masters.site', verbose_name='unidade de entrega'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=80, verbose_name='UF de entrega'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF de entrega normalizada'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='logradouro de entrega'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_zipcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP de entrega'),
        ),
        migrations.AddField(
            model_name='supplierqualificationevent',
            name='event_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='cidade do local'),
        ),
        migrations.AddField(
            model_name='supplierqualificationevent',
            name='event_city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='cidade do local normalizada'),
        ),
        migrations.AddField(
            model_name='supplierqualificationevent',
            name='event_neighborhood',
            field=models.CharField(blank=True, max_length=120, verbose_name='bairro do local'),
        ),
        migrations.AddField(
            model_name='supplierqualificationevent',
            name='event_state',
            field=models.CharField(blank=True, max_length=80, verbose_name='UF do local'),
        ),
        migrations.AddField(
            model_name='supplierqualificationevent',
            name='event_state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF do local normalizada'),
        ),
        migrations.AddField(
            model_name='supplierqualificationevent',
            name='event_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='logradouro do local'),
        ),
        migrations.AddField(
            model_name='supplierqualificationevent',
            name='event_zipcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP do local'),
        ),
        migrations.AddField(
            model_name='supplierqualificationevent',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_qualification_events', to='masters.site', verbose_name='unidade/local'),
        ),
    ]
