# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('planning', '0002_remove_capacityresource_unique_tenant_capacity_resource_code_and_more'),
        ('procurement', '0003_purchaseorder_delivery_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseorder',
            name='unique_tenant_purchase_order_number',
        ),
        migrations.RemoveConstraint(
            model_name='purchasereceipt',
            name='unique_tenant_purchase_receipt_number',
        ),
        migrations.RemoveConstraint(
            model_name='purchaserequisition',
            name='unique_tenant_purchase_requisition_number',
        ),
        migrations.RemoveConstraint(
            model_name='quotationrequest',
            name='unique_tenant_rfq_number',
        ),
        migrations.RemoveConstraint(
            model_name='supplierquotation',
            name='unique_tenant_rfq_supplier_quote',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='procurement_tenant__db6b6c_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='procurement_tenant__0537c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorderitem',
            name='procurement_tenant__aaa40e_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorderitem',
            name='procurement_tenant__640489_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasereceipt',
            name='procurement_tenant__897065_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasereceipt',
            name='procurement_tenant__b33fed_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasereceipt',
            name='procurement_tenant__6da513_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasereceiptitem',
            name='procurement_tenant__1611dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasereceiptitem',
            name='procurement_tenant__27cc6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequisition',
            name='procurement_tenant__992bba_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequisition',
            name='procurement_tenant__6a2275_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequisitionitem',
            name='procurement_tenant__42f3f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequisitionitem',
            name='procurement_tenant__9ffc04_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationrequest',
            name='procurement_tenant__f93051_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationrequest',
            name='procurement_tenant__bc2c0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierqualificationevent',
            name='procurement_tenant__0096d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierqualificationevent',
            name='procurement_tenant__8ac73c_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierquotation',
            name='procurement_tenant__4748e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierquotation',
            name='procurement_tenant__fbfe36_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierquotation',
            name='procurement_tenant__0a0a92_idx',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='purchasereceipt',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='purchasereceiptitem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='purchaserequisitionitem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='supplierqualificationevent',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='procurement_status_6b6895_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='procurement_supplie_b6d45e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['order'], name='procurement_order_i_bce418_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['product'], name='procurement_product_4f7e33_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['status'], name='procurement_status_3e57d3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['order'], name='procurement_order_i_2199bd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['quality_status'], name='procurement_quality_55b0c4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptitem',
            index=models.Index(fields=['receipt'], name='procurement_receipt_981260_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptitem',
            index=models.Index(fields=['product'], name='procurement_product_be285c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['status'], name='procurement_status_dcf830_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['source'], name='procurement_source_1457d1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisitionitem',
            index=models.Index(fields=['requisition'], name='procurement_requisi_66fae9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisitionitem',
            index=models.Index(fields=['product'], name='procurement_product_491046_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationrequest',
            index=models.Index(fields=['status'], name='procurement_status_bd29e8_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationrequest',
            index=models.Index(fields=['requisition'], name='procurement_requisi_3db3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierqualificationevent',
            index=models.Index(fields=['supplier', 'event_type'], name='procurement_supplie_a1f3da_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierqualificationevent',
            index=models.Index(fields=['blocks_purchases'], name='procurement_blocks__da7e46_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierquotation',
            index=models.Index(fields=['rfq'], name='procurement_rfq_id_130dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierquotation',
            index=models.Index(fields=['supplier'], name='procurement_supplie_c8bb07_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierquotation',
            index=models.Index(fields=['status'], name='procurement_status_2d1593_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('order_number',), name='unique_purchase_order_number'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceipt',
            constraint=models.UniqueConstraint(fields=('receipt_number',), name='unique_purchase_receipt_number'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequisition',
            constraint=models.UniqueConstraint(fields=('requisition_number',), name='unique_purchase_requisition_number'),
        ),
        migrations.AddConstraint(
            model_name='quotationrequest',
            constraint=models.UniqueConstraint(fields=('rfq_number',), name='unique_rfq_number'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotation',
            constraint=models.UniqueConstraint(fields=('rfq', 'supplier'), name='unique_rfq_supplier_quote'),
        ),
    ]
