# Generated by Django 5.2.16 on 2026-07-22 17:53

import django.db.models.deletion
from django.db import migrations, models


def validate_legacy_location(apps, schema_editor):
    checks = (
        ('PurchaseOrder', 'delivery_city', 'delivery_city_ref'),
        ('PurchaseOrder', 'delivery_state', 'delivery_state_ref'),
        ('SupplierQualificationEvent', 'event_city', 'event_city_ref'),
        ('SupplierQualificationEvent', 'event_state', 'event_state_ref'),
    )
    invalid_locations = []

    for model_name, legacy_field, normalized_field in checks:
        model = apps.get_model('procurement', model_name)
        has_unmigrated_location = (
            model.objects.filter(
                **{
                    f'{legacy_field}__isnull': False,
                    f'{normalized_field}__isnull': True,
                }
            )
            .exclude(**{legacy_field: ''})
            .exists()
        )
        if has_unmigrated_location:
            invalid_locations.append(f'{model_name}.{legacy_field}')

    if invalid_locations:
        raise RuntimeError(
            'Preencha as referências normalizadas antes de remover os campos legados: '
            + ', '.join(invalid_locations)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('procurement', '0004_remove_purchaseorder_unique_tenant_purchase_order_number_and_more'),
    ]

    operations = [
        migrations.RunPython(validate_legacy_location, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivery_state',
        ),
        migrations.RemoveField(
            model_name='supplierqualificationevent',
            name='event_city',
        ),
        migrations.RemoveField(
            model_name='supplierqualificationevent',
            name='event_state',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_street_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='supplierqualificationevent',
            name='event_complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='supplierqualificationevent',
            name='event_street_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='supplierqualificationevent',
            name='event_city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='supplierqualificationevent',
            name='event_state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF'),
        ),
    ]
