# Generated by Django 5.2.16 on 2026-08-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_purchaseorder_delivery_country_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='cost_center',
        ),
    ]
