# Generated by Django 6.0.7 on 2026-07-08 08:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='competência')),
                ('competency_type', models.CharField(choices=[('technical', 'Técnica'), ('gmp', 'BPF/GMP'), ('safety', 'Segurança'), ('regulatory', 'Regulatória'), ('system', 'Sistema'), ('behavioral', 'Comportamental')], max_length=24, verbose_name='tipo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'competência',
                'verbose_name_plural': 'competências',
                'ordering': ['competency_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=40, verbose_name='código')),
                ('title', models.CharField(max_length=160, verbose_name='cargo')),
                ('area', models.CharField(max_length=120, verbose_name='área')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='departamento')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
                'ordering': ['area', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=40, verbose_name='código')),
                ('title', models.CharField(max_length=180, verbose_name='treinamento')),
                ('training_type', models.CharField(choices=[('document', 'Documento'), ('critical_activity', 'Atividade crítica'), ('equipment', 'Equipamento'), ('module', 'Módulo do sistema'), ('regulatory', 'Requisito regulatório'), ('recycle', 'Reciclagem')], max_length=32, verbose_name='tipo')),
                ('area', models.CharField(max_length=120, verbose_name='área')),
                ('process', models.CharField(blank=True, max_length=120, verbose_name='processo')),
                ('module_code', models.CharField(blank=True, max_length=80, verbose_name='módulo')),
                ('regulatory_requirement_reference', models.CharField(blank=True, max_length=160, verbose_name='requisito regulatório')),
                ('validity_days', models.PositiveIntegerField(default=365, verbose_name='validade em dias')),
                ('alert_before_days', models.PositiveIntegerField(default=30, verbose_name='alertar antes de dias')),
                ('passing_score', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5, verbose_name='nota mínima')),
                ('requires_evaluation', models.BooleanField(default=True, verbose_name='exige avaliação')),
                ('requires_certificate', models.BooleanField(default=True, verbose_name='exige certificado')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='obrigatório')),
                ('block_without_valid_training', models.BooleanField(default=False, verbose_name='bloquear sem treinamento válido')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_requirements', to='training.competency', verbose_name='competência')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_requirements', to='documents.controlleddocument', verbose_name='documento')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_requirements', to='maintenance.equipmentasset', verbose_name='equipamento')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_requirements', to='training.jobposition', verbose_name='cargo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'requisito de treinamento',
                'verbose_name_plural': 'requisitos de treinamento',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CriticalActivityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('activity_code', models.CharField(max_length=80, verbose_name='atividade')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('enforcement_mode', models.CharField(choices=[('block', 'Bloquear'), ('alert', 'Alertar'), ('none', 'Não aplicar')], default='block', max_length=24, verbose_name='modo de aplicação')),
                ('area', models.CharField(blank=True, max_length=120, verbose_name='área')),
                ('process', models.CharField(blank=True, max_length=120, verbose_name='processo')),
                ('module_code', models.CharField(blank=True, max_length=80, verbose_name='módulo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_critical_activity_rules', to='maintenance.equipmentasset', verbose_name='equipamento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='critical_activity_rules', to='training.trainingrequirement', verbose_name='requisito')),
            ],
            options={
                'verbose_name': 'atividade crítica de treinamento',
                'verbose_name_plural': 'atividades críticas de treinamento',
                'ordering': ['activity_code'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('session_number', models.CharField(blank=True, max_length=80, verbose_name='turma')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('delivery_method', models.CharField(choices=[('classroom', 'Presencial'), ('online', 'Online'), ('on_the_job', 'No posto de trabalho'), ('self_study', 'Autotreinamento')], default='classroom', max_length=24, verbose_name='método')),
                ('scheduled_start', models.DateTimeField(verbose_name='início programado')),
                ('scheduled_end', models.DateTimeField(verbose_name='fim programado')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='capacidade')),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('open', 'Aberta'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='planned', max_length=24, verbose_name='status')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='local')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructed_training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='instrutor')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='training.trainingrequirement', verbose_name='requisito')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'turma de treinamento',
                'verbose_name_plural': 'turmas de treinamento',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('enrollment_number', models.CharField(blank=True, max_length=80, verbose_name='registro')),
                ('status', models.CharField(choices=[('convoked', 'Convocado'), ('in_progress', 'Em realização'), ('completed', 'Realizado'), ('approved', 'Aprovado'), ('failed', 'Reprovado'), ('expired', 'Vencido'), ('revoked', 'Revogado')], default='convoked', max_length=24, verbose_name='status')),
                ('convoked_at', models.DateTimeField(blank=True, null=True, verbose_name='convocado em')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='realizado em')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota')),
                ('evidence_reference', models.CharField(blank=True, max_length=255, verbose_name='evidência')),
                ('content_hash', models.CharField(blank=True, max_length=128, verbose_name='hash da evidência')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válido até')),
                ('recertification_due_date', models.DateField(blank=True, null=True, verbose_name='reciclagem até')),
                ('certificate_number', models.CharField(blank=True, max_length=80, verbose_name='certificado')),
                ('certificate_reference', models.CharField(blank=True, max_length=255, verbose_name='referência do certificado')),
                ('failure_reason', models.TextField(blank=True, verbose_name='motivo da reprovação')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revogado em')),
                ('revocation_reason', models.TextField(blank=True, verbose_name='motivo da revogação')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_training_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_people_training_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='realizado por')),
                ('convoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convoked_training_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='convocado por')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_training_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='revogado por')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_training_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='iniciado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people_training_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='training.trainingrequirement', verbose_name='requisito')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='training.trainingsession', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'registro de treinamento',
                'verbose_name_plural': 'registros de treinamento',
                'ordering': ['-convoked_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.CharField(max_length=40, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='função')),
                ('area', models.CharField(max_length=120, verbose_name='área')),
                ('process', models.CharField(blank=True, max_length=120, verbose_name='processo')),
                ('is_critical', models.BooleanField(default=False, verbose_name='crítica')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='functions', to='training.jobposition', verbose_name='cargo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'função',
                'verbose_name_plural': 'funções',
                'ordering': ['area', 'process', 'name'],
            },
        ),
        migrations.AddField(
            model_name='trainingrequirement',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_requirements', to='training.workfunction', verbose_name='função'),
        ),
        migrations.CreateModel(
            name='TrainingMatrixRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='obrigatório')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=24, verbose_name='prioridade')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_requirements', to='training.competency', verbose_name='competência')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrix_requirements', to='training.jobposition', verbose_name='cargo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrix_entries', to='training.trainingrequirement', verbose_name='requisito')),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_requirements', to='training.workfunction', verbose_name='função')),
            ],
            options={
                'verbose_name': 'matriz de treinamento',
                'verbose_name_plural': 'matriz de treinamento',
                'ordering': ['job_position__title', 'requirement__code'],
            },
        ),
        migrations.CreateModel(
            name='TrainingIndicatorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('report_type', models.CharField(choices=[('compliance', 'Aderência'), ('expiration', 'Vencimentos'), ('critical_gaps', 'Lacunas críticas')], max_length=24, verbose_name='tipo de relatório')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('area', models.CharField(blank=True, max_length=120, verbose_name='área')),
                ('process', models.CharField(blank=True, max_length=120, verbose_name='processo')),
                ('period_start', models.DateTimeField(verbose_name='início do período')),
                ('period_end', models.DateTimeField(verbose_name='fim do período')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('generated', 'Gerado')], default='draft', max_length=24, verbose_name='status')),
                ('total_required', models.PositiveIntegerField(default=0, verbose_name='treinamentos requeridos')),
                ('total_completed', models.PositiveIntegerField(default=0, verbose_name='treinamentos realizados')),
                ('total_valid', models.PositiveIntegerField(default=0, verbose_name='treinamentos válidos')),
                ('overdue_trainings', models.PositiveIntegerField(default=0, verbose_name='treinamentos atrasados')),
                ('due_soon_trainings', models.PositiveIntegerField(default=0, verbose_name='treinamentos a vencer')),
                ('compliance_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, verbose_name='aderência %')),
                ('content_reference', models.CharField(blank=True, max_length=255, verbose_name='referência do relatório')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='gerado em')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_training_indicator_reports', to=settings.AUTH_USER_MODEL, verbose_name='gerado por')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_reports', to='training.jobposition', verbose_name='cargo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_reports', to='training.workfunction', verbose_name='função')),
            ],
            options={
                'verbose_name': 'indicador de treinamento',
                'verbose_name_plural': 'indicadores de treinamento',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='competency',
            index=models.Index(fields=['tenant', 'competency_type', 'is_active'], name='training_co_tenant__6f4cca_idx'),
        ),
        migrations.AddIndex(
            model_name='competency',
            index=models.Index(fields=['code'], name='training_co_code_a90a4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='competency',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_competency_code'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['tenant', 'area', 'is_active'], name='training_jo_tenant__2cbec6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['code'], name='training_jo_code_6c1573_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobposition',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_job_position_code'),
        ),
        migrations.AddIndex(
            model_name='criticalactivityrule',
            index=models.Index(fields=['tenant', 'is_active', 'enforcement_mode'], name='training_cr_tenant__cb3ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='criticalactivityrule',
            index=models.Index(fields=['tenant', 'requirement'], name='training_cr_tenant__72ceb8_idx'),
        ),
        migrations.AddIndex(
            model_name='criticalactivityrule',
            index=models.Index(fields=['tenant', 'equipment'], name='training_cr_tenant__f141db_idx'),
        ),
        migrations.AddIndex(
            model_name='criticalactivityrule',
            index=models.Index(fields=['activity_code'], name='training_cr_activit_eea887_idx'),
        ),
        migrations.AddConstraint(
            model_name='criticalactivityrule',
            constraint=models.UniqueConstraint(fields=('tenant', 'activity_code'), name='unique_tenant_people_critical_activity_code'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['tenant', 'requirement', 'status'], name='training_tr_tenant__29b55f_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['tenant', 'scheduled_start'], name='training_tr_tenant__278509_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['tenant', 'instructor'], name='training_tr_tenant__5e0eab_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['session_number'], name='training_tr_session_7f68d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.UniqueConstraint(fields=('tenant', 'session_number'), name='unique_tenant_training_session_number'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['tenant', 'requirement', 'status'], name='training_tr_tenant__3a0ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['tenant', 'session'], name='training_tr_tenant__53fc78_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['tenant', 'user', 'valid_until'], name='training_tr_tenant__5077f0_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['tenant', 'due_date'], name='training_tr_tenant__3fede7_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['tenant', 'certificate_number'], name='training_tr_tenant__3c065b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['enrollment_number'], name='training_tr_enrollm_9afda5_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingenrollment',
            constraint=models.UniqueConstraint(fields=('tenant', 'enrollment_number'), name='unique_tenant_training_enrollment_number'),
        ),
        migrations.AddIndex(
            model_name='workfunction',
            index=models.Index(fields=['tenant', 'area', 'process'], name='training_wo_tenant__301ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='workfunction',
            index=models.Index(fields=['tenant', 'is_critical', 'is_active'], name='training_wo_tenant__7c6220_idx'),
        ),
        migrations.AddIndex(
            model_name='workfunction',
            index=models.Index(fields=['code'], name='training_wo_code_24e322_idx'),
        ),
        migrations.AddConstraint(
            model_name='workfunction',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_work_function_code'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['tenant', 'training_type', 'is_active'], name='training_tr_tenant__0c3f07_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['tenant', 'area', 'process'], name='training_tr_tenant__34f6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['tenant', 'job_position'], name='training_tr_tenant__63e189_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['tenant', 'function'], name='training_tr_tenant__78ad19_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['tenant', 'competency'], name='training_tr_tenant__5d8bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['tenant', 'document'], name='training_tr_tenant__70278b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['tenant', 'equipment'], name='training_tr_tenant__82e0e3_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['code'], name='training_tr_code_52253f_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingrequirement',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_people_training_requirement_code'),
        ),
        migrations.AddIndex(
            model_name='trainingmatrixrequirement',
            index=models.Index(fields=['tenant', 'job_position', 'priority'], name='training_tr_tenant__84ee96_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmatrixrequirement',
            index=models.Index(fields=['tenant', 'function'], name='training_tr_tenant__7d5e04_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmatrixrequirement',
            index=models.Index(fields=['tenant', 'competency'], name='training_tr_tenant__470d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmatrixrequirement',
            index=models.Index(fields=['tenant', 'requirement'], name='training_tr_tenant__8a71ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingmatrixrequirement',
            constraint=models.UniqueConstraint(fields=('tenant', 'job_position', 'function', 'competency', 'requirement'), name='unique_tenant_training_matrix_requirement'),
        ),
        migrations.AddIndex(
            model_name='trainingindicatorreport',
            index=models.Index(fields=['tenant', 'report_type', 'status'], name='training_tr_tenant__854613_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingindicatorreport',
            index=models.Index(fields=['tenant', 'area', 'process'], name='training_tr_tenant__42462d_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingindicatorreport',
            index=models.Index(fields=['tenant', 'job_position'], name='training_tr_tenant__9c0a80_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingindicatorreport',
            index=models.Index(fields=['tenant', 'function'], name='training_tr_tenant__60fcba_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingindicatorreport',
            index=models.Index(fields=['tenant', 'period_start', 'period_end'], name='training_tr_tenant__b472d9_idx'),
        ),
    ]
