# Generated by Django 6.0.8 on 2026-08-29 08:12

from django.conf import settings
from django.db import migrations, models


def validate_unique_certificate_numbers(apps, schema_editor):
    training_enrollment = apps.get_model('training', 'TrainingEnrollment')
    duplicates = list(
        training_enrollment.objects.exclude(certificate_number='')
        .values('certificate_number')
        .annotate(total=models.Count('pk'))
        .filter(total__gt=1)
        .order_by('certificate_number')
        .values_list('certificate_number', flat=True)[:10]
    )
    if duplicates:
        joined = ', '.join(duplicates)
        raise RuntimeError(
            'Existem números de certificado duplicados. Corrija-os antes de '
            f'continuar a migração: {joined}.'
        )


class Migration(migrations.Migration):
    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            validate_unique_certificate_numbers,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='trainingenrollment',
            constraint=models.UniqueConstraint(
                condition=models.Q(('certificate_number', ''), _negated=True),
                fields=('certificate_number',),
                name='unique_nonempty_training_certificate_number',
            ),
        ),
    ]
