# Generated by Django 6.0.8 on 2026-08-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingenrollment_unique_nonempty_training_certificate_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='criticalactivityrule',
            name='training_cr_equipme_c51040_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingrequirement',
            name='training_tr_equipme_c54e26_idx',
        ),
        migrations.AlterField(
            model_name='trainingrequirement',
            name='training_type',
            field=models.CharField(choices=[('document', 'Documento'), ('critical_activity', 'Atividade crítica'), ('module', 'Módulo do sistema'), ('regulatory', 'Requisito regulatório'), ('recycle', 'Reciclagem')], max_length=32, verbose_name='tipo'),
        ),
        migrations.RemoveField(
            model_name='criticalactivityrule',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='trainingrequirement',
            name='equipment',
        ),
    ]
