# Generated by Django 6.0.7 on 2026-07-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0002_populate_auxiliary_references'),
        ('masters', '0003_add_zipcode_and_address'),
        ('training', '0002_criticalactivityrule_area_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='location_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='cidade do local'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='location_city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='cidade do local normalizada'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='location_neighborhood',
            field=models.CharField(blank=True, max_length=120, verbose_name='bairro do local'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='location_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions', to='masters.site', verbose_name='unidade/planta'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='location_state',
            field=models.CharField(blank=True, max_length=80, verbose_name='UF do local'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='location_state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF do local normalizada'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='location_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='logradouro do local'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='location_zipcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP do local'),
        ),
    ]
