# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('documents', '0003_remove_controlleddocument_unique_tenant_document_code_version_and_more'),
        ('maintenance', '0004_remove_equipmentasset_unique_tenant_equipment_asset_code_and_more'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('training', '0003_trainingsession_location_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='competency',
            name='unique_tenant_competency_code',
        ),
        migrations.RemoveConstraint(
            model_name='criticalactivityrule',
            name='unique_tenant_people_critical_activity_code',
        ),
        migrations.RemoveConstraint(
            model_name='jobposition',
            name='unique_tenant_job_position_code',
        ),
        migrations.RemoveConstraint(
            model_name='trainingenrollment',
            name='unique_tenant_training_enrollment_number',
        ),
        migrations.RemoveConstraint(
            model_name='trainingmatrixrequirement',
            name='unique_tenant_training_matrix_requirement',
        ),
        migrations.RemoveConstraint(
            model_name='trainingrequirement',
            name='unique_tenant_people_training_requirement_code',
        ),
        migrations.RemoveConstraint(
            model_name='trainingsession',
            name='unique_tenant_training_session_number',
        ),
        migrations.RemoveConstraint(
            model_name='workfunction',
            name='unique_tenant_work_function_code',
        ),
        migrations.RemoveIndex(
            model_name='competency',
            name='training_co_tenant__6f4cca_idx',
        ),
        migrations.RemoveIndex(
            model_name='criticalactivityrule',
            name='training_cr_tenant__cb3ff5_idx',
        ),
        migrations.RemoveIndex(
            model_name='criticalactivityrule',
            name='training_cr_tenant__72ceb8_idx',
        ),
        migrations.RemoveIndex(
            model_name='criticalactivityrule',
            name='training_cr_tenant__f141db_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobposition',
            name='training_jo_tenant__2cbec6_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingenrollment',
            name='training_tr_tenant__3a0ad4_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingenrollment',
            name='training_tr_tenant__53fc78_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingenrollment',
            name='training_tr_tenant__5077f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingenrollment',
            name='training_tr_tenant__3fede7_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingenrollment',
            name='training_tr_tenant__3c065b_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingindicatorreport',
            name='training_tr_tenant__854613_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingindicatorreport',
            name='training_tr_tenant__42462d_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingindicatorreport',
            name='training_tr_tenant__9c0a80_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingindicatorreport',
            name='training_tr_tenant__60fcba_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingindicatorreport',
            name='training_tr_tenant__b472d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingmatrixrequirement',
            name='training_tr_tenant__84ee96_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingmatrixrequirement',
            name='training_tr_tenant__7d5e04_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingmatrixrequirement',
            name='training_tr_tenant__470d6e_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingmatrixrequirement',
            name='training_tr_tenant__8a71ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingrequirement',
            name='training_tr_tenant__0c3f07_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingrequirement',
            name='training_tr_tenant__34f6ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingrequirement',
            name='training_tr_tenant__63e189_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingrequirement',
            name='training_tr_tenant__78ad19_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingrequirement',
            name='training_tr_tenant__5d8bc3_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingrequirement',
            name='training_tr_tenant__70278b_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingrequirement',
            name='training_tr_tenant__82e0e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingsession',
            name='training_tr_tenant__29b55f_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingsession',
            name='training_tr_tenant__278509_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingsession',
            name='training_tr_tenant__5e0eab_idx',
        ),
        migrations.RemoveIndex(
            model_name='workfunction',
            name='training_wo_tenant__301ac1_idx',
        ),
        migrations.RemoveIndex(
            model_name='workfunction',
            name='training_wo_tenant__7c6220_idx',
        ),
        migrations.RemoveField(
            model_name='competency',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='criticalactivityrule',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='trainingenrollment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='trainingindicatorreport',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='trainingmatrixrequirement',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='trainingrequirement',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='workfunction',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='competency',
            index=models.Index(fields=['competency_type', 'is_active'], name='training_co_compete_e11b51_idx'),
        ),
        migrations.AddIndex(
            model_name='criticalactivityrule',
            index=models.Index(fields=['is_active', 'enforcement_mode'], name='training_cr_is_acti_f564b3_idx'),
        ),
        migrations.AddIndex(
            model_name='criticalactivityrule',
            index=models.Index(fields=['requirement'], name='training_cr_require_9ed9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='criticalactivityrule',
            index=models.Index(fields=['equipment'], name='training_cr_equipme_c51040_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['area', 'is_active'], name='training_jo_area_0bca26_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['requirement', 'status'], name='training_tr_require_f3943c_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['session'], name='training_tr_session_c00a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['user', 'valid_until'], name='training_tr_user_id_931c77_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['due_date'], name='training_tr_due_dat_08508e_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['certificate_number'], name='training_tr_certifi_e7ce20_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingindicatorreport',
            index=models.Index(fields=['report_type', 'status'], name='training_tr_report__86f620_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingindicatorreport',
            index=models.Index(fields=['area', 'process'], name='training_tr_area_6a315b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingindicatorreport',
            index=models.Index(fields=['job_position'], name='training_tr_job_pos_6fa5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingindicatorreport',
            index=models.Index(fields=['function'], name='training_tr_functio_06efee_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingindicatorreport',
            index=models.Index(fields=['period_start', 'period_end'], name='training_tr_period__41707f_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmatrixrequirement',
            index=models.Index(fields=['job_position', 'priority'], name='training_tr_job_pos_f0defe_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmatrixrequirement',
            index=models.Index(fields=['function'], name='training_tr_functio_b0e959_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmatrixrequirement',
            index=models.Index(fields=['competency'], name='training_tr_compete_7746f0_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmatrixrequirement',
            index=models.Index(fields=['requirement'], name='training_tr_require_961191_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['training_type', 'is_active'], name='training_tr_trainin_d21afa_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['area', 'process'], name='training_tr_area_f1bdc9_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['job_position'], name='training_tr_job_pos_09571e_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['function'], name='training_tr_functio_0e3919_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['competency'], name='training_tr_compete_bde526_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['document'], name='training_tr_documen_655fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['equipment'], name='training_tr_equipme_c54e26_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['requirement', 'status'], name='training_tr_require_ab94c3_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['scheduled_start'], name='training_tr_schedul_bbd0e8_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['instructor'], name='training_tr_instruc_5b3b25_idx'),
        ),
        migrations.AddIndex(
            model_name='workfunction',
            index=models.Index(fields=['area', 'process'], name='training_wo_area_cc8336_idx'),
        ),
        migrations.AddIndex(
            model_name='workfunction',
            index=models.Index(fields=['is_critical', 'is_active'], name='training_wo_is_crit_a4f5f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='competency',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_competency_code'),
        ),
        migrations.AddConstraint(
            model_name='criticalactivityrule',
            constraint=models.UniqueConstraint(fields=('activity_code',), name='unique_people_critical_activity_code'),
        ),
        migrations.AddConstraint(
            model_name='jobposition',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_job_position_code'),
        ),
        migrations.AddConstraint(
            model_name='trainingenrollment',
            constraint=models.UniqueConstraint(fields=('enrollment_number',), name='unique_training_enrollment_number'),
        ),
        migrations.AddConstraint(
            model_name='trainingmatrixrequirement',
            constraint=models.UniqueConstraint(fields=('job_position', 'function', 'competency', 'requirement'), name='unique_training_matrix_requirement'),
        ),
        migrations.AddConstraint(
            model_name='trainingrequirement',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_people_training_requirement_code'),
        ),
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.UniqueConstraint(fields=('session_number',), name='unique_training_session_number'),
        ),
        migrations.AddConstraint(
            model_name='workfunction',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_work_function_code'),
        ),
    ]
