# Generated by Django 5.2.16 on 2026-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_trainingsession_location_country_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='trainingrequirement',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='workfunction',
            name='code',
            field=models.CharField(blank=True, max_length=40, verbose_name='código'),
        ),
    ]
