# Generated by Django 6.0.7 on 2026-07-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0002_populate_auxiliary_references'),
        ('recalls', '0002_marketcomplaint_criticality_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcomplaint',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='cidade de origem'),
        ),
        migrations.AddField(
            model_name='marketcomplaint',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='cidade de origem normalizada'),
        ),
        migrations.AddField(
            model_name='marketcomplaint',
            name='state',
            field=models.CharField(blank=True, max_length=80, verbose_name='UF de origem'),
        ),
        migrations.AddField(
            model_name='marketcomplaint',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF de origem normalizada'),
        ),
    ]
