# Generated by Django 5.2.16 on 2026-07-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('capa', '0002_remove_capaapproval_unique_tenant_capa_approval_role_user_and_more'),
        ('crm', '0004_remove_campaign_unique_tenant_campaign_code_and_more'),
        ('deviations', '0003_remove_deviationapproval_unique_tenant_deviation_approval_role_user_and_more'),
        ('documents', '0003_remove_controlleddocument_unique_tenant_document_code_version_and_more'),
        ('fiscal', '0005_remove_fiscalbookentry_unique_tenant_document_book_entry_and_more'),
        ('inventory', '0002_remove_stockbalance_unique_tenant_stock_balance_address_status_and_more'),
        ('masters', '0004_remove_businesspartner_unique_tenant_partner_code_and_more'),
        ('pharmacovigilance', '0004_remove_pharmacovigilanceaction_unique_tenant_pharmacovigilance_action_number_and_more'),
        ('quality', '0003_remove_analyticalspecification_unique_tenant_qc_spec_product_lot_version_and_more'),
        ('recalls', '0003_marketcomplaint_city_marketcomplaint_city_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketcomplaint',
            name='unique_tenant_market_complaint_number',
        ),
        migrations.RemoveConstraint(
            model_name='productreturn',
            name='unique_tenant_product_return_number',
        ),
        migrations.RemoveConstraint(
            model_name='recallcampaign',
            name='unique_tenant_recall_campaign_number',
        ),
        migrations.RemoveConstraint(
            model_name='recallimpactedcustomer',
            name='unique_tenant_recall_customer_distribution',
        ),
        migrations.RemoveIndex(
            model_name='marketcomplaint',
            name='recalls_mar_tenant__195a45_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketcomplaint',
            name='recalls_mar_tenant__5d9c8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketcomplaint',
            name='recalls_mar_tenant__b8b2ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketcomplaint',
            name='recalls_mar_tenant__5a2463_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketcomplaint',
            name='recalls_mar_tenant__f9afe0_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketcomplaint',
            name='recalls_mar_tenant__6d3777_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketcomplaint',
            name='recalls_mar_tenant__2ece9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketcomplaint',
            name='recalls_mar_tenant__c1e5db_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreturn',
            name='recalls_pro_tenant__e55073_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreturn',
            name='recalls_pro_tenant__711f42_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreturn',
            name='recalls_pro_tenant__c4d7df_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreturn',
            name='recalls_pro_tenant__12f584_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreturn',
            name='recalls_pro_tenant__252569_idx',
        ),
        migrations.RemoveIndex(
            model_name='recallcampaign',
            name='recalls_rec_tenant__a866b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='recallcampaign',
            name='recalls_rec_tenant__6af971_idx',
        ),
        migrations.RemoveIndex(
            model_name='recallcampaign',
            name='recalls_rec_tenant__5aa925_idx',
        ),
        migrations.RemoveIndex(
            model_name='recallcampaign',
            name='recalls_rec_tenant__e0fca2_idx',
        ),
        migrations.RemoveIndex(
            model_name='recallcampaign',
            name='recalls_rec_tenant__00f3cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='recallcampaign',
            name='recalls_rec_tenant__4af841_idx',
        ),
        migrations.RemoveIndex(
            model_name='recallcommunication',
            name='recalls_rec_tenant__918573_idx',
        ),
        migrations.RemoveIndex(
            model_name='recallcommunication',
            name='recalls_rec_tenant__dbb3de_idx',
        ),
        migrations.RemoveIndex(
            model_name='recallcommunication',
            name='recalls_rec_tenant__b9936f_idx',
        ),
        migrations.RemoveIndex(
            model_name='recalleffectivenessreport',
            name='recalls_rec_tenant__985669_idx',
        ),
        migrations.RemoveIndex(
            model_name='recalleffectivenessreport',
            name='recalls_rec_tenant__3d5638_idx',
        ),
        migrations.RemoveIndex(
            model_name='recalleffectivenessreport',
            name='recalls_rec_tenant__c3452d_idx',
        ),
        migrations.RemoveIndex(
            model_name='recallimpactedcustomer',
            name='recalls_rec_tenant__f307ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='recallimpactedcustomer',
            name='recalls_rec_tenant__89973d_idx',
        ),
        migrations.RemoveIndex(
            model_name='recallimpactedcustomer',
            name='recalls_rec_tenant__2685d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='recallimpactedcustomer',
            name='recalls_rec_tenant__b8bdaa_idx',
        ),
        migrations.RemoveField(
            model_name='marketcomplaint',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='productreturn',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='recallcampaign',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='recallcommunication',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='recalleffectivenessreport',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='recallimpactedcustomer',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='marketcomplaint',
            index=models.Index(fields=['complaint_type', 'status'], name='recalls_mar_complai_328b55_idx'),
        ),
        migrations.AddIndex(
            model_name='marketcomplaint',
            index=models.Index(fields=['source'], name='recalls_mar_source_8de4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='marketcomplaint',
            index=models.Index(fields=['customer'], name='recalls_mar_custome_8f0f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='marketcomplaint',
            index=models.Index(fields=['product'], name='recalls_mar_product_6274b5_idx'),
        ),
        migrations.AddIndex(
            model_name='marketcomplaint',
            index=models.Index(fields=['stock_lot'], name='recalls_mar_stock_l_1f07d8_idx'),
        ),
        migrations.AddIndex(
            model_name='marketcomplaint',
            index=models.Index(fields=['criticality'], name='recalls_mar_critica_4ba00a_idx'),
        ),
        migrations.AddIndex(
            model_name='marketcomplaint',
            index=models.Index(fields=['received_at'], name='recalls_mar_receive_9756e2_idx'),
        ),
        migrations.AddIndex(
            model_name='marketcomplaint',
            index=models.Index(fields=['responsible'], name='recalls_mar_respons_e03219_idx'),
        ),
        migrations.AddIndex(
            model_name='productreturn',
            index=models.Index(fields=['return_type', 'status'], name='recalls_pro_return__4bfd47_idx'),
        ),
        migrations.AddIndex(
            model_name='productreturn',
            index=models.Index(fields=['complaint'], name='recalls_pro_complai_da6211_idx'),
        ),
        migrations.AddIndex(
            model_name='productreturn',
            index=models.Index(fields=['customer'], name='recalls_pro_custome_0fecf9_idx'),
        ),
        migrations.AddIndex(
            model_name='productreturn',
            index=models.Index(fields=['product'], name='recalls_pro_product_a69f58_idx'),
        ),
        migrations.AddIndex(
            model_name='productreturn',
            index=models.Index(fields=['stock_lot'], name='recalls_pro_stock_l_962ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='recallcampaign',
            index=models.Index(fields=['campaign_type', 'status'], name='recalls_rec_campaig_700ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='recallcampaign',
            index=models.Index(fields=['trigger'], name='recalls_rec_trigger_d3fae7_idx'),
        ),
        migrations.AddIndex(
            model_name='recallcampaign',
            index=models.Index(fields=['product'], name='recalls_rec_product_33359c_idx'),
        ),
        migrations.AddIndex(
            model_name='recallcampaign',
            index=models.Index(fields=['stock_lot'], name='recalls_rec_stock_l_37a79a_idx'),
        ),
        migrations.AddIndex(
            model_name='recallcampaign',
            index=models.Index(fields=['criticality'], name='recalls_rec_critica_cd9966_idx'),
        ),
        migrations.AddIndex(
            model_name='recallcampaign',
            index=models.Index(fields=['target_completion_date'], name='recalls_rec_target__9c08e4_idx'),
        ),
        migrations.AddIndex(
            model_name='recallcommunication',
            index=models.Index(fields=['campaign', 'status'], name='recalls_rec_campaig_4d166b_idx'),
        ),
        migrations.AddIndex(
            model_name='recallcommunication',
            index=models.Index(fields=['impacted_customer'], name='recalls_rec_impacte_b13561_idx'),
        ),
        migrations.AddIndex(
            model_name='recallcommunication',
            index=models.Index(fields=['channel'], name='recalls_rec_channel_d77333_idx'),
        ),
        migrations.AddIndex(
            model_name='recalleffectivenessreport',
            index=models.Index(fields=['campaign', 'status'], name='recalls_rec_campaig_84d000_idx'),
        ),
        migrations.AddIndex(
            model_name='recalleffectivenessreport',
            index=models.Index(fields=['report_type'], name='recalls_rec_report__b3201b_idx'),
        ),
        migrations.AddIndex(
            model_name='recalleffectivenessreport',
            index=models.Index(fields=['generated_at'], name='recalls_rec_generat_4a7961_idx'),
        ),
        migrations.AddIndex(
            model_name='recallimpactedcustomer',
            index=models.Index(fields=['campaign', 'response_status'], name='recalls_rec_campaig_d272b3_idx'),
        ),
        migrations.AddIndex(
            model_name='recallimpactedcustomer',
            index=models.Index(fields=['customer'], name='recalls_rec_custome_04820e_idx'),
        ),
        migrations.AddIndex(
            model_name='recallimpactedcustomer',
            index=models.Index(fields=['sales_order'], name='recalls_rec_sales_o_777ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='recallimpactedcustomer',
            index=models.Index(fields=['fiscal_document'], name='recalls_rec_fiscal__c28a91_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketcomplaint',
            constraint=models.UniqueConstraint(fields=('complaint_number',), name='unique_market_complaint_number'),
        ),
        migrations.AddConstraint(
            model_name='productreturn',
            constraint=models.UniqueConstraint(fields=('return_number',), name='unique_product_return_number'),
        ),
        migrations.AddConstraint(
            model_name='recallcampaign',
            constraint=models.UniqueConstraint(fields=('campaign_number',), name='unique_recall_campaign_number'),
        ),
        migrations.AddConstraint(
            model_name='recallimpactedcustomer',
            constraint=models.UniqueConstraint(fields=('campaign', 'customer', 'sales_order', 'fiscal_document'), name='unique_recall_customer_distribution'),
        ),
    ]
