# Generated by Django 5.2.16 on 2026-07-22 17:53

import django.db.models.deletion
from django.db import migrations, models


def validate_legacy_location(apps, schema_editor):
    model = apps.get_model('recalls', 'MarketComplaint')
    invalid_locations = []

    for legacy_field, normalized_field in (('city', 'city_ref'), ('state', 'state_ref')):
        has_unmigrated_location = (
            model.objects.filter(
                **{
                    f'{legacy_field}__isnull': False,
                    f'{normalized_field}__isnull': True,
                }
            )
            .exclude(**{legacy_field: ''})
            .exists()
        )
        if has_unmigrated_location:
            invalid_locations.append(legacy_field)

    if invalid_locations:
        raise RuntimeError(
            'Preencha as referências normalizadas antes de remover os campos legados: '
            + ', '.join(invalid_locations)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_remove_businessarea_unique_auxiliary_businessarea_tenant_code_and_more'),
        ('recalls', '0004_remove_marketcomplaint_unique_tenant_market_complaint_number_and_more'),
    ]

    operations = [
        migrations.RunPython(validate_legacy_location, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='marketcomplaint',
            name='city',
        ),
        migrations.RemoveField(
            model_name='marketcomplaint',
            name='state',
        ),
        migrations.AlterField(
            model_name='marketcomplaint',
            name='city_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.city', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='marketcomplaint',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auxiliary.stateprovince', verbose_name='UF'),
        ),
    ]
