# Generated by Django 5.2.16 on 2026-07-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0006_stateprovince_country'),
        ('recalls', '0005_remove_marketcomplaint_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketcomplaint',
            name='country_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliary.country', verbose_name='país'),
        ),
    ]
